import type { PlantEntry } from "./types";

const placeholder = (alt: string) => [{ src: "/photo-reelle-a-venir.svg", alt, caption: "Photographie réelle Tibaldo à fournir ; aucune image externe ou générée n’est publiée.", width: 1200, height: 1600 }];
const publishedAt = "2026-08-20";

const sharedToxicity = { level: "Prudence", summary: "Plante ornementale non destinée à la consommation.", details: "Évitez l’ingestion et gardez la plante hors de portée des jeunes enfants et des animaux qui mâchonnent les végétaux. En cas de symptôme, contactez un professionnel de santé ou un vétérinaire." };

const strelitziaSources = [
  { label: "Kew Science — genre Strelitzia et cinq espèces acceptées", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:331300-2" },
  { label: "Royal Horticultural Society — culture des Strelitzia", url: "https://www.rhs.org.uk/plants/strelitzia/growing-guide" },
];

const strelitziaBase = (data: {
  slug: string; botanicalName: string; displayName: string; subtitle: string; species: string;
  commonNames: string[]; origin: string; habitat: string; description: string[]; size: string;
  habit: string; light: string; watering: string; temperature: string; comparisons: PlantEntry["comparisons"];
  problems?: PlantEntry["problems"]; faq: PlantEntry["faq"]; local: string; seoTitle: string; seoDescription: string;
  source: string;
}): PlantEntry => ({
  slug: data.slug, genre: "strelitzia", genreLabel: "Strelitzia", botanicalName: data.botanicalName, displayName: data.displayName,
  listingName: data.botanicalName, subtitle: data.subtitle, family: "Strelitziaceae",
  taxonomy: { order: "Zingiberales", family: "Strelitziaceae", genus: "Strelitzia", species: data.species, cultivar: null, commonNames: data.commonNames },
  filters: { temperatureMin: 5, temperatureIdeal: [16, 28], humidityIdeal: [45, 70], light: "vive", watering: "régulier", substrateTags: ["riche", "aéré", "drainant"], growthRate: "moyenne", habits: ["dressé", "terrestre"], adultSizeCm: data.slug === "reginae" || data.slug === "juncea" ? 200 : 800, needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: false, regions: ["Afrique australe", "Hauts-de-France"] },
  origin: data.origin, habitat: data.habitat,
  hybridization: `Espèce botanique acceptée sous le nom ${data.botanicalName} par Plants of the World Online.`, synonyms: [],
  description: data.description,
  specimen: { observedHeight: "Photographie et mesure Tibaldo à venir", note: "Les dimensions naturelles ne doivent pas être transposées automatiquement à une culture en pot ou en intérieur." },
  growth: { adultSize: data.size, speed: "Moyenne lorsque lumière, chaleur, eau et espace racinaire sont suffisants", habit: data.habit },
  care: { light: 4, water: 3, humidity: 3, difficulty: 3, lightText: data.light, watering: data.watering, humidityText: "Humidité domestique correcte avec circulation d’air ; éviter chauffage desséchant et confinement.", temperature: data.temperature, substrate: "Mélange riche mais très drainant : terreau structuré, matière organique et fraction minérale, dans un pot percé.", repotting: "Rempoter au printemps lorsque les racines occupent le contenant, dans un pot stable seulement un peu plus grand.", fertilizing: "Engrais équilibré et modéré pendant la croissance active, sur substrat déjà humide ; réduire fortement en hiver.", propagation: "Division d’une touffe bien établie ou semis ; la séparation exige des racines propres à chaque division et une reprise chaude." },
  toxicity: sharedToxicity,
  problems: data.problems ?? [
    { title: "Feuilles fendues", cause: "Vent, passages répétés ou déploiement naturel d’un grand limbe.", advice: "Abriter du vent ; une fente ancienne ne se referme pas mais n’empêche pas la feuille de fonctionner." },
    { title: "Bords bruns", cause: "Arrosage irrégulier, sels, air sec ou racines comprimées.", advice: "Contrôler la motte, le drainage et la qualité de l’eau avant d’augmenter les apports." },
    { title: "Pas de floraison", cause: "Jeunesse, manque de lumière, culture intérieure ou nutrition inadaptée.", advice: "Privilégier maturité, soleil progressif et stabilité ; aucune technique ne garantit une floraison en appartement." },
    { title: "Cochenilles ou acariens", cause: "Ravageurs favorisés par une plante confinée ou fragilisée.", advice: "Isoler, identifier puis traiter toutes les faces du feuillage et les gaines." },
  ],
  comparisons: data.comparisons, faq: data.faq,
  tibaldoAdvice: ["Acclimatez au soleil sur plusieurs semaines avant toute sortie estivale.", "Tournez un jeune sujet en intérieur pour équilibrer son port, sans déplacer sans cesse une plante acclimatée.", "En hiver à Lille, la lumière disponible doit guider la réduction de l’eau et de l’engrais."],
  localSpotlight: { title: `Cultiver ${data.botanicalName} à Lille et dans le Nord`, text: data.local },
  editorialSections: [
    { id: "interieur", eyebrow: "Culture intérieure", title: "Lumière, volume et patience.", paragraphs: ["Une baie très lumineuse convient mieux qu’un fond de pièce. La plante demande de l’espace pour déployer ses feuilles et un pot lourd qui ne bascule pas.", "Une sortie estivale est possible après acclimatation progressive. Rentrez avant les nuits froides et inspectez parasites et drainage."] },
    { id: "exterieur", eyebrow: "Terrasse et jardin", title: "Une saison dehors, pas une promesse de rusticité.", paragraphs: ["Dans le Nord, la culture extérieure permanente reste risquée pour les Strelitzia. Vent, gel durable et humidité froide touchent feuilles, collet et racines.", "La culture en pot permet une belle saison au soleil puis un hivernage lumineux, frais à tempéré et protégé du gel."] },
  ],
  mediaNeeds: [{ role: "HERO", description: `Sujet complet de ${data.botanicalName}, correctement identifié.` }, { role: "Galerie", description: "Feuille mature, port, base de la plante et inflorescence si disponible." }],
  gallery: placeholder(`Photographie propriétaire de ${data.botanicalName} à ajouter`),
  seo: { title: data.seoTitle, description: data.seoDescription, keywords: [data.botanicalName, `${data.botanicalName} entretien`, "oiseau de paradis entretien", "Strelitzia Lille"] },
  sources: [...strelitziaSources, { label: `Kew Science — ${data.botanicalName}`, url: data.source }], publishedAt, updatedAt: publishedAt,
});

export const agaveAmericanaVariegata: PlantEntry = {
  slug: "americana-variegata", genre: "agave", genreLabel: "Agave", botanicalName: "Agave americana ‘Variegata’", displayName: "Agave americana ‘Variegata’", listingName: "Agave americana ‘Variegata’",
  subtitle: "Une grande rosette panachée, sculpturale et armée, qui exige soleil, drainage et prudence face à l’humidité hivernale.", family: "Asparagaceae",
  taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Agave", species: "americana", cultivar: "Variegata", commonNames: ["Agave d’Amérique panaché", "Century plant ‘Variegata’"] },
  filters: { temperatureMin: 1, temperatureIdeal: [12, 30], humidityIdeal: [30, 60], light: "soleil", watering: "faible", substrateTags: ["minéral", "très drainant", "succulentes"], growthRate: "lente", habits: ["terrestre", "dressé"], adultSizeCm: 150, needsSupport: false, variegated: true, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Mexique", "Hauts-de-France"] },
  origin: "L’espèce Agave americana est originaire du Mexique et du sud des États-Unis ; ‘Variegata’ est une sélection horticole panachée.", habitat: "Milieux secs, rocheux et très lumineux pour l’espèce, avec un sol qui évacue rapidement l’eau.", hybridization: "Cultivar horticole de l’espèce acceptée Agave americana L. ; il ne doit pas être présenté comme une variété botanique acceptée.", synonyms: ["Century plant ‘Variegata’"],
  description: ["Agave americana ‘Variegata’ forme une rosette persistante de feuilles épaisses gris-vert bordées ou striées de crème. Chaque feuille porte des dents marginales et une épine terminale : son emplacement doit anticiper le passage des personnes et des animaux.", "La rosette grandit lentement puis peut produire une hampe florale spectaculaire après de longues années. Comme l’espèce est monocarpique, la rosette qui fleurit meurt ensuite, tandis que des rejets peuvent assurer la continuité de la touffe.", "La panachure réduit la surface chlorophyllienne : une lumière généreuse soutient un port compact, mais un sujet passé sous abri doit être acclimaté avant le plein soleil."],
  specimen: { observedHeight: "Rosette souvent 1 à 1,5 m à maturité", note: "Photographie et mesures Tibaldo à venir ; taille très dépendante du contenant et du climat." }, growth: { adultSize: "Environ 1 à 1,5 m de haut et de large hors hampe florale", speed: "Lente à moyenne en plein soleil", habit: "Large rosette basale, rigide et drageonnante" },
  care: { light: 5, water: 1, humidity: 1, difficulty: 3, lightText: "Plein soleil après acclimatation ; sous abri, choisir la zone la plus lumineuse.", watering: "Arroser profondément pendant la croissance puis laisser sécher le mélange. Garder presque sec en hiver frais.", humidityText: "Air sec et ventilé ; l’humidité persistante autour du cœur et des racines est un risque majeur.", temperature: "RHS classe ce cultivar H2 : il tolère le froid sans supporter un gel durable. Le froid humide est plus dangereux qu’un minimum isolé.", substrate: "Mélange majoritairement minéral, très drainant, dans un pot percé et surélevé.", repotting: "Au printemps, avec gants et protection des yeux, sans enterrer le collet ni surdimensionner le pot.", fertilizing: "Faible apport pour cactus et succulentes au printemps et en été ; aucun engrais en repos hivernal.", propagation: "Séparer un rejet raciné au printemps ou à l’automne, laisser sécher les plaies puis installer dans un mélange minéral." },
  toxicity: { level: "Irritant et potentiellement toxique", summary: "Sève irritante, épines dangereuses et ingestion nocive.", details: "La RHS signale une irritation cutanée et un danger pour chiens et chats en cas d’ingestion. Portez gants et lunettes, et placez la rosette hors des zones de passage." },
  problems: [{ title: "Base molle", cause: "Froid humide, eau stagnante ou substrat trop organique.", advice: "Mettre au sec, vérifier le collet et les racines, puis corriger drainage et protection contre la pluie." }, { title: "Feuilles allongées", cause: "Manque de soleil.", advice: "Augmenter progressivement la lumière ; les anciennes feuilles ne se raccourciront pas." }, { title: "Brûlures crème", cause: "Passage brutal de l’ombre au soleil.", advice: "Acclimater sur plusieurs semaines et protéger temporairement aux heures fortes." }, { title: "Cochenilles", cause: "Insectes installés dans les aisselles ou sous les feuilles.", advice: "Inspecter avec prudence, isoler et traiter sans accumuler d’eau au cœur." }],
  comparisons: [{ name: "Agave americana", difference: "Forme type non panachée, généralement plus vigoureuse et entièrement gris-vert." }, { name: "Agave americana ‘Mediopicta’", difference: "Panachure principalement centrale, distincte du motif marginal couramment associé à ‘Variegata’." }],
  faq: [{ question: "Est-ce Agave americana var. variegata ?", answer: "Non dans cette fiche : RHS traite ‘Variegata’ comme cultivar horticole. La forme retenue est Agave americana ‘Variegata’." }, { question: "Peut-il rester dehors à Lille ?", answer: "Une pleine terre très drainée et abritée peut limiter les risques, mais la classe RHS H2 et l’hiver humide lillois rendent la culture en pot hiverné hors gel plus prudente." }, { question: "À quelle fréquence arroser ?", answer: "Seulement après séchage réel du mélange ; beaucoup moins en hiver. La saison, le pot et la lumière comptent davantage qu’un calendrier." }, { question: "Est-il dangereux ?", answer: "Oui : dents, épine terminale et sève irritante imposent gants, protection des yeux et emplacement hors passage." }],
  tibaldoAdvice: ["À Lille, protégez surtout de la pluie froide et durable.", "Manipulez la rosette à deux personnes lorsqu’elle devient large.", "N’arrosez jamais pour compenser une température basse ou un manque de lumière."],
  localSpotlight: { title: "Cultiver Agave americana ‘Variegata’ à Lille et dans le Nord", text: "Le froid humide, les pluies hivernales et un drainage imparfait forment le principal risque. Une terrasse plein sud, abritée des pluies, convient pendant la belle saison. En pot, rentrez dans un lieu très lumineux, ventilé et hors gel ; en pleine terre expérimentale, surélevez fortement la plantation, abritez le cœur et n’interprétez jamais une température minimale comme une garantie." },
  editorialSections: [{ id: "floraison", eyebrow: "Cycle de vie", title: "Une floraison tardive et monocarpique.", paragraphs: ["Après de nombreuses années, une rosette mature peut émettre une hampe florale monumentale. La rosette principale meurt après la floraison.", "Les rejets permettent souvent à la colonie de se renouveler. Leur présence ne doit pas conduire à détacher trop tôt une pousse sans racines."] }], mediaNeeds: [{ role: "HERO", description: "Rosette complète photographiée par Tibaldo, sans masquer les épines." }], gallery: placeholder("Photographie propriétaire d’Agave americana ‘Variegata’ à ajouter"),
  seo: { title: "Agave americana ‘Variegata’ : entretien et hivernage", description: "Guide complet de l’Agave americana ‘Variegata’ : soleil, arrosage, drainage, pot, épines, floraison et hivernage prudent à Lille.", keywords: ["Agave americana Variegata", "Agave panaché entretien", "Agave hiver", "Agave Lille"] },
  sources: [{ label: "Kew Science — Agave americana L.", url: "https://powo.science.kew.org/results?q=Agave%20americana" }, { label: "Royal Horticultural Society — Agave americana ‘Variegata’", url: "https://www.rhs.org.uk/plants/74255/agave-americana-variegata-v/details" }], publishedAt, updatedAt: publishedAt,
};

export const fatsiaJaponicaSpidersWeb: PlantEntry = {
  slug: "japonica-spiders-web", genre: "fatsia", genreLabel: "Fatsia", botanicalName: "Fatsia japonica ‘Spider’s Web’", displayName: "Fatsia japonica ‘Spider’s Web’", listingName: "Fatsia japonica ‘Spider’s Web’",
  subtitle: "Un arbuste persistant d’ombre lumineuse, aux grandes feuilles palmées éclaboussées de blanc.", family: "Araliaceae",
  taxonomy: { order: "Apiales", family: "Araliaceae", genus: "Fatsia", species: "japonica", cultivar: "Spider’s Web", commonNames: ["Aralia du Japon ‘Spider’s Web’", "Japanese aralia ‘Tsumugi-shibori’"] },
  filters: { temperatureMin: -10, temperatureIdeal: [10, 24], humidityIdeal: [45, 75], light: "moyenne", watering: "modéré", substrateTags: ["humifère", "frais", "drainant"], growthRate: "lente", habits: ["dressé", "terrestre"], adultSizeCm: 250, needsSupport: false, variegated: true, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Japon", "Corée", "Taïwan", "Hauts-de-France"] },
  origin: "L’espèce Fatsia japonica est originaire du Japon, de Corée et de Taïwan ; ‘Spider’s Web’ est un cultivar horticole accepté par la RHS.", habitat: "Sous-bois, lisières et emplacements abrités pour l’espèce, dans des sols frais mais drainés.", hybridization: "Cultivar horticole de Fatsia japonica, aussi référencé par la RHS sous le nom japonais ‘Tsumugi-shibori’.", synonyms: ["Fatsia japonica ‘Tsumugi-shibori’", "Japanese aralia ‘Spider’s Web’"],
  description: ["Fatsia japonica ‘Spider’s Web’ forme un arbuste persistant aux tiges épaisses et aux grandes feuilles palmées. Leur moucheture blanche, souvent plus dense vers les marges, varie d’une feuille à l’autre.", "Plus lent à s’établir que la forme verte, il préfère un emplacement abrité où le vent ne déchire pas son feuillage. Une ombre trop profonde peut atténuer la panachure, tandis qu’un soleil chaud brûle les zones claires.", "À l’extérieur, les inflorescences automnales en ombelles blanc crème peuvent être suivies de fruits noirs décoratifs non destinés à la consommation."],
  specimen: { observedHeight: "Environ 1,5 à 2,5 m à maturité selon la RHS", note: "Photographie et mesure du spécimen Tibaldo à venir." }, growth: { adultSize: "1,5 à 2,5 m de haut et de large dans un site favorable", speed: "Lente à moyenne ; cultivar plus lent que l’espèce", habit: "Arbuste persistant, buissonnant et architectural" },
  care: { light: 3, water: 3, humidity: 3, difficulty: 2, lightText: "Ombre lumineuse à mi-ombre ; assez de lumière pour la panachure, sans soleil brûlant.", watering: "Garder le sol frais pendant l’installation et les périodes sèches, sans saturation prolongée.", humidityText: "Humidité normale à fraîche ; surtout protéger des vents secs ou froids qui abîment les grandes feuilles.", temperature: "RHS H5 pour le cultivar, tout en précisant qu’un jeune sujet peut être moins rustique. Abri et sol drainé restent importants.", substrate: "Sol humifère, frais et drainant, acide à alcalin selon la RHS ; en pot, mélange structuré et contenant percé.", repotting: "Au printemps lorsque la motte occupe le pot ; choisir un contenant stable et éviter de casser inutilement les racines.", fertilizing: "Compost mûr au jardin ou engrais équilibré modéré pendant la croissance ; éviter l’excès d’azote.", propagation: "Boutures semi-aoûtées selon la RHS ; la multiplication doit conserver fidèlement les caractères du cultivar." },
  toxicity: { level: "Fruits non comestibles", summary: "La RHS recommande des précautions avec les fruits et le port de gants.", details: "Les fruits sont ornementaux et ne doivent pas être consommés. Portez des gants pour les tailles et placez la plante avec discernement auprès des enfants et animaux." },
  problems: [{ title: "Taches brunes", cause: "Soleil fort, froid, maladie foliaire ou feuillage resté humide sans aération.", advice: "Comparer exposition, météo et progression des taches avant de traiter." }, { title: "Feuilles déchirées", cause: "Vent ou passage.", advice: "Déplacer ou protéger du vent ; une feuille abîmée reste fonctionnelle tant qu’elle demeure verte." }, { title: "Panachure moins nette", cause: "Ombre très profonde ou variabilité naturelle du cultivar.", advice: "Augmenter doucement la lumière sans exposer brutalement au soleil." }, { title: "Cochenilles, thrips ou farineuses", cause: "Ravageurs signalés par la RHS.", advice: "Inspecter pétioles et revers, isoler en intérieur et répéter un traitement adapté." }],
  comparisons: [{ name: "Fatsia japonica", difference: "Feuillage vert uni, croissance généralement plus vigoureuse et silhouette adulte souvent plus grande." }, { name: "Fatsia japonica ‘Variegata’", difference: "Panachure plus franche en plages crème, différente du mouchetage diffus de ‘Spider’s Web’." }],
  faq: [{ question: "Peut-il rester dehors à Lille ?", answer: "Oui dans un emplacement abrité et un sol drainé ; la RHS le classe H5. Un jeune sujet en pot reste plus exposé au gel et aux vents froids." }, { question: "Préfère-t-il l’ombre ?", answer: "Ombre lumineuse ou mi-ombre. Une obscurité forte réduit l’expression du feuillage, un soleil brûlant marque les zones blanches." }, { question: "Peut-on le cultiver dedans ?", answer: "Oui dans une pièce claire, fraîche et ventilée, mais l’extérieur abrité correspond mieux à son développement durable." }, { question: "Pourquoi les feuilles blanchissent-elles différemment ?", answer: "Le motif du cultivar varie naturellement entre feuilles et avec la lumière ; une variation n’implique pas une nouvelle identité." }],
  tibaldoAdvice: ["À Lille, placez-le contre un mur protégé des vents d’est.", "Arrosez un sujet en pot avant qu’il ne flétrisse, puis laissez s’écouler l’excédent.", "N’enlevez pas une feuille seulement parce que sa panachure diffère des précédentes."],
  localSpotlight: { title: "Cultiver Fatsia japonica ‘Spider’s Web’ à Lille et dans le Nord", text: "Le cultivar peut vivre dehors dans la métropole lilloise si le sol draine et si les grands limbes sont protégés des vents froids. Une cour claire, un patio ou un mur à l’est ou au nord-est offrent souvent un bon compromis. En pot, isolez le contenant lors des fortes gelées et surveillez le séchage estival ; après un hiver sévère, attendez la reprise avant toute taille radicale." },
  mediaNeeds: [{ role: "HERO", description: "Sujet Tibaldo complet avec panachure lisible et lumière douce." }], gallery: placeholder("Photographie propriétaire de Fatsia japonica ‘Spider’s Web’ à ajouter"),
  seo: { title: "Fatsia japonica ‘Spider’s Web’ : entretien et culture", description: "Guide du Fatsia japonica ‘Spider’s Web’ : ombre, arrosage, panachure, culture en pot ou dehors et rusticité à Lille.", keywords: ["Fatsia japonica Spider's Web", "Fatsia panaché", "Fatsia extérieur Lille", "Fatsia entretien"] },
  sources: [{ label: "Kew Science — Fatsia japonica", url: "https://powo.science.kew.org/results?q=Fatsia%20japonica" }, { label: "Royal Horticultural Society — Fatsia japonica ‘Spider’s Web’", url: "https://www.rhs.org.uk/plants/198563/fatsia-japonica-spiders-web/details" }], publishedAt, updatedAt: publishedAt,
};

export const strelitziaPlants: PlantEntry[] = [
  strelitziaBase({ slug: "alba", botanicalName: "Strelitzia alba", displayName: "Strelitzia alba", species: "alba", commonNames: ["Oiseau de paradis blanc", "Great white strelitzia"], subtitle: "Le grand Strelitzia blanc du Cap, nom accepté auquel se rattache le synonyme botanique Strelitzia augusta.", origin: "Province du Cap, Afrique du Sud", habitat: "Pentes, ravins et végétations subtropicales côtières du Cap.", description: ["Strelitzia alba est une espèce arborescente à grandes feuilles disposées en éventail. Les sujets âgés portent plusieurs tiges et une floraison blanche dans une spathe sombre.", "Kew accepte Strelitzia alba et place Strelitzia augusta Thunb. dans sa synonymie. Cela ne permet pas d’identifier automatiquement une plante de commerce étiquetée « Augusta » : ce nom est aussi employé de manière imprécise.", "Par rapport à S. nicolai, l’identification demande d’observer plusieurs caractères adultes, notamment inflorescence, architecture et origine ; une feuille isolée ne suffit pas."], size: "Grand sujet arborescent pouvant approcher 10 m dans son habitat", habit: "Touffe arborescente à éventails foliaires", light: "Lumière très vive à soleil progressif ; une lumière insuffisante allonge et fragilise le port.", watering: "Arrosages généreux en croissance après séchage partiel, puis nettement réduits en hiver.", temperature: "Espèce subtropicale à protéger du gel ; la culture en pot hiverné est la stratégie prudente à Lille.", comparisons: [{ name: "Strelitzia nicolai", difference: "Très proche ; l’inflorescence, le nombre de spathes et plusieurs caractères adultes sont plus fiables qu’une feuille seule." }, { name: "Strelitzia reginae", difference: "Beaucoup plus compacte, avec fleurs orange et bleues plutôt que blanches." }], faq: [{ question: "Strelitzia augusta est-il une espèce acceptée ?", answer: "Non selon Kew : Strelitzia augusta Thunb. est un synonyme de Strelitzia alba." }, { question: "Une plante vendue « Augusta » est-elle forcément alba ?", answer: "Non. Le commerce emploie parfois ce nom de façon vague ; il faut observer plusieurs caractères adultes et l’origine du lot." }, { question: "Comment la distinguer de nicolai ?", answer: "La floraison et l’architecture adulte aident davantage qu’une feuille isolée ; sans ces caractères, l’identification peut rester prudente." }], local: "Cultivez-la en grand pot, dehors l’été après acclimatation, puis dans un lieu lumineux protégé du gel. Le vent lillois fend les feuilles et une motte froide, humide et peu éclairée augmente les risques.", seoTitle: "Strelitzia alba : entretien et différence avec augusta", seoDescription: "Guide de Strelitzia alba : culture, floraison blanche, différence avec nicolai et statut du synonyme Strelitzia augusta.", source: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:585015-1" }),
  strelitziaBase({ slug: "caudata", botanicalName: "Strelitzia caudata", displayName: "Strelitzia caudata", species: "caudata", commonNames: ["Mountain strelitzia", "Wild banana"], subtitle: "Une grande espèce montagnarde d’Afrique australe, rare en culture et distincte par sa distribution et sa floraison.", origin: "Monts Chimanimani jusqu’à l’Eswatini", habitat: "Forêts et ravins montagnards subtropicaux du Mozambique, Zimbabwe, nord de l’Afrique du Sud et Eswatini.", description: ["Strelitzia caudata est une espèce acceptée décrite par R.A. Dyer en 1946. Elle forme de hautes touffes arborescentes dans des habitats montagnards d’Afrique australe.", "Sa rareté horticole impose d’éviter les identifications rapides. Une grande plante blanche vendue comme oiseau de paradis n’est pas automatiquement S. caudata.", "Ses inflorescences pâles et ses caractères adultes permettent de la comparer aux autres grands Strelitzia, mais une provenance documentée reste précieuse."], size: "Grande espèce arborescente, plusieurs mètres à maturité", habit: "Touffe haute à pseudotroncs multiples", light: "Lumière vive, soleil doux à progressif, avec abri contre les vents desséchants.", watering: "Maintenir une humidité régulière en croissance tout en drainant ; réduire lors du repos frais.", temperature: "Origine montagnarde ne signifie pas rusticité garantie : protéger du gel et de l’humidité froide en pot.", comparisons: [{ name: "Strelitzia alba", difference: "Distribution naturelle centrée sur le Cap et synonymie propre ; caudata est originaire de régions montagnardes plus au nord-est." }, { name: "Strelitzia nicolai", difference: "Espèce plus courante en culture, largement côtière en Afrique australe ; l’identification demande l’inflorescence et la provenance." }], faq: [{ question: "Est-elle courante en intérieur ?", answer: "Non. Beaucoup de grands sujets du commerce sont plutôt vendus sous nicolai ou des appellations imprécises." }, { question: "Est-elle plus rustique parce qu’elle vient des montagnes ?", answer: "Cette origine peut influer sur sa tolérance, mais ne justifie aucune garantie face au gel humide de Lille." }, { question: "Comment confirmer l’identité ?", answer: "Par provenance, caractères adultes et floraison, pas à partir d’une seule feuille." }], local: "À Lille, elle reste une plante de collection à cultiver en contenant mobile, avec saison extérieure abritée et hivernage lumineux hors gel. La provenance montagnarde ne dispense pas d’une protection prudente.", seoTitle: "Strelitzia caudata : culture et identification", seoDescription: "Découvrez Strelitzia caudata, espèce montagnarde d’Afrique australe : morphologie, culture, hivernage et différences avec alba et nicolai.", source: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:585016-1" }),
  strelitziaBase({ slug: "juncea", botanicalName: "Strelitzia juncea", displayName: "Strelitzia juncea", species: "juncea", commonNames: ["Oiseau de paradis à feuilles de jonc", "Rush-leaved strelitzia"], subtitle: "L’oiseau de paradis au port presque sans limbe, graphique, plus compact et adapté aux milieux secs de l’est du Cap.", origin: "Sud-est de l’Afrique du Sud, principalement province du Cap-Oriental", habitat: "Fourrés secs et zones ouvertes de l’est du Cap.", description: ["Strelitzia juncea se distingue à maturité par ses longs pétioles cylindriques presque dépourvus de limbe, formant une touffe verticale très graphique.", "Les jeunes plantes peuvent encore porter un limbe visible : l’identité ne doit donc pas être jugée sur un seul stade juvénile.", "Sa floraison orange et bleue rappelle S. reginae, mais son feuillage adulte en forme de jonc et son port plus vertical permettent de les séparer."], size: "Environ 1,5 à 2 m à maturité", habit: "Touffe compacte de pétioles cylindriques dressés", light: "Soleil généreux après acclimatation ; davantage de lumière qu’un grand Strelitzia conservé en fond de pièce.", watering: "Arroser régulièrement en croissance mais laisser sécher davantage que pour les grands Strelitzia ; ne jamais saturer.", temperature: "Tolère mieux la sécheresse que l’humidité froide ; protéger du gel à Lille.", comparisons: [{ name: "Strelitzia reginae", difference: "Même gamme de couleurs florales, mais reginae conserve de larges limbes alors que juncea adulte développe un feuillage de type jonc." }, { name: "Strelitzia nicolai", difference: "Nicolai devient arborescent, porte de grandes feuilles et des fleurs blanches." }], faq: [{ question: "Pourquoi n’a-t-elle presque pas de feuilles ?", answer: "Chez l’adulte, le limbe est fortement réduit et les pétioles cylindriques assurent l’essentiel de l’aspect graphique." }, { question: "Un jeune plant ressemble-t-il à reginae ?", answer: "Oui, les stades juvéniles peuvent conserver un limbe ; l’identification devient plus nette avec la maturité." }, { question: "Peut-elle vivre en intérieur ?", answer: "Oui près d’une baie très lumineuse, mais la floraison et le port compact demandent beaucoup de lumière." }], local: "À Lille, privilégiez le pot, une exposition très lumineuse et une sortie estivale progressive. Rentrez avant les nuits froides ; un substrat minéral et drainant limite les risques pendant l’hiver peu lumineux.", seoTitle: "Strelitzia juncea : entretien de l’oiseau de paradis jonc", seoDescription: "Guide de Strelitzia juncea : feuillage cylindrique, soleil, arrosage, floraison, culture en pot et hivernage à Lille.", source: "https://powo.science.kew.org/results?q=Strelitzia%20juncea" }),
  strelitziaBase({ slug: "nicolai", botanicalName: "Strelitzia nicolai", displayName: "Strelitzia nicolai", species: "nicolai", commonNames: ["Oiseau de paradis géant", "Giant white bird of paradise"], subtitle: "Le grand oiseau de paradis blanc, spectaculaire en intérieur lumineux mais rapidement encombrant.", origin: "Afrique australe, du Mozambique à l’Afrique du Sud", habitat: "Forêts côtières, ravins et végétations subtropicales chaudes d’Afrique australe.", description: ["Strelitzia nicolai forme de puissantes touffes à grandes feuilles rappelant celles d’un bananier. Avec l’âge, ses bases foliaires composent des pseudotroncs et la plante devient franchement arborescente.", "Ses inflorescences blanches et bleu sombre apparaissent surtout sur des sujets adultes cultivés dans une lumière généreuse. La floraison reste rare dans un appartement.", "Il est fréquemment confondu avec S. alba et commercialisé sous « Augusta ». Une feuille seule ne garantit pas l’identification ; architecture adulte, inflorescence et provenance doivent être croisées."], size: "Jusqu’à environ 8 à 10 m dans son milieu ; bien moins en pot", habit: "Grande touffe arborescente à pseudotroncs multiples", light: "Lumière maximale à soleil progressif ; un fond de pièce produit des pétioles faibles et un port déséquilibré.", watering: "Arroser copieusement en croissance après séchage de la surface, puis vider l’excédent ; réduire en hiver.", temperature: "Chaleur pendant la croissance, hivernage lumineux protégé du gel et des courants d’air froid.", comparisons: [{ name: "Strelitzia alba", difference: "Espèce très proche ; l’inflorescence et l’architecture adulte sont nécessaires pour une distinction prudente." }, { name: "Musa", difference: "Le bananier produit une architecture et des inflorescences différentes ; Strelitzia appartient aux Strelitziaceae et non aux Musaceae." }], faq: [{ question: "Nicolai est-il le même que Augusta ?", answer: "Non botaniquement. Augusta est un synonyme de S. alba selon Kew, mais le commerce emploie parfois ce nom pour de grands Strelitzia non confirmés." }, { question: "Pourquoi ses feuilles se fendent-elles ?", answer: "Les grands limbes se divisent naturellement sous l’effet du vent et des contraintes mécaniques ; protégez-le des courants violents." }, { question: "Peut-il fleurir en appartement ?", answer: "C’est possible mais peu fréquent : il faut un sujet adulte, énormément de lumière et assez d’espace." }], local: "À Lille, une grande baie et une pièce haute sont nécessaires. Sortez-le en été après acclimatation, protégez-le du vent, puis rentrez-le bien avant le gel. Un pot lourd et percé doit rester mobile malgré la taille future.", seoTitle: "Strelitzia nicolai : entretien et différence avec alba", seoDescription: "Guide du Strelitzia nicolai : lumière, arrosage, feuilles fendues, culture intérieure et distinction prudente avec alba et « Augusta ».", source: "https://powo.science.kew.org/results?q=Strelitzia%20nicolai" }),
  strelitziaBase({ slug: "reginae", botanicalName: "Strelitzia reginae", displayName: "Strelitzia reginae", species: "reginae", commonNames: ["Oiseau de paradis", "Bird of paradise flower"], subtitle: "L’oiseau de paradis classique, plus compact, célèbre pour ses fleurs orange et bleues.", origin: "Est et sud de l’Afrique du Sud", habitat: "Fourrés, berges et lisières subtropicales d’Afrique du Sud.", description: ["Strelitzia reginae forme une touffe persistante de feuilles épaisses portées par de longs pétioles. Elle reste nettement plus compacte que les espèces arborescentes alba et nicolai.", "Son inflorescence orange et bleue évoque la tête d’un oiseau et explique son nom commun. Un sujet adulte a besoin de beaucoup de lumière pour préparer ses fleurs.", "Plusieurs sous-espèces et formes horticoles existent ; la fiche générale ne doit pas attribuer un cultivar sans étiquette et caractères concordants."], size: "Environ 1,2 à 2 m en culture selon conditions", habit: "Touffe rhizomateuse compacte, sans pseudotronc arborescent", light: "Soleil doux à plein soleil après acclimatation ; très forte lumière nécessaire pour espérer fleurir.", watering: "Régulier en croissance avec séchage partiel ; plus espacé en hiver sans dessécher totalement la motte.", temperature: "Hivernage lumineux et protégé des gelées ; éviter la motte froide et saturée.", comparisons: [{ name: "Strelitzia juncea", difference: "Floraison proche mais juncea adulte porte des pétioles cylindriques au limbe très réduit." }, { name: "Strelitzia nicolai", difference: "Nicolai devient arborescent, beaucoup plus grand et fleurit en blanc plutôt qu’en orange." }], faq: [{ question: "Comment le faire fleurir ?", answer: "Attendez la maturité et offrez soleil progressif, espace racinaire mesuré, nutrition régulière et hiver lumineux ; aucune méthode ne garantit une date." }, { question: "Peut-il rester dehors dans le Nord ?", answer: "Pas sans risque. La culture en pot sorti l’été puis hiverné hors gel reste la méthode la plus sûre." }, { question: "Faut-il couper les feuilles fendues ?", answer: "Non si elles restent vertes et saines. Retirez seulement une feuille très abîmée ou sèche avec un outil propre." }], local: "À Lille, placez-le près de la fenêtre la plus lumineuse et sortez-le progressivement aux beaux jours. Protégez-le des vents qui déchirent les feuilles et rentrez-le avant les nuits froides dans un espace lumineux hors gel.", seoTitle: "Strelitzia reginae : entretien et floraison", seoDescription: "Guide du Strelitzia reginae : lumière, arrosage, substrat, floraison orange, culture en pot et hivernage dans le Nord.", source: "https://powo.science.kew.org/results?q=Strelitzia%20reginae" }),
];

export const agaveFatsiaStrelitziaPlants = [agaveAmericanaVariegata, fatsiaJaponicaSpidersWeb, ...strelitziaPlants];
