const guide = (name: string, botanicalName: string, lead: string, origin: string, sections: { title: string; text: string }[], facts: { label: string; value: string }[]) => ({
  name, image: "/photo-reelle-a-venir.svg", imageAlt: `Photographie réelle de plusieurs ${name} à ajouter`,
  heroSubtitle: lead, care: { difficulty: 3, light: 5, water: 4, humidity: 3, substrate: "Riche, profond et drainant", nutrition: "Soutenue pendant la croissance active" },
  lead, origin, facts, sections,
  problems: [{ title: "Feuilles fendues", text: "Le vent déchire facilement les grands limbes ; un emplacement protégé réduit les dommages." }, { title: "Jaunissement", text: "Contrôlez froid, humidité du mélange, drainage et activité racinaire." }, { title: "Croissance arrêtée", text: "La baisse de lumière et de température ralentit naturellement ces plantes en hiver." }, { title: "Acariens", text: "Surveillez le revers des feuilles pendant l’hivernage intérieur." }],
  faq: [{ question: `Quelle lumière pour un ${name} ?`, answer: "Une lumière très vive soutient le port et la croissance ; acclimatez toujours le feuillage au soleil." }, { question: "Pourquoi les feuilles se fendent-elles ?", answer: "Le limbe se déchire naturellement sous le vent et les frottements. La feuille reste active." }, { question: "Quel substrat utiliser ?", answer: "Un mélange riche et poreux, régulièrement humide en croissance mais drainé en hiver." }, { question: `Quel est son nom botanique ?`, answer: `Le nom de genre retenu est ${botanicalName}. Chaque fiche précise ensuite l’espèce ou le cultivar.` }],
  sources: [{ label: `Kew Science — ${botanicalName}`, url: `https://powo.science.kew.org/results?q=${encodeURIComponent(botanicalName)}` }],
});

export const bananaGuides = {
  bananiers: guide("Bananiers", "Musaceae", "Musa et Ensete réunis dans un univers horticole clair, sans effacer leurs différences botaniques, leur rusticité ni leur mode de multiplication.", "Le mot bananier rassemble plusieurs genres de la famille des Musaceae. Jungle distingue ici Musa, généralement rhizomateux, et Ensete, normalement solitaire.", [
    { title: "Qu’appelle-t-on un bananier ?", text: "Un bananier est une grande herbe et non un arbre. Son pseudo-tronc est formé par des gaines foliaires emboîtées ; le véritable axe reste court et lié à un organe souterrain." },
    { title: "Musa et Ensete ne sont pas interchangeables", text: "Les Musa peuvent former des rejets depuis leur rhizome. Ensete possède une base renflée et reste normalement solitaire ; sa multiplication et son hivernage ne se conduisent donc pas de la même façon." },
    { title: "Pot ou pleine terre", text: "Un grand pot facilite la rentrée des sujets sensibles mais sèche vite. La pleine terre offre davantage d’eau et de volume racinaire, à condition que le drainage hivernal et la rusticité du taxon soient compatibles." },
    { title: "Eau, nourriture et croissance", text: "En saison chaude, les grandes feuilles consomment beaucoup d’eau et de nutriments. Les apports diminuent avec la lumière et la température ; un sol froid et saturé expose les racines à la pourriture." },
    { title: "Vent et feuilles fendues", text: "Les feuilles se fendent le long des nervures secondaires. Ce phénomène n’est pas une maladie ; un emplacement abrité préserve simplement mieux la silhouette." },
    { title: "Hivernage selon l’identité", text: "Musa basjoo peut repartir d’une souche protégée, tandis qu’Ensete ‘Maurelii’ doit être maintenu hors gel. Florida Variegata demande chaleur et lumière ; Red Tiger ne doit pas recevoir automatiquement les seuils de Basjoo." },
  ], [{ label: "Famille", value: "Musaceae" }, { label: "Genres présentés", value: "Musa · Ensete" }, { label: "Croissance", value: "Rapide en saison chaude" }, { label: "Point clé", value: "Identifier avant d’hiverner" }]),
  musa: guide("Musa", "Musa", "Un genre de Musaceae aux pseudo-troncs vigoureux, souvent rhizomateux, dont les espèces et cultivars diffèrent fortement par leur feuillage et leur tolérance au froid.", "Le genre Musa est natif de l’Asie tropicale et subtropicale jusqu’au Pacifique occidental. Les plantes cultivées comprennent des espèces botaniques, des hybrides et de nombreux cultivars.", [
    { title: "Un genre très divers", text: "Musa réunit des plantes alimentaires, textiles et ornementales. Une identité exacte est indispensable : un nom commun de bananier ne permet pas de déduire rusticité, dimensions ou qualité des fruits." },
    { title: "Pseudo-tronc et rhizome", text: "Les gaines foliaires construisent le pseudo-tronc au-dessus d’un organe souterrain. Plusieurs Musa émettent des rejets qui créent une touffe et permettent une multiplication végétative." },
    { title: "Culture active", text: "Lumière, chaleur, eau et nutrition pilotent la vitesse de croissance. Un pot percé, un mélange structuré et un emplacement protégé du vent sont essentiels." },
    { title: "Trois identités Jungle", text: "Basjoo est étudié pour la pleine terre, Red Tiger pour son feuillage marqué et Florida Variegata pour sa panachure. Chacun dispose d’une fiche distincte." },
  ], [{ label: "Famille", value: "Musaceae" }, { label: "Port", value: "Herbacé à pseudo-tronc" }, { label: "Multiplication", value: "Souvent par rejets" }, { label: "Origine du genre", value: "Asie · Pacifique" }]),
  ensete: guide("Ensete", "Ensete", "De grandes Musaceae à base renflée, généralement solitaires, cultivées pour leur silhouette architecturale plutôt que comme des Musa à rejets.", "Le genre Ensete comprend des espèces africaines et asiatiques. Ensete ventricosum est natif d’Afrique et ‘Maurelii’ en est une sélection ornementale pourpre.", [
    { title: "Ce qui distingue Ensete", text: "La base du pseudo-tronc est renflée, les bractées de l’inflorescence persistent et la plante ne drageonne normalement pas. Cette biologie interdit de copier les conseils de multiplication d’un Musa." },
    { title: "Une plante architecturale", text: "Ensete construit une rosette massive de feuilles. En pot comme en pleine terre estivale, il demande stabilité, eau et nutrition pendant la croissance." },
    { title: "Hivernage hors gel", text: "Sous le climat lillois, Maurelii doit être rentré avant les gelées. Plus l’hivernage est frais et sombre, plus l’arrosage doit être réduit." },
    { title: "Multiplication particulière", text: "Le semis ne reproduit pas fidèlement un cultivar. Les techniques de multiplication induite sont spécialisées et ne doivent pas être présentées comme une simple séparation de rejets." },
  ], [{ label: "Famille", value: "Musaceae" }, { label: "Port", value: "Rosette solitaire" }, { label: "Rejets", value: "Normalement absents" }, { label: "Hivernage", value: "Hors gel" }]),
};
