import type { PlantEntry } from "./types";
import { prayerPlants } from "./prayer-plants";

export const plantFamilies = [
  { slug: "alocasia", name: "Alocasia", eyebrow: "Collection ouverte", description: "Plantes tropicales architecturales aux feuilles spectaculaires, les Alocasia aiment la lumière vive, la chaleur et un substrat très aéré. Découvrez nos conseils de culture et les Alocasia rares observés au Studio Végétal Tibaldo Jungle à Lille.", image: "/alocasia-cuprea-feuillage.jpg", imageAlt: "Feuillage nervuré vert métallique d’un Alocasia cuprea", available: true },
  { slug: "anthurium", name: "Anthurium", eyebrow: "Guide disponible", description: "Des Anthurium d’intérieur fleuris aux espèces botaniques aux feuilles veloutées, ce genre révèle une diversité exceptionnelle. Notre guide détaille lumière, humidité, arrosage et substrat pour cultiver un Anthurium de collection à Lille.", image: "/anthurium-crystallinum-feuille.jpg", imageAlt: "Grande feuille veloutée et nervurée d’Anthurium crystallinum", available: true },
  { slug: "monstera", name: "Monstera", eyebrow: "Guide disponible", description: "Célèbres pour leurs feuilles découpées et leurs fenestrations, les Monstera deviennent de véritables plantes-sculptures lorsqu’ils peuvent grimper. Retrouvez les variétés classiques et rares, ainsi que nos conseils d’entretien adaptés aux intérieurs lillois.", image: "/monstera-deliciosa-feuilles.jpg", imageAlt: "Feuilles découpées et fenêtrées de Monstera deliciosa", available: true },
  { slug: "philodendron", name: "Philodendron", eyebrow: "Guide disponible", description: "Grimpants, rampants ou autoportants, les Philodendron offrent une incroyable palette de formes, de couleurs et de textures. Tibaldo Jungle documente leur croissance, leur rempotage et les bons substrats pour réussir leur culture à Lille.", image: "/philodendron-hastatum-feuillage.jpg", imageAlt: "Feuillage argenté lancéolé de Philodendron hastatum", available: true },
  { slug: "epipremnum", name: "Epipremnum", eyebrow: "Guide disponible", description: "Souvent appelés pothos, les Epipremnum sont des lianes tropicales accessibles qui développent de grandes feuilles lorsqu’elles grimpent dans de bonnes conditions. Découvrez comment améliorer leur lumière, leur tuteurage et leur croissance en intérieur à Lille.", image: "/epipremnum-aureum-pothos.jpg", imageAlt: "Liane panachée d’Epipremnum aureum, aussi appelée pothos doré", available: true },
  { slug: "colocasia", name: "Colocasia", eyebrow: "Guide disponible", description: "Avec leurs immenses feuilles en oreilles d’éléphant, les Colocasia aiment l’eau, la chaleur et une nutrition généreuse pendant leur croissance. Notre guide explique leur culture en pot, leur saison extérieure et leur hivernage sous le climat de Lille.", image: "/colocasia-esculenta-feuille.jpg", imageAlt: "Grande feuille en cœur de Colocasia esculenta, oreille d’éléphant", available: true },
  { slug: "pilea", name: "Pilea", eyebrow: "Espèce documentée", description: "Le genre Pilea rassemble la plante à monnaie chinoise et de nombreuses espèces compactes, rampantes ou texturées. Apprenez à cultiver, tourner et multiplier le Pilea peperomioides, une plante d’intérieur graphique disponible selon les arrivages à Lille.", image: "/pilea-peperomioides-plante.jpg", imageAlt: "Pilea peperomioides en pot avec feuilles rondes et jeunes rejets", available: true },
  { slug: "peperomia", name: "Peperomia", eyebrow: "Guide disponible", description: "Compacts et graphiques, les Peperomia séduisent par leurs feuilles charnues, gaufrées, argentées ou panachées. Découvrez leurs besoins en lumière, leur arrosage modéré et les mélanges drainants conseillés par Tibaldo Jungle à Lille.", image: "/peperomia-argyreia-feuillage.jpg", imageAlt: "Feuillage rayé argent et vert de Peperomia argyreia", available: true },
  { slug: "cactus", name: "Cactus", eyebrow: "Nouvel univers", description: "Des cactus miniatures aux grands cierges sculpturaux, les Cactaceae réunissent des plantes adaptées à la sécheresse mais exigeantes en lumière. Découvrez comment choisir, arroser, rempoter et faire refleurir un cactus dans un intérieur à Lille.", image: "/cactus-collection-serre.jpg", imageAlt: "Collection de cactus globulaires et colonnaires cultivés sous une serre lumineuse", available: true },
  { slug: "maranta", name: "Maranta", eyebrow: "Plantes qui prient", description: "Les Maranta déploient des feuillages peints de nervures rouges, de taches sombres et de nuances veloutées. Découvrez comment préserver leurs couleurs, comprendre le mouvement quotidien de leurs feuilles et réussir leur culture dans un intérieur à Lille.", image: "/maranta-leuconeura-tibaldo.png", imageAlt: "Maranta leuconeura mature aux feuilles vertes marquées de nervures rouges", available: true },
  { slug: "calathea", name: "Calathea", eyebrow: "Feuillages graphiques", description: "Calathea reste le nom horticole familier de nombreuses plantes aujourd’hui classées dans le genre Goeppertia. Leurs grandes feuilles rayées, rondes ou dessinées demandent lumière douce, chaleur stable et arrosage attentif.", image: "/calathea-orbifolia-tibaldo.png", imageAlt: "Calathea orbifolia aux grandes feuilles rondes rayées de vert argenté", available: true },
] as const;

export const plants = [{
  slug: "imperial-red", genre: "alocasia", genreLabel: "Alocasia", botanicalName: "Alocasia ‘Imperial Red’", displayName: "Imperial Red",
  subtitle: "Une Alocasia architecturale aux pétioles rouge bordeaux.", family: "Araceae", origin: "Hybride horticole tropical",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Alocasia", species: "Hybride horticole", cultivar: "Imperial Red", commonNames: ["Oreille d’éléphant Imperial Red", "Alocasia à pétioles rouges"] },
  filters: { temperatureMin: 15, temperatureIdeal: [18, 28], humidityIdeal: [60, 80], light: "vive", watering: "régulier", substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "rapide", habits: ["terrestre", "dressé"], adultSizeCm: 250, needsSupport: false, variegated: false, collection: true, flowering: false, petToxic: true, humanToxic: true, regions: ["Asie tropicale", "Océanie"] },
  habitat: "Hybride horticole issu d’espèces terrestres des forêts tropicales humides, cultivé dans une lumière filtrée et un sol organique très respirant.",
  hybridization: "Alocasia odora × Alocasia macrorrhizos ‘Pink Petiole’, hybridation attribuée à LariAnn Garner.",
  synonyms: ["Alocasia × ‘Imperial Red’", "Imperial Red Elephant Ear"],
  description: [
    "Alocasia ‘Imperial Red’ est une grande plante tropicale au port dressé. Ses larges feuilles vertes sont portées par des pétioles qui prennent, avec la maturité et une lumière adaptée, des nuances rouges, roses puis bordeaux.",
    "Plus vigoureuse que de nombreuses Alocasia compactes, elle devient une véritable plante-sculpture. Elle demande surtout de la lumière, de la chaleur et un substrat respirant : ses racines apprécient une humidité régulière, jamais une terre durablement détrempée.",
  ],
  specimen: { observedHeight: "Environ 160 cm", note: "Hauteur observée sur le spécimen suivi par Tibaldo Jungle. La taille varie selon la lumière, le volume racinaire et les conditions de culture." },
  growth: { adultSize: "Grand développement · souvent 150 à 250 cm en intérieur favorable", speed: "Rapide en période chaude et lumineuse", habit: "Dressé, ample et architectural" },
  care: {
    light: 4, water: 3, humidity: 4, difficulty: 3,
    lightText: "Lumière vive et indirecte. Un soleil doux du matin est possible après acclimatation.",
    watering: "Arroser lorsque les premiers centimètres du mélange commencent à sécher. Vider l’eau du cache-pot et réduire en hiver.",
    humidityText: "Une humidité moyenne à élevée limite les bords secs, avec une circulation d’air indispensable.",
    temperature: "Idéalement 18 à 28 °C. Éviter les courants d’air et les températures durablement inférieures à 15 °C.",
    substrate: "Mélange riche et aéré : terreau structuré, écorce, chips de coco et pierre ponce ou perlite. Pot percé obligatoire.",
    repotting: "Rempoter au printemps lorsque les racines occupent le pot. Choisir seulement une taille au-dessus.",
    fertilizing: "De mars à septembre, engrais équilibré à demi-dose toutes les deux à quatre semaines sur substrat humide.",
    propagation: "Séparation des rejets ou des cormes lors du rempotage, lorsque chaque division possède des racines actives.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et des animaux.", details: "Les Alocasia contiennent des cristaux insolubles d’oxalate de calcium. La mastication peut provoquer irritation, douleur, salivation, gonflement et difficulté à avaler. En cas d’ingestion, contacter rapidement un professionnel de santé ou un vétérinaire." },
  problems: [
    { title: "Feuilles jaunes", cause: "Excès d’eau, refroidissement des racines ou renouvellement naturel.", advice: "Contrôler le drainage et les racines avant d’arroser davantage." },
    { title: "Bords secs", cause: "Air sec, arrosages irréguliers, sels ou chauffage.", advice: "Stabiliser l’arrosage, éloigner du chauffage et rincer ponctuellement le substrat." },
    { title: "Pétioles très allongés", cause: "Lumière insuffisante ou fenêtre située d’un seul côté.", advice: "Rapprocher progressivement la plante de la lumière et tourner le pot." },
    { title: "Thrips", cause: "Insectes laissant plages argentées, déformations et points noirs.", advice: "Isoler, doucher les feuilles et répéter un traitement adapté plusieurs semaines." },
    { title: "Araignées rouges", cause: "Acariens favorisés par l’air chaud et sec.", advice: "Inspecter l’envers des feuilles, isoler, doucher et maintenir une meilleure humidité." },
    { title: "Pourriture", cause: "Substrat compact, pot trop grand, eau stagnante ou froid.", advice: "Retirer les parties molles et rempoter dans un mélange plus respirant." },
  ],
  comparisons: [
    { name: "Alocasia ‘Dark Star’", difference: "La face inférieure des feuilles matures montre généralement une nervation sombre plus marquée." },
    { name: "Alocasia ‘Regal Shields’", difference: "Feuillage plus sombre et velouté, avec un contraste différent entre dessus et revers." },
    { name: "Alocasia macrorrhizos", difference: "Espèce parente de très grand développement, moins caractérisée par les pétioles bordeaux." },
  ],
  faq: [
    { question: "L’Alocasia Imperial Red est-elle une espèce naturelle ?", answer: "Non. Elle est généralement décrite comme un hybride horticole entre Alocasia odora et une forme d’Alocasia macrorrhizos à pétioles roses." },
    { question: "Pourquoi ses pétioles ne sont-ils pas encore rouges ?", answer: "Les jeunes sujets peuvent être plus verts. La génétique, la maturité et une lumière vive influencent les pigments." },
    { question: "Peut-elle dépasser 150 cm ?", answer: "Oui. Le spécimen suivi par Tibaldo Jungle atteint environ 160 cm et de bonnes conditions peuvent produire des sujets imposants." },
    { question: "À quelle fréquence faut-il l’arroser ?", answer: "Il n’existe pas de calendrier fixe. Arrosez lorsque la surface commence à sécher, puis laissez l’excédent s’écouler." },
    { question: "Faut-il vaporiser les feuilles ?", answer: "La vaporisation agit très brièvement. Un humidificateur et une bonne ventilation sont plus réguliers." },
    { question: "Pourquoi perd-elle une feuille quand une nouvelle apparaît ?", answer: "Un jeune sujet peut maintenir peu de feuilles. Si la croissance et les racines sont saines, cela peut être normal." },
    { question: "Quel pot choisir ?", answer: "Un pot percé, stable et seulement légèrement plus grand que la motte." },
    { question: "Est-elle adaptée aux animaux ?", answer: "Non. Les Alocasia sont toxiques par ingestion pour les chats et les chiens." },
  ],
  tibaldoAdvice: ["Ne rempotez pas automatiquement après l’achat : observez d’abord les racines et le rythme de séchage.", "Pour un port dense, privilégiez une lumière franche plutôt qu’une humidité extrême.", "Nettoyez les grandes feuilles : la plante travaille mieux et les parasites deviennent visibles."],
  gallery: [
    { src: "/alocasia-imperial-red.png", alt: "Alocasia Imperial Red mature aux larges feuilles vertes et pétioles bordeaux", caption: "Interprétation éditoriale de l’Alocasia ‘Imperial Red’ — photographies du spécimen du Studio à venir.", width: 1024, height: 1536 },
    { src: "/hero-jungle.jpg", alt: "Grande plante tropicale dans un intérieur lumineux", caption: "Une lumière vive favorise un port plus dense.", width: 2000, height: 1333 },
    { src: "/advice-rempotage.jpg", alt: "Conseil de rempotage pour une plante tropicale", caption: "Le volume du pot et l’aération du mélange sont déterminants.", width: 1200, height: 1800 },
  ],
  seo: { title: "Alocasia Imperial Red : entretien et pétioles rouges", description: "Entretien de l’Alocasia Imperial Red : lumière, arrosage, substrat, toxicité et problèmes. Découvrez notre spécimen de 160 cm à Lille.", keywords: ["Alocasia Imperial Red entretien", "Alocasia pétioles rouges", "Alocasia Lille", "plante XXL Lille"] },
  sources: [{ label: "NC State Extension", url: "https://plants.ces.ncsu.edu/plants/alocasia/common-name/alocasia/" }, { label: "ASPCA", url: "https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/alocasia" }, { label: "Aroidpedia", url: "https://www.aroidpedia.com/journal/alocasia-imperial-red" }],
  publishedAt: "2026-08-06", updatedAt: "2026-08-06",
}, {
  slug: "jacklyn", genre: "alocasia", genreLabel: "Alocasia", botanicalName: "Alocasia sp. ‘Jacklyn’", displayName: "Jacklyn",
  subtitle: "Une Alocasia de Sulawesi aux feuilles profondément découpées et aux pétioles zébrés.", family: "Araceae", origin: "Sulawesi · Indonésie",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Alocasia", species: "Espèce non formellement résolue", cultivar: "Jacklyn", commonNames: ["Alocasia Jacklyn", "Alocasia de Sulawesi"] },
  filters: { temperatureMin: 16, temperatureIdeal: [19, 28], humidityIdeal: [60, 80], light: "vive", watering: "régulier", substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "moyenne", habits: ["terrestre", "dressé"], adultSizeCm: 150, needsSupport: false, variegated: false, collection: true, flowering: false, petToxic: true, humanToxic: true, regions: ["Sulawesi", "Indonésie", "Asie tropicale"] },
  habitat: "Cette Alocasia est associée aux forêts tropicales humides de Sulawesi. En intérieur, elle apprécie une ambiance chaude, lumineuse et stable, avec un mélange racinaire très respirant.",
  hybridization: "Aucune origine hybride reconnue n’est documentée. L’identité botanique reste prudemment présentée sous Alocasia sp. ‘Jacklyn’ : le nom « Tandurusa » circule dans le commerce horticole, sans être actuellement reconnu comme espèce acceptée dans GBIF.",
  synonyms: ["Alocasia sp. Sulawesi ‘Jacklyn’", "Alocasia ‘Jacklyn’", "nom commercial parfois associé à « Tandurusa »"],
  description: [
    "Alocasia sp. ‘Jacklyn’ attire immédiatement le regard par ses feuilles sagittées, profondément découpées et presque dentelées. Leur surface mate, légèrement texturée, souligne un réseau de nervures sombres qui donne au feuillage un caractère très graphique.",
    "Ses pétioles striés de vert et de brun renforcent sa silhouette singulière. Plus exigeante qu’une plante verte classique, elle reste accessible lorsque la lumière est franche, la température stable et les racines maintenues dans un substrat aéré plutôt que constamment humide.",
  ],
  specimen: { observedHeight: "Environ 60 à 120 cm en intérieur", note: "La taille dépend fortement de la lumière, de la chaleur, du volume racinaire et de la durée de culture. Un sujet mature peut devenir nettement plus ample." },
  growth: { adultSize: "Port moyen à grand · souvent 80 à 150 cm en intérieur favorable", speed: "Moyenne, plus active au printemps et en été", habit: "Dressé, ouvert et sculptural" },
  care: {
    light: 4, water: 3, humidity: 4, difficulty: 4,
    lightText: "Lumière vive indirecte. Un soleil doux du matin peut convenir après une acclimatation progressive.",
    watering: "Arroser généreusement lorsque les premiers centimètres du mélange ont commencé à sécher, puis laisser l’excédent s’écouler.",
    humidityText: "Une humidité de 60 à 80 % favorise un beau feuillage, à condition de conserver une circulation d’air régulière.",
    temperature: "Idéalement 19 à 28 °C. Éviter le froid, les courants d’air et les écarts brutaux de température.",
    substrate: "Mélange très aéré pour aroïdes : terreau structuré, écorce de pin, chips de coco et pierre ponce ou perlite.",
    repotting: "Rempoter lorsque les racines occupent réellement le pot. Choisir un contenant percé, stable et seulement une taille au-dessus.",
    fertilizing: "Au printemps et en été, apporter un engrais équilibré dilué toutes les trois à quatre semaines sur un substrat déjà humide.",
    propagation: "Séparation des rejets ou des cormes au moment du rempotage, lorsque chaque division possède des racines actives.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et des animaux.", details: "Comme les autres Alocasia, Jacklyn contient des cristaux insolubles d’oxalate de calcium. La mastication peut provoquer irritation, douleur, salivation et difficulté à avaler. En cas d’ingestion, contacter un professionnel de santé ou un vétérinaire." },
  problems: [
    { title: "Feuilles jaunes", cause: "Excès d’eau, racines froides ou vieillissement naturel d’une feuille.", advice: "Contrôler l’humidité du mélange et l’état des racines avant d’arroser à nouveau." },
    { title: "Bords secs", cause: "Air sec, arrosages irréguliers ou accumulation de sels.", advice: "Stabiliser l’arrosage, éloigner du chauffage et rincer ponctuellement le substrat." },
    { title: "Feuilles recroquevillées", cause: "Manque d’eau, chaleur sèche, froid ou lumière trop brutale.", advice: "Vérifier successivement le substrat, la température et l’exposition plutôt que de corriger au hasard." },
    { title: "Thrips", cause: "Insectes laissant plages argentées, déformations et petits points noirs.", advice: "Isoler la plante, doucher le feuillage et répéter un traitement adapté pendant plusieurs semaines." },
    { title: "Araignées rouges", cause: "Acariens favorisés par une atmosphère chaude et sèche.", advice: "Inspecter l’envers des feuilles, isoler, doucher et améliorer progressivement l’humidité." },
    { title: "Pourriture", cause: "Mélange compact, eau stagnante, pot trop grand ou température trop basse.", advice: "Retirer les parties molles et rempoter dans un substrat plus aéré avec un pot percé." },
  ],
  comparisons: [
    { name: "Alocasia sanderiana", difference: "Ses feuilles sont plus étroites et brillantes, avec une nervation blanche très contrastée et des pétioles différents." },
    { name: "Alocasia ‘Polly’", difference: "Elle reste plus compacte et présente des feuilles anguleuses, brillantes, bordées de nervures claires." },
    { name: "Alocasia ‘Sarian’", difference: "Elle possède aussi des pétioles zébrés, mais ses feuilles sont généralement moins profondément découpées que celles de Jacklyn." },
  ],
  faq: [
    { question: "Faut-il écrire Jacklyn ou Jacqueline ?", answer: "Le nom horticole couramment utilisé est Jacklyn. « Jacqueline » est une confusion phonétique fréquente, mais ce n’est pas le nom sous lequel cette plante est commercialisée." },
    { question: "Alocasia tandurusa est-il le nom botanique correct ?", answer: "Le nom Tandurusa circule dans le commerce horticole, mais il n’est pas actuellement reconnu comme espèce acceptée dans GBIF. Tibaldo Jungle utilise donc la formulation prudente Alocasia sp. ‘Jacklyn’." },
    { question: "Pourquoi les feuilles de l’Alocasia Jacklyn se recroquevillent-elles ?", answer: "Cela peut venir d’un manque d’eau, d’un air trop sec, du froid ou d’une exposition trop forte. Il faut observer le substrat et l’environnement avant d’agir." },
    { question: "Quelle lumière faut-il à l’Alocasia Jacklyn ?", answer: "Une lumière vive indirecte favorise des feuilles compactes et bien dessinées. Évitez le soleil brûlant derrière une vitre sans acclimatation." },
    { question: "Quel substrat utiliser ?", answer: "Un mélange pour aroïdes très aéré, associant terreau structuré, écorce, coco et pierre ponce ou perlite, dans un pot percé." },
    { question: "L’Alocasia Jacklyn aime-t-elle l’humidité ?", answer: "Oui, une humidité moyenne à élevée lui convient, mais elle doit être accompagnée d’une bonne ventilation pour limiter les maladies." },
    { question: "L’Alocasia Jacklyn est-elle toxique ?", answer: "Oui. Comme les autres Alocasia, elle est irritante et toxique par ingestion pour les enfants, les chats et les chiens." },
    { question: "Où trouver une Alocasia Jacklyn à Lille ?", answer: "Tibaldo Jungle peut proposer des Alocasia rares selon les arrivages au Studio Végétal de Lille, avec conseils et rempotage gratuit." },
  ],
  tibaldoAdvice: ["Observez d’abord la vitesse de séchage du pot : une Jacklyn supporte mieux un léger ressuyage qu’un mélange étouffé.", "Nettoyez doucement le feuillage texturé et inspectez les creux des nervures, où les parasites peuvent rester discrets.", "Ne recherchez pas une humidité extrême au détriment de l’air : stabilité, lumière et racines saines restent prioritaires."],
  gallery: [
    { src: "/alocasia-jacklyn-tibaldo.png", alt: "Alocasia Jacklyn aux feuilles profondément découpées et aux pétioles zébrés", caption: "Portrait éditorial de l’Alocasia sp. ‘Jacklyn’, caractérisée par son feuillage découpé.", width: 1024, height: 1536 },
    { src: "/alocasia-jacklyn-tibaldo.png", alt: "Feuilles texturées et nervures sombres de l’Alocasia Jacklyn", caption: "La texture mate et les nervures sombres renforcent son caractère graphique.", width: 1024, height: 1536 },
    { src: "/advice-rempotage.jpg", alt: "Rempotage d’une Alocasia Jacklyn dans un substrat aéré", caption: "Un pot percé et un mélange respirant protègent ses racines sensibles.", width: 1200, height: 1800 },
  ],
  seo: { title: "Alocasia Jacklyn : entretien, lumière et feuilles découpées", description: "Guide de l’Alocasia Jacklyn : lumière, arrosage, substrat, humidité, toxicité et différences. Conseils Tibaldo Jungle à Lille.", keywords: ["Alocasia Jacklyn entretien", "Jacklyn ou Jacqueline", "Alocasia Sulawesi", "Alocasia Lille", "Alocasia Tandurusa"] },
  sources: [{ label: "GBIF — vérification taxonomique", url: "https://api.gbif.org/v1/species/match?name=Alocasia%20tandurusa" }, { label: "NC State Extension", url: "https://plants.ces.ncsu.edu/plants/alocasia/common-name/alocasia/" }, { label: "ASPCA", url: "https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/alocasia" }],
  publishedAt: "2026-08-09", updatedAt: "2026-08-09",
}, {
  slug: "peperomioides", genre: "pilea", genreLabel: "Pilea", botanicalName: "Pilea peperomioides", displayName: "Peperomioides",
  subtitle: "La plante à monnaie chinoise, graphique, généreuse et facile à partager.", family: "Urticaceae", origin: "Sud-ouest de la Chine · Sichuan et Yunnan",
  taxonomy: { order: "Rosales", family: "Urticaceae", genus: "Pilea", species: "Pilea peperomioides", cultivar: null, commonNames: ["Plante à monnaie chinoise", "Plante missionnaire", "Plante de l’amitié"] },
  filters: { temperatureMin: 10, temperatureIdeal: [16, 26], humidityIdeal: [40, 65], light: "vive", watering: "modéré", substrateTags: ["léger", "drainant", "plantes vertes"], growthRate: "rapide", habits: ["terrestre", "dressé"], adultSizeCm: 40, needsSupport: false, variegated: false, collection: false, flowering: true, petToxic: false, humanToxic: false, regions: ["Chine", "Asie"] },
  habitat: "Sous-bois rocheux et humides du sud-ouest de la Chine, notamment dans les provinces du Sichuan et du Yunnan, à une altitude où la lumière reste filtrée.",
  hybridization: "Espèce botanique décrite par Ludwig Diels en 1912.", synonyms: ["Plante à monnaie chinoise", "Plante missionnaire", "Chinese money plant"],
  description: ["Pilea peperomioides se reconnaît à ses feuilles rondes et peltées : le pétiole rejoint presque le centre du limbe, comme sur un petit nénuphar suspendu.", "Avec le temps, son tronc s’allonge et la plante produit de nombreux rejets à sa base. Cette générosité lui vaut aussi le surnom de plante de l’amitié : chaque rejet peut devenir une nouvelle plante à transmettre."],
  specimen: { observedHeight: "Environ 20 à 35 cm", note: "La hauteur dépend de l’âge, de la lumière et de la conduite du tronc. Tourner régulièrement le pot aide à conserver une silhouette équilibrée." },
  growth: { adultSize: "Port compact · généralement 20 à 40 cm en intérieur", speed: "Rapide en saison lumineuse", habit: "Dressé, arrondi puis légèrement arborescent" },
  care: { light: 4, water: 3, humidity: 2, difficulty: 1, lightText: "Lumière vive indirecte, avec soleil doux possible après acclimatation.", watering: "Arroser lorsque la surface du mélange sèche, puis laisser égoutter complètement.", humidityText: "L’humidité normale d’un logement lui convient ; éviter surtout l’air brûlant d’un radiateur.", temperature: "Idéalement 16 à 26 °C, loin des courants d’air froid et des fortes sources de chaleur.", substrate: "Terreau léger et drainant, enrichi de perlite ou pierre ponce. Pot percé indispensable.", repotting: "Rempoter quand les racines occupent le contenant, dans un pot seulement légèrement plus grand.", fertilizing: "Engrais plantes vertes à faible dose toutes les trois à quatre semaines pendant la croissance active.", propagation: "Séparation des rejets racinaires ou bouture de tige au printemps et en été." },
  toxicity: { level: "non toxique selon les références horticoles usuelles", summary: "Généralement considérée comme compatible avec chats et chiens.", details: "Une plante non toxique n’est pas destinée à être consommée. Éloignez-la d’un animal qui mâchouille régulièrement le feuillage et demandez conseil à un vétérinaire en cas de symptômes." },
  problems: [{ title: "Port penché", cause: "La plante se dirige naturellement vers la lumière.", advice: "Tourner le pot d’un quart de tour régulièrement." }, { title: "Feuilles qui retombent", cause: "Manque d’eau, excès d’eau ou racines refroidies.", advice: "Vérifier le substrat et les racines avant d’arroser automatiquement." }, { title: "Taches ou brûlures", cause: "Soleil trop brutal ou feuillage mouillé trop longtemps.", advice: "Acclimater progressivement et arroser directement le substrat." }, { title: "Tige très longue", cause: "Lumière insuffisante ou vieillissement naturel.", advice: "Augmenter la lumière ou rajeunir la plante par bouturage." }],
  comparisons: [{ name: "Peperomia polybotrya", difference: "Feuilles plus épaisses et forme en goutte ; elle appartient aux Piperaceae, pas aux Urticaceae." }, { name: "Pilea depressa", difference: "Port rampant et feuilles minuscules, souvent cultivée en suspension ou terrarium." }, { name: "Pilea cadierei", difference: "Feuilles ovales ornées de plages argentées, avec un port plus ramifié." }],
  faq: [{ question: "Pourquoi tourner un Pilea peperomioides ?", answer: "Ses feuilles s’orientent vers la fenêtre. Une rotation régulière aide à maintenir une couronne plus homogène." }, { question: "À quelle fréquence l’arroser ?", answer: "Il n’existe pas de calendrier universel. Arrosez lorsque la surface sèche et adaptez selon la lumière, la température et la saison." }, { question: "Comment séparer les bébés Pilea ?", answer: "Attendez qu’un rejet soit suffisamment développé, prélevez-le avec quelques racines puis placez-le dans un petit pot drainant." }, { question: "Le Pilea peperomioides est-il un Peperomia ?", answer: "Non. Son nom signifie qu’il ressemble à un Peperomia, mais il appartient au genre Pilea et à la famille des Urticaceae." }, { question: "Le Pilea est-il adapté aux animaux ?", answer: "Il est généralement considéré comme non toxique pour les chats et les chiens, sans être comestible." }, { question: "Où trouver un Pilea peperomioides à Lille ?", answer: "Tibaldo Jungle propose progressivement des Pilea au Studio Végétal de Lille, avec conseils et rempotage gratuit." }],
  tibaldoAdvice: ["Tournez le pot régulièrement plutôt que de chercher une symétrie parfaite en une seule fois.", "Ne séparez pas tous les rejets : quelques jeunes plants donnent une silhouette plus dense.", "Un pot trop grand reste humide trop longtemps ; préférez une progression douce."],
  gallery: [{ src: "/pilea-peperomioides.png", alt: "Pilea peperomioides mature aux feuilles rondes dans un pot en céramique", caption: "Interprétation éditoriale du Pilea peperomioides — photographies du spécimen du Studio à venir.", width: 1024, height: 1536 }, { src: "/pilea-peperomioides.png", alt: "Feuillage rond et pelté du Pilea peperomioides", caption: "Les pétioles rejoignent le centre des feuilles rondes.", width: 1024, height: 1536 }, { src: "/pilea-peperomioides.png", alt: "Pilea peperomioides avec rejets au pied", caption: "Les rejets permettent de multiplier facilement la plante.", width: 1024, height: 1536 }],
  seo: { title: "Pilea peperomioides : entretien et plante à monnaie Lille", description: "Guide du Pilea peperomioides : lumière, arrosage, rejets, substrat et problèmes. Retrouvez la plante à monnaie chinoise à Lille.", keywords: ["Pilea peperomioides entretien", "plante monnaie chinoise Lille", "Pilea Lille", "Pilea animaux", "bouture Pilea"] },
  sources: [{ label: "Kew Science", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:855664-1/general-information" }, { label: "NC State Extension", url: "https://plants.ces.ncsu.edu/plants/pilea-peperomioides/" }, { label: "Plantes Pour Tous — fiche consultée", url: "https://plantespourtous.co/products/pilea-peperomioides" }],
  publishedAt: "2026-08-06", updatedAt: "2026-08-06",
}, ...prayerPlants] satisfies PlantEntry[];

export const plantGenres = Array.from(new Set(plants.map((plant) => plant.genre)));
export const getPlant = (genre: string, slug: string) => plants.find((plant) => plant.genre === genre && plant.slug === slug);
export const getPlantsByGenre = (genre: string) => plants.filter((plant) => plant.genre === genre);
