import type { PlantEntry } from "./types";

export const cycasRevoluta: PlantEntry = {
  slug: "revoluta",
  genre: "cycas",
  genreLabel: "Cycas",
  botanicalName: "Cycas revoluta",
  displayName: "Cycas du Japon",
  listingName: "Cycas revoluta · Cycas du Japon",
  subtitle: "Une cycadale sculpturale, très ancienne dans sa lignée, mais résolument vivante : lente, solaire et exigeante sur le drainage.",
  family: "Cycadaceae",
  origin: "Sud-est de la Chine, sud du Japon et Taïwan",
  taxonomy: {
    order: "Cycadales",
    family: "Cycadaceae",
    genus: "Cycas",
    species: "Cycas revoluta",
    cultivar: null,
    commonNames: ["Cycas du Japon", "Sagoutier du Japon", "Sago palm"],
  },
  filters: {
    temperatureMin: 2,
    temperatureIdeal: [15, 27],
    humidityIdeal: [40, 65],
    light: "soleil",
    watering: "faible",
    substrateTags: ["minéral", "drainant", "extérieur", "cycadales"],
    growthRate: "lente",
    habits: ["terrestre", "dressé"],
    adultSizeCm: 250,
    needsSupport: false,
    variegated: false,
    collection: true,
    flowering: false,
    petToxic: true,
    humanToxic: true,
    regions: ["Chine", "Japon", "Taïwan", "Asie subtropicale"],
  },
  habitat: "Cycas revoluta est originaire du sud-est de la Chine, du sud du Japon — notamment Kyushu et les îles Ryukyu — et de Taïwan. Il pousse dans des milieux subtropicaux lumineux, sur des pentes, falaises et sols bien drainés où ses racines ne restent pas durablement saturées.",
  hybridization: "Espèce botanique acceptée, publiée par Carl Peter Thunberg. C’est une gymnosperme dioïque de l’ordre des Cycadales : malgré sa silhouette et plusieurs noms usuels, elle n’est ni un palmier ni une fougère.",
  synonyms: ["Cycas revoluta Thunb.", "Cycas du Japon", "Sagoutier du Japon"],
  description: [
    "Cycas revoluta forme une couronne très régulière de frondes pennées, coriaces et vert sombre au sommet d’un tronc court appelé caudex. Les folioles étroites ont des bords fortement révolutés — repliés vers le dessous — à l’origine de l’épithète revoluta.",
    "Sa croissance n’est pas continue. La plante peut rester immobile plusieurs mois, puis produire en une seule poussée un cercle complet de nouvelles frondes tendres. Celles-ci durcissent progressivement ; pendant ce déploiement, la lumière doit rester homogène pour éviter une couronne déformée.",
    "Les cycadales appartiennent à une lignée de gymnospermes apparue bien avant les plantes à fleurs. Cette ancienneté évolutive n’en fait pas un fossile figé : Cycas revoluta est une espèce actuelle, dotée d’un fonctionnement propre, notamment de racines coralloïdes associées à des microorganismes fixateurs d’azote.",
    "L’espèce est dioïque : les structures reproductrices mâles et femelles sont portées par des individus distincts. Les graines ne peuvent donc apparaître qu’après pollinisation d’un sujet femelle par le pollen d’un sujet mâle.",
  ],
  specimen: {
    observedHeight: "Sujet Tibaldo cultivé dehors en pot",
    note: "Les photographies montrent le même sujet au jardin, dans son pot de culture puis dans un contenant bleu. Sa croissance lente et sa couronne dense sont observées sans extrapoler une rusticité universelle.",
  },
  growth: {
    adultSize: "Souvent 1 à 2,5 m en culture, beaucoup plus lentement qu’un palmier",
    speed: "Très lente, par poussées de frondes espacées",
    habit: "Caudex dressé surmonté d’une couronne symétrique de frondes",
  },
  care: {
    light: 5,
    water: 2,
    humidity: 2,
    difficulty: 3,
    lightText: "Lumière très vive à soleil direct après acclimatation progressive. Un sujet déplacé brutalement de l’ombre au plein soleil peut brûler ; une lumière insuffisante produit des frondes longues, pâles et déséquilibrées.",
    watering: "Arroser profondément, puis attendre qu’une large partie du mélange sèche avant de recommencer. Réduire fortement lorsque la croissance et l’évaporation ralentissent. Ne jamais laisser d’eau dans un cache-pot ou une soucoupe.",
    humidityText: "L’humidité ordinaire de l’air lui convient. La priorité n’est pas une atmosphère tropicale saturée, mais une bonne circulation d’air et des racines oxygénées, surtout lorsque les températures baissent.",
    temperature: "Croissance confortable autour de 15 à 27 °C. Un sujet adulte, sec, abrité et acclimaté peut supporter de brèves gelées légères, mais les frondes sont plus vulnérables que le caudex. En pot, les racines refroidissent vite : sous le climat lillois, protéger du gel durable et de l’humidité hivernale.",
    substrate: "Mélange très drainant et stable : terreau structuré en proportion mesurée, pouzzolane, pierre ponce ou perlite grossière, et écorce. Le pot doit être percé et suffisamment lourd pour stabiliser la couronne.",
    repotting: "Rempoter rarement, lorsque les racines occupent réellement le pot ou que le mélange s’est dégradé. Choisir un contenant à peine plus large, préserver les racines charnues et maintenir le caudex au-dessus du niveau du substrat.",
    fertilizing: "Pendant une croissance active, utiliser un engrais équilibré à faible dose toutes les quatre à six semaines sur substrat humide. Éviter les apports excessifs : cette plante lente ne doit pas être forcée.",
    propagation: "Semis de graines fraîches et correctement identifiées, avec de fortes précautions en raison de leur toxicité, ou séparation prudente de rejets déjà enracinés. La production de graines exige un sujet mâle, un sujet femelle et une pollinisation réussie.",
  },
  toxicity: {
    level: "toxicité élevée par ingestion",
    summary: "Toutes les parties sont toxiques ; les graines sont particulièrement dangereuses pour les chiens, chats et enfants.",
    details: "Cycas revoluta contient notamment de la cycasine. L’ingestion peut provoquer des atteintes digestives, neurologiques et hépatiques graves ; les chiens sont particulièrement sensibles. Éloignez graines et plante des animaux et des jeunes enfants. En cas d’ingestion suspectée, contactez immédiatement un vétérinaire, un centre antipoison ou un professionnel de santé, sans attendre l’apparition de symptômes.",
  },
  problems: [
    { title: "Frondes jaunes à la base", cause: "Vieillissement normal d’une ancienne couronne, manque de lumière ou racines durablement humides.", advice: "Vérifier d’abord le rythme de séchage et l’état des racines. Ne retirer une fronde que lorsqu’elle est totalement jaune et sèche." },
    { title: "Nouvelles frondes longues et molles", cause: "Lumière insuffisante pendant la poussée ou plante tournée trop tard.", advice: "Installer le Cycas dans sa lumière définitive avant le déploiement et assurer une exposition homogène sans soleil brutal." },
    { title: "Taches brunes après sortie", cause: "Coup de soleil sur des frondes produites à l’intérieur ou au frais.", advice: "Acclimater sur deux à trois semaines, d’abord à l’ombre lumineuse puis au soleil doux avant une exposition plus forte." },
    { title: "Caudex mou ou odeur anormale", cause: "Pourriture favorisée par l’eau stagnante, le froid et un substrat compact.", advice: "Stopper les arrosages, dépoter et faire diagnostiquer rapidement l’état du caudex et des racines ; ne pas masquer le problème avec de l’engrais." },
    { title: "Cochenilles farineuses ou à bouclier", cause: "Colonies cachées à la base des folioles, sous les frondes ou dans le cœur.", advice: "Isoler, inspecter chaque insertion et répéter un traitement adapté sur plusieurs cycles en protégeant le cœur de l’excès de liquide." },
    { title: "Acariens sous abri", cause: "Air chaud et sec, plante confinée et surveillance insuffisante du revers des frondes.", advice: "Améliorer l’aération, nettoyer doucement et traiter selon un protocole adapté sans multiplier les pulvérisations inutiles." },
    { title: "Aucune nouvelle pousse", cause: "Rythme naturellement lent, manque de chaleur ou de lumière, ou racines occupées à se rétablir.", advice: "Observer le caudex et les racines plutôt que forcer la croissance. Une longue pause est normale chez un sujet sain." },
  ],
  comparisons: [
    { name: "Un palmier", difference: "Un palmier est une angiosperme de la famille des Arecaceae ; Cycas revoluta est une gymnosperme de la famille des Cycadaceae, sans fleurs ni fruits véritables." },
    { name: "Zamia furfuracea", difference: "Autre cycadale, au feuillage plus court et plus large, dont les folioles ont une texture différente ; elle n’appartient pas au genre Cycas." },
    { name: "Dioon edule", difference: "Cycadale mexicaine aux frondes généralement plus bleutées et à l’architecture différente, souvent confondue dans les collections de plantes dites préhistoriques." },
  ],
  faq: [
    { question: "Le Cycas revoluta est-il un palmier ?", answer: "Non. Sa couronne rappelle un palmier, mais il appartient aux Cycadales, une lignée de gymnospermes très différente des Arecaceae." },
    { question: "Peut-on cultiver un Cycas dehors à Lille ?", answer: "Oui pendant la belle saison et, pour un sujet acclimaté, dans un emplacement très abrité et drainant. En pot, protégez les racines du gel durable et de la pluie froide ; une serre froide lumineuse ou un local hors gel reste la solution la plus sûre." },
    { question: "Quelle est la rusticité du Cycas revoluta ?", answer: "Elle ne se résume pas à un chiffre. La durée du gel, le vent, l’humidité, le drainage, l’âge et l’acclimatation comptent. Les frondes sont endommagées avant le caudex et les racines en pot sont particulièrement exposées." },
    { question: "Pourquoi mon Cycas ne pousse-t-il pas ?", answer: "Il pousse très lentement et par poussées espacées. Si le caudex est ferme et les racines saines, plusieurs mois sans nouvelle fronde ne sont pas forcément inquiétants." },
    { question: "Quand arroser un Cycas en pot ?", answer: "Après un séchage marqué du mélange. Arrosez à fond puis laissez égoutter ; espacez nettement en hiver et par faible lumière." },
    { question: "Quel substrat choisir ?", answer: "Un mélange minéral, aéré et très drainant dans un pot percé. La rétention d’eau doit rester modérée, surtout pendant l’hiver." },
    { question: "Le Cycas est-il toxique pour les animaux ?", answer: "Oui. Toutes les parties sont toxiques, et les graines concentrent un risque majeur. Les chiens sont particulièrement sensibles : empêchez tout accès et contactez immédiatement un vétérinaire en cas d’ingestion suspectée." },
    { question: "Faut-il couper les anciennes frondes ?", answer: "Attendez qu’elles soient totalement jaunes ou sèches. Les frondes encore vertes participent à la photosynthèse et leur suppression systématique affaiblit la plante." },
  ],
  tibaldoAdvice: [
    "À Lille et dans le Nord, privilégiez un mur abrité, une exposition lumineuse et un pot qui s’égoutte immédiatement. La combinaison froid + humidité est plus dangereuse qu’une brève fraîcheur sèche.",
    "N’entourez jamais le cœur d’un matériau humide pour l’hiver. Protégez le contenant, gardez la couronne aérée et mettez le sujet hors gel lors d’un épisode durable.",
    "Pendant une nouvelle poussée, ne déplacez plus la plante chaque jour : une lumière stable aide les frondes à durcir en couronne régulière.",
    "Portez des gants pour manipuler feuilles et graines, et placez le sujet hors de portée des enfants et animaux qui mâchonnent les plantes.",
  ],
  localSpotlight: {
    title: "Cultiver un Cycas revoluta à Lille et dans le Nord",
    text: "Le climat lillois cumule humidité, vent et périodes de gel : la réussite dépend donc davantage de l’abri et du drainage que d’un chiffre de rusticité isolé. Un sujet en pot peut passer la belle saison dehors après acclimatation, contre un mur lumineux et protégé des vents. Avant une séquence froide durable, placez-le dans un espace lumineux hors gel ou protégez soigneusement le contenant tout en gardant le cœur sec et aéré. Reprenez progressivement les arrosages et le soleil au printemps.",
  },
  gallery: [
    { src: "/media/images/cycas-revoluta/cycas-revoluta-terrasse-tibaldo.webp", alt: "Cycas revoluta adulte cultivé en pot sur la terrasse végétalisée de Tibaldo Jungle", caption: "Le sujet propriétaire Tibaldo dans son environnement extérieur ; cette vue complète a été retenue comme HERO car aucun élément ne masque le pot.", width: 1200, height: 2133 },
    { src: "/media/images/cycas-revoluta/cycas-revoluta-port-couronne.webp", alt: "Cycas revoluta en pot noir montrant son caudex et sa couronne régulière de frondes", caption: "IMG_6050.JPG : la candidate initiale au détourage, conservée intacte en photographie d’ambiance car le transat masque le bas du pot.", width: 1200, height: 2133 },
    { src: "/media/images/cycas-revoluta/cycas-revoluta-pot-noir-exterieur.webp", alt: "Cycas revoluta entier en pot noir sous un ciel bleu dans un jardin lumineux", caption: "Vue verticale du port entier et des frondes rigides exposées au soleil après acclimatation.", width: 1200, height: 2133 },
    { src: "/media/images/cycas-revoluta/cycas-revoluta-pot-bleu-frondes.webp", alt: "Cycas revoluta installé dans un grand pot bleu avec détail des frondes pennées", caption: "Le même sujet installé dans son contenant bleu, photographié par Tibaldo.", width: 1200, height: 2133 },
  ],
  seo: {
    title: "Cycas revoluta : entretien, rusticité et toxicité",
    description: "Guide complet du Cycas revoluta : lumière, arrosage, substrat, croissance lente, culture dehors, hivernage à Lille, rusticité nuancée et toxicité.",
    keywords: ["Cycas revoluta", "Cycas revoluta entretien", "Cycas revoluta rusticité", "Cycas revoluta arrosage", "Cycas revoluta toxique", "Cycas du Japon"],
  },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:328823-2/general-information" },
    { label: "Royal Horticultural Society — Cycas revoluta", url: "https://www.rhs.org.uk/plants/5127/cycas-revoluta/details" },
    { label: "NC State Extension — Cycas revoluta", url: "https://plants.ces.ncsu.edu/plants/cycas-revoluta/common-name/cycad/" },
    { label: "Merck Veterinary Manual — ornamental plants toxic to animals", url: "https://www.merckvetmanual.com/toxicology/poisonous-plants/houseplants-and-ornamentals-toxic-to-animals" },
  ],
  publishedAt: "2026-08-20",
  updatedAt: "2026-08-20",
};
