import type { PlantEntry, PlantMediaLicense } from "./types";
type PlantImage = PlantEntry["gallery"][number];
const verified = (creator:string, license:string, licenseUrl:string, sourceUrl:string, note:string):PlantMediaLicense => ({status:"verified",creator,license,licenseUrl,sourceUrl,registryPath:"/credits-images",note:`Vague documentaire Wave 5 V1 · contrôle du 1er septembre 2026. ${note}`});
const media:Readonly<Record<string,PlantImage>> = {
  "/plantes/agave/americana-variegata": {src:"/documentary-media-wave-5-v1/agave-variegata.webp",alt:"Rosette panachée jaune et verte d’Agave americana ‘Variegata’",caption:"Agave americana ‘Variegata’ à la Palmeraie de Wałbrzych · Agnieszka Kwiecień, Nova.",width:1400,height:1050,license:verified("Agnieszka Kwiecień, Nova","CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/","https://commons.wikimedia.org/wiki/File:Agave_americana_%27Variegata%27_Agawa_ameryka%C5%84ska_2023-10-31_02.jpg","La fiche Commons nomme explicitement le cultivar. Recadrage, redimensionnement et conversion WebP.")},
  "/plantes/fatsia/japonica-spiders-web": {src:"/documentary-media-wave-5-v1/fatsia-spiders-web.webp",alt:"Feuilles palmées mouchetées de blanc de Fatsia japonica ‘Spider’s Web’",caption:"Fatsia japonica ‘Spider’s Web’ au Lincoln Park Conservatory · Krzysztof Ziarnek, Kenraiz.",width:1364,height:2000,license:verified("Krzysztof Ziarnek, Kenraiz","CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/","https://commons.wikimedia.org/wiki/File:Fatsia_japonica_%27Spider%27s_Web%27_kz1.jpg","La fiche Commons nomme explicitement le cultivar et le lieu de collection. Redimensionnement et conversion WebP.")},
};
export const documentaryMediaWave5V1Registry=Object.entries(media).map(([route,image])=>({route,source:image.license?.sourceUrl??"",creator:image.license?.creator??"",license:image.license?.license??"",localFile:image.src}));
export const applyDocumentaryMediaCompletionWave5V1=(plants:PlantEntry[]):PlantEntry[]=>plants.map((plant)=>{const image=media[`/plantes/${plant.genre}/${plant.slug}`];return image?{...plant,gallery:[image]}:plant;});
