import type { PlantEntry } from "./types";

const sharedAnthuriumFilters = {
  temperatureMin: 16,
  temperatureIdeal: [18, 27] as [number, number],
  humidityIdeal: [60, 80] as [number, number],
  light: "vive" as const,
  watering: "modéré" as const,
  substrateTags: ["aroïdes", "aéré", "drainant", "écorce"],
  growthRate: "lente" as const,
  needsSupport: false,
  variegated: false,
  collection: true,
  flowering: true,
  petToxic: true,
  humanToxic: true,
};

export const encyclopediaV2Step1Plants = [
  {
    slug: "clarinervium",
    genre: "anthurium",
    genreLabel: "Anthurium",
    botanicalName: "Anthurium clarinervium",
    displayName: "Clarinervium",
    listingName: "Anthurium clarinervium",
    subtitle: "Un Anthurium mexicain terrestre aux feuilles de velours sombres parcourues de nervures claires.",
    family: "Araceae",
    origin: "Mexique · Chiapas",
    taxonomy: {
      order: "Alismatales",
      family: "Araceae",
      genus: "Anthurium",
      species: "Anthurium clarinervium",
      cultivar: null,
      commonNames: ["Anthurium velours", "Anthurium carton"],
    },
    filters: {
      ...sharedAnthuriumFilters,
      humidityIdeal: [55, 75],
      habits: ["terrestre", "dressé"],
      adultSizeCm: 65,
      regions: ["Mexique", "Chiapas"],
    },
    habitat: "Espèce endémique du Chiapas, au Mexique, observée dans un biome tropical saisonnièrement sec. Elle pousse surtout à terre, profondément enracinée dans les interstices de roches calcaires, et plus rarement comme plante épipétrique dans une fine couche de sol.",
    hybridization: "Espèce botanique acceptée, décrite par Eizi Matuda. Il ne s’agit ni d’un hybride ni d’un cultivar horticole.",
    synonyms: ["Anthurium clarinervium Matuda"],
    description: [
      "Anthurium clarinervium forme une rosette compacte de feuilles ovales à cordiformes. Leur limbe épais, mat et velouté devient vert sombre tandis que les nervures principales blanc verdâtre dessinent un réseau très graphique.",
      "La plante se distingue des Anthurium strictement épiphytes par son ancrage terrestre dans les fissures calcaires. En culture, cette origine invite à rechercher un mélange poreux qui retient un peu d’humidité sans enfermer les racines dans une masse compacte.",
      "Les nouvelles feuilles sont tendres et plus claires. Elles gagnent progressivement en épaisseur, en contraste et en rigidité ; les manipulations répétées pendant leur déploiement laissent facilement des marques définitives.",
    ],
    specimen: {
      observedHeight: "Port compact · feuilles généralement dressées à étalées",
      note: "La taille réelle dépend du clone et des conditions de culture. Chaque plante destinée au Shop doit conserver ses propres mesures commerciales, séparées de cette identité botanique.",
    },
    growth: {
      adultSize: "Rosette d’intérieur souvent comprise entre 40 et 65 cm",
      speed: "Lente à moyenne, avec une feuille après l’autre",
      habit: "Terrestre, profondément enraciné et en rosette",
    },
    care: {
      light: 4,
      water: 3,
      humidity: 4,
      difficulty: 3,
      lightText: "Lumière vive indirecte. Un soleil doux et filtré peut convenir après acclimatation, mais le soleil chaud décolore ou brûle le velours.",
      watering: "Arroser complètement lorsque la partie supérieure du mélange a commencé à sécher, puis laisser l’excédent s’évacuer. Éviter autant la motte détrempée en permanence que le dessèchement intégral prolongé.",
      humidityText: "Une humidité stable supérieure à la moyenne favorise un déploiement propre, à condition de maintenir une circulation d’air réelle. Une vitrine fermée et stagnante augmente les risques de taches et de pourriture.",
      temperature: "Idéalement 18 à 27 °C. Protéger la plante des courants d’air froids et éviter durablement les températures inférieures à 16 °C.",
      substrate: "Mélange acide, poreux et structuré : écorce fine à moyenne, fibre ou chips de coco, fraction minérale drainante et petite part de terreau. Pot percé indispensable.",
      repotting: "Rempoter seulement lorsque les racines ont réellement colonisé le contenant. Préserver les racines charnues, choisir un pot à peine plus grand et maintenir le collet au-dessus du mélange.",
      fertilizing: "Pendant la croissance, apporter un engrais complet très dilué toutes les trois à quatre semaines sur un substrat déjà humide. Suspendre ou espacer fortement lorsque la lumière et la croissance diminuent.",
      propagation: "Division d’un sujet portant plusieurs points de croissance, bouture de tige comprenant un nœud viable, ou semis de graines fraîches issues de baies mûres. Une feuille seule ne reforme pas une plante complète sans nœud.",
    },
    toxicity: {
      level: "toxique par ingestion",
      summary: "À tenir hors de portée des enfants, chats et chiens.",
      details: "Comme les autres Anthurium, ses tissus contiennent des cristaux insolubles d’oxalate de calcium. Leur mastication peut provoquer douleur, irritation de la bouche, salivation et gonflement ; la sève peut également irriter la peau sensible.",
    },
    problems: [
      { title: "Feuilles jaunes et molles", cause: "Mélange durablement saturé, pot trop grand, froid ou racines asphyxiées.", advice: "Inspecter la motte avant tout nouvel arrosage, retirer les racines molles et réinstaller la plante dans un mélange plus respirant si nécessaire." },
      { title: "Bords bruns et cassants", cause: "Dessèchement prolongé, air très sec, accumulation de sels ou alternance brutale entre sec et détrempé.", advice: "Stabiliser l’arrosage, utiliser une eau peu minéralisée et rincer périodiquement le mélange sans laisser d’eau stagnante." },
      { title: "Nouvelles feuilles déformées", cause: "Humidité instable, contact pendant le déploiement, thrips ou racines affaiblies.", advice: "Ne pas aider mécaniquement la feuille à s’ouvrir ; inspecter le revers, les pétioles et le point de croissance." },
      { title: "Taches sombres", cause: "Feuillage mouillé trop longtemps, air stagnant, froid ou infection opportuniste.", advice: "Éloigner les feuilles malades, améliorer la ventilation et arroser directement le substrat plutôt que le feuillage." },
      { title: "Thrips, cochenilles ou acariens", cause: "Parasites cachés sur le revers, les pétioles ou les jeunes pousses.", advice: "Isoler immédiatement, nettoyer minutieusement puis répéter un traitement adapté sur plusieurs cycles." },
    ],
    comparisons: [
      { name: "Anthurium crystallinum", difference: "Feuilles souvent plus allongées et moins épaisses, avec un port généralement moins compact." },
      { name: "Anthurium magnificum", difference: "Pétioles nettement anguleux et développement plus imposant ; le Clarinervium conserve une rosette plus ramassée." },
      { name: "Anthurium forgetii", difference: "Base du limbe fermée ou presque fermée, sans le sinus cordiforme largement ouvert du Clarinervium." },
    ],
    faq: [
      { question: "Quelle lumière donner à Anthurium clarinervium ?", answer: "Une lumière vive indirecte permet de garder un feuillage compact et contrasté. Évitez le soleil chaud direct, surtout sur une nouvelle feuille." },
      { question: "Quand arroser Anthurium clarinervium ?", answer: "Arrosez après un début de séchage de la partie supérieure, jamais selon un jour fixe. Le pot doit ensuite s’égoutter complètement." },
      { question: "Quel substrat utiliser ?", answer: "Un mélange acide, aéré et drainant associant écorce, coco, composant minéral et une petite fraction de terreau convient mieux qu’un terreau compact utilisé seul." },
      { question: "Faut-il une humidité très élevée ?", answer: "Une humidité moyenne à élevée et stable aide les feuilles à se déployer, mais elle doit toujours être associée à une bonne ventilation." },
      { question: "Pourquoi les nervures sont-elles moins blanches ?", answer: "Le contraste varie avec l’âge de la feuille, le clone et la lumière. Une jeune feuille n’a pas encore sa coloration définitive." },
      { question: "Peut-on multiplier une feuille seule ?", answer: "Non. Une multiplication végétative doit conserver un nœud ou un point de croissance viable ; une feuille isolée peut survivre un temps sans produire une nouvelle plante." },
    ],
    tibaldoAdvice: [
      "Gardez le pot relativement ajusté : un grand volume de mélange humide ralentit fortement l’oxygénation des racines.",
      "Ne frottez pas le velours. Dépoussiérez-le délicatement avec un pinceau très souple et sec.",
      "À la réception, stabilisez d’abord lumière, chaleur et arrosage avant d’envisager un rempotage.",
    ],
    gallery: [{
      src: "/photo-reelle-a-venir.svg",
      alt: "Photographie réelle d’Anthurium clarinervium à ajouter",
      caption: "Photographie du spécimen à réaliser au Studio Végétal ; aucun visuel généré n’est utilisé pour identifier cette plante.",
      width: 1200,
      height: 1500,
    }],
    seo: {
      title: "Anthurium clarinervium : entretien, arrosage et substrat",
      description: "Guide complet d’Anthurium clarinervium : origine, feuilles veloutées, lumière, arrosage, humidité, substrat, rempotage et problèmes fréquents.",
      keywords: ["Anthurium clarinervium", "Anthurium clarinervium entretien", "Anthurium clarinervium arrosage", "substrat Anthurium clarinervium", "humidité Anthurium clarinervium"],
    },
    sources: [
      { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15185-2/general-information" },
      { label: "CATE Araceae — Anthurium clarinervium", url: "https://cate-araceae.myspecies.info/taxonomy/term/1227/descriptions" },
      { label: "Royal Horticultural Society — Anthurium clarinervium", url: "https://www.rhs.org.uk/plants/84264/anthurium-clarinervium/details" },
      { label: "NC State Extension — Anthurium", url: "https://plants.ces.ncsu.edu/plants/anthurium/common-name/tailflower/" },
    ],
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-19",
  },
  {
    slug: "warocqueanum",
    genre: "anthurium",
    genreLabel: "Anthurium",
    botanicalName: "Anthurium warocqueanum",
    displayName: "Warocqueanum",
    listingName: "Anthurium warocqueanum · Queen Anthurium",
    subtitle: "Le Queen Anthurium colombien aux longues feuilles de velours qui retombent comme un rideau.",
    family: "Araceae",
    origin: "Colombie",
    taxonomy: {
      order: "Alismatales",
      family: "Araceae",
      genus: "Anthurium",
      species: "Anthurium warocqueanum",
      cultivar: null,
      commonNames: ["Queen Anthurium", "Piel de tigre", "Terciopelo"],
    },
    filters: {
      ...sharedAnthuriumFilters,
      temperatureMin: 17,
      temperatureIdeal: [19, 27],
      humidityIdeal: [70, 85],
      growthRate: "moyenne",
      habits: ["épiphyte", "hémiépiphyte", "retombant"],
      adultSizeCm: 180,
      needsSupport: true,
      regions: ["Colombie", "Andes", "Pacifique colombien"],
    },
    habitat: "Espèce endémique de Colombie, présente dans les régions andines et pacifiques jusqu’à environ 2 250 mètres d’altitude. Elle vit dans le biome tropical humide comme épiphyte, hémiépiphyte ou plante grimpante, les racines restant aérées autour des supports forestiers.",
    hybridization: "Espèce botanique acceptée, décrite par Thomas Moore. Les termes XXL, Baby ou Narrow indiquent une taille, un stade ou une description commerciale et ne définissent pas une identité botanique distincte.",
    synonyms: ["Anthurium warocqueanum T.Moore", "Piel de tigre", "Terciopelo"],
    description: [
      "Anthurium warocqueanum développe de longues feuilles pendantes, étroites et cordiformes, couvertes d’un velours vert profond. Une nervure centrale claire et des nervures latérales régulières structurent le limbe sans interrompre son mouvement vertical.",
      "Le port retombant est constitutif de l’espèce : elle doit être installée en hauteur ou devant un espace libre afin que les feuilles ne frottent ni sur un mur ni sur le sol. Les nouvelles feuilles sont extrêmement fragiles avant leur durcissement.",
      "La réussite repose moins sur une humidité maximale que sur un équilibre stable entre chaleur, humidité, lumière filtrée, ventilation et oxygénation racinaire. Une plante récemment déplacée peut sacrifier une feuille pendant son acclimatation sans que cela annonce nécessairement son déclin.",
    ],
    specimen: {
      observedHeight: "Feuillage très allongé et naturellement pendant",
      note: "XXL décrit uniquement un ancien format commercial. Les dimensions réelles doivent être portées par le produit du Shop, jamais par une seconde fiche encyclopédique.",
    },
    growth: {
      adultSize: "Grande espèce pendante pouvant produire des feuilles très longues",
      speed: "Moyenne en conditions stables, souvent lente après acclimatation",
      habit: "Épiphyte à hémiépiphyte, grimpant puis fortement retombant",
    },
    care: {
      light: 4,
      water: 3,
      humidity: 5,
      difficulty: 5,
      lightText: "Lumière vive et diffuse. Une exposition trop sombre réduit la croissance ; un soleil chaud direct marque rapidement le velours et les jeunes feuilles.",
      watering: "Maintenir une humidité régulière sans saturation. Arroser lorsque le mélange a commencé à s’alléger, puis égoutter entièrement ; adapter la fréquence à l’activité des racines et non au calendrier.",
      humidityText: "Une humidité élevée et stable aide les longues feuilles à se dérouler sans sécher, mais l’air doit circuler. Éviter les boîtes fermées, les feuilles constamment mouillées et les variations brutales.",
      temperature: "Idéalement 19 à 27 °C avec très peu d’écarts. Éviter le froid durable, les vitres froides, les radiateurs et les courants d’air.",
      substrate: "Mélange épiphyte très ouvert : écorce moyenne, chips de coco, sphaigne fibreuse en proportion mesurée et fraction minérale. Le contenant doit évacuer l’eau immédiatement tout en laissant respirer les racines.",
      repotting: "Intervenir seulement si le mélange est dégradé ou si les racines ont colonisé le contenant. Manipuler le moins possible les racines actives, conserver un petit pot très drainant et installer le support définitif avant de déployer le feuillage.",
      fertilizing: "Engrais complet très dilué pendant une croissance visible, sur mélange humide. Un apport excessif ne compense ni une lumière insuffisante ni un système racinaire inactif.",
      propagation: "Division d’une plante possédant plusieurs points de croissance ou bouture de tige avec nœud viable et racines aériennes. L’enracinement exige chaleur stable, forte aération et patience.",
    },
    toxicity: {
      level: "toxique par ingestion",
      summary: "À tenir hors de portée des enfants, chats et chiens.",
      details: "Ses tissus contiennent, comme ceux des autres Anthurium, des cristaux insolubles d’oxalate de calcium irritants pour la bouche et le tube digestif. La sève peut également irriter la peau sensible.",
    },
    problems: [
      { title: "Acclimatation difficile", cause: "Changement brutal de lumière, humidité, eau, température ou milieu racinaire.", advice: "Conserver le premier emplacement plusieurs semaines, ne pas rempoter immédiatement et juger la reprise sur les racines et le point de croissance plutôt que sur une seule ancienne feuille." },
      { title: "Nouvelle feuille bloquée ou froissée", cause: "Air trop sec, variation d’humidité, contact mécanique ou racines momentanément inactives.", advice: "Stabiliser l’ambiance et laisser la feuille se libérer seule ; toute aide manuelle peut déchirer le limbe encore tendre." },
      { title: "Pointes et marges sèches", cause: "Arrosage irrégulier, humidité basse, sels, chaleur sèche ou racines endommagées.", advice: "Contrôler la motte, employer une eau peu minéralisée et augmenter l’humidité sans supprimer la ventilation." },
      { title: "Racines brunes et molles", cause: "Mélange compact, pot trop grand, eau stagnante, froid ou rempotage traumatique.", advice: "Retirer seulement les tissus réellement morts, désinfecter l’outil et réinstaller la plante dans un volume ajusté et très aéré." },
      { title: "Thrips, acariens ou cochenilles", cause: "Parasites installés sur le revers, les pétioles et les feuilles en déploiement.", advice: "Isoler la plante, inspecter toute sa longueur et répéter un protocole adapté ; une seule intervention ne couvre pas tous les stades du parasite." },
    ],
    comparisons: [
      { name: "Anthurium pallidiflorum", difference: "Feuilles rubanées plus étroites, sans sinus cordiforme marqué ni nervation claire aussi contrastée." },
      { name: "Anthurium veitchii", difference: "Feuilles profondément gaufrées et côtelées, plutôt que veloutées et parcourues de nervures argentées." },
      { name: "Anthurium regale", difference: "Feuilles largement cordiformes et plus horizontales, avec une silhouette beaucoup moins étroite et pendante." },
    ],
    faq: [
      { question: "Quelle humidité pour Anthurium warocqueanum ?", answer: "Une humidité élevée et stable est préférable, mais elle doit toujours être accompagnée d’une circulation d’air. L’humidité stagnante augmente les maladies." },
      { question: "Comment arroser un Warocqueanum ?", answer: "Arrosez lorsque le mélange ouvert commence à perdre son humidité, puis laissez toute l’eau s’évacuer. Les racines ne doivent être ni constamment détrempées ni desséchées longtemps." },
      { question: "Pourquoi perd-il une feuille après l’achat ?", answer: "L’espèce réagit aux changements d’environnement. Une ancienne feuille peut décliner pendant l’acclimatation ; surveillez surtout le point de croissance et l’état des racines." },
      { question: "Quel substrat choisir ?", answer: "Un mélange épiphyte grossier, stable et très aéré à base d’écorce, coco et fraction minérale est plus sûr qu’un terreau fin utilisé seul." },
      { question: "Faut-il rempoter immédiatement ?", answer: "Non. Sauf problème racinaire manifeste, laissez d’abord la plante s’acclimater. Cumuler transport et rempotage augmente fortement le stress." },
      { question: "Warocqueanum XXL est-il une variété ?", answer: "Non. XXL décrit une taille commerciale. La fiche botanique reste Anthurium warocqueanum, quelle que soit la taille vendue." },
    ],
    tibaldoAdvice: [
      "Préparez l’espace vertical avant l’arrivée de la plante : une feuille qui frotte se marque définitivement.",
      "N’accumulez pas les changements. Après un transport, laissez la plante reprendre avant de modifier pot, substrat et emplacement.",
      "Regardez les racines à travers un pot transparent ou ajouré lorsque cela est possible : elles donnent une information plus fiable que la seule surface du mélange.",
    ],
    gallery: [{
      src: "/photo-reelle-a-venir.svg",
      alt: "Photographie réelle d’Anthurium warocqueanum à ajouter",
      caption: "Photographie du spécimen à réaliser au Studio Végétal ; aucun visuel généré n’est utilisé pour identifier cette plante.",
      width: 1200,
      height: 1500,
    }],
    seo: {
      title: "Anthurium warocqueanum : entretien du Queen Anthurium",
      description: "Guide d’Anthurium warocqueanum : feuilles pendantes, acclimatation, lumière, humidité, arrosage, racines, substrat, rempotage et problèmes.",
      keywords: ["Anthurium warocqueanum", "Anthurium warocqueanum entretien", "Queen Anthurium", "Anthurium warocqueanum humidité", "substrat Warocqueanum"],
    },
    sources: [
      { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:85496-1/general-information" },
      { label: "Royal Horticultural Society — cultiver les Anthurium", url: "https://www.rhs.org.uk/plants/anthuriums/" },
      { label: "International Aroid Society — Anthurium", url: "https://www.aroid.org/genera/anthurium/" },
      { label: "NC State Extension — Anthurium", url: "https://plants.ces.ncsu.edu/plants/anthurium/common-name/tailflower/" },
    ],
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-19",
  },
] satisfies PlantEntry[];
