import type { PlantEntry } from "./types";
import { p1VerifiedMediaByRoute } from "./final-media-completion-v1.ts";

type P1PlantDraft = Omit<PlantEntry, "gallery" | "mediaNeeds" | "publishedAt" | "updatedAt">;

const publicationDate = "2026-08-30";

const withHonestMediaGap = (plant: P1PlantDraft): PlantEntry => ({
  ...plant,
  mediaNeeds: [
    {
      role: "Portrait botanique principal",
      description: `Photographie documentaire vérifiée de ${plant.botanicalName}, avec provenance et droits réutilisables.`,
    },
    {
      role: "Détail d’identification",
      description: `Vue complémentaire montrant le caractère le plus utile pour reconnaître ${plant.displayName}.`,
    },
  ],
  gallery: [
    {
      src: "/photo-reelle-a-venir.svg",
      alt: `Emplacement documentaire réservé à ${plant.botanicalName}`,
      caption: "Média absent : aucune photographie non vérifiée n’est substituée à l’espèce.",
      width: 1200,
      height: 1500,
      license: {
        status: "media-gap",
        note: "Photographie à documenter sans compromettre l’identité botanique ni les droits.",
      },
    },
  ],
  publishedAt: publicationDate,
  updatedAt: publicationDate,
});

export const p1AliasCanonicalMap = {
  "/plantes/alocasia/jacklyn": "/plantes/alocasia/tandurusa",
  "/plantes/alocasia/polly": "/plantes/alocasia/mortfontanensis-polly",
  "/plantes/alocasia/amazonica": "/plantes/alocasia/mortfontanensis-polly",
  "/plantes/philodendron/scandens": "/plantes/philodendron/hederaceum",
  "/plantes/philodendron/philodendron-scandens": "/plantes/philodendron/hederaceum",
  "/plantes/monstera/albo": "/plantes/monstera/albo-variegata",
  "/plantes/monstera/variegata": "/plantes/monstera/albo-variegata",
  "/plantes/monstera/deliciosa-albo": "/plantes/monstera/albo-variegata",
  "/plantes/dracaena/trifasciata": "/plantes/sansevieria/trifasciata",
} as const;

const alocasiaTandurusa = withHonestMediaGap({
  slug: "tandurusa",
  genre: "alocasia",
  genreLabel: "Alocasia",
  botanicalName: "Alocasia tandurusa",
  displayName: "Tandurusa",
  listingName: "Alocasia tandurusa · Jacklyn",
  subtitle: "Une espèce de Sulawesi aux feuilles profondément découpées et aux pétioles mouchetés.",
  family: "Araceae",
  taxonomy: {
    order: "Alismatales",
    family: "Araceae",
    genus: "Alocasia",
    species: "Alocasia tandurusa",
    cultivar: null,
    commonNames: ["Jacklyn", "Alocasia Jacklyn"],
  },
  filters: {
    temperatureMin: 16,
    temperatureIdeal: [18, 28],
    humidityIdeal: [55, 80],
    light: "vive",
    watering: "régulier",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"],
    growthRate: "moyenne",
    habits: ["terrestre", "dressé"],
    adultSizeCm: 120,
    needsSupport: false,
    variegated: false,
    collection: true,
    flowering: true,
    petToxic: true,
    humanToxic: true,
    regions: ["Sulawesi", "Indonésie"],
  },
  origin: "Sulawesi, Indonésie",
  habitat: "Espèce de forêt tropicale humide de Sulawesi, décrite scientifiquement en 2023 à partir de matériel provenant du nord de l’île.",
  hybridization: "Espèce botanique acceptée ; ce n’est pas un hybride horticole.",
  synonyms: ["Alocasia ‘Jacklyn’", "Alocasia Jacklyn"],
  description: [
    "Alocasia tandurusa est reconnaissable à ses feuilles sagittées profondément lobées, presque ramifiées, portées par des pétioles sombres et mouchetés. Le nom tandurusa dérive de l’expression indonésienne signifiant « bois de cerf », une référence directe à cette silhouette.",
    "Sa découpe ne doit pas être confondue avec une feuille abîmée. C’est un caractère stable de l’espèce, qui demande en intérieur une lumière vive filtrée, une chaleur régulière et un substrat très respirant.",
  ],
  specimen: {
    observedHeight: "Développement moyen · souvent 60 à 120 cm en culture",
    note: "La taille dépend de la maturité et des conditions ; aucune mesure d’un spécimen Tibaldo n’est revendiquée ici.",
  },
  growth: {
    adultSize: "Plante terrestre de taille moyenne, au feuillage largement étalé",
    speed: "Moyenne pendant la saison chaude",
    habit: "Dressé, en touffe issue d’un corme",
  },
  care: {
    light: 4,
    water: 3,
    humidity: 4,
    difficulty: 4,
    difficultyText: "Demande surtout de la stabilité et une bonne lecture du séchage.",
    lightText: "Lumière vive indirecte. Un soleil doux peut convenir après acclimatation, jamais un soleil chaud brutal.",
    watering: "Arroser lorsque les premiers centimètres du mélange commencent à sécher, puis laisser l’eau s’évacuer complètement.",
    humidityText: "Une humidité moyenne à élevée soutient le feuillage, avec une circulation d’air constante.",
    temperature: "Croissance régulière au-dessus d’environ 16 °C ; viser une ambiance intérieure chaude, autour de 18 à 28 °C.",
    substrate: "Mélange structuré et aéré pour aroïdes : fraction organique, écorce, coco et composant minéral drainant.",
    repotting: "Rempoter seulement lorsque les racines occupent le pot, dans un contenant percé à peine plus grand.",
    fertilizing: "Apport équilibré et dilué pendant la croissance active, toujours sur un substrat déjà humide.",
    propagation: "Séparation de rejets ou de cormes suffisamment enracinés ; la multiplication ne doit pas affaiblir la plante mère.",
  },
  toxicity: {
    level: "toxique",
    summary: "À tenir hors de portée des enfants et des animaux.",
    details: "Comme les autres Alocasia, ses tissus contiennent des cristaux insolubles d’oxalate de calcium irritants en cas de mastication ou d’ingestion.",
  },
  problems: [
    { title: "Bords secs", cause: "Air trop sec, arrosages irréguliers ou sels accumulés.", advice: "Stabiliser l’arrosage et éloigner la plante du chauffage sans saturer le pot." },
    { title: "Feuille qui jaunit", cause: "Racines durablement humides, froid ou renouvellement naturel.", advice: "Contrôler le drainage et l’état du corme avant de réarroser." },
    { title: "Pétioles qui s’allongent", cause: "Lumière insuffisante ou éclairage unilatéral.", advice: "Rapprocher progressivement d’une fenêtre et tourner le pot régulièrement." },
    { title: "Acariens ou thrips", cause: "Parasites discrets sur l’envers et les jeunes feuilles.", advice: "Isoler, inspecter les découpes et intervenir plusieurs fois avec une méthode adaptée." },
  ],
  comparisons: [
    { name: "Alocasia portei", difference: "Autre espèce très découpée, mais de bien plus grand développement et à la morphologie différente." },
    { name: "Alocasia brancifolia", difference: "Feuilles également divisées, avec une architecture des lobes et des pétioles distincte." },
    { name: "Feuille endommagée", difference: "Les lobes de Tandurusa se répètent de façon organisée et symétrique ; une déchirure est irrégulière." },
  ],
  faq: [
    { question: "Jacklyn et Alocasia tandurusa sont-ils la même plante ?", answer: "Oui. Jacklyn est le nom horticole sous lequel l’espèce a circulé avant sa description scientifique sous le nom Alocasia tandurusa." },
    { question: "Pourquoi ses feuilles sont-elles aussi découpées ?", answer: "Cette silhouette en bois de cerf est un caractère botanique de l’espèce, pas le résultat d’un dommage." },
    { question: "Peut-elle vivre loin d’une fenêtre ?", answer: "Non durablement. Elle conserve un port plus dense et une croissance plus stable en lumière vive indirecte." },
    { question: "Doit-elle rester humide en permanence ?", answer: "Non. Le mélange doit rester souple et respirant, avec un léger séchage en surface entre deux arrosages." },
    { question: "Est-elle sans danger pour les animaux ?", answer: "Non. Comme les autres Alocasia, elle est irritante et toxique par ingestion." },
  ],
  tibaldoAdvice: [
    "Observez le poids du pot plutôt qu’un calendrier d’arrosage.",
    "Nettoyez doucement les pétioles mouchetés : les premiers signes de cochenilles peuvent s’y confondre.",
    "Un pot ajusté et aéré vaut mieux qu’un grand volume de terre humide.",
  ],
  localSpotlight: {
    title: "Une lumière franche dans un intérieur lillois",
    text: "En hiver, placez cette Alocasia près de la fenêtre tout en la protégeant du verre froid et des radiateurs.",
  },
  editorialSections: [
    { id: "identifier", eyebrow: "Reconnaître", title: "Une découpe en bois de cerf", paragraphs: ["Les lobes profonds et ordonnés constituent le premier repère. Les pétioles sombres, souvent mouchetés, complètent l’identification."], points: ["Lobes profonds", "Pétioles mouchetés", "Port dressé"] },
    { id: "comprendre", eyebrow: "Comprendre", title: "Une espèce récente pour la science", paragraphs: ["La plante circulait comme Jacklyn avant la publication du nom Alocasia tandurusa en 2023. Le nom commercial reste utile comme alias, pas comme seconde espèce."] },
    { id: "cultiver", eyebrow: "Cultiver", title: "Chaleur, lumière, respiration", paragraphs: ["Sa réussite tient moins à une humidité extrême qu’à l’équilibre entre lumière, chaleur et oxygénation des racines."] },
  ],
  seo: {
    title: "Alocasia tandurusa (Jacklyn) : entretien et identification",
    description: "Reconnaître et cultiver Alocasia tandurusa, connue comme Jacklyn : origine à Sulawesi, lumière, arrosage, substrat et problèmes.",
    keywords: ["Alocasia tandurusa", "Alocasia Jacklyn", "Jacklyn entretien", "Alocasia découpée"],
  },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A77328544-1" },
    { label: "International Plant Names Index", url: "https://www.ipni.org/n/77328544-1" },
    { label: "Royal Horticultural Society — Alocasia tandurusa", url: "https://www.rhs.org.uk/plants/531022/alocasia-tandurusa/details" },
  ],
});

const alocasiaMelo = withHonestMediaGap({
  slug: "melo",
  genre: "alocasia",
  genreLabel: "Alocasia",
  botanicalName: "Alocasia melo",
  displayName: "Melo",
  subtitle: "Une Alocasia de Bornéo aux feuilles épaisses, bleutées et fortement gaufrées.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Alocasia", species: "Alocasia melo", cultivar: null, commonNames: ["Alocasia Melo", "Alocasia rugueuse"] },
  filters: {
    temperatureMin: 16, temperatureIdeal: [18, 28], humidityIdeal: [55, 80], light: "vive", watering: "modéré",
    substrateTags: ["aroïdes", "minéral", "aéré", "drainant"], growthRate: "lente", habits: ["terrestre"], adultSizeCm: 60,
    needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Sabah", "Bornéo", "Malaisie"],
  },
  origin: "Sabah, Bornéo malaisien",
  habitat: "Espèce terrestre de Sabah associée à des substrats ultramafiques, dans un climat tropical humide mais sur un sol minéral et très drainant.",
  hybridization: "Espèce botanique décrite en 1997 ; ce n’est pas un hybride horticole.",
  synonyms: ["Alocasia melo A.Hay, P.C.Boyce & K.M.Wong"],
  description: [
    "Alocasia melo forme une rosette compacte de feuilles presque rondes, épaisses et coriaces. Leur surface gris-vert est profondément rugueuse et bullée, comme sculptée dans la pierre.",
    "Cette texture révèle aussi sa stratégie de culture : la plante apprécie une humidité régulière, mais ses racines ne doivent jamais rester dans un mélange compact. Un substrat riche en structure minérale est plus cohérent qu’un terreau fin et saturé.",
  ],
  specimen: { observedHeight: "Plante compacte · généralement 30 à 60 cm", note: "Aucune mesure d’un spécimen Tibaldo n’est revendiquée ; le port reste bas comparé aux grandes Alocasia." },
  growth: { adultSize: "Rosette compacte de faible à moyen développement", speed: "Lente", habit: "Terrestre, dense et bas" },
  care: {
    light: 4, water: 2, humidity: 4, difficulty: 4,
    difficultyText: "Sensible surtout aux mélanges compacts et aux excès d’eau froids.",
    lightText: "Lumière vive filtrée ; éviter le soleil chaud qui marque les feuilles épaisses.",
    watering: "Laisser la surface sécher légèrement puis arroser à cœur, sans laisser d’eau dans le cache-pot.",
    humidityText: "Humidité moyenne à élevée, toujours associée à une bonne aération du feuillage et des racines.",
    temperature: "Ambiance chaude et stable, idéalement 18 à 28 °C ; éviter les refroidissements sous environ 16 °C.",
    substrate: "Mélange très structuré : écorce, coco grossière et fraction minérale poreuse, avec peu de fines compactantes.",
    repotting: "Rempoter avec retenue dans un pot percé et ajusté ; un excès de volume ralentit le séchage.",
    fertilizing: "Engrais équilibré, dilué et espacé pendant la croissance active.",
    propagation: "Séparation de rejets ou de cormes déjà enracinés au moment d’un rempotage nécessaire.",
  },
  toxicity: { level: "toxique", summary: "Irritante et toxique par ingestion.", details: "Les cristaux d’oxalate de calcium des Alocasia peuvent provoquer douleur orale, salivation et gonflement chez l’humain ou l’animal." },
  problems: [
    { title: "Base molle", cause: "Mélange saturé, manque d’air ou température trop basse.", advice: "Sortir la motte, retirer les tissus atteints et réinstaller dans un substrat plus minéral et respirant." },
    { title: "Feuille qui pâlit", cause: "Lumière insuffisante ou racines affaiblies.", advice: "Vérifier d’abord les racines, puis rapprocher progressivement de la lumière." },
    { title: "Bords croustillants", cause: "Séchage prolongé, sels ou soleil trop direct.", advice: "Stabiliser l’eau et tamiser la lumière chaude." },
    { title: "Acariens", cause: "Air chaud et sec autour des feuilles gaufrées.", advice: "Inspecter les creux du limbe et traiter de façon répétée sans saturer le substrat." },
  ],
  comparisons: [
    { name: "Alocasia baginda ‘Dragon Scale’", difference: "Feuille plus sagittée, marquée d’un réseau de nervures contrastées plutôt que d’un gaufrage presque uniforme." },
    { name: "Alocasia maharani", difference: "Hybride horticole à texture intermédiaire, généralement plus sombre et plus pointu." },
    { name: "Alocasia rugosa", difference: "Nom parfois rencontré dans le commerce mais à ne pas employer comme second nom accepté de Melo." },
  ],
  faq: [
    { question: "Pourquoi Alocasia melo semble-t-elle faite de pierre ?", answer: "Son limbe épais, coriace et fortement bullé diffuse la lumière en relief, ce qui crée cet aspect minéral." },
    { question: "Faut-il beaucoup l’arroser ?", answer: "Non. Elle demande une humidité régulière mais un séchage partiel et une forte oxygénation des racines." },
    { question: "Quel pot choisir ?", answer: "Un pot percé, plutôt ajusté et stable, associé à un mélange grossier qui s’égoutte vite." },
    { question: "Melo et Dragon Scale sont-elles identiques ?", answer: "Non. Ce sont deux taxons différents, reconnaissables notamment à la forme et au dessin de leurs feuilles." },
    { question: "Est-elle toxique ?", answer: "Oui. Elle doit rester hors de portée des animaux et des jeunes enfants." },
  ],
  tibaldoAdvice: [
    "Soulevez le pot avant d’arroser : l’épaisseur des feuilles ne renseigne pas sur l’humidité des racines.",
    "N’enfouissez pas profondément le collet.",
    "Préférez un mélange poreux stable plutôt qu’une surenchère d’humidité ambiante.",
  ],
  localSpotlight: { title: "Protéger les racines du froid", text: "Dans un hiver lillois, gardez le pot à distance d’un vitrage froid : un substrat humide et refroidi est le principal risque." },
  editorialSections: [
    { id: "surface", eyebrow: "Identifier", title: "Une feuille minérale", paragraphs: ["Le relief serré, la texture coriace et le port compact distinguent Melo des Alocasia à limbe lisse."], points: ["Limbe épais", "Relief bullé", "Rosette compacte"] },
    { id: "sol", eyebrow: "Comprendre", title: "Une origine sur substrat ultramafique", paragraphs: ["Son habitat ne justifie pas de reproduire chimiquement un sol naturel en pot ; il invite surtout à préserver structure et drainage."] },
    { id: "racines", eyebrow: "Cultiver", title: "Humide n’est pas saturé", paragraphs: ["La croissance reste plus sûre quand l’eau traverse rapidement un mélange oxygéné."] },
  ],
  seo: { title: "Alocasia melo : entretien de l’Alocasia gaufrée", description: "Guide d’Alocasia melo : origine à Sabah, feuille rugueuse, lumière, arrosage, substrat minéral, toxicité et différences avec Dragon Scale.", keywords: ["Alocasia melo", "Alocasia melo entretien", "Alocasia rugueuse", "Alocasia de Bornéo"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A995487-1/general-information" },
    { label: "Curtis’s Botanical Magazine — Alocasia melo", url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-8748.00072" },
    { label: "International Plant Names Index", url: "https://www.ipni.org/n/995487-1" },
  ],
});

const alocasiaPolly = withHonestMediaGap({
  slug: "mortfontanensis-polly",
  genre: "alocasia",
  genreLabel: "Alocasia",
  botanicalName: "Alocasia × mortfontanensis ‘Polly’",
  displayName: "Polly",
  listingName: "Alocasia × mortfontanensis ‘Polly’",
  subtitle: "Une oreille d’éléphant compacte aux feuilles sombres bordées de nervures claires.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Alocasia", species: "Alocasia × mortfontanensis", cultivar: "Polly", commonNames: ["Alocasia Polly", "Alocasia amazonica Polly", "African mask plant"] },
  filters: {
    temperatureMin: 16, temperatureIdeal: [18, 28], humidityIdeal: [50, 75], light: "vive", watering: "régulier",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "moyenne", habits: ["terrestre", "dressé"], adultSizeCm: 70,
    needsSupport: false, variegated: false, collection: false, flowering: true, petToxic: true, humanToxic: true, regions: ["Horticole"],
  },
  origin: "Hybride horticole d’Alocasia longiloba et Alocasia sanderiana",
  habitat: "Le taxon n’a pas d’aire naturelle propre. Sa culture reprend les besoins d’Alocasia forestières tropicales : chaleur, lumière filtrée et racines aérées.",
  hybridization: "Hybride artificiel accepté sous Alocasia × mortfontanensis ; la formule parentale reconnue est A. longiloba × A. sanderiana.",
  synonyms: ["Alocasia × amazonica ‘Polly’", "Alocasia amazonica ‘Polly’", "Alocasia ‘Polly’"],
  description: [
    "Alocasia ‘Polly’ forme une rosette compacte de feuilles sagittées, vert très sombre, bordées d’un liseré ondulé et parcourues de nervures claires. C’est l’une des Alocasia d’intérieur les plus reconnaissables.",
    "Le nom Alocasia amazonica est encore très courant dans le commerce, mais la plante n’est pas originaire d’Amazonie. Le traitement retenu ici suit Kew : Alocasia × mortfontanensis, un hybride horticole issu de deux espèces asiatiques.",
  ],
  specimen: { observedHeight: "Format compact · généralement 30 à 70 cm", note: "La dimension varie selon le clone, l’âge et la lumière ; aucune taille d’un lot commercial n’est annoncée." },
  growth: { adultSize: "Alocasia compacte adaptée à la culture en pot", speed: "Moyenne en saison chaude", habit: "Rosette dressée issue d’un corme" },
  care: {
    light: 4, water: 3, humidity: 4, difficulty: 3,
    difficultyText: "Accessible si l’arrosage suit réellement le séchage du pot.",
    lightText: "Lumière vive indirecte pour conserver un port compact et des contrastes nets.",
    watering: "Arroser lorsque les cinq premiers centimètres du mélange approchent du sec, puis laisser égoutter complètement.",
    humidityText: "Une humidité moyenne à élevée est utile, mais ne remplace ni la ventilation ni un bon drainage.",
    temperature: "Croissance au chaud, idéalement 18 à 28 °C ; éviter les séjours prolongés sous environ 16 °C.",
    substrate: "Mélange organique mais très aéré, avec écorce, coco et fraction minérale drainante.",
    repotting: "Rempoter au printemps si les racines occupent le pot, sans surdimensionner le nouveau contenant.",
    fertilizing: "Engrais équilibré et dilué toutes les trois à quatre semaines pendant la croissance active.",
    propagation: "Séparation de rejets ou de cormes déjà enracinés ; une feuille seule ne produit pas une nouvelle plante.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et des animaux.", details: "Les tissus contiennent des cristaux insolubles d’oxalate de calcium, irritants par mastication et ingestion." },
  problems: [
    { title: "Feuille jaune", cause: "Excès d’eau, lumière faible, froid ou vieillissement naturel.", advice: "Contrôler la motte et les racines plutôt que d’ajouter immédiatement de l’eau." },
    { title: "Bord brun", cause: "Séchage irrégulier, air très sec ou sels accumulés.", advice: "Régulariser l’arrosage et éloigner du chauffage." },
    { title: "Port lâche", cause: "Manque de lumière.", advice: "Rapprocher progressivement d’une fenêtre et tourner le pot." },
    { title: "Acariens", cause: "Air chaud et sec, surtout sous les feuilles.", advice: "Isoler, doucher et traiter plusieurs fois en inspectant les nervures." },
  ],
  comparisons: [
    { name: "Alocasia sanderiana", difference: "Espèce parentale plus élancée, originaire des Philippines, avec une silhouette moins compacte." },
    { name: "Alocasia micholitziana ‘Frydek’", difference: "Limbe velouté plus souple et vert, sans l’aspect vernissé et le bord ondulé de Polly." },
    { name: "Alocasia ‘Bambino’", difference: "Format encore plus étroit et souvent plus petit, issu d’un autre matériel horticole." },
  ],
  faq: [
    { question: "Alocasia amazonica vient-elle d’Amazonie ?", answer: "Non. Amazonica est un ancien nom horticole ; l’hybride associe deux espèces asiatiques." },
    { question: "Pourquoi employer Alocasia × mortfontanensis ?", answer: "Kew reconnaît ce nom pour l’hybride A. longiloba × A. sanderiana et traite Alocasia × amazonica comme synonyme horticole non valablement publié." },
    { question: "Polly peut-elle vivre dans une pièce sombre ?", answer: "Elle y survit parfois, mais perd en densité et devient plus sensible aux excès d’eau. Une lumière vive indirecte est préférable." },
    { question: "Doit-elle rester humide en permanence ?", answer: "Non. Attendez que la partie supérieure du mélange approche du sec avant un arrosage complet." },
    { question: "Une feuille coupée peut-elle faire une bouture ?", answer: "Non. La propagation nécessite un corme, un rejet ou une portion viable portant un point de croissance." },
  ],
  tibaldoAdvice: [
    "Ne confondez pas humidité de l’air et humidité permanente du pot.",
    "Conservez le nom Polly comme cultivar, mais utilisez × mortfontanensis pour clarifier son identité hybride.",
    "Une reprise plus lente en hiver n’appelle pas davantage d’engrais.",
  ],
  localSpotlight: { title: "Polly en hiver à Lille", text: "Rapprochez-la de la lumière tout en isolant le pot du vitrage froid ; réduisez l’eau dès que le séchage ralentit." },
  editorialSections: [
    { id: "masque", eyebrow: "Reconnaître", title: "Un masque végétal", paragraphs: ["La feuille sombre, les nervures ivoire et le bord ondulé forment une identité immédiate."], points: ["Feuille sagittée", "Nervures claires", "Bord ondulé"] },
    { id: "nom", eyebrow: "Nommer", title: "Amazonica n’est pas une origine", paragraphs: ["Le nom commercial historique ne décrit pas une provenance. La formule hybride retenue relie Polly à deux Alocasia asiatiques."] },
    { id: "rythme", eyebrow: "Cultiver", title: "Lire le pot avant d’arroser", paragraphs: ["La compacité du feuillage n’exige pas un sol constamment mouillé. L’aération des racines reste prioritaire."] },
  ],
  seo: { title: "Alocasia Polly : entretien et vrai nom × mortfontanensis", description: "Guide d’Alocasia × mortfontanensis ‘Polly’ : vrai nom, origine hybride, lumière, arrosage, substrat, toxicité et différences.", keywords: ["Alocasia Polly", "Alocasia amazonica", "Alocasia mortfontanensis", "Alocasia Polly entretien"] },
  sources: [
    { label: "Kew Science — Alocasia × mortfontanensis", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A84211-1" },
    { label: "Royal Horticultural Society — Alocasia", url: "https://www.rhs.org.uk/plants/alocasia/growing-guide" },
  ],
});

const anthuriumLuxurians = withHonestMediaGap({
  slug: "luxurians",
  genre: "anthurium",
  genreLabel: "Anthurium",
  botanicalName: "Anthurium luxurians",
  displayName: "Luxurians",
  subtitle: "Un Anthurium colombien aux feuilles sombres, épaisses et profondément gaufrées.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Anthurium", species: "Anthurium luxurians", cultivar: null, commonNames: ["Anthurium Luxurians", "Anthurium gaufré"] },
  filters: {
    temperatureMin: 16, temperatureIdeal: [18, 28], humidityIdeal: [60, 80], light: "vive", watering: "régulier",
    substrateTags: ["aroïdes", "terrestre", "aéré", "drainant"], growthRate: "lente", habits: ["terrestre", "dressé"], adultSizeCm: 100,
    needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Colombie"],
  },
  origin: "Colombie",
  habitat: "Sous-bois très humides de Colombie. L’espèce est terrestre et développe un axe court et robuste dans un climat tropical humide.",
  hybridization: "Espèce botanique acceptée ; elle ne doit pas être confondue avec les hybrides horticoles qui l’utilisent comme parent.",
  synonyms: ["Anthurium luxurians Croat & R.N.Cirino"],
  description: [
    "Anthurium luxurians construit une rosette de feuilles ovales à cordiformes, très épaisses, brillantes et profondément bullées. Le limbe devient vert foncé à presque noir selon l’âge et la lumière.",
    "Son relief compact diffère du plissage longitudinal d’Anthurium veitchii. Cette espèce terrestre apprécie une lumière filtrée, une chaleur stable et un mélange qui conserve un peu d’humidité tout en laissant l’air circuler entre les racines.",
  ],
  specimen: { observedHeight: "Développement moyen · rosette souvent inférieure à un mètre", note: "Aucune mesure d’un spécimen Tibaldo n’est revendiquée ; la feuille s’élargit et se texture avec la maturité." },
  growth: { adultSize: "Rosette dense de taille moyenne", speed: "Lente", habit: "Terrestre, compact et dressé" },
  care: {
    light: 4, water: 3, humidity: 4, difficulty: 4,
    difficultyText: "Exige de la constance, sans saturation du substrat.",
    lightText: "Lumière vive indirecte ; protéger du soleil chaud qui peut décolorer ou brûler le limbe sombre.",
    watering: "Arroser quand la surface commence à sécher, puis laisser l’excédent s’écouler. Éviter les alternances extrêmes.",
    humidityText: "Humidité supérieure à la moyenne et air mobile ; une atmosphère confinée favorise les problèmes foliaires.",
    temperature: "Idéalement 18 à 28 °C ; éviter les courants d’air et les températures durablement inférieures à 16 °C.",
    substrate: "Mélange d’aroïde terrestre, aéré mais légèrement rétenteur : fraction organique, écorce fine, coco et composant minéral poreux.",
    repotting: "Rempoter lorsque les racines remplissent le contenant, sans enterrer le point de croissance.",
    fertilizing: "Nutrition équilibrée à faible dose pendant la croissance ; rincer périodiquement le mélange pour limiter les sels.",
    propagation: "Division d’un sujet portant plusieurs axes ou semis de graines fraîches issues d’une pollinisation contrôlée.",
  },
  toxicity: { level: "toxique", summary: "À éloigner des enfants et animaux.", details: "Les Anthurium contiennent des cristaux d’oxalate de calcium pouvant irriter fortement la bouche et le tube digestif en cas d’ingestion." },
  problems: [
    { title: "Relief peu marqué", cause: "Plante juvénile, lumière faible ou croissance interrompue.", advice: "Stabiliser lumière, chaleur et nutrition ; le gaufrage se renforce avec la maturité." },
    { title: "Taches aqueuses", cause: "Humidité stagnante sur le limbe et mauvaise circulation d’air.", advice: "Espacer le feuillage, éviter de laisser de l’eau dans les creux et améliorer l’aération." },
    { title: "Pointes brunes", cause: "Sels, air sec ou irrégularité des arrosages.", advice: "Utiliser une eau peu minéralisée et maintenir un rythme plus stable." },
    { title: "Racines brunes", cause: "Mélange compact ou froid et humide.", advice: "Retirer les tissus mous et rempoter dans un substrat plus structuré." },
  ],
  comparisons: [
    { name: "Anthurium veitchii", difference: "Feuilles beaucoup plus longues, nervures transversales régulières et silhouette retombante." },
    { name: "Anthurium radicans", difference: "Port plus rampant et feuilles généralement plus petites ; l’espèce intervient dans des hybrides proches." },
    { name: "Anthurium splendidum", difference: "Texture et architecture différentes, avec des caractères de pétiole et de limbe à examiner au-delà du seul gaufrage." },
  ],
  faq: [
    { question: "Comment reconnaître Anthurium luxurians ?", answer: "Recherchez une feuille épaisse, très sombre, brillante et profondément bullée, sur une plante terrestre à axe court." },
    { question: "A-t-il besoin d’un tuteur ?", answer: "Non. Son port est terrestre et compact, contrairement aux Anthurium grimpants ou retombants." },
    { question: "Pourquoi ses feuilles restent-elles vert clair ?", answer: "La jeunesse, une lumière insuffisante ou une croissance encore lente peuvent retarder l’assombrissement du limbe." },
    { question: "Quel substrat lui convient ?", answer: "Un mélange aéré qui conserve une humidité modérée sans rester saturé : écorce fine, organique structuré et fraction minérale." },
    { question: "Est-il adapté aux animaux ?", answer: "Non. Il est irritant et toxique par ingestion." },
  ],
  tibaldoAdvice: [
    "Ne lustrer jamais le limbe : nettoyez les reliefs avec un chiffon humide très doux.",
    "L’air mobile compte autant que le pourcentage d’humidité.",
    "Observez la masse racinaire avant d’augmenter le diamètre du pot.",
  ],
  localSpotlight: { title: "Une stabilité avant tout", text: "Dans un intérieur lillois chauffé, éloignez Luxurians du radiateur et privilégiez une lumière franche avec une ambiance stable." },
  editorialSections: [
    { id: "relief", eyebrow: "Reconnaître", title: "Un feuillage presque sculpté", paragraphs: ["Les reliefs profonds, serrés et brillants donnent au limbe un aspect de cuir martelé."], points: ["Limbe bullé", "Texture coriace", "Rosette compacte"] },
    { id: "port", eyebrow: "Comprendre", title: "Un Anthurium terrestre", paragraphs: ["Luxurians ne se conduit pas comme une liane. Son point de croissance reste proche du substrat et demande de l’espace latéral."] },
    { id: "stabilite", eyebrow: "Cultiver", title: "Conserver, sans étouffer", paragraphs: ["Le mélange doit tamponner les variations d’humidité tout en gardant des volumes d’air autour des racines."] },
  ],
  seo: { title: "Anthurium luxurians : entretien et identification", description: "Identifier et cultiver Anthurium luxurians : feuilles sombres gaufrées, origine colombienne, lumière, humidité, substrat et problèmes.", keywords: ["Anthurium luxurians", "Anthurium luxurians entretien", "Anthurium gaufré", "Anthurium sombre"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A60439860-2/general-information" },
    { label: "Royal Horticultural Society — cultiver les Anthurium", url: "https://www.rhs.org.uk/plants/anthuriums/how-to-grow-anthuriums" },
  ],
});

const anthuriumWendlingeri = withHonestMediaGap({
  slug: "wendlingeri",
  genre: "anthurium",
  genreLabel: "Anthurium",
  botanicalName: "Anthurium wendlingeri",
  displayName: "Wendlingeri",
  subtitle: "Un Anthurium épiphyte aux longues feuilles rubanées et à l’inflorescence spiralée.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Anthurium", species: "Anthurium wendlingeri", cultivar: null, commonNames: ["Anthurium Wendlingeri", "Anthurium à spadice spiralé"] },
  filters: {
    temperatureMin: 16, temperatureIdeal: [18, 28], humidityIdeal: [60, 85], light: "vive", watering: "régulier",
    substrateTags: ["aroïdes", "épiphyte", "aéré", "drainant"], growthRate: "lente", habits: ["épiphyte", "retombant"], adultSizeCm: 160,
    needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Nicaragua", "Costa Rica", "Panama", "Colombie"],
  },
  origin: "Du sud-est du Nicaragua au nord-ouest de la Colombie",
  habitat: "Épiphyte des forêts tropicales humides d’Amérique centrale et du nord-ouest de l’Amérique du Sud, où feuilles et inflorescences pendent librement.",
  hybridization: "Espèce botanique acceptée, décrite par G.S. Bunting.",
  synonyms: ["Anthurium wendlingeri G.S.Bunting"],
  description: [
    "Anthurium wendlingeri développe de longues feuilles étroites et pendantes. Son caractère le plus spectaculaire apparaît à la floraison : un spadice d’abord droit s’allonge puis se vrille en spirale.",
    "Cette architecture exige de la hauteur sous la plante. Une suspension ou un support élevé permet de lire la silhouette sans plier les feuilles ni l’inflorescence, tout en maintenant les racines épiphytes dans un mélange très aéré.",
  ],
  specimen: { observedHeight: "Feuilles pendantes décrites de 32 à 80 cm", note: "Le spadice peut devenir très long ; aucune floraison d’un spécimen Tibaldo n’est revendiquée ici." },
  growth: { adultSize: "Grand Anthurium retombant", speed: "Lente à moyenne", habit: "Épiphyte en rosette, suspendu et retombant" },
  care: {
    light: 4, water: 3, humidity: 5, difficulty: 4,
    difficultyText: "Demande hauteur, aération et humidité régulière sans confinement.",
    lightText: "Lumière vive filtrée, sans soleil chaud direct sur le feuillage rubané.",
    watering: "Arroser quand le mélange épiphyte commence à s’alléger, puis laisser l’eau s’écouler immédiatement.",
    humidityText: "Humidité élevée favorable, avec une circulation d’air indispensable autour des feuilles et des racines.",
    temperature: "Maintenir une ambiance tropicale stable autour de 18 à 28 °C ; éviter les températures durables sous 16 °C.",
    substrate: "Mélange grossier d’épiphyte : écorce, coco, sphaigne en quantité mesurée et composant minéral poreux.",
    repotting: "Utiliser un panier ou pot percé stable, assez haut pour laisser retomber le feuillage ; rempoter seulement si le mélange se dégrade.",
    fertilizing: "Nutrition légère et régulière en croissance, très diluée pour ne pas brûler les racines aérées.",
    propagation: "Division d’une plante à plusieurs axes ou semis de graines fraîches après pollinisation.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et animaux.", details: "Les cristaux d’oxalate de calcium présents dans les Anthurium provoquent une irritation en cas de mastication ou d’ingestion." },
  problems: [
    { title: "Feuilles pliées", cause: "Manque d’espace sous la plante ou frottement contre un meuble.", advice: "Installer le pot plus haut et libérer le trajet des feuilles avant qu’elles ne s’allongent." },
    { title: "Pointes sèches", cause: "Air sec, sels ou arrosages irréguliers.", advice: "Stabiliser l’humidité du mélange et utiliser une eau peu minéralisée." },
    { title: "Racines qui noircissent", cause: "Substrat fin, froid ou eau stagnante.", advice: "Supprimer les tissus atteints et réinstaller dans une structure plus grossière." },
    { title: "Absence de floraison", cause: "Plante juvénile, lumière faible ou croissance instable.", advice: "Améliorer la lumière et la régularité sans rechercher une floraison forcée." },
  ],
  comparisons: [
    { name: "Anthurium pallidiflorum", difference: "Feuilles rubanées comparables, mais sans le spadice long et spiralé caractéristique de Wendlingeri." },
    { name: "Anthurium vittariifolium", difference: "Autre espèce pendante ; l’identification sûre doit intégrer l’inflorescence et les caractères du pétiole." },
    { name: "Anthurium bakeri", difference: "Feuilles plus courtes et inflorescence non spiralée de la même manière." },
  ],
  faq: [
    { question: "Pourquoi l’inflorescence de Wendlingeri est-elle spiralée ?", answer: "Le spadice s’allonge en mûrissant et adopte naturellement cette forme torsadée, propre à l’espèce." },
    { question: "Doit-on le cultiver en suspension ?", answer: "Ce n’est pas obligatoire, mais une installation haute évite que les longues feuilles et l’inflorescence touchent le sol ou un meuble." },
    { question: "Quel substrat utiliser ?", answer: "Un mélange grossier d’épiphyte qui retient un peu d’humidité tout en laissant beaucoup d’air aux racines." },
    { question: "Pourquoi ne fleurit-il pas ?", answer: "La maturité, la lumière et la stabilité de culture précèdent la floraison ; un jeune sujet peut rester longtemps uniquement végétatif." },
    { question: "Est-il toxique pour les animaux ?", answer: "Oui. Comme les autres Anthurium, il est irritant et toxique par ingestion." },
  ],
  tibaldoAdvice: [
    "Choisissez sa hauteur d’installation avant que les feuilles ne s’allongent.",
    "N’enfermez pas une forte humidité : ajoutez toujours de l’air en mouvement.",
    "Ne coupez pas le spadice uniquement parce qu’il se vrille ; c’est son développement normal.",
  ],
  localSpotlight: { title: "Créer de la hauteur sans courant d’air", text: "À Lille, une fenêtre lumineuse permet la culture en hauteur, à condition de protéger la plante des ouvrants froids en hiver." },
  editorialSections: [
    { id: "ruban", eyebrow: "Observer", title: "Une cascade de feuilles", paragraphs: ["Le feuillage étroit descend verticalement ; la composition doit lui réserver une zone libre."], points: ["Feuilles rubanées", "Port pendant", "Épiphyte"] },
    { id: "spirale", eyebrow: "Identifier", title: "Le spadice devient spirale", paragraphs: ["L’inflorescence est le caractère distinctif le plus spectaculaire, mais elle n’apparaît que sur une plante suffisamment mature."] },
    { id: "air", eyebrow: "Cultiver", title: "Des racines suspendues, jamais étouffées", paragraphs: ["Un mélange grossier, un pot percé et de l’air mobile reproduisent mieux la logique épiphyte qu’un terreau lourd."] },
  ],
  seo: { title: "Anthurium wendlingeri : entretien et spadice spiralé", description: "Guide d’Anthurium wendlingeri : feuilles rubanées, inflorescence en spirale, origine, lumière, humidité, substrat et culture en hauteur.", keywords: ["Anthurium wendlingeri", "Anthurium spirale", "Anthurium retombant", "Wendlingeri entretien"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A15824-2/general-information" },
    { label: "Missouri Botanical Garden — Revision of Anthurium", url: "https://www.missouribotanicalgarden.org/Portals/0/staff/PDFs/croat/ARevisionGenusAnthuriumMexicoCentralAmericaPart%20I.pdf" },
    { label: "Royal Horticultural Society — cultiver les Anthurium", url: "https://www.rhs.org.uk/plants/anthuriums/how-to-grow-anthuriums" },
  ],
});

const philodendronHederaceum = withHonestMediaGap({
  slug: "hederaceum",
  genre: "philodendron",
  genreLabel: "Philodendron",
  botanicalName: "Philodendron hederaceum",
  displayName: "Hederaceum",
  listingName: "Philodendron hederaceum · scandens",
  subtitle: "La liane à feuilles en cœur qui reste souple en suspension et change d’échelle lorsqu’elle grimpe.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Philodendron", species: "Philodendron hederaceum", cultivar: null, commonNames: ["Philodendron scandens", "Philodendron cœur", "Heartleaf philodendron"] },
  filters: {
    temperatureMin: 15, temperatureIdeal: [18, 27], humidityIdeal: [40, 70], light: "moyenne", watering: "modéré",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "rapide", habits: ["grimpant", "retombant", "hémiépiphyte"], adultSizeCm: 300,
    needsSupport: true, variegated: false, collection: false, flowering: false, petToxic: true, humanToxic: true, regions: ["Mexique", "Amérique tropicale"],
  },
  origin: "Du Mexique à l’Amérique tropicale",
  habitat: "Liane épiphyte ou hémiépiphyte des forêts tropicales humides, capable de ramper, retomber puis grimper vers la lumière.",
  hybridization: "Espèce botanique acceptée. Scandens correspond à un nom historique et horticole rattaché au même traitement, pas à une seconde fiche.",
  synonyms: ["Philodendron scandens", "Philodendron oxycardium", "Philodendron hederaceum var. hederaceum"],
  description: [
    "Philodendron hederaceum porte de fines feuilles vertes en forme de cœur sur des tiges souples. En suspension, il forme une cascade facile à conduire ; sur un support, les entre-nœuds se raccourcissent et les feuilles peuvent gagner en dimension.",
    "Le nom Philodendron scandens reste très utilisé, mais ne justifie pas une page distincte. Cette fiche réunit l’intention botanique et l’intention horticole sous le nom accepté Philodendron hederaceum.",
  ],
  specimen: { observedHeight: "Longueur de tige variable · liane de plusieurs mètres avec le temps", note: "La longueur observée dépend entièrement de la taille et du mode de conduite ; aucune dimension de stock n’est annoncée." },
  growth: { adultSize: "Longue liane ; format compact maintenu par la taille", speed: "Rapide en lumière et chaleur suffisantes", habit: "Grimpant ou retombant" },
  care: {
    light: 3, water: 2, humidity: 3, difficulty: 1,
    difficultyText: "Tolérant, avec une croissance plus dense en bonne lumière.",
    lightText: "Lumière moyenne à vive indirecte. Une faible lumière ralentit la croissance et allonge les entre-nœuds.",
    watering: "Laisser sécher légèrement la surface, puis arroser complètement et vider le cache-pot.",
    humidityText: "L’humidité moyenne d’un intérieur convient ; éviter surtout l’air brûlant d’un radiateur.",
    temperature: "Maintenir au-dessus d’environ 15 °C, idéalement 18 à 27 °C.",
    substrate: "Mélange organique souple et aéré, avec écorce et composant minéral drainant.",
    repotting: "Rempoter quand les racines occupent le pot ou que le mélange se tasse ; renouveler le support au besoin.",
    fertilizing: "Engrais équilibré à faible dose pendant la croissance active.",
    propagation: "Bouture de tige avec au moins un nœud, enracinée dans l’eau ou un substrat léger.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et animaux.", details: "La mastication libère des cristaux d’oxalate de calcium irritants, comme chez de nombreux Philodendron." },
  problems: [
    { title: "Tiges dégarnies", cause: "Manque de lumière ou croissance non taillée.", advice: "Rapprocher de la lumière et bouturer les extrémités pour densifier le pot." },
    { title: "Feuilles jaunes", cause: "Substrat trop humide ou vieillissement ponctuel.", advice: "Contrôler le séchage et le drainage avant le prochain arrosage." },
    { title: "Petites feuilles", cause: "Port retombant, faible lumière ou absence de support.", advice: "Guider une tige sur un support et renforcer progressivement la lumière." },
    { title: "Cochenilles", cause: "Insectes regroupés aux nœuds et sous les pétioles.", advice: "Isoler la plante et traiter chaque nœud de façon répétée." },
  ],
  comparisons: [
    { name: "Epipremnum aureum", difference: "Le pétiole et la gaine foliaire diffèrent ; l’Epipremnum a souvent une feuille plus épaisse et asymétrique." },
    { name: "Philodendron micans", difference: "Micans porte un limbe velouté aux reflets bronze, contrairement au vert satiné de Hederaceum." },
    { name: "Philodendron ‘Brasil’", difference: "Cultivar de Hederaceum marqué d’une bande centrale jaune à vert clair." },
  ],
  faq: [
    { question: "Philodendron scandens et hederaceum sont-ils différents ?", answer: "Dans cette encyclopédie, scandens est traité comme synonyme horticole de Philodendron hederaceum, sans créer une seconde page." },
    { question: "Peut-il vivre en suspension ?", answer: "Oui. Il retombe facilement, mais ses feuilles restent souvent plus petites que sur un support vertical." },
    { question: "Comment densifier le pot ?", answer: "Taillez au-dessus d’un nœud, enracinez les boutures puis replantez-les autour de la plante mère." },
    { question: "Tolère-t-il peu de lumière ?", answer: "Il peut survivre en lumière moyenne, mais une lumière vive indirecte donne un port plus compact et une croissance plus active." },
    { question: "Est-il toxique ?", answer: "Oui. Il ne doit pas être mâchouillé par les animaux ou les jeunes enfants." },
  ],
  tibaldoAdvice: [
    "Choisissez dès le départ : cascade souple ou croissance sur support.",
    "Pour densifier sans grand pot, replantez plusieurs boutures dans le même contenant.",
    "Scandens est une porte d’entrée horticole ; Hederaceum reste la référence canonique de la fiche.",
  ],
  localSpotlight: { title: "Un Philodendron lisible en hiver", text: "À Lille, une place proche de la fenêtre limite les longues tiges clairsemées lorsque les jours raccourcissent." },
  editorialSections: [
    { id: "coeur", eyebrow: "Reconnaître", title: "Une feuille en cœur, une tige souple", paragraphs: ["Le sinus marqué, le limbe fin et les longues tiges permettent de reconnaître le Hederaceum commun."], points: ["Feuille cordiforme", "Liane souple", "Nœuds faciles à bouturer"] },
    { id: "deux-ports", eyebrow: "Conduire", title: "Retomber ou grimper", paragraphs: ["La même plante produit deux silhouettes : légère en suspension, plus mature contre un support."] },
    { id: "nom", eyebrow: "Nommer", title: "Scandens mène à Hederaceum", paragraphs: ["Les deux intentions de recherche sont réunies ici pour éviter une duplication botanique et éditoriale."] },
  ],
  seo: { title: "Philodendron hederaceum (scandens) : entretien", description: "Guide du Philodendron hederaceum, souvent appelé scandens : lumière, arrosage, bouture, support, différences avec pothos et toxicité.", keywords: ["Philodendron hederaceum", "Philodendron scandens", "Philodendron cœur", "scandens entretien"] },
  sources: [
    { label: "Kew Science — Philodendron hederaceum", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A87797-1/general-information" },
    { label: "Royal Horticultural Society — cultiver les Philodendron", url: "https://www.rhs.org.uk/plants/philodendron/growing-guide" },
  ],
});

const philodendronPinkPrincess = withHonestMediaGap({
  slug: "pink-princess",
  genre: "philodendron",
  genreLabel: "Philodendron",
  botanicalName: "Philodendron ‘Pink Princess’",
  displayName: "Pink Princess",
  subtitle: "Un Philodendron grimpant dont chaque feuille mêle différemment vert sombre, crème et rose.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Philodendron", species: "Cultivar horticole rattaché au groupe de Philodendron erubescens", cultivar: "Pink Princess", commonNames: ["Philodendron Pink Princess", "Philodendron rose panaché"] },
  filters: {
    temperatureMin: 15, temperatureIdeal: [18, 27], humidityIdeal: [45, 70], light: "vive", watering: "modéré",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "moyenne", habits: ["grimpant"], adultSizeCm: 180,
    needsSupport: true, variegated: true, collection: true, flowering: false, petToxic: true, humanToxic: true, regions: ["Horticole"],
  },
  origin: "Cultivar horticole, sans aire naturelle propre",
  habitat: "Pink Princess n’existe pas comme population sauvage. Sa culture suit la logique des Philodendron grimpants tropicaux auxquels il est rattaché.",
  hybridization: "Cultivar horticole reconnu sous le nom Philodendron ‘Pink Princess’. Son origine parentale précise n’est pas affirmée ici faute de source primaire concluante.",
  synonyms: ["Philodendron erubescens ‘Pink Princess’", "Pink Princess Philodendron"],
  description: [
    "Philodendron ‘Pink Princess’ porte des feuilles épaisses et sombres, irrégulièrement éclaboussées de rose, de crème ou de vert plus clair. La répartition varie d’une feuille à l’autre et ne peut pas être programmée par l’arrosage.",
    "C’est une liane : un support vertical, une lumière vive filtrée et une taille raisonnée aident à maintenir un port dense. Une feuille presque blanche ou rose contient moins de chlorophylle et n’est pas forcément un objectif durable pour la plante.",
  ],
  specimen: { observedHeight: "Liane de taille moyenne · souvent 80 à 180 cm avec support", note: "Le niveau de panachure et la taille varient selon le clone et la maturité ; aucune apparence identique n’est garantie." },
  growth: { adultSize: "Liane de taille moyenne, maîtrisable par la taille", speed: "Moyenne, ralentie par une forte panachure", habit: "Grimpant" },
  care: {
    light: 4, water: 2, humidity: 3, difficulty: 3,
    difficultyText: "La culture est accessible ; la stabilité de la panachure demande observation et taille sélective.",
    lightText: "Lumière vive indirecte pour soutenir les zones panachées, sans soleil chaud sur les parties claires.",
    watering: "Laisser sécher légèrement la surface, puis arroser entièrement et vider l’eau résiduelle.",
    humidityText: "Une humidité intérieure moyenne convient ; éviter l’air très sec du chauffage sur les nouvelles feuilles.",
    temperature: "Maintenir au-dessus d’environ 15 °C, idéalement entre 18 et 27 °C.",
    substrate: "Mélange aéré pour aroïdes grimpantes, associant matière organique structurée, écorce et fraction minérale.",
    repotting: "Rempoter lorsque les racines occupent le pot et installer un support stable avant que la tige ne s’allonge.",
    fertilizing: "Engrais équilibré et modéré en croissance ; un excès ne crée pas davantage de rose.",
    propagation: "Bouture de tige avec nœud viable et panachure visible sur la tige ; une feuille sans nœud ne repart pas.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et animaux.", details: "Comme les autres Philodendron, la plante contient des cristaux d’oxalate de calcium irritants en cas d’ingestion." },
  problems: [
    { title: "Retour au vert", cause: "Un axe produit plusieurs feuilles sans panachure ou la tige a perdu les tissus panachés actifs.", advice: "Observer la panachure de la tige et, si nécessaire, retailler au-dessus d’un nœud visiblement panaché." },
    { title: "Zones roses qui brunissent", cause: "Faible chlorophylle, soleil direct, air sec ou arrosage irrégulier.", advice: "Stabiliser lumière et eau ; une zone très claire reste naturellement plus fragile." },
    { title: "Petites feuilles", cause: "Manque de support, lumière faible ou racines en difficulté.", advice: "Installer un tuteur, vérifier les racines et renforcer progressivement la lumière." },
    { title: "Thrips", cause: "Insectes attirés par les jeunes feuilles encore enroulées.", advice: "Isoler, inspecter les gaines et répéter un traitement adapté." },
  ],
  comparisons: [
    { name: "Philodendron ‘Pink Congo’", difference: "Une coloration rose temporaire induite commercialement ne correspond pas à la panachure stable par secteurs de Pink Princess." },
    { name: "Philodendron ‘White Princess’", difference: "Panachure principalement blanche ou crème, avec une distribution de couleurs et des pétioles différents." },
    { name: "Philodendron erubescens", difference: "Le groupe botanique de référence est généralement vert à rougeâtre, sans la panachure rose propre au cultivar." },
  ],
  faq: [
    { question: "Comment obtenir plus de rose ?", answer: "La lumière soutient la plante mais ne commande pas le motif. La répartition dépend du tissu panaché présent dans chaque nœud." },
    { question: "Faut-il couper une feuille entièrement verte ?", answer: "Une seule feuille verte n’impose pas une coupe. Surveillez plusieurs nœuds et la tige avant une taille sélective." },
    { question: "Une feuille rose peut-elle rester rose ?", answer: "Oui, mais elle contient peu de chlorophylle, brunit plus facilement et contribue moins à la croissance." },
    { question: "A-t-il besoin d’un tuteur ?", answer: "Oui. Un support rapproche sa culture du port grimpant et favorise des feuilles plus grandes." },
    { question: "Est-il toxique pour les animaux ?", answer: "Oui. Il ne doit pas être mâchouillé par les chats, chiens ou jeunes enfants." },
  ],
  tibaldoAdvice: [
    "Jugez la panachure sur plusieurs feuilles et surtout sur la tige, jamais sur une seule photo.",
    "Ne poursuivez pas le rose au détriment des zones vertes nécessaires à la plante.",
    "Installez le support tôt pour éviter une tige cassante et couchée.",
  ],
  localSpotlight: { title: "La panachure demande de la lumière", text: "À Lille, rapprochez Pink Princess de la fenêtre en hiver, sans exposer ses zones roses au soleil chaud de l’été." },
  editorialSections: [
    { id: "mosaique", eyebrow: "Observer", title: "Une mosaïque jamais identique", paragraphs: ["Chaque nœud distribue différemment les tissus verts et panachés. La plante reste un organisme vivant, pas un motif imprimé."], points: ["Vert chlorophyllien", "Rose variable", "Tige panachée"] },
    { id: "support", eyebrow: "Conduire", title: "Une princesse qui grimpe", paragraphs: ["Le nom évoque la couleur ; le port reste celui d’une liane qui gagne en qualité contre un support."] },
    { id: "equilibre", eyebrow: "Cultiver", title: "Préserver assez de vert", paragraphs: ["Un équilibre de feuilles vertes et panachées soutient mieux la croissance qu’une succession de feuilles presque sans chlorophylle."] },
  ],
  seo: { title: "Philodendron Pink Princess : entretien et panachure rose", description: "Guide du Philodendron Pink Princess : lumière, arrosage, tuteur, panachure rose, retour au vert, bouture et toxicité.", keywords: ["Philodendron Pink Princess", "Pink Princess entretien", "Philodendron rose", "Pink Princess panachure"] },
  sources: [
    { label: "Royal Horticultural Society — Philodendron ‘Pink Princess’", url: "https://www.rhs.org.uk/plants/272080/philodendron-pink-princess-v/details" },
    { label: "NC State Extension — Philodendron erubescens", url: "https://plants.ces.ncsu.edu/plants/philodendron-erubescens/common-name/blushing-philodendron/" },
    { label: "International Aroid Society — cultivar registry", url: "https://www.aroid.org/cultivarregistry" },
  ],
});

const monsteraAlboVariegata = withHonestMediaGap({
  slug: "albo-variegata",
  genre: "monstera",
  genreLabel: "Monstera",
  botanicalName: "Monstera deliciosa ‘Albo Variegata’",
  displayName: "Albo Variegata",
  subtitle: "La forme panachée de Monstera deliciosa, marbrée de blanc et conçue pour grimper.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Monstera", species: "Monstera deliciosa", cultivar: "Albo Variegata", commonNames: ["Monstera Albo", "Monstera Variegata", "Monstera deliciosa panachée"] },
  filters: {
    temperatureMin: 15, temperatureIdeal: [18, 25], humidityIdeal: [45, 70], light: "vive", watering: "modéré",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "moyenne", habits: ["grimpant", "hémiépiphyte"], adultSizeCm: 300,
    needsSupport: true, variegated: true, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Horticole", "Amérique tropicale"],
  },
  origin: "Sélection horticole de Monstera deliciosa, espèce originaire du Mexique au Panama",
  habitat: "Le cultivar n’a pas d’aire naturelle distincte. L’espèce est une liane de forêt tropicale humide qui grimpe grâce à ses racines aériennes.",
  hybridization: "Forme horticole panachée de Monstera deliciosa. Cette fiche rassemble les usages Albo, Albo-Variegata et Variegata sans créer de doublons.",
  synonyms: ["Monstera deliciosa ‘Variegata’", "Monstera deliciosa ‘Albo-Variegata’", "Monstera Albo"],
  description: [
    "Monstera deliciosa ‘Albo Variegata’ associe des secteurs verts à des marbrures crème ou blanches. La panachure apparaît aussi sur la tige : elle permet de lire le potentiel d’un futur nœud, sans garantir le dessin exact de la prochaine feuille.",
    "Comme la forme verte, elle change avec l’âge. Un support, une lumière vive filtrée et une croissance stable favorisent des feuilles plus grandes et fenêtrées. Les tissus blancs, sans chlorophylle, restent plus fragiles.",
  ],
  specimen: { observedHeight: "Grande liane · plusieurs mètres avec support", note: "La page décrit le taxon, pas un lot commercial. Le niveau de panachure et les dimensions varient selon chaque individu." },
  growth: { adultSize: "Grande liane d’intérieur, maîtrisable par la taille", speed: "Moyenne, souvent plus lente que la forme verte", habit: "Grimpant et hémiépiphyte" },
  care: {
    light: 4, water: 2, humidity: 3, difficulty: 3,
    difficultyText: "Culture proche de Deliciosa, avec plus d’attention portée à la lumière et aux tissus blancs.",
    lightText: "Lumière vive indirecte. Les zones blanches brûlent plus vite au soleil direct et ne compensent pas un emplacement sombre.",
    watering: "Arroser lorsque le quart à un tiers supérieur du mélange a séché, puis laisser l’excédent s’évacuer.",
    humidityText: "Une humidité intérieure modérée convient si l’arrosage et la ventilation restent réguliers.",
    temperature: "Idéalement 18 à 25 °C ; éviter le froid, les courants d’air et les températures prolongées sous environ 15 °C.",
    substrate: "Mélange structuré d’aroïde grimpante : organique, écorce, coco grossière et fraction minérale drainante.",
    repotting: "Rempoter lorsque les racines occupent réellement le pot et prévoir un tuteur assez stable pour durer.",
    fertilizing: "Engrais équilibré et modéré pendant la croissance ; l’engrais ne crée pas de panachure.",
    propagation: "Bouture de tige avec au moins un nœud viable et un bourgeon ; la panachure de la tige aide à évaluer le potentiel de reprise." },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des enfants et animaux.", details: "Les tissus contiennent des cristaux insolubles d’oxalate de calcium qui irritent la bouche et le tube digestif en cas de mastication." },
  problems: [
    { title: "Retour au vert", cause: "La croissance repart d’un secteur de tige peu ou pas panaché.", advice: "Observer plusieurs nœuds et retailler seulement si un axe devient durablement vert." },
    { title: "Blanc qui brunit", cause: "Faible chlorophylle, soleil direct, dessèchement ou sels.", advice: "Stabiliser lumière et eau ; accepter qu’une zone entièrement blanche reste fragile." },
    { title: "Pas de fenestrations", cause: "Plante jeune, lumière insuffisante ou absence de support.", advice: "Guider la liane sur un support et renforcer progressivement la lumière." },
    { title: "Feuille jaune", cause: "Excès d’eau, racines compactées ou faible lumière.", advice: "Contrôler les racines et le temps de séchage avant de modifier l’arrosage." },
  ],
  comparisons: [
    { name: "Monstera deliciosa ‘Thai Constellation’", difference: "Panachure crème généralement plus mouchetée et distribuée, issue d’un matériel horticole distinct." },
    { name: "Epipremnum pinnatum ‘Albo’", difference: "Tige, pétiole et forme juvénile différents ; le nom Monstera est parfois utilisé à tort dans le commerce." },
    { name: "Monstera deliciosa verte", difference: "Même espèce de base, sans secteurs blancs dépourvus de chlorophylle." },
  ],
  faq: [
    { question: "Albo, Variegata et Albo-Variegata désignent-ils la même plante ?", answer: "Ces noms horticoles sont couramment employés pour la même forme blanche panachée de Monstera deliciosa ; cette fiche les réunit sous un seul canonique." },
    { question: "Comment garder la panachure ?", answer: "Offrez une lumière vive indirecte et surveillez la panachure de la tige ; aucune méthode ne garantit le motif d’une feuille." },
    { question: "Pourquoi le blanc brunit-il ?", answer: "Ces tissus sans chlorophylle sont plus fragiles. Soleil direct, air sec, arrosage irrégulier et sels peuvent accélérer le brunissement." },
    { question: "Faut-il un tuteur ?", answer: "Oui. Un support stable aide la liane à produire des feuilles plus grandes et plus matures." },
    { question: "Une feuille seule peut-elle être bouturée ?", answer: "Non. Il faut au minimum un nœud viable et son bourgeon ; une feuille avec seulement un pétiole ne reforme pas une liane." },
  ],
  tibaldoAdvice: [
    "Regardez la tige et le nœud, pas seulement la dernière feuille.",
    "Préservez assez de vert : la plante a besoin de chlorophylle pour soutenir sa croissance.",
    "Dimensionnez ensemble pot et tuteur afin d’éviter un rempotage prématuré.",
  ],
  localSpotlight: { title: "Plus près de la fenêtre en hiver", text: "La lumière hivernale lilloise justifie souvent un rapprochement de la fenêtre, sans contact avec le vitrage froid." },
  editorialSections: [
    { id: "panachure", eyebrow: "Observer", title: "Lire le blanc sur la tige", paragraphs: ["Le dessin foliaire varie, mais la répartition des tissus sur la tige donne une indication plus utile sur le nœud suivant."], points: ["Secteurs verts", "Marbrures blanches", "Nœud viable"] },
    { id: "maturite", eyebrow: "Comprendre", title: "La panachure ne remplace pas la maturité", paragraphs: ["Fenestrations, taille et port dépendent encore de la lumière, du support et de l’âge de la liane."] },
    { id: "equilibre", eyebrow: "Cultiver", title: "Chercher l’équilibre, pas le tout blanc", paragraphs: ["Une proportion suffisante de vert soutient une croissance plus régulière et durable."] },
  ],
  seo: { title: "Monstera deliciosa Albo Variegata : entretien", description: "Guide du Monstera deliciosa Albo Variegata : panachure blanche, lumière, tuteur, arrosage, bouture, retour au vert et différences avec Thai Constellation.", keywords: ["Monstera Albo", "Monstera Albo Variegata", "Monstera Variegata", "Monstera panachée"] },
  sources: [
    { label: "Royal Horticultural Society — Monstera deliciosa ‘Variegata’", url: "https://www.rhs.org.uk/plants/90394/monstera-deliciosa-variegata-v/details" },
    { label: "Royal Horticultural Society — cultiver les Monstera", url: "https://www.rhs.org.uk/plants/swiss-cheese-plants/how-to-grow-swiss-cheese-plants" },
    { label: "NC State Extension — Monstera deliciosa", url: "https://plants.ces.ncsu.edu/plants/monstera-deliciosa/" },
  ],
});

const ficusElastica = withHonestMediaGap({
  slug: "elastica",
  genre: "ficus",
  genreLabel: "Ficus",
  botanicalName: "Ficus elastica",
  displayName: "Elastica",
  listingName: "Ficus elastica · caoutchouc",
  subtitle: "Un figuier tropical devenu plante d’intérieur, porté par de grandes feuilles épaisses et brillantes.",
  family: "Moraceae",
  taxonomy: { order: "Rosales", family: "Moraceae", genus: "Ficus", species: "Ficus elastica", cultivar: null, commonNames: ["Caoutchouc", "Figuier caoutchouc", "Rubber plant"] },
  filters: {
    temperatureMin: 10, temperatureIdeal: [18, 26], humidityIdeal: [40, 65], light: "vive", watering: "modéré",
    substrateTags: ["organique", "drainant", "structuré"], growthRate: "moyenne", habits: ["dressé"], adultSizeCm: 300,
    needsSupport: false, variegated: false, collection: false, flowering: false, petToxic: true, humanToxic: true, regions: ["Népal", "Inde", "Asie du Sud-Est", "Malesie"],
  },
  origin: "Du Népal à l’ouest du Yunnan et à la Malesie occidentale",
  habitat: "Grand arbre de forêt tropicale humide. En pot, il conserve un port dressé et ramifié mais reste très loin de ses dimensions naturelles.",
  hybridization: "Espèce botanique acceptée ; de nombreux cultivars colorés ou panachés existent sans modifier le canonique de l’espèce.",
  synonyms: ["Ficus elastica Roxb. ex Hornem.", "Ficus robusta (nom horticole historique)"],
  description: [
    "Ficus elastica produit de larges feuilles coriaces et vernissées, déroulées depuis une stipule souvent rougeâtre. Sa sève blanche et collante a inspiré son nom commun de caoutchouc.",
    "En intérieur, il devient un petit arbre graphique. Une lumière vive, une orientation stable et un arrosage qui laisse sécher la surface évitent le port dégarni et les chutes de feuilles les plus fréquentes.",
  ],
  specimen: { observedHeight: "Petit arbre d’intérieur · souvent 100 à 300 cm", note: "La taille dépend de l’âge, du cultivar et de la taille de formation ; aucune dimension de stock n’est annoncée." },
  growth: { adultSize: "Grand sujet d’intérieur, maîtrisable par la taille", speed: "Moyenne à rapide en forte lumière", habit: "Arborescent et dressé" },
  care: {
    light: 4, water: 2, humidity: 2, difficulty: 2,
    difficultyText: "Robuste si la lumière est suffisante et le pot jamais saturé.",
    lightText: "Lumière vive indirecte ; un peu de soleil doux est possible après acclimatation.",
    watering: "Laisser sécher plusieurs centimètres en surface avant un arrosage complet, puis vider le cache-pot.",
    humidityText: "L’humidité moyenne d’un intérieur convient ; nettoyer les grandes feuilles sans produit lustrant.",
    temperature: "Ambiance intérieure stable autour de 18 à 26 °C ; éviter les courants d’air et les températures sous environ 10 °C.",
    substrate: "Terreau structuré et drainant, enrichi d’une fraction minérale ou d’écorce pour préserver l’air autour des racines.",
    repotting: "Rempoter au printemps lorsque les racines remplissent le pot ; les grands sujets peuvent être surfaçés entre deux rempotages.",
    fertilizing: "Engrais équilibré une à deux fois par mois pendant la croissance, à dose modérée.",
    propagation: "Bouture de tige sous chaleur ou marcottage aérien sur une tige lignifiée ; se protéger de la sève irritante.",
  },
  toxicity: { level: "irritant et toxique", summary: "La sève et l’ingestion demandent de la prudence.", details: "Le latex peut irriter la peau et les yeux ; l’ingestion peut provoquer des troubles chez les humains et les animaux. Porter des gants lors de la taille." },
  problems: [
    { title: "Chute de feuilles", cause: "Excès d’eau, froid, courant d’air, faible lumière ou changement brutal.", advice: "Identifier le changement récent et vérifier les racines avant de déplacer à nouveau la plante." },
    { title: "Tige nue", cause: "Lumière insuffisante ou absence de taille de formation.", advice: "Augmenter progressivement la lumière et tailler au printemps pour stimuler une ramification." },
    { title: "Feuilles ternes", cause: "Poussière ou dépôt calcaire.", advice: "Essuyer avec un chiffon humide, sans huile ni lustrant." },
    { title: "Cochenilles", cause: "Insectes fixés le long des nervures et de la tige.", advice: "Isoler et retirer méthodiquement les colonies, puis répéter le contrôle." },
  ],
  comparisons: [
    { name: "Ficus lyrata", difference: "Feuilles plus grandes en forme de lyre et silhouette moins souple face aux changements d’ambiance." },
    { name: "Ficus benghalensis", difference: "Feuilles plus mates et souvent légèrement veloutées, sans le même aspect verni." },
    { name: "Ficus elastica ‘Robusta’", difference: "Nom horticole d’une sélection vigoureuse de la même espèce, pas une espèce séparée." },
  ],
  faq: [
    { question: "Pourquoi mon Ficus elastica perd-il ses feuilles ?", answer: "Cherchez d’abord un excès d’eau, un courant d’air froid, une baisse de lumière ou un déplacement récent." },
    { question: "Peut-on le tailler ?", answer: "Oui, de préférence en période de croissance. Portez des gants car la sève blanche est irritante." },
    { question: "Comment le faire ramifier ?", answer: "Une taille au-dessus d’un nœud sur une plante saine et bien éclairée peut réveiller un ou plusieurs bourgeons latéraux." },
    { question: "Faut-il vaporiser les feuilles ?", answer: "Ce n’est pas nécessaire. Un nettoyage doux et une humidité ambiante normale sont plus utiles." },
    { question: "Est-il toxique pour les animaux ?", answer: "Oui. Sa sève et ses tissus ne doivent pas être ingérés." },
  ],
  tibaldoAdvice: [
    "Faites pivoter le pot par petites étapes pour équilibrer la couronne.",
    "Tuteurez un jeune tronc si nécessaire, mais retirez les liens avant qu’ils ne marquent l’écorce.",
    "Après une taille, épongez la sève et protégez peau, yeux et surfaces.",
  ],
  localSpotlight: { title: "Un vrai besoin de lumière", text: "À Lille, Ficus elastica mérite une place proche d’une fenêtre ; un fond de pièce donne souvent une tige longue et dégarnie." },
  editorialSections: [
    { id: "stipule", eyebrow: "Reconnaître", title: "Une feuille déroulée depuis un étui rouge", paragraphs: ["La stipule protège la jeune feuille puis tombe à son ouverture. Le limbe épais et brillant complète l’identité."], points: ["Limbe coriace", "Stipule rougeâtre", "Latex blanc"] },
    { id: "arbre", eyebrow: "Comprendre", title: "Un arbre maintenu en intérieur", paragraphs: ["Le pot et la taille contiennent une espèce naturellement arborescente ; la lumière reste nécessaire à sa structure."] },
    { id: "former", eyebrow: "Conduire", title: "Tailler pour construire une couronne", paragraphs: ["Une taille réfléchie vaut mieux que des coupes répétées sur une plante affaiblie ou mal éclairée."] },
  ],
  seo: { title: "Ficus elastica : entretien du caoutchouc d’intérieur", description: "Guide de Ficus elastica : lumière, arrosage, taille, ramification, chute de feuilles, bouture et précautions avec la sève.", keywords: ["Ficus elastica", "plante caoutchouc", "Ficus elastica entretien", "Ficus feuilles jaunes"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A60458499-2/general-information" },
    { label: "Royal Horticultural Society — ornamental figs", url: "https://www.rhs.org.uk/plants/ornamental-figs/growing-guide" },
  ],
});

const hoyaCarnosa = withHonestMediaGap({
  slug: "carnosa",
  genre: "hoya",
  genreLabel: "Hoya",
  botanicalName: "Hoya carnosa",
  displayName: "Carnosa",
  listingName: "Hoya carnosa · fleur de porcelaine",
  subtitle: "Une liane épiphyte aux feuilles charnues et aux ombelles parfumées en forme de porcelaine.",
  family: "Apocynaceae",
  taxonomy: { order: "Gentianales", family: "Apocynaceae", genus: "Hoya", species: "Hoya carnosa", cultivar: null, commonNames: ["Fleur de porcelaine", "Fleur de cire", "Wax plant"] },
  filters: {
    temperatureMin: 10, temperatureIdeal: [16, 24], humidityIdeal: [40, 65], light: "vive", watering: "modéré",
    substrateTags: ["épiphyte", "aéré", "drainant", "organique"], growthRate: "moyenne", habits: ["grimpant", "retombant", "épiphyte"], adultSizeCm: 300,
    needsSupport: true, variegated: false, collection: false, flowering: true, petToxic: false, humanToxic: false, regions: ["Chine", "Laos", "Japon", "Taïwan"],
  },
  origin: "Du sud de la Chine au Laos, ainsi que du sud du Japon à Taïwan",
  habitat: "Liane épiphyte ou lithophyte des forêts subtropicales, installée sur des supports très aérés plutôt que dans un sol lourd.",
  hybridization: "Espèce botanique acceptée. De nombreux cultivars panachés ou compacts existent, mais cette fiche décrit l’espèce type.",
  synonyms: ["Hoya carnosa (L.f.) R.Br.", "Asclepias carnosa L.f."],
  description: [
    "Hoya carnosa produit de longues tiges souples garnies de feuilles opposées, épaisses et légèrement cireuses. Ses fleurs étoilées se regroupent en ombelles parfumées sur de courts pédoncules persistants.",
    "La plante préfère être conduite sur un cercle, un treillage ou en suspension. Sa réserve foliaire ne signifie pas qu’elle doit rester sèche pendant des semaines : l’arrosage suit le séchage du mélange, avec une vraie respiration des racines.",
  ],
  specimen: { observedHeight: "Longue liane · tiges de plusieurs mètres avec le temps", note: "Le port se maîtrise par le support et la taille ; la floraison dépend de la maturité et des conditions, jamais d’une promesse commerciale." },
  growth: { adultSize: "Liane longue, adaptable à un support ou une suspension", speed: "Moyenne", habit: "Grimpant, retombant et épiphyte" },
  care: {
    light: 4, water: 2, humidity: 2, difficulty: 2,
    difficultyText: "Robuste en forte lumière et dans un mélange vraiment drainant.",
    lightText: "Lumière vive indirecte avec éventuellement un soleil doux du matin après acclimatation.",
    watering: "Arroser quand une partie du mélange a séché, puis laisser s’égoutter ; réduire nettement si la température baisse.",
    humidityText: "Une humidité intérieure moyenne convient, avec une bonne ventilation autour des tiges.",
    temperature: "Idéalement 16 à 24 °C ; Hoya carnosa tolère ponctuellement plus frais mais doit rester au-dessus d’environ 10 °C.",
    substrate: "Mélange très aéré d’épiphyte : écorce, fibre ou chips de coco, fraction organique et minéral poreux.",
    repotting: "Rempoter seulement lorsque le mélange se dégrade ou que les racines saturent le pot ; un contenant légèrement ajusté convient.",
    fertilizing: "Engrais équilibré et dilué pendant la croissance et la préparation florale.",
    propagation: "Bouture de tige comportant deux ou trois nœuds, ou marcottage d’une tige encore reliée à la plante mère.",
  },
  toxicity: { level: "non toxique selon l’ASPCA", summary: "Hoya carnosa est classée non toxique pour les chats et les chiens.", details: "Une plante non toxique n’est pas destinée à être consommée. Éloignez-la d’un animal qui mâchouille régulièrement le feuillage et demandez conseil à un vétérinaire en cas de symptôme." },
  problems: [
    { title: "Pas de fleurs", cause: "Lumière insuffisante, plante jeune, taille des pédoncules ou changements répétés.", advice: "Renforcer la lumière, conserver les pédoncules et laisser la plante stabiliser son emplacement." },
    { title: "Feuilles molles", cause: "Soif prolongée ou racines abîmées par excès d’eau.", advice: "Inspecter les racines avant de conclure à un simple manque d’eau." },
    { title: "Taches liégeuses", cause: "Œdème lié à une absorption d’eau plus rapide que l’évaporation.", advice: "Espacer les arrosages, augmenter la lumière et l’aération." },
    { title: "Cochenilles farineuses", cause: "Colonies aux nœuds et sous les feuilles.", advice: "Isoler, nettoyer chaque insertion et répéter le traitement." },
  ],
  comparisons: [
    { name: "Hoya pubicalyx", difference: "Feuilles souvent plus longues et lancéolées ; fleurs et pédoncules présentent d’autres caractères." },
    { name: "Hoya australis", difference: "Feuilles plus rondes et croissance généralement plus vigoureuse, avec une ombelle différente." },
    { name: "Hoya carnosa ‘Compacta’", difference: "Cultivar de la même espèce aux feuilles fortement recourbées et imbriquées." },
  ],
  faq: [
    { question: "Pourquoi mon Hoya carnosa ne fleurit-il pas ?", answer: "La maturité et une lumière vive sont déterminantes. Gardez la plante stable et ne coupez pas ses anciens pédoncules." },
    { question: "Faut-il couper la tige après les fleurs ?", answer: "Non. Les pédoncules peuvent refleurir ; retirez seulement les fleurs fanées sans supprimer leur base." },
    { question: "Aime-t-il être serré dans son pot ?", answer: "Il tolère un pot ajusté, mais cela ne doit pas devenir un prétexte pour conserver un substrat dégradé ou des racines asphyxiées." },
    { question: "Peut-on le cultiver en suspension ?", answer: "Oui. Il peut retomber, grimper sur un support ou combiner les deux ports." },
    { question: "Ses feuilles épaisses signifient-elles qu’il faut très peu d’eau ?", answer: "Elles stockent une partie de l’eau, mais la plante doit être arrosée à fond après un séchage partiel, pas abandonnée au dessèchement prolongé." },
  ],
  tibaldoAdvice: [
    "Marquez les pédoncules avant une taille pour ne pas les supprimer par erreur.",
    "Évitez de déplacer une plante en boutons : un changement brutal peut interrompre la floraison.",
    "L’arrosage se décide au poids du pot et à l’état des racines, pas à la seule fermeté des feuilles.",
  ],
  localSpotlight: { title: "Lumière d’hiver et floraison", text: "Dans le Nord, une place proche d’une fenêtre aide Hoya carnosa à constituer les réserves nécessaires à sa croissance et à sa floraison." },
  editorialSections: [
    { id: "ombelle", eyebrow: "Reconnaître", title: "Une ombelle de cire", paragraphs: ["Les fleurs étoilées paraissent modelées dans la porcelaine et se regroupent sur un pédoncule qui reste utile après la floraison."], points: ["Feuilles opposées", "Tiges souples", "Ombelles parfumées"] },
    { id: "pedoncule", eyebrow: "Comprendre", title: "Ne pas couper le futur", paragraphs: ["Un ancien pédoncule peut produire une nouvelle ombelle ; il appartient à l’architecture durable de la liane."] },
    { id: "epiphyte", eyebrow: "Cultiver", title: "Des racines qui veulent respirer", paragraphs: ["La structure du mélange compte davantage qu’un grand volume de terreau nutritif."] },
  ],
  seo: { title: "Hoya carnosa : entretien et floraison de la fleur de porcelaine", description: "Guide de Hoya carnosa : lumière, arrosage, floraison, pédoncules, substrat, bouture et différences avec les autres Hoya.", keywords: ["Hoya carnosa", "fleur de porcelaine", "Hoya carnosa entretien", "Hoya floraison"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A107308-3/general-information" },
    { label: "Royal Horticultural Society — cultiver les Hoya", url: "https://www.rhs.org.uk/plants/hoya/how-to-grow" },
    { label: "Royal Horticultural Society — Hoya carnosa", url: "https://www.rhs.org.uk/plants/8852/hoya-carnosa/details" },
    { label: "ASPCA — Hoya carnosa (Wax Plant)", url: "https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/honey-plant" },
  ],
});

const syngoniumPodophyllum = withHonestMediaGap({
  slug: "podophyllum",
  genre: "syngonium",
  genreLabel: "Syngonium",
  botanicalName: "Syngonium podophyllum",
  displayName: "Podophyllum",
  listingName: "Syngonium podophyllum · patte-d’oie",
  subtitle: "Une liane dont les jeunes feuilles en flèche se divisent progressivement en grandissant.",
  family: "Araceae",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Syngonium", species: "Syngonium podophyllum", cultivar: null, commonNames: ["Patte-d’oie", "Plante flèche", "Arrowhead vine"] },
  filters: {
    temperatureMin: 15, temperatureIdeal: [18, 27], humidityIdeal: [45, 75], light: "moyenne", watering: "modéré",
    substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate: "rapide", habits: ["grimpant", "retombant", "hémiépiphyte"], adultSizeCm: 250,
    needsSupport: true, variegated: false, collection: false, flowering: false, petToxic: true, humanToxic: true, regions: ["Mexique", "Amérique tropicale"],
  },
  origin: "Du Mexique à l’Amérique tropicale",
  habitat: "Liane de forêt tropicale humide qui grimpe dans la végétation. La forme des feuilles change nettement entre les stades juvénile et adulte.",
  hybridization: "Espèce botanique acceptée, à l’origine de nombreux cultivars de couleur et de panachure.",
  synonyms: ["Nephthytis podophylla", "Syngonium affine (usage horticole historique)"],
  description: [
    "Syngonium podophyllum commence avec des feuilles simples en pointe de flèche. Lorsqu’une tige mûrit sur un support, le limbe se divise progressivement jusqu’à former plusieurs segments disposés comme une patte d’oie.",
    "Cette transformation est souvent masquée par la taille des plantes commerciales, maintenues compactes. Laisser une tige grimper permet d’observer l’hétéroblastie sans changer d’espèce.",
  ],
  specimen: { observedHeight: "Liane de plusieurs mètres dans le temps ; format compact par la taille", note: "La page décrit l’espèce type. Les nombreux cultivars colorés demandent un traitement propre lorsqu’ils sont documentés." },
  growth: { adultSize: "Longue liane, facilement maintenue compacte", speed: "Rapide", habit: "Grimpant, retombant ou couvre-sol" },
  care: {
    light: 3, water: 3, humidity: 3, difficulty: 1,
    difficultyText: "Très adaptable, à condition d’éviter l’eau stagnante.",
    lightText: "Lumière moyenne à vive indirecte ; la forme verte tolère une luminosité modérée mais s’étire davantage.",
    watering: "Arroser lorsque la surface commence à sécher, puis vider l’eau résiduelle.",
    humidityText: "Une humidité intérieure moyenne convient ; une ambiance plus humide aide les nouvelles feuilles à se déployer.",
    temperature: "Ambiance chaude et stable entre 18 et 27 °C, sans séjour prolongé sous environ 15 °C.",
    substrate: "Mélange organique aéré et drainant, avec écorce ou fraction minérale pour éviter le tassement.",
    repotting: "Rempoter lorsque les racines remplissent le pot ; installer un support si l’objectif est d’observer la forme adulte.",
    fertilizing: "Engrais équilibré à faible dose pendant la croissance active.",
    propagation: "Bouture de tige avec un ou plusieurs nœuds, dans l’eau ou un substrat léger ; division possible d’une touffe dense.",
  },
  toxicity: { level: "toxique", summary: "À éloigner des enfants et animaux.", details: "Les cristaux d’oxalate de calcium irritent la bouche et le tube digestif si la plante est mâchée ou ingérée." },
  problems: [
    { title: "Tiges longues et feuilles rares", cause: "Lumière insuffisante.", advice: "Rapprocher progressivement de la fenêtre et bouturer les extrémités pour densifier." },
    { title: "Feuilles qui restent simples", cause: "Plante juvénile, taille régulière ou absence de support.", advice: "Laisser une tige grimper et gagner en maturité." },
    { title: "Jaunissement", cause: "Substrat trop humide ou lumière très faible.", advice: "Contrôler le séchage et l’état des racines avant le prochain arrosage." },
    { title: "Thrips", cause: "Insectes cachés dans les nouvelles feuilles enroulées.", advice: "Isoler, ouvrir seulement par observation sans forcer la feuille, et traiter plusieurs fois." },
  ],
  comparisons: [
    { name: "Caladium", difference: "Le Caladium pousse depuis un tubercule et ne forme pas la même longue liane à nœuds." },
    { name: "Philodendron hederaceum", difference: "Feuille juvénile plus franchement cordiforme et forme adulte ne se divisant pas en patte d’oie." },
    { name: "Syngonium angustatum", difference: "Taxon proche à distinguer par des caractères botaniques au-delà du seul nom commercial." },
  ],
  faq: [
    { question: "Pourquoi les feuilles changent-elles de forme ?", answer: "Syngonium podophyllum est hétéroblastique : la feuille juvénile en flèche se divise lorsque la liane mûrit." },
    { question: "A-t-il besoin d’un tuteur ?", answer: "Pas pour survivre, mais un support favorise une croissance mature et des feuilles davantage divisées." },
    { question: "Peut-on le garder compact ?", answer: "Oui. Taillez les tiges et replantez des boutures dans le pot pour former une touffe dense." },
    { question: "Tolère-t-il peu de lumière ?", answer: "La forme verte le supporte mieux que les cultivars panachés, mais une lumière vive indirecte donne une croissance plus équilibrée." },
    { question: "Est-il toxique ?", answer: "Oui. Il est irritant et toxique par ingestion pour les humains et les animaux." },
  ],
  tibaldoAdvice: [
    "Gardez une tige non taillée sur support si vous voulez observer le passage vers la feuille adulte.",
    "Pour un pot dense, replantez des boutures plutôt que de choisir un contenant trop grand.",
    "Ne forcez jamais l’ouverture d’une jeune feuille enroulée.",
  ],
  localSpotlight: { title: "Une liane adaptable à la lumière du Nord", text: "En hiver à Lille, rapprochez le pot de la fenêtre pour limiter les entre-nœuds longs et conserver un feuillage dense." },
  editorialSections: [
    { id: "fleche", eyebrow: "Observer", title: "D’abord une flèche", paragraphs: ["La forme juvénile est simple, sagittée et souple ; c’est celle que montrent la plupart des jeunes plantes en pot."], points: ["Feuille sagittée", "Tige à nœuds", "Racines aériennes"] },
    { id: "metamorphose", eyebrow: "Comprendre", title: "Puis une patte d’oie", paragraphs: ["La division du limbe accompagne la maturité et la grimpe. Elle ne signale ni maladie ni changement de variété."] },
    { id: "choisir-port", eyebrow: "Conduire", title: "Touffe ou liane", paragraphs: ["La taille conserve une silhouette compacte ; le support révèle le développement adulte."] },
  ],
  seo: { title: "Syngonium podophyllum : entretien et feuilles adultes", description: "Guide de Syngonium podophyllum : feuille en flèche, forme adulte divisée, lumière, arrosage, tuteur, bouture et toxicité.", keywords: ["Syngonium podophyllum", "plante patte d’oie", "Syngonium entretien", "Syngonium feuille adulte"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A89152-1/general-information" },
    { label: "NC State Extension — Syngonium podophyllum", url: "https://plants.ces.ncsu.edu/plants/syngonium-podophyllum/" },
  ],
});

const dracaenaTrifasciata = withHonestMediaGap({
  slug: "trifasciata",
  genre: "sansevieria",
  genreLabel: "Sansevieria",
  botanicalName: "Dracaena trifasciata",
  displayName: "Trifasciata",
  listingName: "Dracaena trifasciata · Sansevieria",
  subtitle: "La langue de belle-mère : une Dracaena rhizomateuse aux feuilles verticales et sobres en eau.",
  family: "Asparagaceae",
  taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Dracaena", species: "Dracaena trifasciata", cultivar: null, commonNames: ["Sansevieria trifasciata", "Langue de belle-mère", "Snake plant"] },
  filters: {
    temperatureMin: 10, temperatureIdeal: [18, 27], humidityIdeal: [30, 60], light: "vive", watering: "faible",
    substrateTags: ["succulentes", "minéral", "drainant", "aéré"], growthRate: "lente", habits: ["terrestre", "dressé"], adultSizeCm: 120,
    needsSupport: false, variegated: false, collection: false, flowering: true, petToxic: true, humanToxic: true, regions: ["Afrique de l’Ouest", "Afrique centrale", "Tanzanie"],
  },
  origin: "Du sud du Nigeria à l’Afrique tropicale occidentale et centrale, jusqu’à la Tanzanie",
  habitat: "Géophyte rhizomateuse des régions tropicales saisonnièrement sèches. Ses feuilles charnues et son rhizome stockent l’eau.",
  hybridization: "Espèce botanique acceptée dans le genre Dracaena. Sansevieria trifasciata reste son synonyme horticole majeur et explique son classement dans le hub Sansevieria.",
  synonyms: ["Sansevieria trifasciata", "Sansevieria zeylanica (nom souvent mal appliqué en horticulture)"],
  description: [
    "Dracaena trifasciata forme des touffes de feuilles dressées, épaisses et marquées de bandes transversales vertes. Les nouvelles rosettes apparaissent le long de rhizomes souterrains qui colonisent progressivement le pot.",
    "Toujours connue comme Sansevieria, elle est aujourd’hui placée dans le genre Dracaena. Sa réputation de plante indestructible doit être nuancée : elle tolère l’oubli d’eau, mais pourrit vite dans un pot froid et humide.",
  ],
  specimen: { observedHeight: "Touffe dressée · souvent 40 à 120 cm selon la forme", note: "La page décrit l’espèce ; les cultivars nains, panachés ou cylindriques appartiennent à des traitements séparés lorsque documentés." },
  growth: { adultSize: "Touffe verticale de taille moyenne", speed: "Lente à moyenne", habit: "Rhizomateux, terrestre et dressé" },
  care: {
    light: 4, water: 1, humidity: 1, difficulty: 1,
    difficultyText: "Très tolérante, mais vulnérable à l’excès d’eau.",
    lightText: "Lumière vive indirecte à soleil doux après acclimatation. Elle tolère moins de lumière mais y pousse beaucoup plus lentement.",
    watering: "Laisser sécher le mélange très largement, voire complètement en profondeur, avant un nouvel arrosage ; réduire fortement en hiver.",
    humidityText: "L’humidité ordinaire d’un intérieur suffit ; éviter l’eau logée dans le cœur des rosettes.",
    temperature: "Idéalement 18 à 27 °C ; conserver au-dessus d’environ 10 °C et presque au sec si l’ambiance fraîchit.",
    substrate: "Mélange très drainant et minéral, dans un pot percé ; la structure doit évacuer rapidement l’eau.",
    repotting: "Rempoter quand les rhizomes déforment le pot ou que les racines le remplissent, dans un contenant stable légèrement plus large.",
    fertilizing: "Apport léger et espacé au printemps et en été ; éviter les doses fortes dans un pot peu arrosé.",
    propagation: "Division du rhizome pour conserver fidèlement la plante ; bouture de feuille possible pour la forme verte, mais certains cultivars perdent leur panachure.",
  },
  toxicity: { level: "toxique", summary: "À tenir hors de portée des animaux et des jeunes enfants.", details: "L’ingestion peut provoquer des troubles digestifs ; les animaux domestiques ne doivent pas mâchouiller les feuilles." },
  problems: [
    { title: "Base molle", cause: "Excès d’eau, substrat froid ou eau restée dans la rosette.", advice: "Retirer les tissus atteints, sécher puis rempoter dans un mélange très drainant." },
    { title: "Feuilles qui se plissent", cause: "Sécheresse prolongée ou racines déjà détruites.", advice: "Contrôler d’abord les racines ; n’arroser abondamment que si elles sont saines." },
    { title: "Croissance arrêtée", cause: "Faible lumière, fraîcheur ou repos saisonnier.", advice: "Augmenter progressivement la lumière et patienter avant tout apport d’eau ou d’engrais." },
    { title: "Cochenilles", cause: "Colonies cachées à la base et entre les feuilles.", advice: "Écarter doucement les feuilles, isoler et répéter le traitement." },
  ],
  comparisons: [
    { name: "Dracaena angolensis", difference: "Feuilles cylindriques plutôt que plates et rubanées." },
    { name: "Dracaena trifasciata ‘Laurentii’", difference: "Cultivar de la même espèce bordé de jaune ; la division du rhizome conserve mieux cette panachure." },
    { name: "Sansevieria zeylanica", difference: "Nom commercial souvent utilisé de façon imprécise ; il ne doit pas remplacer automatiquement l’identification Trifasciata." },
  ],
  faq: [
    { question: "Sansevieria trifasciata et Dracaena trifasciata sont-elles la même plante ?", answer: "Oui. Dracaena trifasciata est le nom botanique accepté ; Sansevieria trifasciata reste un synonyme horticole très connu." },
    { question: "Peut-elle vivre dans le noir ?", answer: "Non. Elle tolère une lumière faible mais ne peut pas vivre sans lumière et y croît très lentement." },
    { question: "À quelle fréquence faut-il l’arroser ?", answer: "Il n’existe pas de calendrier universel. Attendez que le mélange ait très largement séché, puis adaptez à la saison et à la température." },
    { question: "Pourquoi les feuilles deviennent-elles molles ?", answer: "La cause la plus fréquente est une pourriture liée à l’excès d’eau, surtout au froid. Contrôlez la base et les racines." },
    { question: "Comment la multiplier ?", answer: "La division du rhizome est la méthode la plus fidèle. Une bouture de feuille fonctionne pour la forme verte, mais pas toujours pour conserver une panachure." },
  ],
  tibaldoAdvice: [
    "En cas de doute, attendez avant d’arroser : le rhizome supporte mieux le sec que la saturation.",
    "Gardez le nom Sansevieria visible pour l’usage, tout en affichant Dracaena trifasciata comme canonique.",
    "Un pot percé et un mélange minéral valent mieux qu’un cache-pot décoratif constamment humide.",
  ],
  localSpotlight: { title: "Peu d’eau pendant l’hiver lillois", text: "Quand lumière et température baissent, le mélange sèche lentement : espacez fortement les arrosages et gardez la plante près d’une fenêtre." },
  editorialSections: [
    { id: "verticale", eyebrow: "Reconnaître", title: "Des lames verticales", paragraphs: ["Les feuilles plates, dressées et marquées de bandes transversales émergent en rosettes reliées par un rhizome."], points: ["Feuilles rubanées", "Bandes vertes", "Rhizome souterrain"] },
    { id: "nom", eyebrow: "Nommer", title: "Sansevieria devient Dracaena", paragraphs: ["Le nom familier reste utile pour la découverte, tandis que la fiche adopte le nom accepté Dracaena trifasciata."] },
    { id: "sec", eyebrow: "Cultiver", title: "Stocker l’eau, éviter l’excès", paragraphs: ["Feuilles et rhizomes rendent la plante sobre ; ils deviennent vulnérables lorsque le pot reste froid et mouillé."] },
  ],
  seo: { title: "Dracaena trifasciata : entretien de la Sansevieria", description: "Guide de Dracaena trifasciata, la Sansevieria : lumière, arrosage, rempotage, pourriture, multiplication et nouveau nom botanique.", keywords: ["Dracaena trifasciata", "Sansevieria trifasciata", "langue de belle-mère", "Sansevieria entretien"] },
  sources: [
    { label: "Kew Science — Plants of the World Online", url: "https://powo.science.kew.org/taxon/urn%3Alsid%3Aipni.org%3Anames%3A77164235-1/general-information" },
    { label: "Royal Horticultural Society — Sansevieria", url: "https://www.rhs.org.uk/plants/sansevieria/growing-guide" },
    { label: "NC State Extension — Dracaena trifasciata", url: "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/" },
  ],
});

const encyclopediaP1Drafts = [
  alocasiaTandurusa,
  alocasiaMelo,
  alocasiaPolly,
  anthuriumLuxurians,
  anthuriumWendlingeri,
  philodendronHederaceum,
  philodendronPinkPrincess,
  monsteraAlboVariegata,
  ficusElastica,
  hoyaCarnosa,
  syngoniumPodophyllum,
  dracaenaTrifasciata,
] satisfies PlantEntry[];

export const encyclopediaP1Plants = encyclopediaP1Drafts.map((plant) => {
  const gallery = p1VerifiedMediaByRoute[`${plant.genre}/${plant.slug}`];
  return gallery
    ? { ...plant, gallery, mediaNeeds: undefined, updatedAt: publicationDate }
    : plant;
});

export const encyclopediaP1Routes = encyclopediaP1Plants.map(
  (plant) => `/plantes/${plant.genre}/${plant.slug}`,
);
