export const familyEditorials = {
  alocasia: [
    { title: "Une présence tropicale spectaculaire", text: "Les Alocasia sont recherchés pour leur silhouette architecturale, leurs pétioles graphiques et leurs feuilles parfois immenses. Certaines espèces restent compactes tandis que d’autres deviennent de véritables plantes XXL. Leur aspect varie beaucoup selon la variété : limbes veloutés, nervures contrastées, reflets métalliques ou tiges colorées. Cette diversité permet de choisir un Alocasia adapté à une étagère lumineuse comme à un grand séjour." },
    { title: "Réussir un Alocasia à Lille", text: "Dans un intérieur lillois, la lumière constitue le premier facteur de réussite. Une place proche d’une fenêtre lumineuse, protégée du soleil brûlant, favorise des feuilles plus solides et une croissance régulière. En hiver, la baisse de luminosité ralentit naturellement la plante : les arrosages doivent alors diminuer. Le froid contre une vitre, les courants d’air et un substrat constamment détrempé sont plus dangereux qu’une humidité ambiante imparfaite." },
    { title: "Racines, substrat et nutrition", text: "Un mélange aéré associant terreau structuré, écorce, coco et fraction minérale laisse circuler l’oxygène autour des racines. Le pot doit être percé et proportionné à la motte. Pendant la croissance, une fertilisation douce mais régulière accompagne la production de grandes feuilles. Tibaldo Jungle adapte le rempotage à l’état réel des racines plutôt qu’à un calendrier automatique, afin d’éviter les pots trop volumineux et les excès d’eau." },
  ],
  anthurium: [
    { title: "Bien plus que l’Anthurium fleuri", text: "Le genre Anthurium réunit des plantes très différentes. Aux formes florifères bien connues s’ajoutent des espèces de collection cultivées pour leurs feuilles veloutées, cordiformes, allongées ou fortement nervurées. Certaines poussent en rosette, d’autres développent une tige grimpante. Cette richesse botanique explique pourquoi deux Anthurium peuvent avoir une apparence et un rythme de culture très éloignés." },
    { title: "Lumière douce et humidité stable", text: "Les Anthurium apprécient généralement une lumière vive sans soleil agressif. À Lille, une fenêtre bien exposée devient précieuse en automne et en hiver, tandis qu’un léger recul peut être nécessaire l’été. L’objectif n’est pas de maintenir un substrat mouillé, mais d’éviter les alternances brutales entre sécheresse prolongée et saturation. Une humidité régulière, accompagnée d’une bonne circulation d’air, aide les nouvelles feuilles à se déployer proprement." },
    { title: "Cultiver les racines autant que les feuilles", text: "Les racines d’Anthurium ont besoin d’un mélange respirant. Écorce fine, sphaigne utilisée avec mesure, chips de coco et éléments minéraux peuvent compléter un terreau de qualité. Les espèces épiphytes tolèrent mal les mélanges lourds. Une nutrition diluée pendant la période lumineuse soutient la croissance sans charger le substrat en sels. Au Studio, chaque rempotage est ajusté au type de racines et au comportement de la plante." },
  ],
  monstera: [
    { title: "Une liane qui change avec l’âge", text: "Le Monstera n’est pas une plante figée : son feuillage évolue lorsqu’il gagne en maturité, en lumière et en qualité de support. Une jeune feuille peut être entière, puis devenir progressivement plus grande, découpée ou fenestrée. Les racines aériennes participent à son ancrage. Comprendre ce comportement grimpant permet d’obtenir une plante plus équilibrée et plus spectaculaire qu’en la laissant simplement retomber." },
    { title: "Des Monstera adaptés aux intérieurs lillois", text: "Une lumière vive indirecte reste essentielle pour conserver des entre-nœuds courts et favoriser la maturation des feuilles. Dans les logements de Lille, il faut tenir compte des saisons : rapprocher progressivement la plante d’une fenêtre en hiver, puis surveiller le soleil direct au retour des beaux jours. Un grand Monstera demande aussi de l’espace, un support stable et un pot suffisamment lourd pour éviter le basculement." },
    { title: "Arrosage, tuteur et rempotage", text: "Le substrat doit retenir assez d’humidité tout en évacuant rapidement l’excédent. Un tuteur en fibre, en liège ou un support rigide guide la face arrière de la tige et permet aux racines aériennes de s’ancrer. Le rempotage n’est utile que lorsque la motte est réellement occupée. Tibaldo Jungle conseille aussi la taille, le bouturage et la reprise sur support pour rajeunir les sujets devenus trop longs." },
  ],
  philodendron: [
    { title: "Un genre aux formes presque infinies", text: "Les Philodendron peuvent être grimpants, rampants ou autoportants. Certains portent des feuilles en cœur très accessibles, d’autres développent un feuillage velouté, découpé, coloré ou fortement nervuré. Avant de choisir une variété, il faut comprendre son port : un grimpant demande un support vertical, un rampant réclame un contenant plus large et un hybride autoportant construit seul sa silhouette." },
    { title: "Trouver la bonne place à Lille", text: "La majorité des Philodendron préfère une lumière vive filtrée, une température stable et une croissance sans courant d’air froid. Une variété verte tolère souvent mieux une lumière moyenne qu’une forme panachée. Dans un intérieur lillois, l’observation de la distance entre les nouvelles feuilles renseigne rapidement : une tige qui s’allonge excessivement cherche généralement davantage de lumière." },
    { title: "Accompagner une croissance durable", text: "Un mélange organique et minéral, suffisamment aéré, protège les racines des excès d’eau. Les arrosages suivent le séchage réel du pot et non un jour fixe de la semaine. La fertilisation reste progressive pendant les mois lumineux. Au Studio Végétal, nous aidons à choisir le bon support, à réorienter une plante et à rempoter les grands Philodendron sans déstabiliser leur système racinaire." },
  ],
  epipremnum: [
    { title: "Le pothos peut devenir gigantesque", text: "Souvent vendu comme petite plante retombante, l’Epipremnum est en réalité une liane capable de produire des feuilles beaucoup plus grandes lorsqu’elle grimpe. Ses nœuds émettent facilement des racines aériennes et rendent le bouturage accessible. Les variétés vertes, dorées, blanches ou argentées n’ont toutefois pas exactement la même vigueur ni les mêmes besoins en lumière." },
    { title: "Une plante facile, mais pas indifférente", text: "L’Epipremnum tolère plusieurs situations, ce qui ne signifie pas qu’il prospère partout. Une lumière insuffisante ralentit la croissance, allonge les tiges et réduit les panachures. À Lille, placez-le près d’une source lumineuse en hiver et protégez les feuilles claires d’un soleil estival brutal. Laissez le mélange sécher partiellement entre deux arrosages afin de préserver les racines." },
    { title: "Créer une plante dense ou mature", text: "Pour un pot fourni, plusieurs boutures peuvent être regroupées et taillées régulièrement. Pour obtenir de grandes feuilles, mieux vaut conduire une tige sur un support vertical et lui offrir chaleur, lumière et nutrition. Tibaldo Jungle peut préparer un mélange drainant, installer un tuteur adapté et expliquer comment bouturer les sections devenues trop longues sans perdre la plante mère." },
  ],
  asparagus: [
    { title: "Une fausse fougère pleine de mouvement", text: "Asparagus setaceus est souvent vendu comme fougère asparagus ou Asparagus plumosus. Il appartient pourtant à la famille de l’asperge. Ses fins cladodes composent des étages de verdure très légers, portés par des tiges qui s’arquent puis cherchent naturellement à s’appuyer." },
    { title: "Préserver la finesse du feuillage", text: "Dans un intérieur lillois, placez-le près d’une fenêtre lumineuse, loin d’un radiateur. Le mélange reste légèrement frais pendant la croissance sans demeurer saturé. Une tige jaunie ne redevient pas verte : elle se retire à la base afin de favoriser un nouveau départ." },
    { title: "Du petit pot à la plante sarmenteuse", text: "Le jeune Plumosus semble compact, mais ses racines vigoureuses et ses longues tiges peuvent rapidement transformer sa silhouette. Un rempotage progressif, une taille réfléchie et un support léger permettent de choisir entre un port retombant et une allure plus grimpante." },
  ],
  epiphyllum: [
    { title: "Un cactus de forêt au port graphique", text: "Le cactus zigzag pousse naturellement comme une plante épiphyte dans les forêts mexicaines. Ses tiges aplaties et profondément découpées lui donnent cette silhouette caractéristique, très différente des cactus de désert. Son nom botanique accepté est Disocactus anguliger, tandis que le nom Epiphyllum anguliger reste très répandu dans le commerce horticole." },
    { title: "Une lumière vive sans soleil brûlant", text: "À Lille, installez-le près d’une fenêtre lumineuse en évitant le soleil direct des heures les plus chaudes. Son substrat doit être aéré et sécher partiellement entre deux arrosages, sans subir la sécheresse prolongée réservée aux cactus désertiques. Une atmosphère stable et une bonne lumière favorisent des tiges fermes et une croissance régulière." },
    { title: "Floraison, suspension et rempotage", text: "Son port retombant convient particulièrement aux suspensions et aux pots placés en hauteur. Une période plus fraîche et légèrement plus sèche en hiver peut encourager la floraison sur un sujet mature. Le Studio adapte son rempotage à ses racines épiphytes avec un mélange organique, drainant et un pot obligatoirement percé." },
  ],
  colocasia: [
    { title: "L’oreille d’éléphant qui aime l’eau", text: "Les Colocasia se distinguent par leur vigueur et leurs grandes feuilles souvent orientées vers l’extérieur ou vers le bas. Ils développent leur plein potentiel pendant les périodes chaudes, avec beaucoup d’eau et de nutriments. Leur culture diffère donc de celle de nombreuses plantes d’intérieur classiques et de certains Alocasia, malgré une ressemblance évidente pour un œil non averti." },
    { title: "Une culture saisonnière à Lille", text: "À Lille, le Colocasia peut profiter d’un extérieur lumineux pendant l’été, à condition d’être acclimaté progressivement et protégé du vent. Il doit rentrer avant les températures froides. La diminution de lumière peut provoquer un fort ralentissement ou une dormance. Il faut alors réduire les apports d’eau et surveiller le rhizome plutôt que chercher à maintenir artificiellement une croissance estivale." },
    { title: "Volume, nourriture et humidité", text: "En pleine croissance, un Colocasia consomme davantage d’eau et de nutriments que beaucoup d’autres genres tropicaux. Un substrat riche, un contenant stable et une fertilisation suivie permettent d’accompagner son feuillage. Les grands sujets doivent être contrôlés régulièrement : parasites sous les feuilles, racines serrées et dessèchement rapide du pot sont les principaux signaux à observer." },
  ],
  pilea: [
    { title: "Un genre riche au-delà de la plante à monnaie", text: "Pilea peperomioides est l’espèce la plus célèbre, mais le genre Pilea rassemble aussi des plantes rampantes, gaufrées, argentées ou minuscules. Elles appartiennent aux Urticaceae et non au genre Peperomia. Leur format souvent compact convient aux petits espaces, aux étagères lumineuses et, pour certaines espèces, aux compositions humides ou aux terrariums bien ventilés." },
    { title: "Cultiver le Pilea peperomioides à Lille", text: "La plante à monnaie chinoise apprécie une lumière vive indirecte et se tourne naturellement vers la fenêtre. Une rotation régulière du pot aide à conserver une silhouette harmonieuse. Dans les intérieurs lillois moins lumineux en hiver, la croissance ralentit et les arrosages doivent s’espacer. Un pot percé et ajusté à la motte réduit fortement le risque de racines asphyxiées." },
    { title: "Une plante faite pour être partagée", text: "Le Pilea peperomioides produit volontiers des rejets autour de sa base. Ils peuvent être conservés pour densifier le pot ou séparés lorsqu’ils possèdent assez de racines. Cette multiplication facile explique son surnom de plante de l’amitié. Tibaldo Jungle accompagne le choix du substrat, la séparation des jeunes plants et le rempotage gratuit des Pilea apportés au Studio." },
  ],
  peperomia: [
    { title: "Petites plantes, immense diversité", text: "Les Peperomia appartiennent aux Piperaceae, la famille botanique du poivre. Le genre réunit des formes dressées, rampantes ou en rosette, avec des feuilles charnues, nervurées, gaufrées ou panachées. Leur taille contenue convient particulièrement aux petits appartements, aux bureaux et aux compositions végétales où une grande plante tropicale manquerait d’espace." },
    { title: "La lumière sans l’excès d’eau", text: "Le principal risque vient souvent d’un arrosage trop fréquent dans un mélange qui sèche lentement. Les feuilles épaisses de nombreuses espèces stockent déjà une partie de l’eau. Une lumière vive indirecte maintient des tiges compactes et des couleurs nettes. Pendant l’hiver lillois, il est préférable de rapprocher la plante de la lumière et de réduire l’arrosage plutôt que d’ajouter de l’eau par habitude." },
    { title: "Un petit système racinaire à respecter", text: "Les Peperomia possèdent souvent des racines fines et apprécient un pot relativement ajusté. Un terreau léger enrichi d’éléments minéraux sèche plus régulièrement qu’un grand volume compact. L’engrais est distribué à faible dose pendant la croissance. Les boutures de tige ou de feuille permettent de renouveler facilement certaines espèces et de conserver une plante devenue moins dense." },
  ],
  maranta: [
    { title: "Des feuilles qui vivent au rythme du jour", text: "La Maranta est l’une des plantes dites priantes : son feuillage change naturellement d’angle entre la journée et la nuit. Ses nervures rouges, ses taches sombres ou ses bandes claires composent un décor vivant qui varie selon les espèces et cultivars. Ce mouvement ne doit pas être confondu avec un flétrissement systématique." },
    { title: "Réussir une Maranta dans un intérieur lillois", text: "Près d’une fenêtre à lumière filtrée, loin d’une vitre froide et du chauffage, la Maranta conserve un port dense. En hiver à Lille, la baisse de lumière ralentit sa consommation d’eau. Une humidité stable et une eau peu minéralisée limitent les bords secs mieux que des vaporisations occasionnelles." },
    { title: "Une touffe à entretenir et à partager", text: "Son port bas permet de la cultiver sur un meuble ou en suspension. Les tiges longues se bouturent facilement lorsqu’elles comportent un nœud. Un substrat fin, organique et aéré soutient ses racines sans les asphyxier. Le Studio accompagne aussi la taille et le rempotage gratuit des Maranta à Lille." },
  ],
  calathea: [
    { title: "Un nom familier, une botanique qui évolue", text: "Le mot Calathea reste ancré dans le langage des amateurs de plantes, alors que de nombreuses espèces sont aujourd’hui classées parmi les Goeppertia. Cette précision permet de mieux comprendre leur parenté sans rendre le choix plus compliqué : l’important reste d’identifier chaque espèce et son comportement réel." },
    { title: "Des feuillages spectaculaires mais sensibles", text: "Orbifolia, makoyana, roseopicta ou lancifolia révèlent des formes et des dessins très différents. Toutes apprécient généralement une lumière filtrée, une température stable et une humidité régulière. Les feuilles larges réagissent vite au soleil direct, au chauffage et aux variations brutales d’arrosage." },
    { title: "Calathea et Goeppertia à Lille", text: "Dans un appartement lillois, la priorité consiste à éviter les extrêmes : coin sombre, vitre froide, radiateur ou cache-pot plein d’eau. Un mélange humifère mais respirant, une eau adaptée et un pot proportionné forment une base solide. Tibaldo Jungle aide à choisir une variété cohérente avec votre lumière et propose son rempotage gratuit au Studio." },
  ],
  syngonium: [
    { title: "Une feuille qui évolue en grimpant", text: "Le Syngonium est souvent reconnu à sa jeune feuille en pointe de flèche. Avec la maturité et un support vertical, plusieurs espèces développent pourtant des feuilles divisées en lobes distincts. Cette transformation explique pourquoi un jeune plant et un sujet adulte peuvent sembler appartenir à deux plantes différentes." },
    { title: "Couleurs, panachures et lumière", text: "Vert, crème, rose, argent ou presque blanc : les cultivars de Syngonium n’expriment pas tous leurs couleurs avec la même intensité. Une lumière vive filtrée maintient une croissance compacte et soutient les panachures. Les parties très claires restent plus sensibles au soleil direct et poussent souvent plus lentement." },
    { title: "Choisir entre port compact et liane", text: "Tailler régulièrement favorise un pot dense, tandis qu’un tuteur permet au Syngonium de grimper et de mûrir. Son mélange doit rester organique mais respirant, avec un pot percé. Les boutures comportant un nœud s’enracinent facilement et permettent de rajeunir une tige devenue trop longue." },
  ],
  hoya: [
    { title: "Une liane épiphyte, pas une succulente classique", text: "De nombreux Hoya portent des feuilles charnues capables de résister à un léger séchage, mais leurs racines épiphytes ne tolèrent ni un terreau compact ni une sécheresse interminable. Les espèces diffèrent beaucoup : feuilles fines ou épaisses, rondes ou rubanées, vertes, argentées ou fortement nervurées." },
    { title: "La lumière prépare la floraison", text: "Un emplacement lumineux favorise des tiges solides et la formation des ombelles. Le soleil doux peut convenir après acclimatation, tandis qu’un manque de lumière réduit la floraison. Une fois les pédoncules apparus, mieux vaut les conserver : plusieurs Hoya refleurissent au même endroit." },
    { title: "Racines aérées et arrosage mesuré", text: "Un petit pot percé et un mélange très aéré limitent l’eau stagnante autour des racines. L’arrosage intervient lorsque le mélange a suffisamment séché pour l’espèce concernée, puis l’excédent est évacué. Le support peut prendre la forme d’un arceau, d’un treillage ou d’une suspension." },
  ],
  ficus: [
    { title: "Un genre bien plus vaste que le caoutchouc", text: "Le genre Ficus rassemble des arbres, arbustes et plantes grimpantes aux silhouettes très différentes. Ficus elastica, lyrata, benjamina, binnendijkii ou pumila ne demandent ni le même espace ni exactement le même rythme d’entretien. Chaque fiche devra donc partir de l’espèce réellement identifiée." },
    { title: "Stabilité et lumière dans un intérieur lillois", text: "Les Ficus réagissent aux déplacements brutaux, aux courants d’air et à la baisse de lumière. Une place lumineuse et stable limite la chute des feuilles. En hiver à Lille, rapprocher progressivement la plante d’une fenêtre est souvent plus utile que d’augmenter les arrosages ou l’engrais." },
    { title: "Anticiper la taille et les racines", text: "Certaines espèces deviennent de véritables arbres d’intérieur. Un pot stable, un drainage franc et une taille réfléchie permettent de conserver une silhouette cohérente. Le latex blanc libéré lors d’une coupe peut être irritant : la taille se réalise avec précaution et des outils propres." },
  ],
  sansevieria: [
    { title: "Sansevieria dans le commerce, Dracaena en botanique", text: "Le nom Sansevieria reste très utilisé en horticulture, mais les espèces ont été intégrées au genre Dracaena. Conserver les deux noms sur la page facilite la recherche tout en présentant la nomenclature actuelle. Les formes comprennent des feuilles plates, cylindriques, courtes, géantes ou panachées." },
    { title: "La lumière avant la résistance", text: "Ces plantes survivent dans une lumière moyenne, mais développent une croissance plus robuste et des dessins plus nets près d’une fenêtre lumineuse. Le soleil direct demande une acclimatation. Une zone sombre augmente surtout le temps nécessaire au séchage du pot et donc le risque d’excès d’eau." },
    { title: "Peu d’eau, mais un vrai arrosage", text: "Lorsque le mélange est sec, arrosez complètement puis laissez l’excédent s’évacuer. Un petit apport répété maintient inutilement la base humide. Les rhizomes et feuilles charnues réclament un substrat très drainant, un pot percé et une réduction marquée de l’eau pendant l’hiver." },
  ],
  fougeres: [
    { title: "Un univers, plusieurs lignées botaniques", text: "Le mot fougère ne désigne pas un genre unique. Nephrolepis, Asplenium, Phlebodium, Adiantum ou Microsorum possèdent des frondes et des besoins différents. La page d’univers sert donc de porte d’entrée, tandis que chaque fiche d’espèce précise son habitat, son port et sa tolérance au séchage." },
    { title: "L’humidité ne remplace pas l’observation", text: "Beaucoup de fougères apprécient un mélange régulièrement frais et une atmosphère non desséchante, mais l’eau stagnante reste dangereuse. Les frondes fines réagissent vite au chauffage, aux oublis et aux sels présents dans l’eau. Une salle de bain ne convient que si elle reçoit aussi suffisamment de lumière." },
    { title: "Des frondes à laisser se renouveler", text: "Une fronde ancienne ou abîmée peut être retirée proprement à sa base sans couper le cœur en croissance. Le rempotage respecte les rhizomes et le type de racines de l’espèce. Les mélanges fins, humifères et aérés sont souvent préférables aux substrats grossiers conçus pour les aroïdes." },
  ],
  yucca: [
    { title: "Du Yucca d’intérieur au sujet sculptural extérieur", text: "Le genre Yucca réunit des espèces très différentes. Les cannes vendues pour l’intérieur ne se cultivent pas comme Yucca rostrata, espèce extérieure au tronc fibreux et au feuillage bleu. L’identification de l’espèce détermine la rusticité, la taille adulte et la gestion de l’hiver." },
    { title: "Le soleil construit la silhouette", text: "Les Yucca demandent une lumière généreuse. Un manque de soleil assouplit les nouvelles feuilles et fragilise le port. Les sujets extérieurs sont acclimatés progressivement, tandis qu’un Yucca d’intérieur doit rester près d’une fenêtre et loin d’un angle sombre." },
    { title: "Le drainage comme priorité", text: "Un Yucca tolère mieux un léger manque d’eau qu’un mélange saturé. Le pot doit être percé et le substrat fortement drainant. Pour Yucca rostrata à Lille, l’humidité hivernale autour du cœur et des racines constitue un risque majeur malgré une bonne tolérance au froid sec." },
  ],
  cycas: [
    { title: "Ni palmier, ni fougère", text: "Le Cycas appartient à une ancienne lignée de gymnospermes. Sa couronne de frondes rigides évoque un palmier, mais sa botanique et son rythme de croissance sont très différents. Cycas revoluta, originaire du sud-est de la Chine, du sud du Japon et de Taïwan, est l’espèce la plus couramment cultivée." },
    { title: "Soleil, lenteur et drainage", text: "Une lumière généreuse produit une couronne plus compacte. En pot, le mélange doit être très drainant et sécher partiellement entre les arrosages. À Lille, un sujet extérieur doit être acclimaté et protégé des longues périodes de froid humide, particulièrement autour du cœur et des racines." },
    { title: "Une plante toxique à manipuler avec prudence", text: "Toutes les parties du Cycas sont toxiques par ingestion, particulièrement les graines. La plante doit rester hors de portée des enfants et des animaux. Sa croissance lente impose aussi d’éviter les tailles inutiles : seules les frondes entièrement sèches sont retirées proprement." },
  ],
  cactus: [
    { title: "Une architecture façonnée par la sécheresse", text: "Les cactus appartiennent à la famille des Cactaceae et ont développé des formes remarquables pour stocker l’eau et limiter les pertes : tiges côtelées, tissus charnus, aréoles, épines et parfois un duvet protecteur. Derrière le mot cactus se cachent pourtant des centaines de silhouettes, des petits Mammillaria globulaires aux grands Cereus colonnaires, en passant par les Opuntia en raquettes et les cactus épiphytes qui vivent dans les forêts tropicales." },
    { title: "Cultiver un cactus dans un intérieur à Lille", text: "À Lille, la réussite repose d’abord sur la lumière. Une fenêtre plein sud ou sud-ouest, une véranda lumineuse ou un emplacement extérieur progressivement acclimaté pendant la belle saison permettent une croissance compacte. Le manque de soleil déforme les nouvelles pousses et ne se corrige pas avec davantage d’engrais. En hiver, une pièce fraîche, sèche et très lumineuse aide de nombreuses espèces à respecter leur repos et prépare leur future floraison." },
    { title: "L’eau, le pot et le rythme des saisons", text: "Un cactus n’est pas une plante que l’on arrose un peu chaque semaine. Pendant la croissance, le mélange est humidifié complètement puis laissé sécher jusqu’au cœur avant un nouvel apport. En période froide et peu lumineuse, l’arrosage devient très rare, voire suspendu pour certaines espèces. Tibaldo Jungle privilégie les pots percés, les volumes ajustés et un substrat fortement minéral afin que l’eau traverse rapidement la motte sans rester prisonnière autour des racines." },
  ],
} as const;
