export const familyEditorials = {
  alocasia: [
    { title: "Une présence tropicale spectaculaire", text: "Les Alocasia sont recherchés pour leur silhouette architecturale, leurs pétioles graphiques et leurs feuilles parfois immenses. Certaines espèces restent compactes tandis que d’autres deviennent de véritables plantes XXL. Leur aspect varie beaucoup selon la variété : limbes veloutés, nervures contrastées, reflets métalliques ou tiges colorées. Cette diversité permet de choisir un Alocasia adapté à une étagère lumineuse comme à un grand séjour." },
    { title: "Réussir un Alocasia à Lille", text: "Dans un intérieur lillois, la lumière constitue le premier facteur de réussite. Une place proche d’une fenêtre lumineuse, protégée du soleil brûlant, favorise des feuilles plus solides et une croissance régulière. En hiver, la baisse de luminosité ralentit naturellement la plante : les arrosages doivent alors diminuer. Le froid contre une vitre, les courants d’air et un substrat constamment détrempé sont plus dangereux qu’une humidité ambiante imparfaite." },
    { title: "Racines, substrat et nutrition", text: "Un mélange aéré associant terreau structuré, écorce, coco et fraction minérale laisse circuler l’oxygène autour des racines. Le pot doit être percé et proportionné à la motte. Pendant la croissance, une fertilisation douce mais régulière accompagne la production de grandes feuilles. Tibaldo Jungle adapte le rempotage à l’état réel des racines plutôt qu’à un calendrier automatique, afin d’éviter les pots trop volumineux et les excès d’eau." },
  ],
  anthurium: [
    { title: "Bien plus que l’Anthurium fleuri", text: "Le genre Anthurium réunit des plantes très différentes. Aux formes florifères bien connues s’ajoutent des espèces de collection cultivées pour leurs feuilles veloutées, cordiformes, allongées ou fortement nervurées. Certaines poussent en rosette, d’autres développent une tige grimpante. Cette richesse botanique explique pourquoi deux Anthurium peuvent avoir une apparence et un rythme de culture très éloignés." },
    { title: "Lumière douce et humidité stable", text: "Les Anthurium apprécient généralement une lumière vive sans soleil agressif. À Lille, une fenêtre bien exposée devient précieuse en automne et en hiver, tandis qu’un léger recul peut être nécessaire l’été. L’objectif n’est pas de maintenir un substrat mouillé, mais d’éviter les alternances brutales entre sécheresse prolongée et saturation. Une humidité régulière, accompagnée d’une bonne circulation d’air, aide les nouvelles feuilles à se déployer proprement." },
    { title: "Cultiver les racines autant que les feuilles", text: "Les racines d’Anthurium ont besoin d’un mélange respirant. Écorce fine, sphaigne utilisée avec mesure, chips de coco et éléments minéraux peuvent compléter un terreau de qualité. Les espèces épiphytes tolèrent mal les mélanges lourds. Une nutrition diluée pendant la période lumineuse soutient la croissance sans charger le substrat en sels. Au Studio, chaque rempotage est ajusté au type de racines et au comportement de la plante." },
  ],
  monstera: [
    { title: "Une liane qui change avec l’âge", text: "Le Monstera n’est pas une plante figée : son feuillage évolue lorsqu’il gagne en maturité, en lumière et en qualité de support. Une jeune feuille peut être entière, puis devenir progressivement plus grande, découpée ou fenestrée. Les racines aériennes participent à son ancrage. Comprendre ce comportement grimpant permet d’obtenir une plante plus équilibrée et plus spectaculaire qu’en la laissant simplement retomber." },
    { title: "Des Monstera adaptés aux intérieurs lillois", text: "Une lumière vive indirecte reste essentielle pour conserver des entre-nœuds courts et favoriser la maturation des feuilles. Dans les logements de Lille, il faut tenir compte des saisons : rapprocher progressivement la plante d’une fenêtre en hiver, puis surveiller le soleil direct au retour des beaux jours. Un grand Monstera demande aussi de l’espace, un support stable et un pot suffisamment lourd pour éviter le basculement." },
    { title: "Arrosage, tuteur et rempotage", text: "Le substrat doit retenir assez d’humidité tout en évacuant rapidement l’excédent. Un tuteur en fibre, en liège ou un support rigide guide la face arrière de la tige et permet aux racines aériennes de s’ancrer. Le rempotage n’est utile que lorsque la motte est réellement occupée. Tibaldo Jungle conseille aussi la taille, le bouturage et la reprise sur support pour rajeunir les sujets devenus trop longs." },
  ],
  philodendron: [
    { title: "Un genre aux formes presque infinies", text: "Les Philodendron peuvent être grimpants, rampants ou autoportants. Certains portent des feuilles en cœur très accessibles, d’autres développent un feuillage velouté, découpé, coloré ou fortement nervuré. Avant de choisir une variété, il faut comprendre son port : un grimpant demande un support vertical, un rampant réclame un contenant plus large et un hybride autoportant construit seul sa silhouette." },
    { title: "Trouver la bonne place à Lille", text: "La majorité des Philodendron préfère une lumière vive filtrée, une température stable et une croissance sans courant d’air froid. Une variété verte tolère souvent mieux une lumière moyenne qu’une forme panachée. Dans un intérieur lillois, l’observation de la distance entre les nouvelles feuilles renseigne rapidement : une tige qui s’allonge excessivement cherche généralement davantage de lumière." },
    { title: "Accompagner une croissance durable", text: "Un mélange organique et minéral, suffisamment aéré, protège les racines des excès d’eau. Les arrosages suivent le séchage réel du pot et non un jour fixe de la semaine. La fertilisation reste progressive pendant les mois lumineux. Au Studio Végétal, nous aidons à choisir le bon support, à réorienter une plante et à rempoter les grands Philodendron sans déstabiliser leur système racinaire." },
  ],
  epipremnum: [
    { title: "Le pothos peut devenir gigantesque", text: "Souvent vendu comme petite plante retombante, l’Epipremnum est en réalité une liane capable de produire des feuilles beaucoup plus grandes lorsqu’elle grimpe. Ses nœuds émettent facilement des racines aériennes et rendent le bouturage accessible. Les variétés vertes, dorées, blanches ou argentées n’ont toutefois pas exactement la même vigueur ni les mêmes besoins en lumière." },
    { title: "Une plante facile, mais pas indifférente", text: "L’Epipremnum tolère plusieurs situations, ce qui ne signifie pas qu’il prospère partout. Une lumière insuffisante ralentit la croissance, allonge les tiges et réduit les panachures. À Lille, placez-le près d’une source lumineuse en hiver et protégez les feuilles claires d’un soleil estival brutal. Laissez le mélange sécher partiellement entre deux arrosages afin de préserver les racines." },
    { title: "Créer une plante dense ou mature", text: "Pour un pot fourni, plusieurs boutures peuvent être regroupées et taillées régulièrement. Pour obtenir de grandes feuilles, mieux vaut conduire une tige sur un support vertical et lui offrir chaleur, lumière et nutrition. Tibaldo Jungle peut préparer un mélange drainant, installer un tuteur adapté et expliquer comment bouturer les sections devenues trop longues sans perdre la plante mère." },
  ],
  colocasia: [
    { title: "L’oreille d’éléphant qui aime l’eau", text: "Les Colocasia se distinguent par leur vigueur et leurs grandes feuilles souvent orientées vers l’extérieur ou vers le bas. Ils développent leur plein potentiel pendant les périodes chaudes, avec beaucoup d’eau et de nutriments. Leur culture diffère donc de celle de nombreuses plantes d’intérieur classiques et de certains Alocasia, malgré une ressemblance évidente pour un œil non averti." },
    { title: "Une culture saisonnière à Lille", text: "À Lille, le Colocasia peut profiter d’un extérieur lumineux pendant l’été, à condition d’être acclimaté progressivement et protégé du vent. Il doit rentrer avant les températures froides. La diminution de lumière peut provoquer un fort ralentissement ou une dormance. Il faut alors réduire les apports d’eau et surveiller le rhizome plutôt que chercher à maintenir artificiellement une croissance estivale." },
    { title: "Volume, nourriture et humidité", text: "En pleine croissance, un Colocasia consomme davantage d’eau et de nutriments que beaucoup d’autres genres tropicaux. Un substrat riche, un contenant stable et une fertilisation suivie permettent d’accompagner son feuillage. Les grands sujets doivent être contrôlés régulièrement : parasites sous les feuilles, racines serrées et dessèchement rapide du pot sont les principaux signaux à observer." },
  ],
  pilea: [
    { title: "Un genre riche au-delà de la plante à monnaie", text: "Pilea peperomioides est l’espèce la plus célèbre, mais le genre Pilea rassemble aussi des plantes rampantes, gaufrées, argentées ou minuscules. Elles appartiennent aux Urticaceae et non au genre Peperomia. Leur format souvent compact convient aux petits espaces, aux étagères lumineuses et, pour certaines espèces, aux compositions humides ou aux terrariums bien ventilés." },
    { title: "Cultiver le Pilea peperomioides à Lille", text: "La plante à monnaie chinoise apprécie une lumière vive indirecte et se tourne naturellement vers la fenêtre. Une rotation régulière du pot aide à conserver une silhouette harmonieuse. Dans les intérieurs lillois moins lumineux en hiver, la croissance ralentit et les arrosages doivent s’espacer. Un pot percé et ajusté à la motte réduit fortement le risque de racines asphyxiées." },
    { title: "Une plante faite pour être partagée", text: "Le Pilea peperomioides produit volontiers des rejets autour de sa base. Ils peuvent être conservés pour densifier le pot ou séparés lorsqu’ils possèdent assez de racines. Cette multiplication facile explique son surnom de plante de l’amitié. Tibaldo Jungle accompagne le choix du substrat, la séparation des jeunes plants et le rempotage gratuit des Pilea apportés au Studio." },
  ],
  peperomia: [
    { title: "Petites plantes, immense diversité", text: "Les Peperomia appartiennent aux Piperaceae, la famille botanique du poivre. Le genre réunit des formes dressées, rampantes ou en rosette, avec des feuilles charnues, nervurées, gaufrées ou panachées. Leur taille contenue convient particulièrement aux petits appartements, aux bureaux et aux compositions végétales où une grande plante tropicale manquerait d’espace." },
    { title: "La lumière sans l’excès d’eau", text: "Le principal risque vient souvent d’un arrosage trop fréquent dans un mélange qui sèche lentement. Les feuilles épaisses de nombreuses espèces stockent déjà une partie de l’eau. Une lumière vive indirecte maintient des tiges compactes et des couleurs nettes. Pendant l’hiver lillois, il est préférable de rapprocher la plante de la lumière et de réduire l’arrosage plutôt que d’ajouter de l’eau par habitude." },
    { title: "Un petit système racinaire à respecter", text: "Les Peperomia possèdent souvent des racines fines et apprécient un pot relativement ajusté. Un terreau léger enrichi d’éléments minéraux sèche plus régulièrement qu’un grand volume compact. L’engrais est distribué à faible dose pendant la croissance. Les boutures de tige ou de feuille permettent de renouveler facilement certaines espèces et de conserver une plante devenue moins dense." },
  ],
} as const;
