import type { PlantEntry } from "./types";

type PlantImage = PlantEntry["gallery"][number];

type LicensedImage = Omit<PlantImage, "license"> & {
  creator: string;
  licenseName: string;
  licenseUrl: string;
  sourceUrl: string;
  botanicalIdentityEvidence: string;
};

const licensedImage = ({
  creator,
  licenseName,
  licenseUrl,
  sourceUrl,
  botanicalIdentityEvidence,
  ...image
}: LicensedImage): PlantImage => ({
  ...image,
  license: {
    status: "verified",
    creator,
    license: licenseName,
    licenseUrl,
    sourceUrl,
    registryPath: "/credits-images",
    note: `Téléchargé le 30 août 2026. Conversion WebP responsive sans recadrage ni transformation morphologique. Attribution requise sauf mention contraire. Identité botanique : ${botanicalIdentityEvidence}`,
  },
});

const ccBySa4 = "https://creativecommons.org/licenses/by-sa/4.0/";
const ccBySa3 = "https://creativecommons.org/licenses/by-sa/3.0/";

export const p1VerifiedMediaByRoute: Readonly<Record<string, PlantImage[]>> = {
  "alocasia/tandurusa": [
    licensedImage({
      src: "/media/final-media-v35/alocasia-tandurusa-port.webp",
      alt: "Alocasia tandurusa Jacklyn adulte aux feuilles profondément lobées",
      caption: "Port adulte et découpe foliaire d’Alocasia tandurusa ‘Jacklyn’ au jardin botanique Roger-Van den Hende · Cephas · CC BY-SA 4.0.",
      width: 1600,
      height: 2400,
      creator: "Cephas",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Alocasia_Tandurusa_%27Jacklyn%27_JRVdH_02.jpg",
      botanicalIdentityEvidence: "le fichier et sa description nomment Alocasia tandurusa ‘Jacklyn’ dans une collection botanique documentée",
    }),
    licensedImage({
      src: "/media/final-media-v35/alocasia-tandurusa-feuillage.webp",
      alt: "Feuillage profondément découpé d’Alocasia tandurusa Jacklyn",
      caption: "Vue complémentaire des lobes et de la texture d’Alocasia tandurusa ‘Jacklyn’ · Cephas · CC BY-SA 4.0.",
      width: 1600,
      height: 1200,
      creator: "Cephas",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Alocasia_Tandurusa_%27Jacklyn%27_JRVdH_01.jpg",
      botanicalIdentityEvidence: "le fichier et sa description nomment Alocasia tandurusa ‘Jacklyn’ dans une collection botanique documentée",
    }),
  ],
  "alocasia/mortfontanensis-polly": [
    licensedImage({
      src: "/media/final-media-v35/alocasia-polly.webp",
      alt: "Alocasia × mortfontanensis Polly cultivée en hydroculture",
      caption: "Deux sujets du cultivar ‘Polly’, historiquement diffusé sous le nom Alocasia × amazonica · Tim Kortekamp · CC BY-SA 4.0.",
      width: 1600,
      height: 2400,
      creator: "Tim Kortekamp",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Alocasia_x_amazonica_%27Polly%27.jpg",
      botanicalIdentityEvidence: "le fichier nomme explicitement le cultivar ‘Polly’ et Commons le classe sous Alocasia × mortfontanensis",
    }),
  ],
  "anthurium/wendlingeri": [
    licensedImage({
      src: "/media/final-media-v35/anthurium-wendlingeri-port.webp",
      alt: "Anthurium wendlingeri mature aux longues feuilles rubanées retombantes",
      caption: "Port mature d’Anthurium wendlingeri au Cairns Botanic Gardens · Steve Fitzgerald · CC BY-SA 4.0.",
      width: 1600,
      height: 2133,
      creator: "Steve Fitzgerald",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Anthurium-wendlingeri-SF24277-01.jpg",
      botanicalIdentityEvidence: "spécimen nommé Anthurium wendlingeri dans la collection du Cairns Botanic Gardens",
    }),
    licensedImage({
      src: "/media/final-media-v35/anthurium-wendlingeri-inflorescence.webp",
      alt: "Anthurium wendlingeri avec son inflorescence spiralée",
      caption: "Feuillage rubané et inflorescence spiralée d’Anthurium wendlingeri au jardin botanique de Berlin-Dahlem · Krzysztof Ziarnek · CC BY-SA 4.0.",
      width: 1600,
      height: 2400,
      creator: "Krzysztof Ziarnek, Kenraiz",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Anthurium_wendlingeri_kz01.jpg",
      botanicalIdentityEvidence: "spécimen nommé Anthurium wendlingeri dans la collection du Botanischer Garten Berlin-Dahlem",
    }),
  ],
  "philodendron/hederaceum": [
    licensedImage({
      src: "/media/final-media-v35/philodendron-hederaceum-port.webp",
      alt: "Philodendron hederaceum grimpant au feuillage en cœur",
      caption: "Port grimpant de Philodendron hederaceum au Singapore Botanic Gardens · Moheen Reeyad · CC BY-SA 4.0.",
      width: 1600,
      height: 2400,
      creator: "Moheen Reeyad",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Philodendron_hederaceum,_Singapore_Botanic_Gardens_(141542).jpg",
      botanicalIdentityEvidence: "spécimen nommé Philodendron hederaceum au Singapore Botanic Gardens",
    }),
    licensedImage({
      src: "/media/final-media-v35/philodendron-hederaceum-feuillage.webp",
      alt: "Feuillage en cœur de Philodendron hederaceum sur un support végétal",
      caption: "Feuillage et habitus de Philodendron hederaceum à l’Estufa Fria de Lisbonne · Krzysztof Ziarnek · CC BY-SA 4.0.",
      width: 1600,
      height: 2133,
      creator: "Krzysztof Ziarnek, Kenraiz",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Philodendron_hederaceum_kz01.jpg",
      botanicalIdentityEvidence: "spécimen nommé Philodendron hederaceum à l’Estufa Fria de Lisbonne",
    }),
  ],
  "philodendron/pink-princess": [
    licensedImage({
      src: "/media/final-media-v35/philodendron-pink-princess.webp",
      alt: "Philodendron Pink Princess aux feuilles sombres panachées de rose",
      caption: "Panachure rose et feuillage sombre du Philodendron ‘Pink Princess’ · Srikandi73 · CC BY-SA 4.0.",
      width: 1600,
      height: 2133,
      creator: "Srikandi73",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Philodendron_Pink_Princess.jpg",
      botanicalIdentityEvidence: "le fichier est classé par Commons comme Philodendron erubescens ‘Pink Princess’ et montre sa panachure caractéristique",
    }),
  ],
  "monstera/albo-variegata": [
    licensedImage({
      src: "/media/final-media-v35/monstera-albo-variegata.webp",
      alt: "Feuille adulte de Monstera deliciosa Albo Variegata panachée de blanc",
      caption: "Feuille adulte de Monstera deliciosa ‘Albo-Variegata’ · Mokkie · CC BY-SA 3.0.",
      width: 1349,
      height: 2400,
      creator: "Mokkie",
      licenseName: "CC BY-SA 3.0",
      licenseUrl: ccBySa3,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Fruit_Salad_Plant_(Monstera_deliciosa_%27Albo-Variegata%27)_1.jpg",
      botanicalIdentityEvidence: "le fichier nomme explicitement Monstera deliciosa ‘Albo-Variegata’ et Commons le classe parmi les cultivars panachés",
    }),
  ],
  "ficus/elastica": [
    licensedImage({
      src: "/media/final-media-v35/ficus-elastica-port.webp",
      alt: "Jeune Ficus elastica avec nouvelle feuille rouge et feuillage sombre",
      caption: "Jeune pousse et feuillage coriace de Ficus elastica · Karlfonza · CC BY-SA 4.0.",
      width: 1600,
      height: 2398,
      creator: "Karlfonza",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ficus_elastica_(rubber_plant).jpg",
      botanicalIdentityEvidence: "le fichier et sa catégorie Commons identifient Ficus elastica",
    }),
    licensedImage({
      src: "/media/final-media-v35/ficus-elastica-feuille.webp",
      alt: "Feuille rétroéclairée de Ficus elastica montrant sa nervation",
      caption: "Texture et nervation d’une jeune feuille de Ficus elastica · Julian Herzog · CC BY 4.0.",
      width: 1600,
      height: 2300,
      creator: "Julian Herzog",
      licenseName: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Backlit_ficus_elastica_leaf_texture_2014_02.jpg",
      botanicalIdentityEvidence: "la description et la catégorie Commons identifient une jeune feuille de Ficus elastica",
    }),
  ],
  "hoya/carnosa": [
    licensedImage({
      src: "/media/final-media-v35/hoya-carnosa-port.webp",
      alt: "Hoya carnosa mature grimpant sur un support",
      caption: "Port lianescent d’un Hoya carnosa mature au Wellington Botanic Garden · Daderot · CC0.",
      width: 1600,
      height: 2400,
      creator: "Daderot",
      licenseName: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoya_carnosa_-_Begonia_House_-_Wellington_Botanic_Garden_-_Wellington,_NZ_-_DSC09338.jpg",
      botanicalIdentityEvidence: "spécimen nommé Hoya carnosa au Wellington Botanic Garden",
    }),
    licensedImage({
      src: "/media/final-media-v35/hoya-carnosa-fleurs.webp",
      alt: "Ombelle rose de Hoya carnosa portant des gouttes de nectar",
      caption: "Ombelle de Hoya carnosa et gouttes de nectar · Franz van Duns · CC BY-SA 4.0.",
      width: 1600,
      height: 1067,
      creator: "Franz van Duns",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoya_carnosa_-_umbel_with_nectar_droplets.jpg",
      botanicalIdentityEvidence: "la description, la catégorie et les caractères floraux documentent Hoya carnosa",
    }),
  ],
  "syngonium/podophyllum": [
    licensedImage({
      src: "/media/final-media-v35/syngonium-podophyllum-feuillage.webp",
      alt: "Feuillage sagitté de Syngonium podophyllum",
      caption: "Feuilles en pointe de flèche de Syngonium podophyllum · David J. Stang · CC BY-SA 4.0.",
      width: 1600,
      height: 2400,
      creator: "David J. Stang",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Syngonium_podophyllum_10zz.jpg",
      botanicalIdentityEvidence: "le fichier, sa description et sa catégorie Commons identifient Syngonium podophyllum",
    }),
    licensedImage({
      src: "/media/final-media-v35/syngonium-podophyllum-port.webp",
      alt: "Syngonium podophyllum grimpant dans son milieu tropical",
      caption: "Port grimpant de Syngonium podophyllum en Guadeloupe · Krzysztof Ziarnek · CC BY-SA 4.0.",
      width: 1600,
      height: 2313,
      creator: "Krzysztof Ziarnek, Kenraiz",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Syngonium_podophyllum_kz02.jpg",
      botanicalIdentityEvidence: "observation nommée Syngonium podophyllum dans son milieu en Guadeloupe",
    }),
  ],
  "sansevieria/trifasciata": [
    licensedImage({
      src: "/media/final-media-v35/dracaena-trifasciata-port.webp",
      alt: "Dracaena trifasciata aux longues feuilles verticales rubanées",
      caption: "Port vertical de Dracaena trifasciata, encore couramment appelée Sansevieria · Fanti Salms · CC BY-SA 4.0.",
      width: 1349,
      height: 2400,
      creator: "Fanti Salms",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Dracaena_Trifasciata_Plant.jpg",
      botanicalIdentityEvidence: "le fichier et sa catégorie Commons identifient Dracaena trifasciata",
    }),
    licensedImage({
      src: "/media/final-media-v35/dracaena-trifasciata-jardin-botanique.webp",
      alt: "Dracaena trifasciata cultivée au jardin botanique de Leyde",
      caption: "Dracaena trifasciata au Hortus botanicus Leiden, sous son ancien nom Sansevieria trifasciata · Rudolphous · CC BY-SA 4.0.",
      width: 1568,
      height: 2400,
      creator: "Rudolphous",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: ccBySa4,
      sourceUrl: "https://commons.wikimedia.org/wiki/File:20210623_Hortus_botanicus_Leiden_-_Sansevieria_trifasciata_v2.jpg",
      botanicalIdentityEvidence: "spécimen nommé Sansevieria trifasciata, synonyme horticole de Dracaena trifasciata, au Hortus botanicus Leiden",
    }),
  ],
};

export const monsteraDeliciosaPexelsMedia = licensedImage({
  src: "/media/final-media-v35/monstera-deliciosa-jonathan-borba-pexels.webp",
  alt: "Monstera deliciosa adulte aux feuilles vertes profondément fenêtrées",
  caption: "Vue documentaire distincte de Monstera deliciosa · Jonathan Borba / Pexels.",
  width: 1600,
  height: 2400,
  creator: "Jonathan Borba",
  licenseName: "Pexels License",
  licenseUrl: "https://www.pexels.com/fr-fr/license/",
  sourceUrl: "https://www.pexels.com/fr-fr/photo/feuilles-de-monstera-d-un-vert-luxuriant-a-la-texture-naturelle-37181425/",
  botanicalIdentityEvidence: "casting Deliciosa V3 contrôlé : sujet adulte net, fenestrations fortes et morphologie compatible avec Monstera deliciosa",
});
