import type { PlantEntry } from "./types";
import { stockIdentityPlants } from "./stock-identities-v1.ts";

// Species-level care is shared; identity, evidence and media never inherit from another cultivar.
const sansevieriaCare = stockIdentityPlants.find(p => p.genre === "sansevieria")!.care;
const finish = (plant: PlantEntry): PlantEntry => ({
  ...plant,
  editorialSections: [{ id: "multiplication", eyebrow: "Multiplier", title: "Conserver la sélection", paragraphs: [plant.care.propagation] }],
});
const specimen = { observedHeight: "Aucune mesure de spécimen publiée", note: "Les repères de culture ne sont ni une mesure d’un sujet du Studio ni des seuils de survie. Aucune disponibilité commerciale n’est déduite de cette fiche." };

export const horticulturalIdentityPlants: PlantEntry[] = [finish({
  slug: "black-diamond", genre: "sansevieria", genreLabel: "Sansevieria", displayName: "Black Diamond", listingName: "Sansevieria ‘Black Diamond’",
  botanicalName: "Dracaena trifasciata ‘Black Diamond’", family: "Asparagaceae",
  subtitle: "Une sansevière sombre et graphique, connue sous un nom horticole.",
  taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Dracaena", species: "Dracaena trifasciata", cultivar: "Black Diamond", commonNames: ["Sansevieria Black Diamond", "Langue de belle-mère Black Diamond"] },
  filters: { temperatureMin: 10, temperatureIdeal: [18, 24], humidityIdeal: [30, 60], light: "vive", watering: "faible", substrateTags: ["drainant", "succulentes"], growthRate: "lente", habits: ["terrestre", "dressé"], adultSizeCm: 100, needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Horticulture"] },
  origin: "Sélection horticole ; lieu de sélection et obtenteur non établis ici.",
  habitat: "Pas d’aire sauvage propre à Black Diamond. L’espèce Dracaena trifasciata est africaine.",
  hybridization: "Black Diamond est un nom horticole commercialisé sous Sansevieria trifasciata, aujourd’hui Dracaena trifasciata. Ce n’est pas une espèce botanique distincte. L’usage de ce nom est documenté, mais aucun enregistrement officiel de cultivar ni parentage précis n’est établi par les sources retenues.",
  synonyms: ["Sansevieria trifasciata ‘Black Diamond’"],
  description: ["Les feuilles dressées et charnues donnent une silhouette verticale. Grow Tropicals décrit un vert très sombre et une fine marge plus claire ; il ne s’agit pas d’une feuille uniformément noire.", "Le nom Black Diamond ne suffit pas à démontrer une synonymie avec Midnight Shine, Black Gold ou Black Robusta. Jungle conserve ces identités séparées : une ressemblance visuelle ne remplace pas une étiquette fiable."],
  specimen,
  growth: { adultSize: "Développement variable avec le clone, l’âge et la culture. Le repère de filtre de 1 m concerne le gabarit de l’espèce, pas une hauteur maximale démontrée pour Black Diamond.", speed: "Lente, davantage encore en faible lumière", habit: "Touffe dressée, multiplication par rhizomes" },
  care: { ...sansevieriaCare, propagation: "Préférez la division d’un rejet enraciné provenant d’un sujet correctement étiqueté. Une bouture de feuille ne garantit pas tous les caractères d’une sélection horticole ; conservez la traçabilité de la plante mère." },
  toxicity: { level: "Toxique à l’ingestion", summary: "Ne laissez pas les enfants ou les animaux mâchonner les feuilles.", details: "La toxicité décrite pour Dracaena trifasciata est notamment liée aux saponines. La plante n’est pas présentée comme comestible." },
  problems: [{ title: "Base molle", cause: "Pourriture possible", advice: "Vérifiez les racines et le drainage avant d’ajouter de l’eau." }, { title: "Croissance presque immobile", cause: "Lumière insuffisante ou repos", advice: "Privilégiez un emplacement lumineux ; ne compensez pas par davantage d’eau." }],
  comparisons: [{ name: "Black Gold", difference: "Sélection à bordure dorée, distincte de Black Diamond." }, { name: "Midnight Shine", difference: "Aucune synonymie suffisamment étayée n’est retenue ici." }],
  faq: [{ question: "Black Diamond est-il une espèce botanique ?", answer: "Non. C’est une dénomination horticole rattachée commercialement à Dracaena trifasciata. Son usage est documenté, sans preuve d’enregistrement officiel présentée ici." }, { question: "Pourquoi garder Sansevieria dans la navigation ?", answer: "C’est le nom familier utilisé en horticulture. Le classement botanique actuel dans Dracaena est précisé dans la fiche." }],
  tibaldoAdvice: [], gallery: [], mediaNeeds: [{ role: "Portrait documentaire", description: "Sujet Black Diamond identifié, avec droits documentés ; aucune substitution par Black Gold." }],
  seo: { title: "Sansevieria ‘Black Diamond’ : identité et entretien", description: "Comprendre le nom horticole Black Diamond : Dracaena trifasciata, feuillage sombre, lumière, arrosage et division. Sources et limites d’identification.", keywords: ["Sansevieria Black Diamond", "Dracaena trifasciata", "Black Diamond entretien"] },
  sources: [{ label: "Grow Tropicals — usage horticole et description de Black Diamond", url: "https://growtropicals.com/products/sansevieria-trifasciata-black-diamond" }, { label: "NC State Extension — Dracaena trifasciata, classification et précautions", url: "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/" }, { label: "RHS — culture et multiplication des sansevières", url: "https://www.rhs.org.uk/plants/sansevieria/growing-guide" }],
  showSources: true, publishedAt: "2026-09-13", updatedAt: "2026-09-13",
}), finish({
  slug: "metallica", genre: "colocasia", genreLabel: "Colocasia", botanicalName: "Colocasia esculenta ‘Metallica’", displayName: "Metallica", family: "Araceae",
  subtitle: "Un nom horticole de Colocasia, à distinguer des Alocasia portant un nom proche.",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Colocasia", species: "Colocasia esculenta", cultivar: "Metallica", commonNames: ["Colocasia Metallica", "Oreille d’éléphant Metallica"] },
  filters: { temperatureMin: 15, temperatureIdeal: [18, 26], humidityIdeal: [50, 70], light: "vive", watering: "régulier", substrateTags: ["humifère", "drainant"], growthRate: "moyenne", habits: ["terrestre", "dressé"], adultSizeCm: 150, needsSupport: false, variegated: false, collection: true, flowering: true, petToxic: true, humanToxic: true, regions: ["Horticulture"] },
  origin: "Sélection horticole ; origine précise et obtenteur non établis ici.",
  habitat: "Le nom Metallica ne désigne pas une population sauvage. Les conseils ci-dessous relèvent du cadre de culture de Colocasia esculenta.",
  hybridization: "La RHS répertorie Colocasia esculenta ‘Metallica’, avec un statut de nom non résolu (Unresolved). Denis Plants utilise également cette dénomination dans son catalogue. La fiche documente donc un nom horticole attesté, sans le présenter comme une espèce distincte ni comme un cultivar officiellement accepté par la RHS.",
  synonyms: [],
  description: ["Les Colocasia esculenta développent de grandes feuilles portées par de longs pétioles, à partir d’un organe souterrain de réserve. Cette architecture ample demande de la place autour du contenant.", "Metallica reste ici le nom de la sélection documentée par les sources horticoles. En l’absence de description diagnostique complète, une teinte sombre ou un reflet ne suffit pas à authentifier un sujet. Aucun caractère d’un Alocasia homonyme n’est transféré à cette fiche."],
  specimen,
  growth: { adultSize: "Grand gabarit possible ; le repère de 1,5 m appartient à l’ordre de grandeur de C. esculenta, pas à une mesure ni à une limite validée pour Metallica.", speed: "Dépend de la chaleur et de la saison", habit: "Touffe à grandes feuilles et organe souterrain de réserve" },
  care: { light: 4, water: 4, humidity: 4, difficulty: 3, lightText: "Lumière filtrée ou mi-ombre, à l’abri du vent fort.", watering: "En croissance, gardez le mélange humide sans le laisser sécher complètement. Adaptez les apports à l’activité de la plante.", humidityText: "Évitez un emplacement desséchant ; les valeurs du filtre sont des repères d’ambiance, pas des mesures propres à Metallica.", temperature: "À Lille, privilégiez un contenant pouvant hiverner hors gel. Aucune rusticité spécifique de Metallica n’est garantie.", substrate: "Mélange riche en matière organique, retenant l’humidité mais laissant l’excédent s’évacuer.", repotting: "À la reprise, contrôlez l’espace disponible et rempotez si la touffe manque de place. Préservez les racines saines.", fertilizing: "Apport équilibré pendant la croissance selon la notice du produit ; ne forcez pas une plante au repos.", propagation: "La division d’un départ viable conserve l’identité de la plante mère. Le semis ne garantit pas la sélection Metallica." },
  toxicity: { level: "Irritant à l’ingestion", summary: "Plante ornementale à tenir hors de portée des enfants et des animaux.", details: "Colocasia esculenta contient des cristaux d’oxalate de calcium irritants. Le nom de taro ne constitue pas une recommandation alimentaire pour cette plante horticole." },
  problems: [{ title: "Feuilles abîmées après une sortie", cause: "Vent, froid ou changement d’exposition", advice: "Reprenez une acclimatation progressive dans un emplacement abrité." }, { title: "Déclin en saison froide", cause: "Repos ou conditions inadaptées", advice: "Contrôlez l’état de l’organe souterrain et de la motte ; ne cherchez pas à maintenir la croissance par l’engrais." }],
  comparisons: [{ name: "Alocasia ‘Metallica’", difference: "Un nom proche dans un autre genre n’est pas un synonyme retenu pour ce Colocasia." }, { name: "Colocasia esculenta", difference: "L’espèce fournit le cadre botanique et les conseils généraux ; Metallica désigne le nom horticole documenté ici." }],
  faq: [{ question: "Est-ce bien un Colocasia et non un Alocasia ?", answer: "Oui : la dénomination Colocasia esculenta ‘Metallica’ figure chez la RHS et Denis Plants. Elle ne doit pas être remplacée automatiquement par Alocasia." }, { question: "Le nom est-il définitivement accepté ?", answer: "La RHS indique actuellement Unresolved, c’est-à-dire non résolu. Jungle conserve cette réserve plutôt que de revendiquer une validation nomenclaturale." }, { question: "Peut-il rester dehors tout l’hiver à Lille ?", answer: "Cette fiche ne garantit pas sa survie en pleine terre. Un contenant à rentrer hors gel permet de mieux maîtriser l’hivernage." }],
  tibaldoAdvice: [], gallery: [], mediaNeeds: [{ role: "Portrait documentaire", description: "Colocasia Metallica identifié et droits documentés ; aucune image d’Alocasia de substitution." }],
  seo: { title: "Colocasia ‘Metallica’ : identité, entretien et hivernage", description: "Colocasia esculenta ‘Metallica’ : nom horticole documenté, statut RHS non résolu, arrosage, culture en pot et hivernage. À distinguer des Alocasia.", keywords: ["Colocasia Metallica", "Colocasia esculenta Metallica", "Colocasia hivernage"] },
  sources: [{ label: "RHS — Metallica, statut du nom non résolu", url: "https://www.rhs.org.uk/plants/512281/colocasia-esculenta-metallica/details" }, { label: "Denis Plants — catalogue producteur Colocasia", url: "https://www.denis-plants.com/genus/colocasia/" }, { label: "NC State Extension — cadre botanique et culture de C. esculenta", url: "https://plants.ces.ncsu.edu/plants/colocasia-esculenta/" }, { label: "Hayloft — culture et hivernage des Colocasia", url: "https://hayloft.co.uk/how-to-grow-colocasia" }],
  showSources: true, publishedAt: "2026-09-13", updatedAt: "2026-09-13",
})];
