import type { PlantEntry } from "./types";

type Draft = {
  slug: string; genre: string; genreLabel: string; botanicalName: string; displayName: string;
  listingName?: string;
  subtitle: string; family: string; origin: string; genus: string; species: string; cultivar: string | null;
  commonNames: string[]; habitat: string; hybridization: string; synonyms: string[]; description: string[];
  image: string; imageAlt: string; imageCaption: string; imageWidth: number; imageHeight: number;
  light: 1 | 2 | 3 | 4 | 5; water: 1 | 2 | 3 | 4 | 5; humidity: 1 | 2 | 3 | 4 | 5; difficulty: 1 | 2 | 3 | 4 | 5;
  lightText: string; watering: string; humidityText: string; temperature: string; substrate: string;
  growth: PlantEntry["growth"]; specimen: PlantEntry["specimen"]; filters: PlantEntry["filters"];
  comparisons: PlantEntry["comparisons"]; extraAdvice: string[]; source: { label: string; url: string };
};

const genericToxicity = { level: "toxique", summary: "À tenir hors de portée des enfants, chats et chiens.", details: "Comme de nombreuses Araceae, cette plante contient des cristaux d’oxalate de calcium irritants en cas de mastication ou d’ingestion." };

function makePlant(d: Draft): PlantEntry {
  return {
    slug: d.slug, genre: d.genre, genreLabel: d.genreLabel, botanicalName: d.botanicalName, displayName: d.displayName, listingName: d.listingName,
    subtitle: d.subtitle, family: d.family, origin: d.origin,
    taxonomy: { order: d.family === "Cactaceae" ? "Caryophyllales" : "Alismatales", family: d.family, genus: d.genus, species: d.species, cultivar: d.cultivar, commonNames: d.commonNames },
    filters: d.filters, habitat: d.habitat, hybridization: d.hybridization, synonyms: d.synonyms, description: d.description,
    specimen: d.specimen, growth: d.growth,
    care: {
      light: d.light, water: d.water, humidity: d.humidity, difficulty: d.difficulty,
      lightText: d.lightText, watering: d.watering, humidityText: d.humidityText, temperature: d.temperature, substrate: d.substrate,
      repotting: "Rempoter lorsque les racines occupent réellement le contenant, dans un pot percé seulement légèrement plus grand.",
      fertilizing: "Apporter un engrais complet dilué pendant la période lumineuse, sur un substrat déjà humide.",
      propagation: d.family === "Cactaceae" ? "Bouture de segment cicatrisée avant installation dans un mélange léger." : "Bouture comportant au moins un nœud actif, ou division d’un sujet bien établi.",
    },
    toxicity: d.family === "Cactaceae" ? { level: "non classée comme toxique", summary: "Éviter néanmoins toute ingestion.", details: "La sève et les tissus végétaux peuvent provoquer une gêne digestive ou une irritation chez les personnes et animaux sensibles." } : genericToxicity,
    problems: [
      { title: "Feuilles jaunes", cause: "Excès d’eau, froid, lumière insuffisante ou vieillissement naturel.", advice: "Contrôler les racines et le séchage réel du pot avant de modifier l’arrosage." },
      { title: "Pointes ou plages brunes", cause: "Soleil chaud, air sec, sels ou arrosages irréguliers.", advice: "Stabiliser la culture et protéger la plante des écarts brusques." },
      { title: "Croissance ralentie", cause: "Manque de lumière, température basse ou racines inactives.", advice: "Revoir d’abord la lumière et la température plutôt que d’ajouter de l’engrais." },
      { title: "Thrips ou acariens", cause: "Parasites souvent installés sur les jeunes pousses ou le revers des feuilles.", advice: "Isoler, nettoyer et répéter une surveillance attentive plusieurs semaines." },
    ],
    comparisons: d.comparisons,
    faq: [
      { question: `Quelle lumière pour ${d.botanicalName} ?`, answer: d.lightText },
      { question: `Comment arroser ${d.displayName} ?`, answer: d.watering },
      { question: "Quel substrat utiliser ?", answer: d.substrate },
      { question: "Faut-il un pot percé ?", answer: "Oui. Après chaque arrosage, l’excédent doit pouvoir quitter complètement la motte." },
      { question: "Cette plante est-elle toxique ?", answer: d.family === "Cactaceae" ? "Elle n’est pas classée parmi les plantes d’intérieur couramment toxiques, mais l’ingestion reste déconseillée." : "Oui, la mastication des tissus peut être irritante pour les personnes et les animaux." },
      { question: "Quand la rempoter ?", answer: "Lorsque les racines ont colonisé le pot et que le mélange sèche anormalement vite, plutôt que selon un calendrier fixe." },
    ],
    tibaldoAdvice: ["Observez la motte avant chaque arrosage : la surface seule ne raconte pas tout.", "Une lumière adaptée produit une croissance plus solide qu’un apport d’engrais excessif.", ...d.extraAdvice],
    gallery: [{ src: d.image, alt: d.imageAlt, caption: d.imageCaption, width: d.imageWidth, height: d.imageHeight }],
    seo: { title: `${d.botanicalName} : entretien et conseils`, description: `Guide de ${d.botanicalName} : lumière, arrosage, substrat, croissance, toxicité et entretien en intérieur à Lille.`, keywords: [`${d.botanicalName} entretien`, `${d.displayName} Lille`, `${d.genus} arrosage`, `${d.genus} substrat`] },
    sources: [d.source], publishedAt: "2026-08-15", updatedAt: "2026-08-15",
  };
}

const aroidFilters = (variegated: boolean, growthRate: "lente" | "moyenne" | "rapide" = "moyenne"): PlantEntry["filters"] => ({ temperatureMin: 15, temperatureIdeal: [18, 28], humidityIdeal: [50, 75], light: "vive", watering: "modéré", substrateTags: ["aroïdes", "aéré", "drainant", "organique"], growthRate, habits: ["grimpant", "hémiépiphyte"], adultSizeCm: 250, needsSupport: true, variegated, collection: variegated, flowering: false, petToxic: true, humanToxic: true, regions: ["Amérique tropicale", "Horticulture"] });

export const requestedPlants = [
  makePlant({
    slug: "anguliger", genre: "epiphyllum", genreLabel: "Epiphyllum", botanicalName: "Disocactus anguliger", displayName: "Epiphyllum anguliger", listingName: "Cactus zigzag · Epiphyllum anguliger", subtitle: "Le cactus zigzag aux longues tiges découpées et aux fleurs nocturnes parfumées.", family: "Cactaceae", origin: "Mexique", genus: "Disocactus", species: "Disocactus anguliger", cultivar: null,
    commonNames: ["Epiphyllum anguliger", "Cactus zigzag", "Cactus arête-de-poisson"], habitat: "Cactus épiphyte des forêts humides mexicaines, installé sur les branches dans une lumière filtrée.", hybridization: "Espèce botanique aujourd’hui acceptée sous le nom Disocactus anguliger. Epiphyllum anguliger reste son nom horticole historique le plus utilisé.", synonyms: ["Epiphyllum anguligerum", "Phyllocactus anguliger"],
    description: ["Ses tiges plates dessinent une succession de lobes profonds qui évoquent une arête de poisson.", "Contrairement aux cactus désertiques, il apprécie une lumière vive filtrée, un mélange organique très aéré et des arrosages réguliers pendant sa croissance."],
    image: "/disocactus-anguliger-cactus-zigzag.webp", imageAlt: "Disocactus anguliger suspendu en serre avec de longues tiges vertes plates et profondément découpées", imageCaption: "Photographie réelle du cactus zigzag Disocactus anguliger cultivé en suspension sous serre.", imageWidth: 1672, imageHeight: 941,
    light: 4, water: 3, humidity: 3, difficulty: 2, lightText: "Lumière vive indirecte ; un soleil doux aide la floraison, mais le soleil brûlant marque les tiges.", watering: "Arroser lorsque le mélange a partiellement séché, davantage en croissance et beaucoup moins en hiver.", humidityText: "Une humidité domestique moyenne convient si l’air circule.", temperature: "Idéalement 16 à 26 °C, avec une période hivernale plus fraîche sans gel.", substrate: "Mélange pour cactus épiphytes : terreau fibreux, écorce fine et fraction minérale, dans un pot percé.",
    specimen: { observedHeight: "Tiges retombantes de 30 à 100 cm", note: "Le port devient particulièrement spectaculaire en suspension." }, growth: { adultSize: "Tiges pouvant approcher un mètre", speed: "Moyenne à rapide en saison", habit: "Épiphyte et retombant" },
    filters: { temperatureMin: 10, temperatureIdeal: [16, 26], humidityIdeal: [40, 65], light: "vive", watering: "modéré", substrateTags: ["cactus épiphyte", "aéré", "écorce", "drainant"], growthRate: "moyenne", habits: ["épiphyte", "retombant"], adultSizeCm: 100, needsSupport: false, variegated: false, collection: false, flowering: true, petToxic: false, humanToxic: false, regions: ["Mexique"] },
    comparisons: [{ name: "Selenicereus anthonyanus", difference: "Découpes généralement plus longues et plus étroites, donnant un zigzag différent." }, { name: "Disocactus ackermannii", difference: "Tiges moins profondément lobées et floraison rouge spectaculaire." }], extraAdvice: ["Une baisse modérée des températures hivernales peut favoriser la formation des boutons."], source: { label: "Kew Science — Disocactus anguliger", url: "https://powo.science.kew.org/results?q=Disocactus%20anguliger" },
  }),
  makePlant({
    slug: "deliciosa", genre: "monstera", genreLabel: "Monstera", botanicalName: "Monstera deliciosa", displayName: "Deliciosa", subtitle: "La grande Monstera aux feuilles naturellement découpées et fenêtrées.", family: "Araceae", origin: "Mexique à Amérique centrale", genus: "Monstera", species: "Monstera deliciosa", cultivar: null,
    commonNames: ["Faux philodendron", "Plante gruyère", "Monstera"], habitat: "Liane hémiépiphyte des forêts tropicales humides, qui grimpe sur les troncs vers la lumière.", hybridization: "Espèce botanique.", synonyms: ["Philodendron pertusum hort."], description: ["Les feuilles juvéniles sont entières puis développent découpes et perforations en gagnant maturité, lumière et support.", "Un tuteur stable et une lumière vive permettent d’obtenir un port plus vertical et des feuilles plus grandes."],
    image: "/monstera-deliciosa-feuilles.jpg", imageAlt: "Feuilles réelles découpées et fenêtrées de Monstera deliciosa", imageCaption: "Feuillage mature de Monstera deliciosa.", imageWidth: 1200, imageHeight: 800,
    light: 4, water: 2, humidity: 3, difficulty: 2, lightText: "Lumière vive indirecte, avec éventuellement un soleil doux après acclimatation.", watering: "Laisser sécher plusieurs centimètres du mélange puis arroser complètement et égoutter.", humidityText: "Une humidité moyenne suffit ; la stabilité compte davantage que les vaporisations.", temperature: "18 à 28 °C, sans froid durable sous 15 °C.", substrate: "Mélange aroïdes grossier et respirant dans un pot percé.",
    specimen: { observedHeight: "Jusqu’à plusieurs mètres avec support", note: "La taille des feuilles dépend fortement de la lumière et de la possibilité de grimper." }, growth: { adultSize: "Grande liane d’intérieur", speed: "Rapide en conditions lumineuses", habit: "Grimpant et hémiépiphyte" }, filters: aroidFilters(false, "rapide"), comparisons: [{ name: "Monstera borsigiana", difference: "Nom horticole encore utilisé, mais généralement traité dans Monstera deliciosa." }, { name: "Rhaphidophora tetrasperma", difference: "Feuilles plus petites, découpées sans perforations internes typiques." }], extraAdvice: ["Fixez le dos de la tige contre le support afin que les racines aériennes puissent s’y ancrer."], source: { label: "Kew Science — Monstera deliciosa", url: "https://powo.science.kew.org/results?q=Monstera%20deliciosa" },
  }),
  makePlant({
    slug: "thai-constellation", genre: "monstera", genreLabel: "Monstera", botanicalName: "Monstera deliciosa ‘Thai Constellation’", displayName: "Thai Constellation", subtitle: "Une Monstera constellée de crème, à la panachure stable mais exigeante en lumière.", family: "Araceae", origin: "Cultivar horticole", genus: "Monstera", species: "Monstera deliciosa", cultivar: "Thai Constellation", commonNames: ["Monstera Thai Constellation", "Monstera panachée crème"], habitat: "Cultivar dérivé de Monstera deliciosa et cultivé en intérieur lumineux.", hybridization: "Cultivar horticole sélectionné pour sa panachure crème mouchetée répartie dans les tissus.", synonyms: ["Monstera deliciosa Thai Constellation"], description: ["Ses feuilles associent plages crème et fines éclaboussures qui rappellent un ciel étoilé.", "Moins chlorophyllienne qu’une deliciosa verte, elle pousse plus lentement et demande une lumière vive sans soleil chaud."],
    image: "/monstera-thai-constellation-planche-botanique.webp", imageAlt: "Sept feuilles adultes de Monstera deliciosa Thai Constellation disposées en planche botanique", imageCaption: "Planche botanique créée à partir de la photographie fournie du spécimen ‘Thai Constellation’.", imageWidth: 1619, imageHeight: 971,
    light: 5, water: 2, humidity: 3, difficulty: 3, lightText: "Lumière très vive indirecte pour soutenir les parties crème, sans soleil chaud.", watering: "Laisser sécher le haut du pot ; ses racines supportent mal une humidité permanente.", humidityText: "Humidité moyenne à élevée avec ventilation.", temperature: "18 à 28 °C, idéalement stable.", substrate: "Mélange très aéré pour aroïdes, en pot percé ajusté.", specimen: { observedHeight: "Grande liane panachée", note: "La proportion de crème varie naturellement d’une feuille à l’autre." }, growth: { adultSize: "Plusieurs mètres avec support", speed: "Moyenne à lente", habit: "Grimpant" }, filters: aroidFilters(true, "lente"), comparisons: [{ name: "Monstera deliciosa ‘Albo Variegata’", difference: "Panachure souvent plus blanche, sectorielle et plus variable d’un nœud à l’autre." }, { name: "Monstera deliciosa ‘Mint’", difference: "Marbrure pâle diffuse et aspect mentholé plutôt que ponctuation crème." }], extraAdvice: ["Les zones crème brûlent plus vite : augmentez la lumière progressivement."], source: { label: "RHS — Monstera deliciosa", url: "https://www.rhs.org.uk/plants/11344/monstera-deliciosa/details" },
  }),
  makePlant({
    slug: "mint", genre: "monstera", genreLabel: "Monstera", botanicalName: "Monstera deliciosa ‘Mint’", displayName: "Mint", subtitle: "Une Monstera de collection à la panachure vert pâle finement marbrée.", family: "Araceae", origin: "Cultivar horticole", genus: "Monstera", species: "Monstera deliciosa", cultivar: "Mint", commonNames: ["Monstera Mint", "Monstera deliciosa Mint"], habitat: "Cultivar de Monstera deliciosa cultivé pour sa panachure diffuse.", hybridization: "Nom horticole employé pour des lignées panachées vert clair ; l’origine commerciale peut varier.", synonyms: ["Monstera deliciosa Mint Variegata"], description: ["Le terme Mint décrit une panachure pâle, diffuse et marbrée plutôt que de grandes plages blanches nettes.", "Cette plante de collection doit être évaluée sur la stabilité de sa tige et de ses nouvelles feuilles, pas seulement sur une photographie commerciale."],
    image: "/monstera-mint-planche-botanique.webp", imageAlt: "Sept feuilles adultes de Monstera deliciosa Mint isolées sur une planche botanique ivoire", imageCaption: "Planche botanique créée à partir de la photographie fournie du spécimen Monstera ‘Mint’.", imageWidth: 1619, imageHeight: 971,
    light: 5, water: 2, humidity: 3, difficulty: 4, lightText: "Lumière très vive indirecte, indispensable pour une plante fortement panachée.", watering: "Arroser après séchage partiel et ne jamais laisser d’eau au fond du cache-pot.", humidityText: "Humidité stable et air en mouvement.", temperature: "18 à 28 °C.", substrate: "Mélange aroïdes très respirant dans un pot ajusté.", specimen: { observedHeight: "Variable selon le clone", note: "Photographie du spécimen Tibaldo Jungle encore nécessaire." }, growth: { adultSize: "Grande liane sur support", speed: "Lente à moyenne", habit: "Grimpant" }, filters: aroidFilters(true, "lente"), comparisons: [{ name: "Thai Constellation", difference: "Ponctuation crème plus régulière et identité horticole généralement mieux définie." }, { name: "Albo Variegata", difference: "Contrastes blancs plus francs et panachure souvent sectorielle." }], extraAdvice: ["Demandez toujours une photo de la tige et de la dernière feuille avant l’achat d’un clone Mint."], source: { label: "Kew Science — Monstera deliciosa", url: "https://powo.science.kew.org/results?q=Monstera%20deliciosa" },
  }),
  makePlant({
    slug: "adansonii", genre: "monstera", genreLabel: "Monstera", botanicalName: "Monstera adansonii", displayName: "Adansonii · Monkey Mask", subtitle: "La véritable plante gruyère, aussi appelée Monkey Mask, percée de nombreuses fenêtres dès son jeune âge.", family: "Araceae", origin: "Amérique tropicale", genus: "Monstera", species: "Monstera adansonii", cultivar: null, commonNames: ["Monkey Mask", "Plante gruyère", "Monstera à trous"], habitat: "Liane des forêts tropicales américaines, grimpant dans une atmosphère chaude et humide.", hybridization: "Espèce botanique comportant plusieurs sous-espèces reconnues.", synonyms: ["Monstera pertusa hort.", "Monstera friedrichsthalii hort."], description: ["Ses feuilles restent plus petites que celles de Monstera deliciosa et portent de nombreuses perforations internes.", "Elle peut retomber, mais grimper sur un support lui permet de produire des feuilles plus grandes et mieux fenêtrées."],
    image: "/monstera-adansonii-monkey-mask.webp", imageAlt: "Grande Monstera adansonii Monkey Mask grimpante couverte de feuilles vertes naturellement perforées", imageCaption: "Composition photographique réalisée à partir des images de Monstera adansonii fournies.", imageWidth: 1122, imageHeight: 1402,
    light: 4, water: 3, humidity: 4, difficulty: 2, lightText: "Lumière vive indirecte, sans soleil brûlant.", watering: "Arroser après le séchage des premiers centimètres, puis laisser égoutter.", humidityText: "Une humidité supérieure à la moyenne soutient les jeunes feuilles, avec ventilation.", temperature: "18 à 28 °C.", substrate: "Mélange aroïdes aéré, légèrement plus fin que pour une grande deliciosa.", specimen: { observedHeight: "Liane de plusieurs mètres", note: "Les feuilles gagnent en taille lorsqu’elle grimpe." }, growth: { adultSize: "Longue liane tropicale", speed: "Rapide", habit: "Grimpant ou retombant" }, filters: aroidFilters(false, "rapide"), comparisons: [{ name: "Monstera deliciosa", difference: "Feuilles adultes beaucoup plus grandes, avec découpes externes en plus des perforations." }, { name: "Monstera obliqua", difference: "Espèce beaucoup plus rare et délicate, aux limbes parfois extrêmement perforés." }], extraAdvice: ["Un support humide et stable favorise des feuilles plus grandes sans forcer les arrosages."], source: { label: "Kew Science — Monstera adansonii", url: "https://powo.science.kew.org/taxon/87464-1" },
  }),
  makePlant({
    slug: "royal-queen", genre: "philodendron", genreLabel: "Philodendron", botanicalName: "Philodendron ‘Royal Queen’", displayName: "Royal Queen", subtitle: "Un Philodendron sombre dont les nouvelles feuilles passent du bordeaux au vert profond.", family: "Araceae", origin: "Cultivar horticole", genus: "Philodendron", species: "Hybride horticole", cultivar: "Royal Queen", commonNames: ["Philodendron Royal Queen", "Philo Queen"], habitat: "Cultivar d’intérieur sélectionné pour son feuillage sombre et son port compact à dressé.", hybridization: "Cultivar horticole ; sa parenté exacte est rapportée de façon variable dans le commerce.", synonyms: ["Philodendron New Red"], description: ["Les nouvelles feuilles émergent dans des tons rouge bordeaux avant de foncer en mûrissant.", "Son identité doit être conservée sous le nom de cultivar ‘Royal Queen’, sans lui attribuer une espèce incertaine."],
    image: "/photo-reelle-a-venir.svg", imageAlt: "Emplacement réservé à une photographie réelle de Philodendron Royal Queen", imageCaption: "Photo réelle du Philodendron ‘Royal Queen’ du Studio à ajouter.", imageWidth: 1200, imageHeight: 1500,
    light: 4, water: 2, humidity: 3, difficulty: 2, lightText: "Lumière vive indirecte pour conserver un port dense et des couleurs profondes.", watering: "Laisser sécher partiellement le mélange entre deux arrosages.", humidityText: "Humidité domestique moyenne à élevée.", temperature: "18 à 28 °C.", substrate: "Mélange aroïdes aéré et riche, dans un pot percé.", specimen: { observedHeight: "Port compact à dressé", note: "Photo et dimensions du spécimen Tibaldo Jungle à relever." }, growth: { adultSize: "Environ 80 à 120 cm selon la lignée", speed: "Moyenne", habit: "Dressé à semi-grimpant" }, filters: { ...aroidFilters(false), needsSupport: false, habits: ["dressé"] }, comparisons: [{ name: "Philodendron ‘Black Cardinal’", difference: "Port très autoportant et feuillage souvent plus large et compact." }, { name: "Philodendron ‘Imperial Red’", difference: "Silhouette plus compacte et nouvelles feuilles rouges plus franches." }], extraAdvice: ["Conservez l’étiquette fournisseur : plusieurs Philodendron sombres sont facilement confondus."], source: { label: "RHS — Philodendron ‘Royal Queen’", url: "https://www.rhs.org.uk/plants/187941/philodendron-royal-queen/details" },
  }),
  makePlant({
    slug: "delta-force", genre: "anthurium", genreLabel: "Anthurium", botanicalName: "Anthurium ‘Delta Force’", displayName: "Delta Force", subtitle: "Le clone de collection sélectionné pour ses grandes feuilles deltoïdes à la pointe étroite.", family: "Araceae", origin: "Hybride horticole · Miami, années 1990", genus: "Anthurium", species: "Hybride horticole", cultivar: "Delta Force", commonNames: ["Anthurium Delta Force"], habitat: "Hybride cultivé dans des conditions chaudes, lumineuses et très aérées.", hybridization: "Sélection clonale issue du croisement Anthurium clarinervium × Anthurium pedatoradiatum réalisé par Steve Nock à Ree Gardens, à Miami, dans les années 1990. Parmi la descendance variable, un seul semis s’est distingué par son limbe deltoïde et sa pointe particulièrement longue : ce sujet a reçu le nom ‘Delta Force’.", synonyms: ["Anthurium clarinervium × Anthurium pedatoradiatum ‘Delta Force’"], description: ["Du clarinervium, le clone conserve une texture sombre et veloutée ainsi qu’un réseau de nervures claires. L’influence du pedatoradiatum se lit dans une architecture plus anguleuse, mais la sélection ‘Delta Force’ reste peu lobée et forme un triangle très reconnaissable.", "Refaire le même croisement produit des frères et sœurs génétiquement différents : ces semis sont des Anthurium clarinervium × pedatoradiatum, mais ne sont pas automatiquement ‘Delta Force’. Un véritable ‘Delta Force’ doit descendre végétativement du clone sélectionné, par division ou culture in vitro traçable."],
    image: "/anthurium-delta-force-triangulaire.webp", imageAlt: "Anthurium Delta Force en pot avec une grande feuille veloutée sombre de forme triangulaire et une longue pointe étroite", imageCaption: "Composition photographique réalisée à partir de la photographie d’Anthurium ‘Delta Force’ fournie.", imageWidth: 1122, imageHeight: 1402,
    light: 4, water: 3, humidity: 4, difficulty: 4, lightText: "Lumière vive indirecte, sans soleil chaud sur le limbe.", watering: "Maintenir une humidité légère et régulière, jamais une saturation permanente.", humidityText: "Humidité élevée avec excellente circulation de l’air.", temperature: "18 à 27 °C.", substrate: "Mélange très aéré pour Anthurium : écorce, sphaigne, coco et fraction minérale.", specimen: { observedHeight: "Plante de collection à croissance modérée", note: "Le caractère deltoïde s’affirme avec la maturité ; les jeunes feuilles peuvent être moins typées." }, growth: { adultSize: "Feuillage ample et étalé", speed: "Lente à moyenne", habit: "Dressé en rosette" }, filters: { ...aroidFilters(false, "lente"), habits: ["terrestre", "dressé"], needsSupport: false, collection: true }, comparisons: [{ name: "Anthurium pedatoradiatum", difference: "Feuilles adultes divisées en lobes plus fins et plus nombreux." }, { name: "Anthurium clarinervium", difference: "Feuilles plus cordiformes, aux épaules arrondies et au sinus davantage marqué." }, { name: "Clarinervium × pedatoradiatum de semis", difference: "Même parentage annoncé, mais silhouette variable et absence de garantie qu’il s’agisse du clone sélectionné ‘Delta Force’." }], extraAdvice: ["Un simple semis du même croisement ne doit pas être étiqueté ‘Delta Force’ sans traçabilité clonale.", "Pour un achat de collection, demandez si la plante provient d’une division ou d’une culture in vitro identifiée du clone."], source: { label: "Carnivero — histoire du clone Anthurium ‘Delta Force’", url: "https://www.carnivero.com/products/anthurium-delta-force" },
  }),
  makePlant({
    slug: "melanochrysum", genre: "philodendron", genreLabel: "Philodendron", botanicalName: "Philodendron melanochrysum", displayName: "Melanochrysum", subtitle: "Le Philodendron velours aux longues feuilles sombres parcourues de nervures dorées.", family: "Araceae", origin: "Colombie", genus: "Philodendron", species: "Philodendron melanochrysum", cultivar: null, commonNames: ["Black Gold Philodendron", "Philodendron velours"], habitat: "Liane des forêts humides colombiennes, signalée dans les Andes à altitude intermédiaire.", hybridization: "Espèce botanique.", synonyms: ["Philodendron andreanum"], description: ["Ses feuilles juvéniles s’allongent progressivement pour devenir de grands limbes veloutés vert sombre.", "Il demande surtout un support vertical, une lumière vive et des conditions stables pour produire des feuilles adultes."],
    image: "/philodendron-melanochrysum-real.jpg", imageAlt: "Philodendron melanochrysum réel aux feuilles sombres veloutées", imageCaption: "Photographie réelle de Philodendron melanochrysum par Chhe, domaine public — Wikimedia Commons.", imageWidth: 1920, imageHeight: 2560,
    light: 4, water: 3, humidity: 4, difficulty: 4, lightText: "Lumière vive indirecte et régulière.", watering: "Arroser après séchage superficiel, sans laisser les racines détrempées.", humidityText: "Humidité élevée et ventilation douce pour préserver les jeunes feuilles.", temperature: "18 à 27 °C.", substrate: "Mélange aroïdes très aéré et support vertical adapté.", specimen: { observedHeight: "Liane à très grandes feuilles", note: "Les feuilles adultes peuvent devenir spectaculaires sur un support bien colonisé." }, growth: { adultSize: "Liane de plusieurs mètres", speed: "Moyenne", habit: "Grimpant" }, filters: { ...aroidFilters(false), collection: true }, comparisons: [{ name: "Philodendron verrucosum", difference: "Pétioles velus et nervation plus contrastée sur des feuilles généralement plus cordiformes." }, { name: "Philodendron gigas", difference: "Feuillage sombre proche, mais morphologie et coloration juvénile différentes." }], extraAdvice: ["Ne laissez pas les nouvelles feuilles frotter contre un mur : elles se marquent avant de durcir."], source: { label: "Kew Science — Philodendron melanochrysum", url: "https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87882-1" },
  }),
  makePlant({
    slug: "brasil", genre: "philodendron", genreLabel: "Philodendron", botanicalName: "Philodendron hederaceum ‘Brasil’", displayName: "Brasil", subtitle: "Le philodendron scandens panaché d’une bande citron au cœur de chaque feuille.", family: "Araceae", origin: "Cultivar horticole", genus: "Philodendron", species: "Philodendron hederaceum", cultivar: "Brasil", commonNames: ["Philodendron scandens Brasil", "Philo Brasil", "Philodendron Brazil"], habitat: "Cultivar d’une liane tropicale américaine, adapté à la culture grimpante ou retombante.", hybridization: "Cultivar horticole de Philodendron hederaceum. L’orthographe du cultivar est ‘Brasil’, avec un s.", synonyms: ["Philodendron scandens ‘Brasil’", "Philodendron oxycardium ‘Brasil’"], description: ["Chaque feuille en cœur porte une panachure centrale jaune à vert citron encadrée de vert foncé.", "Très souple, il peut retomber en suspension ou grimper sur un support pour augmenter progressivement la taille de ses feuilles."],
    image: "/photo-reelle-a-venir.svg", imageAlt: "Emplacement réservé à une photographie réelle de Philodendron hederaceum Brasil", imageCaption: "Photo réelle du Philodendron hederaceum ‘Brasil’ du Studio à ajouter.", imageWidth: 1200, imageHeight: 1500,
    light: 4, water: 2, humidity: 3, difficulty: 1, lightText: "Lumière moyenne à vive indirecte ; davantage de lumière maintient une panachure plus nette.", watering: "Laisser sécher le haut du mélange avant d’arroser complètement.", humidityText: "Une humidité domestique moyenne lui convient.", temperature: "18 à 28 °C.", substrate: "Mélange aéré pour aroïdes, dans un pot percé.", specimen: { observedHeight: "Longues tiges souples", note: "Le même sujet peut être cultivé en suspension ou sur tuteur." }, growth: { adultSize: "Liane de plusieurs mètres", speed: "Rapide", habit: "Grimpant ou retombant" }, filters: { ...aroidFilters(true, "rapide"), collection: false, habits: ["grimpant", "retombant", "hémiépiphyte"] }, comparisons: [{ name: "Philodendron hederaceum vert", difference: "Même silhouette, mais feuillage uniformément vert." }, { name: "Epipremnum aureum", difference: "Souvent confondu avec lui ; pétiole, gaine et croissance des feuilles diffèrent." }], extraAdvice: ["Si une tige redevient entièrement verte, taillez-la jusqu’au dernier nœud correctement panaché."], source: { label: "University of Connecticut — Philodendron", url: "https://homegarden.cahnr.uconn.edu/factsheets/philodendron/" },
  }),
] satisfies PlantEntry[];
