import type { PlantEntry } from "./types";

// Editorial identities, not commercial products. Evidence decisions: docs/stock-identities-v1.md.
type Draft = Omit<PlantEntry, "gallery" | "mediaNeeds" | "publishedAt" | "updatedAt" | "specimen" | "seo" | "tibaldoAdvice">;
const entry = (plant: Draft): PlantEntry => ({
  ...plant,
  showSources: true,
  editorialSections: [{ id: "multiplication", eyebrow: "Multiplier", title: "Conserver l’identité de la plante", paragraphs: [plant.care.propagation] }],
  specimen: { observedHeight: "Aucune mesure de spécimen publiée", note: "Les dimensions sont des repères de culture, pas une mesure d’un sujet du Studio. Les plages de température et d’humidité sont des repères indicatifs, non des seuils de survie." },
  gallery: [],
  mediaNeeds: [{ role: "Portrait documentaire", description: `Photographie identifiée de ${plant.botanicalName}, avec droits documentés.` }],
  seo: { title: `${plant.botanicalName} : entretien et identification`, description: `${plant.subtitle} Lumière, arrosage, substrat et multiplication : une fiche botanique documentée, indépendante de toute disponibilité commerciale.`, keywords: [plant.botanicalName, plant.genreLabel, `${plant.botanicalName} entretien`] },
  tibaldoAdvice: [],
  publishedAt: "2026-09-12", updatedAt: "2026-09-12",
});

const source = (label: string, url: string) => ({ label, url });
const powo = (name: string, id: string) => source(`Kew — ${name}`, `https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:${id}`);
const uncertainToxicity = { level: "Données spécifiques limitées", summary: "Aucune garantie d’innocuité n’est formulée pour cette identité.", details: "Cette fiche ne présente pas la plante comme comestible ni comme certifiée sans risque pour les animaux. L’absence de donnée spécifique n’est pas une preuve d’innocuité." };
const defaults: PlantEntry["filters"] = { temperatureMin: 15, temperatureIdeal: [18, 24], humidityIdeal: [45, 65], light: "vive", watering: "modéré", substrateTags: ["aéré", "drainant"], growthRate: "moyenne", habits: ["terrestre", "dressé"], adultSizeCm: 100, needsSupport: false, variegated: false, collection: false, flowering: true, petToxic: null, humanToxic: null, regions: ["Horticulture"] };

const imperialGreen = entry({
  slug: "imperial-green", genre: "philodendron", genreLabel: "Philodendron", botanicalName: "Philodendron ‘Imperial Green’", displayName: "Imperial Green", family: "Araceae",
  subtitle: "Un cultivar au feuillage ample, lustré et entièrement vert.",
  taxonomy: { order: "Alismatales", family: "Araceae", genus: "Philodendron", species: "Parentage non précisé", cultivar: "Imperial Green", commonNames: ["Philodendron Imperial Green"] },
  filters: { ...defaults, adultSizeCm: 120, petToxic: true, humanToxic: true },
  origin: "Sélection horticole ; origine précise du cultivar non établie ici.",
  habitat: "Un cultivar cultivé ne possède pas d’aire sauvage propre. Les conditions d’intérieur doivent être adaptées à son feuillage tropical.",
  hybridization: "Nom horticole accepté par la RHS au niveau du genre. Aucun parent botanique ni croisement n’est déduit de ce nom.", synonyms: [],
  description: ["Imperial Green apporte une masse de grandes feuilles vertes plutôt qu’une panachure rose. Les limbes larges et brillants composent une silhouette dense ; les feuilles neuves se déploient progressivement.", "Il ne s’agit ni d’une taille de pot ni d’une forme adulte de Pink Princess. Ces noms horticoles restent distincts dans l’encyclopédie."],
  growth: { adultSize: "Environ 1,2 m dans de bonnes conditions en contenant ; volume et maturité font varier ce repère.", speed: "Progressive en intérieur lumineux", habit: "Port feuillu dense, à laisser se déployer sans comprimer les pétioles" },
  care: { light: 4, water: 3, humidity: 3, difficulty: 2, lightText: "Une lumière abondante filtrée soutient les grandes feuilles. Évitez le soleil estival brûlant.", watering: "Attendez un début de séchage en surface, puis arrosez et laissez égoutter. Réduisez la fréquence si la motte reste humide en hiver.", humidityText: "Éloignez le feuillage du chauffage desséchant et conservez une circulation d’air douce.", temperature: "Une pièce chaude et stable convient ; évitez les nuits sous 15 °C et le contact avec une vitre froide.", substrate: "Terreau sans tourbe pour plantes d’intérieur, structuré et drainant, dans un pot percé.", repotting: "Au printemps lorsque les racines occupent le pot ; choisissez un contenant légèrement plus large, pas une réserve de terreau détrempé.", fertilizing: "Un apport modéré pendant la croissance, selon la notice ; ne fertilisez pas une motte sèche ou une plante au repos.", propagation: "Une multiplication végétative nécessite un fragment de tige portant un nœud ou un rejet enraciné. Une feuille seule ne reconstitue pas le cultivar." },
  toxicity: { level: "Irritant à l’ingestion", summary: "Philodendron à tenir hors de portée des enfants et des animaux.", details: "Les tissus contiennent des cristaux d’oxalate de calcium irritants. Évitez le contact de la sève avec les muqueuses ; portez des gants lors de la coupe." },
  problems: [{ title: "Feuille jaune et motte humide", cause: "Excès d’eau possible", advice: "Contrôlez drainage et racines avant tout nouvel arrosage." }, { title: "Feuilles marquées", cause: "Soleil brûlant ou parasites possibles", advice: "Inspectez les deux faces ; adaptez l’exposition et isolez en présence de parasites." }],
  comparisons: [{ name: "Pink Princess", difference: "Cultivar panaché de rose, distinct d’Imperial Green ; aucune substitution de nom." }],
  faq: [{ question: "Imperial Green est-il une espèce ?", answer: "Non, c’est un cultivar. La RHS le répertorie sous Philodendron ‘Imperial Green’, sans préciser de parent botanique." }],
  sources: [source("RHS — identité Imperial Green", "https://www.rhs.org.uk/plants/345645/philodendron-imperial-green/details"), source("RHS — culture des Philodendron", "https://www.rhs.org.uk/plants/philodendron"), source("NC State Extension — Philodendron, culture et toxicité", "https://plants.ces.ncsu.edu/plants/philodendron/"), source("RHS Plants — dimensions horticoles indicatives", "https://www.rhsplants.co.uk/plants/_/philodendron-imperial-green/classid.2000034365/")],
});

const callistophylla = entry({
  slug: "callistophylla", genre: "hoya", genreLabel: "Hoya", botanicalName: "Hoya callistophylla", displayName: "Callistophylla", family: "Apocynaceae",
  subtitle: "Une liane de Bornéo aux feuilles épaisses parcourues de nervures sombres.",
  taxonomy: { order: "Gentianales", family: "Apocynaceae", genus: "Hoya", species: "Hoya callistophylla", cultivar: null, commonNames: [] },
  filters: { ...defaults, temperatureMin: 16, humidityIdeal: [50, 70], habits: ["grimpant", "épiphyte", "retombant"], adultSizeCm: 500, needsSupport: true, collection: true, petToxic: true, humanToxic: true, regions: ["Bornéo"] },
  origin: "Bornéo", habitat: "Forêts tropicales de Bornéo ; liane pouvant pousser en épiphyte.", hybridization: "Espèce acceptée par Kew, décrite par T. Green en 2000. Aucun cultivar ni numéro de collecte n’est ajouté.", synonyms: [],
  description: ["Les feuilles opposées, coriaces et allongées portent un réseau de nervures vert foncé particulièrement lisible. Elles accompagnent des tiges volubiles plutôt qu’une rosette autonome.", "Les petites fleurs cireuses sont réunies en ombelles. Le feuillage ne permet pas à lui seul d’attribuer une provenance de collecte ou une sélection commerciale particulière."],
  growth: { adultSize: "Jusqu’à plusieurs mètres de tige, 5 m signalés par NParks ; encombrement très différent sur un petit support en intérieur.", speed: "Variable avec lumière et chaleur", habit: "Liane à guider ou à laisser retomber" },
  care: { light: 4, water: 2, humidity: 4, difficulty: 3, lightText: "Lumière vive filtrée, loin du soleil brûlant.", watering: "Laissez le mélange s’aérer et sécher partiellement entre les apports, sans dessèchement prolongé. Égouttez toujours.", humidityText: "Une ambiance modérément humide et ventilée convient mieux qu’un feuillage constamment mouillé.", temperature: "Gardez une ambiance douce à chaude ; 18–24 °C est un repère d’intérieur, sans test de résistance au froid revendiqué.", substrate: "Mélange poreux pour épiphytes avec une fraction organique et des éléments grossiers ; pot percé.", repotting: "Intervenez lorsque les racines manquent réellement de place, en limitant les perturbations et le surpotage.", fertilizing: "Fertilisation légère en croissance, ralentie avec la plante ; laissez une période de reprise après rempotage.", propagation: "Bouture de tige avec nœud au printemps ou en début d’été. Conservez les anciens pédoncules floraux : ils peuvent refleurir." },
  toxicity: { level: "Précaution avec la sève", summary: "Évitez l’ingestion et le contact de la sève avec la peau.", details: "NParks signale un risque d’irritation et recommande l’éloignement des enfants et animaux. Cette prudence spécifique n’est pas remplacée par une affirmation générale sur tous les Hoya." },
  problems: [{ title: "Feuilles fripées", cause: "Déshydratation ou racines altérées", advice: "Examinez motte et racines avant d’ajouter de l’eau." }, { title: "Absence de fleurs", cause: "Maturité ou lumière insuffisante", advice: "Améliorez progressivement la lumière et préservez les pédoncules." }, { title: "Amas cotonneux", cause: "Cochenilles possibles", advice: "Inspectez nœuds et revers des feuilles, puis isolez la plante atteinte." }],
  comparisons: [{ name: "Hoya carnosa", difference: "Une autre espèce : ne pas lui transférer automatiquement l’identité ni la tolérance hivernale de carnosa." }],
  faq: [{ question: "Callistophylla signifie-t-il une sélection panachée ?", answer: "Non. C’est le nom d’une espèce de Bornéo ; ses nervures sombres ne sont pas une panachure horticole." }],
  sources: [powo("Hoya callistophylla", "20005842-1"), source("NParks — morphologie, habitat et précautions", "https://www.nparks.gov.sg/florafaunaweb/flora/6/9/6904"), source("RHS — culture et multiplication des Hoya", "https://www.rhs.org.uk/plants/hoya/how-to-grow")],
});

const blackGold = entry({
  slug: "black-gold", genre: "sansevieria", genreLabel: "Sansevieria", botanicalName: "Dracaena trifasciata ‘Black Gold’", displayName: "Black Gold", listingName: "Sansevieria ‘Black Gold’", family: "Asparagaceae",
  subtitle: "Des feuilles vert sombre bordées d’or, sous le nom familier de Sansevieria.",
  taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Dracaena", species: "Dracaena trifasciata", cultivar: "Black Gold", commonNames: ["Sansevieria Black Gold", "Langue de belle-mère Black Gold"] },
  filters: { ...defaults, temperatureMin: 10, humidityIdeal: [30, 60], watering: "faible", growthRate: "lente", variegated: true, petToxic: true, humanToxic: true },
  origin: "Cultivar horticole ; l’espèce est africaine.", habitat: "Pas d’aire sauvage attribuée au cultivar. Ses feuilles succulentes lui permettent de supporter des périodes sèches.", hybridization: "NC State répertorie Black Gold parmi les cultivars de Dracaena trifasciata. Sansevieria reste le nom horticole et la route historique Jungle.", synonyms: ["Sansevieria trifasciata ‘Black Gold’"],
  description: ["Les limbes dressés, charnus et vert foncé sont soulignés par une bordure jaune. La touffe s’étoffe par le développement de nouveaux départs.", "Black Gold ne doit pas être fusionné avec Black Jack, Black Robusta ou une forme naine sur la seule base d’une couleur sombre."],
  growth: { adultSize: "Encombrement variable selon maturité et clone ; aucune hauteur maximale propre au cultivar n’est certifiée ici.", speed: "Lente, surtout en lumière réduite", habit: "Touffe dressée à rhizomes" },
  care: { light: 4, water: 1, humidity: 1, difficulty: 1, lightText: "Une bonne lumière filtrée favorise la croissance. La tolérance à l’ombre ne signifie pas une croissance optimale dans le noir.", watering: "Laissez sécher le mélange entre deux arrosages. En hiver ou en faible lumière, le délai peut être long : observez la motte plutôt qu’un calendrier.", humidityText: "L’air ordinaire d’une pièce convient ; aucune brumisation systématique n’est nécessaire.", temperature: "Évitez le froid humide. Une pièce tempérée convient ; le repère bas de 10 °C n’est pas une garantie pour une motte mouillée.", substrate: "Mélange pour succulentes très drainant, pot percé et eau résiduelle vidée.", repotting: "Rempotez au printemps seulement si la touffe et les rhizomes saturent le contenant ; choisissez un pot stable.", fertilizing: "Peu d’engrais, uniquement pendant la croissance, selon la notice du produit.", propagation: "La division d’un rejet enraciné conserve mieux la bordure du cultivar. Les boutures de feuille peuvent perdre la panachure." },
  toxicity: { level: "Toxique à l’ingestion", summary: "À éloigner des enfants et des animaux susceptibles de mâchonner les feuilles.", details: "NC State décrit une toxicité faible liée notamment aux saponines. Faible toxicité ne signifie pas plante comestible." },
  problems: [{ title: "Base molle", cause: "Excès d’eau et pourriture possibles", advice: "Examinez les racines et corrigez le drainage ; ne rajoutez pas d’eau par réflexe." }, { title: "Rejet entièrement vert", cause: "Perte de panachure possible", advice: "Ne renommez pas la plante entière ; préservez l’étiquette et observez les nouveaux départs." }],
  comparisons: [{ name: "Dracaena trifasciata", difference: "La fiche de l’espèce donne le cadre botanique ; Black Gold désigne la sélection à bordure dorée." }],
  faq: [{ question: "Pourquoi l’URL dit-elle Sansevieria ?", answer: "Jungle conserve ce nom horticole familier pour la navigation, tout en indiquant le classement botanique dans Dracaena." }],
  sources: [source("NC State Extension — Dracaena trifasciata et Black Gold", "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/"), source("RHS — culture et division des Sansevieria", "https://www.rhs.org.uk/plants/sansevieria/growing-guide")],
});

const nidus = entry({
  slug: "nidus", genre: "asplenium", genreLabel: "Asplenium", botanicalName: "Asplenium nidus", displayName: "Nidus", family: "Aspleniaceae",
  subtitle: "La fougère nid-d’oiseau forme une couronne de frondes entières et lustrées.",
  taxonomy: { order: "Polypodiales", family: "Aspleniaceae", genus: "Asplenium", species: "Asplenium nidus", cultivar: null, commonNames: ["Fougère nid-d’oiseau"] },
  filters: { ...defaults, temperatureIdeal: [16, 22], humidityIdeal: [50, 75], watering: "régulier", habits: ["épiphyte", "dressé"], flowering: false, regions: ["Asie tropicale", "Australasie"] },
  origin: "Régions tropicales de l’Ancien Monde ; distribution détaillée dans Kew.", habitat: "Fougère notamment épiphyte des forêts humides, dont la rosette peut retenir des débris végétaux.", hybridization: "Espèce botanique acceptée. Le nom commun nid-d’oiseau couvre aussi d’autres Asplenium et ne suffit pas à les identifier.", synonyms: [],
  description: ["Les frondes simples partent d’un cœur central et portent une nervure médiane sombre. Elles ne sont pas découpées en petites folioles comme celles d’un Nephrolepis.", "Au revers des frondes adultes, les lignes brunes régulières correspondent aux sores portant les spores : ce ne sont pas automatiquement des parasites."],
  growth: { adultSize: "Rosette pouvant devenir large ; dimensions fortement liées à la maturité et aux conditions, sans mesure de sujet du Studio.", speed: "Progressive lorsque chaleur et eau restent régulières", habit: "Rosette, sans fleurs" },
  care: { light: 3, water: 4, humidity: 4, difficulty: 3, lightText: "Lumière tamisée à vive indirecte ; évitez le soleil qui décolore les frondes.", watering: "Maintenez une légère humidité dans le mélange sans saturation. Arrosez autour de la rosette plutôt que de laisser de l’eau au cœur.", humidityText: "Protégez du chauffage et des courants d’air desséchants ; une humidité régulière et de l’air renouvelé sont utiles.", temperature: "Une ambiance douce, autour de 16–22 °C, est un repère de culture. Cette fougère tropicale ne doit pas subir le gel.", substrate: "Mélange humifère et poreux pour fougères, jamais compacté, dans un contenant percé.", repotting: "Intervenez délicatement lorsque les racines occupent le volume ; préservez le cœur et ne l’enterrez pas.", fertilizing: "Apport dilué pendant la croissance ; évitez de verser l’engrais sur les jeunes frondes.", propagation: "La multiplication par spores demande chaleur, humidité et hygiène. Une fronde détachée n’est pas une bouture et une rosette unique ne se divise pas comme une touffe de Nephrolepis." },
  toxicity: uncertainToxicity,
  problems: [{ title: "Bandes brunes au revers", cause: "Sores possibles", advice: "Vérifiez leur disposition régulière avant de traiter." }, { title: "Cœur noirci", cause: "Pourriture possible", advice: "Contrôlez l’eau stagnante et aérez sans dessécher la motte." }, { title: "Bords secs", cause: "Dessèchement ou air trop chaud", advice: "Vérifiez l’humidité du mélange et éloignez la plante du radiateur." }],
  comparisons: [{ name: "Nephrolepis exaltata", difference: "Ses frondes sont divisées ; nidus porte des frondes entières." }, { name: "Asplenium australasicum", difference: "Autre espèce de fougère nid-d’oiseau, à ne pas fusionner à partir du seul nom commun." }],
  faq: [{ question: "Les lignes brunes sont-elles une maladie ?", answer: "Des sores réguliers sous une fronde mature sont normaux. Une tache irrégulière ou un cœur mou demande un autre diagnostic." }],
  sources: [powo("Asplenium nidus", "17048040-1"), source("NC State Extension — Asplenium nidus", "https://plants.ces.ncsu.edu/plants/asplenium-nidus/"), source("Flore des fougères — Asplenium nidus", "https://apps.lucidcentral.org/ferns/text/entities/asplenium_nidus.htm")],
});

const fernCare: PlantEntry["care"] = { light: 3, water: 4, humidity: 4, difficulty: 3, lightText: "Lumière filtrée, sans soleil brûlant sur les frondes.", watering: "Gardez le mélange légèrement humide et égouttez. Ne laissez ni motte totalement sèche ni eau permanente dans le cache-pot.", humidityText: "Air modérément humide, loin du chauffage, avec ventilation douce.", temperature: "Privilégiez une pièce tempérée ; 18–24 °C est un repère, pas une garantie de résistance au froid.", substrate: "Mélange pour fougères, humifère et drainant, sans tourbe si possible.", repotting: "Au printemps lorsque les racines remplissent le pot ; ne compactez pas la nouvelle motte.", fertilizing: "Apport léger en croissance, réduit en hiver ; respectez la notice et évitez une motte sèche.", propagation: "Les divisions ou stolons enracinés conservent les caractères d’un cultivar. Les spores ne garantissent pas une descendance identique ; respecter les droits applicables aux sélections protégées." };
const fernProblems = [{ title: "Frondes sèches", cause: "Air sec ou motte desséchée", advice: "Corrigez l’arrosage et éloignez le chauffage ; les parties sèches ne reverdissent pas." }, { title: "Touffe qui jaunit", cause: "Drainage, lumière ou racines à contrôler", advice: "Examinez le fond du pot avant d’augmenter l’eau ou l’engrais." }];
const fern = (moment: boolean): PlantEntry => {
  const cultivar = moment ? "Green Moment" : "Green Lady";
  return entry({
    slug: moment ? "green-moment" : "green-lady", genre: "nephrolepis", genreLabel: "Nephrolepis", botanicalName: `Nephrolepis exaltata ‘${cultivar}’`, displayName: cultivar, family: "Polypodiaceae",
    subtitle: moment ? "Une sélection de fougère de Boston au feuillage dense et à la chute de folioles réduite." : "Une fougère de Boston aux frondes souples, d’abord dressées puis arquées.",
    taxonomy: { order: "Polypodiales", family: "Polypodiaceae", genus: "Nephrolepis", species: "Nephrolepis exaltata", cultivar, commonNames: [`Fougère de Boston ${cultivar}`] },
    filters: { ...defaults, humidityIdeal: [50, 75], watering: "régulier", flowering: false, adultSizeCm: moment ? 50 : 100, habits: ["terrestre", "retombant"], regions: ["Horticulture"] },
    origin: moment ? "Sélection horticole découverte aux Pays-Bas." : "Sélection horticole ; obtenteur et lieu de sélection non établis ici.",
    habitat: "L’espèce N. exaltata est présente notamment dans les Amériques ; cela ne constitue pas une aire sauvage du cultivar.",
    hybridization: moment ? "Cultivar accepté par la RHS ; Vitro Plus le documente sous Nephrolepis exaltata. Il est issu d’une mutation de Boston Blue Bell selon sa description de sélection." : "Dénomination horticole documentée par la RHS sous N. exaltata, mais son statut de nom y reste non résolu. Elle n’est donc pas présentée comme une nouvelle espèce ou une identité taxonomique acceptée séparément.",
    synonyms: [],
    description: [moment ? "Les frondes vertes composent une touffe fournie. La sélection a été décrite pour un feuillage plus robuste et une chute réduite des folioles, non pour une absence absolue de feuilles sèches." : "Les frondes pennées sont formées de nombreuses petites divisions vertes, disposées de part et d’autre d’un axe souple. La touffe peut s’arquer au-dessus du bord du pot.", "Le classement familial suit ici Kew : Polypodiaceae. D’autres référentiels utilisent Nephrolepidaceae ou Lomariopsidaceae ; ces différences ne créent pas trois identités commerciales."],
    growth: { adultSize: moment ? "Jusqu’à environ 50 cm selon Vitro Plus, avec retombée et volume variables." : "Environ 50 cm à 1 m selon la RHS, selon âge et conditions.", speed: moment ? "Rapide en conditions favorables" : "Régulière en conditions favorables", habit: "Touffe rhizomateuse à frondes arquées" },
    care: { ...fernCare }, toxicity: uncertainToxicity, problems: fernProblems,
    comparisons: [{ name: moment ? "Green Lady" : "Green Moment", difference: moment ? "Green Lady désigne une autre sélection horticole, pas un synonyme automatique." : "Green Moment est une sélection documentée notamment pour limiter la chute des folioles." }, { name: "Asplenium nidus", difference: "Frondes entières en rosette, au lieu des frondes divisées de Nephrolepis." }],
    faq: [{ question: "Cette fougère produit-elle des fleurs ?", answer: "Non. Les fougères produisent des spores ; leurs caractères horticoles se conservent plus sûrement par multiplication végétative que par spores." }],
    sources: [powo("Nephrolepis exaltata — classement et distribution", "17160830-1"), source(`RHS — ${cultivar}`, moment ? "https://www.rhs.org.uk/plants/353292/nephrolepis-exaltata-green-moment/details" : "https://www.rhs.org.uk/plants/304353/nephrolepis-exaltata-green-lady/details"), source("NC State Extension — Nephrolepis exaltata", "https://plants.ces.ncsu.edu/plants/nephrolepis-exaltata/"), ...(moment ? [source("Vitro Plus — Green Moment", "https://www.vitroplus.nl/green-moment-ppaf")] : [])],
  });
};

const spider = (bonnie: boolean): PlantEntry => {
  const cultivar = bonnie ? "Bonnie" : "Ocean";
  return entry({
    slug: cultivar.toLowerCase(), genre: "chlorophytum", genreLabel: "Chlorophytum", botanicalName: `Chlorophytum comosum ‘${cultivar}’`, displayName: cultivar, family: "Asparagaceae",
    subtitle: bonnie ? "Un Chlorophytum compact aux feuilles bouclées et au centre clair." : "Un Chlorophytum compact aux feuilles vertes bordées de crème.",
    taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Chlorophytum", species: "Chlorophytum comosum", cultivar, commonNames: [`Plante araignée ${cultivar}`] },
    filters: { ...defaults, temperatureMin: 10, adultSizeCm: 50, variegated: true, petToxic: false, habits: ["terrestre", "retombant"] },
    origin: "Cultivar horticole de Chlorophytum comosum, espèce africaine.", habitat: "Pas de distribution naturelle propre attribuée au cultivar.", hybridization: "Cultivar reconnu par la RHS, et non une espèce supplémentaire.", synonyms: [],
    description: [bonnie ? "Bonnie se reconnaît à sa silhouette ramassée et à ses feuilles recourbées. Une bande claire parcourt le centre du limbe vert, dont les boucles donnent du volume à la touffe." : "Ocean porte des feuilles plus courtes et trapues que certaines formes classiques. Le centre est vert ; les marges crème dessinent la panachure.", "De petites fleurs blanches peuvent apparaître sur de longues hampes, puis des plantules. Leur présence dépend de la maturité et des conditions de culture."],
    growth: { adultSize: "Environ 10 à 50 cm pour la touffe selon la RHS ; les hampes et plantules peuvent retomber plus loin.", speed: "Régulière en saison favorable", habit: "Touffe arquée, plantules retombantes" },
    care: { light: 3, water: 3, humidity: 2, difficulty: 1, lightText: "Lumière indirecte ; évitez le soleil estival brûlant.", watering: "Arrosez régulièrement mais videz l’eau résiduelle. Ajustez au séchage de la motte.", humidityText: "Évitez la proximité immédiate d’un radiateur.", temperature: "Cultivez hors gel dans une pièce tempérée ; les repères du filtre ne sont pas des seuils de survie.", substrate: "Terreau polyvalent sans tourbe, drainant, en pot percé.", repotting: "Contrôlez les racines tous les deux à trois ans ; divisez ou rempotez si nécessaire.", fertilizing: "Fertilisez modérément en croissance, selon la notice, sans multiplier les apports.", propagation: "Enracinez une plantule ou divisez une touffe ; le semis ne garantit pas le cultivar. Respectez les droits applicables aux sélections protégées." },
    toxicity: { level: "Non toxique pour chats et chiens selon l’ASPCA", summary: "L’ASPCA classe Chlorophytum comosum comme non toxique pour les chats et les chiens.", details: "Cette référence concerne l’espèce et ne vaut pas recommandation d’ingestion. Aucun usage alimentaire ou garantie spécifique pour l’humain n’est avancé." },
    problems: [{ title: "Pointes brunes", cause: "Arrosage, air chaud ou sels à vérifier", advice: "Contrôlez les conditions avant de multiplier les engrais." }, { title: "Feuilles pâles ou brûlées", cause: "Exposition inadaptée possible", advice: "Écartez du soleil brûlant sans placer la plante dans l’obscurité." }],
    comparisons: [{ name: bonnie ? "Ocean" : "Bonnie", difference: bonnie ? "Ocean porte une marge crème et des feuilles moins bouclées." : "Bonnie porte une zone centrale claire et un feuillage bouclé." }, { name: "Chlorophytum comosum", difference: "L’espèce fournit le cadre botanique ; les cultivars conservent leurs fiches distinctes." }],
    faq: [{ question: `Comment conserver les caractères de ${cultivar} ?`, answer: "La multiplication végétative par plantule ou division est préférable au semis, qui ne garantit pas les mêmes caractères." }],
    sources: [source(`RHS — ${cultivar}`, bonnie ? "https://www.rhs.org.uk/plants/191491/chlorophytum-comosum-bonnie-v/details" : "https://www.rhs.org.uk/plants/312670/chlorophytum-comosum-ocean/details"), source("RHS — culture des plantes araignées", "https://www.rhs.org.uk/plants/spider-plants/growing-guide"), source("ASPCA — Chlorophytum comosum", "https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/spider-plant")],
  });
};

const recurvata = entry({
  slug: "recurvata", genre: "beaucarnea", genreLabel: "Beaucarnea", botanicalName: "Beaucarnea recurvata", displayName: "Recurvata", family: "Asparagaceae",
  subtitle: "Le pied-d’éléphant mexicain, au tronc renflé et aux longues feuilles retombantes.",
  taxonomy: { order: "Asparagales", family: "Asparagaceae", genus: "Beaucarnea", species: "Beaucarnea recurvata", cultivar: null, commonNames: ["Pied-d’éléphant", "Arbre bouteille", "Nolina recurvata"] },
  filters: { ...defaults, temperatureMin: 10, humidityIdeal: [30, 60], light: "soleil", watering: "faible", growthRate: "lente", adultSizeCm: 250, petToxic: false, regions: ["Mexique"] },
  origin: "Mexique", habitat: "Milieux rocheux et forêts basses à saison sèche ; le renflement de la tige stocke l’eau.", hybridization: "Espèce botanique, également connue sous le synonyme Nolina recurvata. Malgré son nom anglais, ce n’est pas un palmier.", synonyms: ["Nolina recurvata"],
  description: ["La base élargie du tronc porte une couronne de feuilles étroites qui se recourbent et retombent. La silhouette change lentement avec l’âge.", "La floraison en panicules de petites fleurs claires reste rare en intérieur. Cette fiche documentaire n’identifie pas les plantes d’un arrivage portant seulement l’étiquette Beaucarnea."],
  growth: { adultSize: "Environ 1,5 à 2,5 m à long terme en culture selon la RHS ; beaucoup plus grand en milieu tropical. Un petit pot ne prédit pas la taille adulte.", speed: "Lente", habit: "Tige renflée, couronne retombante" },
  care: { light: 5, water: 1, humidity: 1, difficulty: 2, lightText: "Fenêtre très lumineuse, avec soleil après acclimatation progressive.", watering: "Arrosez puis laissez sécher le mélange. Réduisez fortement en hiver, surtout si lumière et température baissent.", humidityText: "L’air ordinaire d’une pièce convient ; évitez les soins humides réservés aux fougères tropicales.", temperature: "En climat froid, gardez-le en contenant et hivernez à l’intérieur. Le repère de 10 °C ne justifie pas une exposition au gel.", substrate: "Mélange pour cactées et succulentes, très drainant, avec pot percé.", repotting: "Rempotez lorsque nécessaire dans un contenant stable ; conservez le renflement au-dessus du mélange.", fertilizing: "Apport modéré durant la croissance, selon la notice, et pas pour tenter d’accélérer artificiellement une plante naturellement lente.", propagation: "Le semis est possible à chaud. Une simple feuille ne donne pas un nouveau pied ; les opérations sur les rejets demandent un départ viable et des soins adaptés." },
  toxicity: { level: "Non toxique pour chats et chiens selon l’ASPCA", summary: "L’ASPCA classe Beaucarnea recurvata comme non toxique pour chats, chiens et chevaux.", details: "Ce classement ne fait pas de la plante un aliment et ne s’étend pas à une plante non identifiée vendue sous un nom générique." },
  problems: [{ title: "Base molle", cause: "Pourriture possible", advice: "Contrôlez motte et drainage avant tout arrosage supplémentaire." }, { title: "Pointes sèches", cause: "Stress hydrique ou conditions à contrôler", advice: "Observez la motte et les nouvelles feuilles, sans inonder par réflexe." }, { title: "Amas blancs", cause: "Cochenilles possibles", advice: "Inspectez la couronne et isolez le sujet atteint." }],
  comparisons: [{ name: "Yucca", difference: "Autre genre des Asparagaceae ; un nom de plante à tronc ne suffit pas à les confondre." }],
  faq: [{ question: "Beaucarnea sur une facture signifie-t-il recurvata ?", answer: "Non. Le genre comprend plusieurs espèces ; la présence de cette fiche ne permet pas de compléter une étiquette fournisseur imprécise." }],
  sources: [source("RHS — Beaucarnea recurvata et synonymie", "https://www.rhs.org.uk/plants/1993/beaucarnea-recurvata/details"), source("NC State Extension — habitat et culture", "https://plants.ces.ncsu.edu/plants/beaucarnea-recurvata/"), source("Iowa State Extension — multiplication des plantes d’intérieur", "https://yardandgarden.extension.iastate.edu/how-to/propagating-houseplants"), source("ASPCA — Beaucarnea recurvata", "https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/pony-tail")],
});

export const stockIdentityPlants: PlantEntry[] = [imperialGreen, callistophylla, blackGold, nidus, fern(false), fern(true), spider(true), spider(false), recurvata];
