import type { PlantEntry } from "./types.ts";

export type VerifiedGroupMedia = PlantEntry["gallery"][number] & {
  rights: "verified";
};

export const verifiedGroupMediaByGenre: Readonly<Record<string, VerifiedGroupMedia>> = {
  agave: {
    src:"/hub-media-wave-5-v1/hub-agave.webp",alt:"Collection botanique de rosettes d’Agave aux formes variées",caption:"Collection d’Agave · Kenizzer · CC BY-SA 4.0.",width:1600,height:1200,rights:"verified",
    license:{status:"verified",creator:"Kenizzer",license:"CC BY-SA 4.0",licenseUrl:"https://creativecommons.org/licenses/by-sa/4.0/",sourceUrl:"https://commons.wikimedia.org/wiki/File:Agave_collection_summer_2020.jpg",registryPath:"/credits-images",note:"Hero Wave 5 · collection de plusieurs Agave ; redimensionnement et conversion WebP."},
  },
  equisetum: {
    src:"/hub-media-wave-5-v1/hub-equisetum.webp",alt:"Tableau dense de tiges verticales d’Equisetum hyemale",caption:"Equisetum hyemale au Jardin botanique de Brasília · Daderot · CC0 1.0.",width:1400,height:1867,rights:"verified",
    license:{status:"verified",creator:"Daderot",license:"CC0 1.0",licenseUrl:"https://creativecommons.org/publicdomain/zero/1.0/",sourceUrl:"https://commons.wikimedia.org/wiki/File:Equisetum_hyemale_-_Jardim_Bot%C3%A2nico_de_Bras%C3%ADlia_-_DSC09678.JPG",registryPath:"/credits-images",note:"Hero Wave 5 · peuplement dense d’une espèce du genre ; redimensionnement et conversion WebP."},
  },
  maranta: {
    src:"/hub-media-wave-5-v1/hub-maranta.webp",alt:"Tableau de feuilles dessinées de Maranta leuconeura ‘Tricolor’",caption:"Maranta leuconeura ‘Tricolor’ · Krzysztof Ziarnek, Kenraiz · CC BY-SA 4.0.",width:1600,height:1143,rights:"verified",
    license:{status:"verified",creator:"Krzysztof Ziarnek, Kenraiz",license:"CC BY-SA 4.0",licenseUrl:"https://creativecommons.org/licenses/by-sa/4.0/",sourceUrl:"https://commons.wikimedia.org/wiki/File:Maranta_leuconeura_%27Tricolor%27_kz01.jpg",registryPath:"/credits-images",note:"Hero Wave 5 · tableau horizontal de nombreuses feuilles d’une espèce du genre ; redimensionnement et conversion WebP."},
  },
  fatsia: {
    src: "/hub-media-wave-4-v1/fatsia.webp",
    alt: "Tableau de feuilles palmées de Fatsia japonica en fructification",
    caption: "Fatsia japonica au Jardin botanique royal de Madrid · Dinkum · CC0 1.0.",
    width: 1600,
    height: 980,
    rights: "verified",
    license: {
      status: "verified", creator: "Dinkum", license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Fatsia_japonica_leaves.jpg",
      registryPath: "/credits-images",
      note: "Hero Wave 4 · source paysage montrant de nombreuses feuilles de Fatsia japonica ; redimensionnement et conversion WebP.",
    },
  },
  ensete: {
    src: "/hub-media-wave-4-v1/ensete.webp",
    alt: "Ensemble de grandes feuilles nervurées d’Ensete ventricosum",
    caption: "Ensete ventricosum au Walter Sisulu Botanical Garden · Rotational · domaine public.",
    width: 1600,
    height: 2400,
    rights: "verified",
    license: {
      status: "verified", creator: "Rotational", license: "Domaine public",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ensete_ventricosum00.jpg",
      registryPath: "/credits-images",
      note: "Hero Wave 4 · plusieurs feuilles d’Ensete ventricosum au jardin botanique ; recadrage responsive, redimensionnement et conversion WebP.",
    },
  },
  pilea: {
    src: "/pilea-peperomioides-plante.jpg",
    alt: "Pilea peperomioides aux feuilles rondes portées par de longs pétioles",
    caption: "Pilea peperomioides · Husky · CC0 1.0.",
    width: 1280,
    height: 1707,
    rights: "verified",
    license: {
      status: "verified",
      creator: "Husky",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pilea_peperomioides_Chinese_money_plant.jpg",
      registryPath: "/credits-images",
      note: "Média déjà conservé localement et présent dans le registre de crédits Jungle ; réutilisation hub vérifiée le 31 août 2026.",
    },
  },
  peperomia: {
    src: "/peperomia-argyreia-feuillage.jpg",
    alt: "Feuillage argenté et rayé de Peperomia argyraea",
    caption: "Peperomia argyraea, publié sous son synonyme Peperomia argyreia · Mokkie · CC BY-SA 4.0.",
    width: 1280,
    height: 720,
    rights: "verified",
    license: {
      status: "verified",
      creator: "Mokkie",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Watermelon_Peperomia_(Peperomia_argyreia).jpg",
      registryPath: "/credits-images",
      note: "Média déjà conservé localement et présent dans le registre de crédits Jungle ; nom accepté Peperomia argyraea vérifié le 31 août 2026.",
    },
  },
  cactus: {
    src: "/cactus-collection-serre.jpg",
    alt: "Collection de Cactaceae globulaires et colonnaires en serre",
    caption: "Collection de cactus en serre · Anita Austvika · Licence Unsplash.",
    width: 1800,
    height: 2700,
    rights: "verified",
    license: {
      status: "verified",
      creator: "Anita Austvika",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      sourceUrl: "https://unsplash.com/photos/a-variety-of-cactus-plants-in-a-greenhouse-Ip9vn5h-aSE",
      registryPath: "/credits-images",
      note: "Média de collection Cactaceae déjà conservé localement et présent dans le registre de crédits Jungle ; usage limité au hub familial.",
    },
  },
  epipremnum: {
    src: "/epipremnum-aureum-pothos.jpg",
    alt: "Epipremnum aureum grimpant au feuillage panaché jaune et vert",
    caption: "Epipremnum aureum · Filo gèn’ · CC BY-SA 4.0.",
    width: 1280,
    height: 1707,
    rights: "verified",
    license: {
      status: "verified",
      creator: "Filo gèn’",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Epipremnum_aureum_(Golden_pothos).jpg",
      registryPath: "/credits-images",
      note: "Média déjà conservé localement et présent dans le registre de crédits Jungle ; réutilisation hub vérifiée le 31 août 2026.",
    },
  },
  philodendron: {
    src: "/philodendron-hastatum-feuillage.jpg",
    alt: "Ensemble de feuilles argentées lancéolées de Philodendron hastatum",
    caption: "Philodendron hastatum · Krzysztof Ziarnek, Kenraiz · CC BY-SA 4.0.",
    width: 1280,
    height: 853,
    rights: "verified",
    license: {
      status: "verified",
      creator: "Krzysztof Ziarnek, Kenraiz",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Philodendron_hastatum_kz2.jpg",
      registryPath: "/credits-images",
      note: "Source naturellement horizontale montrant plusieurs feuilles ; identité et droits déjà enregistrés dans Jungle, validation hero du 1er septembre 2026.",
    },
  },
};
