import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = { title: "Programme de fidélité | Tibaldo Jungle Lille", description: "Découvrez les avantages du programme fidélité gratuit Tibaldo Jungle à Lille.", alternates: { canonical: "/programme-fidelite" }, robots: { index: false, follow: false } };
const sections: LegalSection[] = [
  { id: "adhesion", title: "Adhésion gratuite et compte personnel", content: <><p>Le programme est gratuit, facultatif, nominatif et réservé aux personnes physiques. Un seul compte est autorisé par personne. L’adhésion nécessite les informations strictement utiles à l’identification et au suivi des avantages.</p><p>Le compte et les récompenses ne peuvent être cédés, vendus, regroupés entre plusieurs personnes ni utilisés à des fins professionnelles ou frauduleuses.</p></> },
  { id: "cumul-euros", title: "10 € offerts tous les 200 €", content: <><p>Chaque tranche complète de 200 € TTC d’achats éligibles enregistrés sur le compte génère 10 € de réduction. L’éventuel montant excédant la tranche est conservé pour la tranche suivante.</p><p>La réduction est utilisable lors d’un achat ultérieur. Elle n’est pas convertible en espèces et ne donne lieu à aucun rendu de monnaie. Les achats annulés, remboursés, réglés par une récompense ou correspondant à l’achat d’une carte cadeau ne génèrent pas de nouveau cumul.</p></> },
  { id: "passages", title: "Une petite plante tous les 10 passages", content: <><p>Un passage correspond à une visite distincte donnant effectivement lieu à un achat encaissé. Tous les dix passages éligibles, le membre peut choisir une petite plante d’une valeur commerciale indicative d’environ 5 €, dans une sélection déterminée par Tibaldo Jungle selon les stocks.</p><p>Le fractionnement artificiel d’un même achat en plusieurs tickets, paiements ou passages n’est pas pris en compte. La récompense n’est ni échangeable contre une autre référence hors sélection ni convertible en argent.</p></> },
  { id: "anniversaire", title: "Avantage anniversaire", content: <><p>Le membre bénéficie de 10 % de remise le jour exact de son anniversaire, sur une seule vente et dans la limite de 1 000 € d’achats, soit 100 € de réduction maximale.</p><p>Le titulaire doit être physiquement présent et présenter une pièce d’identité originale. Aucune copie n’est conservée pour ce contrôle. L’avantage est personnel, non transmissible, non reportable et utilisable une seule fois. Pour une personne née le 29 février, l’avantage est proposé le 1er mars lors des années non bissextiles.</p><p>L’avantage anniversaire n’est pas cumulable avec une promotion, une récompense fidélité ou un autre code de réduction sur les mêmes articles ; l’avantage le plus favorable au client est appliqué.</p></> },
  { id: "fonctionnement", title: "Enregistrement et rectification", content: <><p>Les achats et passages sont enregistrés au moment du paiement lorsque le compte est identifié. Le membre peut demander la consultation et la rectification de son historique sur présentation d’une preuve d’achat.</p><p>Les retours, annulations, erreurs d’encaissement et remboursements entraînent l’ajustement correspondant du cumul et des récompenses. Tibaldo Jungle conserve un historique permettant d’expliquer les mouvements.</p></> },
  { id: "fraude", title: "Utilisation loyale et suspension", content: <><p>Tibaldo Jungle peut suspendre temporairement un compte en cas d’anomalie sérieuse, de duplication, de fraude présumée ou d’utilisation manifestement contraire aux présentes règles, le temps de procéder aux vérifications. Le membre peut présenter ses observations.</p><p>Une clôture et l’annulation des avantages obtenus frauduleusement ne peuvent intervenir qu’après examen des éléments disponibles, sans préjudice des autres droits de Tibaldo Jungle.</p></> },
  { id: "donnees", title: "Données personnelles et communications", content: <><p>Le programme implique le traitement de l’identité, des coordonnées choisies, de la date de naissance, des achats, passages et récompenses. Ces données servent uniquement à administrer le programme et à prévenir les abus, selon la <a href="/politique-confidentialite">Politique de confidentialité</a>.</p><p>L’adhésion ne vaut jamais consentement à recevoir des e-mails, SMS ou appels publicitaires. Ce choix fait l’objet d’une demande distincte, libre et révocable.</p></> },
  { id: "evolution", title: "Durée, modification et arrêt du programme", content: <><p>Le programme est proposé sans durée déterminée. Tibaldo Jungle peut le faire évoluer ou l’arrêter pour un motif légitime, avec une information préalable raisonnable permettant, sauf impossibilité, l’utilisation des récompenses déjà acquises.</p><p>Une modification ne peut supprimer rétroactivement un avantage déjà utilisé ni porter atteinte aux droits légaux du membre.</p></> },
];
export default function LoyaltyPage() { return <LegalPage eyebrow="La Jungle vous remercie" title="Programme de fidélité" intro="Deux façons simples de faire grandir vos avantages au fil de vos visites." updated="7 août 2026" warning={<><strong>Règles particulières</strong><p>Le 29 février est reporté au 1er mars les années non bissextiles. Les promotions et avantages ne se cumulent pas : le plus favorable est appliqué.</p></>} sections={sections} />; }
