import type { JungleEvent } from "./types";

export const openingEvent: JungleEvent = {
  id: "opening-2026",
  slug: "ouverture-tibaldo-jungle-lille",
  title: "Ouverture du Studio Végétal – Tibaldo Jungle à Lille",
  category: "ouverture",
  status: "published",
  startAt: "2026-09-26T10:00:00+02:00",
  endAt: "2026-09-26T19:00:00+02:00",
  venueName: "Studio Végétal – Tibaldo Jungle",
  address: "3 place de l’Arbonnoise",
  postalCode: "59000",
  city: "Lille",
  excerpt: "Que faire à Lille le 26 septembre 2026 ? Découvrez l’ouverture du Studio Végétal – Tibaldo Jungle : plantes rares, conseils, substrats et rempotage gratuit.",
  description: "Le samedi 26 septembre 2026, Studio Végétal – Tibaldo Jungle ouvre officiellement ses portes au 3 place de l’Arbonnoise à Lille. Cette journée d’inauguration gratuite est pensée comme une rencontre autour du vivant, au cœur de la métropole lilloise : découvrir une sélection de plantes d’intérieur rares et exotiques, rencontrer un passionné, comprendre les besoins de ses plantes et visiter une nouvelle adresse végétale à Lille.\n\nRomain vous accueille de 10 h à 19 h pour présenter le projet, les plantes disponibles, les substrats en vrac et le service de rempotage gratuit proposé toute l’année. Cette sortie végétale du 26 septembre est accessible aux curieux comme aux collectionneurs.",
  program: [
    { time: "10:00", title: "Ouverture des portes", description: "Première découverte du Studio, de la sélection végétale et des espaces." },
    { time: "11:30", title: "Rencontre autour des plantes rares", description: "Échanges libres sur les arrivages, la culture et l’acclimatation à Lille." },
    { time: "14:00", title: "Démonstrations de rempotage", description: "Comprendre les racines, choisir le bon pot et composer un substrat adapté." },
    { time: "Toute la journée", title: "Conseils personnalisés", description: "Venez avec une photo de votre intérieur ou de votre plante pour recevoir un conseil sincère." },
  ],
  faq: [
    { question: "L’entrée est-elle gratuite ?", answer: "Oui, l’inauguration est ouverte librement au public pendant les horaires indiqués." },
    { question: "Faut-il réserver ?", answer: "Aucune réservation n’est nécessaire pour découvrir la boutique. Les éventuels ateliers avec places limitées seront signalés séparément." },
    { question: "Comment indiquer ma présence à l’ouverture ?", answer: "Rendez-vous sur la page Facebook Tibaldo Jungle, ouvrez la publication ou l’événement consacré à l’inauguration et indiquez « Participe » ou « Intéressé ». Cela nous aide à préparer votre accueil et vous permet de recevoir les dernières informations avant le 26 septembre." },
    { question: "Que faire à Lille le 26 septembre 2026 ?", answer: "L’ouverture de Tibaldo Jungle est une sortie gratuite à Lille consacrée aux plantes rares, aux conseils d’entretien, aux substrats et au rempotage. Le Studio est ouvert de 10 h à 19 h au 3 place de l’Arbonnoise, près du centre de Lille." },
    { question: "L’événement convient-il aux familles et aux débutants ?", answer: "Oui. La journée est ouverte aux familles, aux passionnés et aux personnes qui découvrent les plantes d’intérieur. Les conseils sont accessibles, personnalisés et sans jargon inutile." },
    { question: "Puis-je apporter une plante à rempoter ?", answer: "Oui. Le rempotage est gratuit toute l’année ; seuls le pot et les matières utilisées sont facturés lorsqu’ils sont nécessaires." },
    { question: "Comment venir à Tibaldo Jungle ?", answer: "Le Studio se situe au 3 place de l’Arbonnoise, 59000 Lille. Le bouton itinéraire ouvre directement la navigation Google Maps." },
    { question: "Les animaux sont-ils acceptés ?", answer: "Les animaux calmes et tenus sont les bienvenus, dans le respect des plantes et des autres visiteurs." },
  ],
  gallery: [
    { src: "/opening-jungle.jpg", alt: "Univers végétal de l’ouverture du Studio Végétal TIBALDO Jungle à Lille", caption: "TIBALDO Jungle — Studio Végétal, nouvelle boutique de plantes à Lille." },
    { src: "/hero-jungle.jpg", alt: "Collection de plantes tropicales Tibaldo Jungle", caption: "Plantes d’intérieur, raretés et grands spécimens." },
    { src: "/advice-rempotage.jpg", alt: "Service de rempotage de plantes à Lille", caption: "Le rempotage est gratuit toute l’année au Studio." },
  ],
  coverImage: "/opening-jungle.jpg",
  facebookUrl: "https://www.facebook.com/events/895747596492933/",
  instagramUrl: "https://www.instagram.com/tibaldojungle",
  mapsUrl: "https://www.google.com/maps/dir/?api=1&destination=3%20place%20de%20l%27Arbonnoise%2059000%20Lille",
  registrationUrl: null,
  videoUrl: null,
  seoTitle: "Ouverture du Studio Végétal à Lille — 26 septembre 2026",
  seoDescription: "Que faire à Lille le 26 septembre 2026 ? Découvrez l’ouverture gratuite du Studio Végétal – Tibaldo Jungle, avec plantes rares, conseils et rempotage.",
  seoKeywords: ["que faire à Lille", "sortie Lille septembre 2026", "événement Lille 26 septembre 2026", "événement gratuit Lille", "activité Lille", "sortie famille Lille", "agenda Lille", "événement plantes Lille", "ouverture boutique Lille", "ouverture boutique plantes Lille", "nouvelle boutique Lille", "boutique plantes Lille", "plantes rares Lille", "plantes exotiques Lille", "plantes intérieur Lille", "rempotage Lille", "substrats Lille", "Studio Végétal Lille", "événement métropole lilloise", "sortie Nord", "Tibaldo Jungle ouverture"],
  publishedAt: "2026-08-07T08:00:00+02:00",
  archivedAt: null,
  createdAt: "2026-08-07T08:00:00+02:00",
  updatedAt: "2026-08-11T20:00:00+02:00",
  sortOrder: 100,
};

export const eventFallbacks = [openingEvent];
