import type { Metadata } from "next";
import { plants } from "@/lib/plants/catalog";
import GoldenGenusHub, { type GoldenGroupGuide } from "../GoldenGenusHub";

const origin = "https://jungle.tibaldo.fr";
const bananaPlants = plants.filter((plant) => plant.genre === "musa" || plant.genre === "ensete");
const guide: GoldenGroupGuide = {
  name: "Bananiers", image: bananaPlants.find((plant) => plant.gallery[0])?.gallery[0].src ?? "/photo-reelle-a-venir.svg", imageAlt: "Feuillage réel de bananier documenté dans Jungle", heroSubtitle: "Musa et Ensete : des silhouettes proches, mais des racines, des rejets et des hivernages qui ne se conduisent pas de la même façon.",
  care: { difficulty: 3, light: 5, water: 4, humidity: 3, substrate: "Riche, stable et drainant", nutrition: "Soutenue pendant la croissance" },
  lead: "Un bananier est une grande plante herbacée, pas un arbre. Son pseudo-tronc est formé par les gaines des feuilles. Sous terre, les Musa sont souvent rhizomateux et capables de rejeter, tandis que les Ensete restent normalement solitaires.",
  origin: "Cette différence commande la multiplication, la place nécessaire et l’hivernage. La rusticité ne se résume jamais à un chiffre : feuille, pseudo-tronc et rhizome n’ont pas la même résistance, et l’humidité hivernale peut être aussi décisive que le froid.",
  facts: [{ label: "Lumière", value: "Généreuse, soleil acclimaté" }, { label: "Vent", value: "Situation abritée" }, { label: "Eau", value: "Abondante en croissance" }, { label: "Hiver", value: "Conduite selon le taxon" }],
  sections: [{ title: "Lumière et vent", text: "Une lumière généreuse soutient les grandes feuilles. L’acclimatation au soleil et la protection contre les rafales limitent les déchirures." }, { title: "Eau et nutrition", text: "Les apports sont abondants en croissance, puis diminuent nettement avec la température et la lumière." }, { title: "Sol et pot", text: "Un mélange riche mais drainant, un pot percé et un volume stable conviennent à ces plantes rapidement lourdes." }, { title: "Hiver", text: "Pailler une souche rustique et rentrer un sujet sensible ne sont pas des gestes équivalents : le taxon doit être identifié." }],
  problems: [{ title: "Feuilles déchirées", text: "Le vent marque naturellement les grands limbes ; vérifiez l’exposition avant de chercher une maladie." }, { title: "Croissance arrêtée", text: "Le froid et la baisse de lumière ralentissent fortement les bananiers." }, { title: "Rhizome ou base molle", text: "Froid et excès d’eau pendant le repos peuvent provoquer une pourriture." }, { title: "Feuilles pâles", text: "En croissance active, contrôlez lumière, nutrition et volume racinaire." }],
  faq: [{ question: "Peut-on cultiver un bananier dehors à Lille ?", answer: "Oui selon le taxon et la saison. Musa basjoo est le candidat le plus logique en pleine terre protégée ; les formes sensibles sont rentrées hors gel." }, { question: "Musa et Ensete rejettent-ils de la même façon ?", answer: "Non. Les Musa sont souvent rhizomateux et capables de rejeter ; les Ensete restent normalement solitaires." }, { question: "Pourquoi les feuilles se déchirent-elles ?", answer: "Leur grande surface est sensible au vent. Une situation abritée limite ce phénomène sans le supprimer complètement." }, { question: "Quand rentrer un bananier en pot ?", answer: "Avant les froids automnaux, selon la sensibilité du taxon et les conditions de l’emplacement." }],
  sources: [{ label: "Kew Science — Musa", url: "https://powo.science.kew.org/" }, { label: "Kew Science — Ensete", url: "https://powo.science.kew.org/" }],
};

export const metadata: Metadata = { title: "Bananiers : entretien, Musa, Ensete et hivernage", description: "Guide des bananiers : différences entre Musa et Ensete, culture en pot ou pleine terre, eau, substrat, vent, froid et hivernage dans le Nord.", alternates: { canonical: "/plantes/bananiers" }, robots: { index: false, follow: false, nocache: true }, openGraph: { title: "Bananiers : comprendre Musa et Ensete", description: "Culture, entretien, rusticité et comparaison de bananiers documentés par Jungle.", type: "article" } };

export default function BananiersPage() {
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", "@id": `${origin}/plantes/bananiers#page`, name: "Bananiers : Musa et Ensete", url: `${origin}/plantes/bananiers`, description: metadata.description }, { "@type": "ItemList", numberOfItems: bananaPlants.length, itemListElement: bananaPlants.map((plant, index) => ({ "@type": "ListItem", position: index + 1, name: plant.botanicalName, url: `${origin}/plantes/${plant.genre}/${plant.slug}` })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: origin }, { "@type": "ListItem", position: 2, name: "Plantes", item: `${origin}/plantes` }, { "@type": "ListItem", position: 3, name: "Bananiers", item: `${origin}/plantes/bananiers` }] }] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><GoldenGenusHub genre="bananiers" title="Bananiers" label="Univers horticole · Musaceae" guide={guide} plants={bananaPlants} additionalStory={[{ title: "Lille et le Nord", text: "Le climat lillois associe gels possibles, faible lumière hivernale, vent et périodes humides. En pleine terre, choisissez un endroit abrité et un sol qui évacue l’eau." }, { title: "Transition saisonnière", text: "En pot, anticipez la rentrée avant l’automne. Au printemps, attendez le réchauffement du sol avant de reprendre franchement eau et engrais." }]} /></>;
}
