import Link from "next/link";
import type { Metadata } from "next";
import LegalPage, { CompanyIdentity, type LegalSection } from "../LegalPage";
export const metadata: Metadata = { title: "Mentions légales | Studio Végétal Tibaldo Jungle", description: "Mentions légales du site officiel Studio Végétal Tibaldo Jungle à Lille.", alternates: { canonical: "/mentions-legales" }, robots: { index: false, follow: false } };
const sections: LegalSection[] = [
  { id: "editeur", title: "Éditeur du site", content: <><CompanyIdentity /><p>Nom du site : Studio Végétal — Tibaldo Jungle<br />Adresse : <a href="https://jungle.tibaldo.fr">https://jungle.tibaldo.fr</a></p></> },
  { id: "publication", title: "Direction de la publication", content: <><p>Directeur de la publication : <strong>Romain Pruvost</strong>, entrepreneur individuel.</p><p>Contact éditorial : <a href="mailto:jungle@tibaldo.fr">jungle@tibaldo.fr</a>.</p></> },
  { id: "hebergement", title: "Hébergement et nom de domaine", content: <><p><strong>OpenAI Ireland Limited — ChatGPT Sites</strong><br />1st Floor, The Liffey Trust Centre<br />117-126 Sheriff Street Upper<br />Dublin 1, D01 YC43, Irlande<br />Numéro d’entreprise : 737350<br /><a href="https://openai.com" target="_blank" rel="noreferrer">openai.com</a></p><p>Le nom de domaine et sa configuration DNS sont gérés auprès de <strong>Hostinger International Limited</strong>, 61 Lordou Vironos Street, 6023 Larnaca, Chypre. Hostinger n’héberge pas actuellement le contenu de ce site vitrine.</p></> },
  { id: "propriete", title: "Propriété intellectuelle", content: <><p>La structure du site, les textes originaux, signes distinctifs, compositions graphiques, photographies appartenant à Tibaldo Jungle et éléments créés pour le site sont protégés par les droits applicables. Toute reproduction ou adaptation substantielle nécessite une autorisation préalable, sauf exception légale.</p><p>Les photographies provenant de tiers sont utilisées selon leurs licences ou autorisations et sont identifiées sur la page <Link href="/credits-images">Crédits photos</Link>.</p></> },
  { id: "contenus", title: "Informations horticoles", content: <><p>Les contenus botaniques et conseils d’entretien sont fournis à titre pédagogique. Les besoins d’un végétal varient selon le spécimen, son état, le climat intérieur et les pratiques de culture. Ils ne remplacent pas un diagnostic individualisé et ne garantissent pas un résultat déterminé.</p><p>Tibaldo Jungle s’efforce de maintenir les informations à jour et corrige les erreurs qui lui sont signalées.</p></> },
  { id: "liens", title: "Liens et services tiers", content: <><p>Le site peut proposer des liens vers Google Maps, Plans, Waze, Facebook, Instagram ou d’autres services. Ces services sont indépendants et appliquent leurs propres conditions et politiques de confidentialité.</p><p>Tibaldo Jungle n’exerce aucun contrôle sur la disponibilité ou les contenus externes, sans que cela limite sa responsabilité pour ses propres choix éditoriaux ou obligations légales.</p></> },
  { id: "donnees", title: "Données personnelles", content: <><p>Les modalités de traitement et les droits sont présentés dans la <Link href="/politique-confidentialite">Politique de confidentialité</Link>.</p></> },
  { id: "signalement", title: "Contact et signalement", content: <><p>Pour signaler une erreur, un contenu ou une difficulté d’accès : <a href="mailto:jungle@tibaldo.fr">jungle@tibaldo.fr</a> ou 07 43 72 70 79.</p></> },
];
export default function LegalNoticesPage() { return <LegalPage eyebrow="Informations légales" title="Mentions légales" intro="L’identité de l’éditeur et les règles applicables au site officiel Tibaldo Jungle." updated="7 août 2026" sections={sections} />; }
