CREATE TABLE `events` (
	`id` text PRIMARY KEY NOT NULL,
	`slug` text NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`start_at` text NOT NULL,
	`end_at` text,
	`venue_name` text NOT NULL,
	`address` text NOT NULL,
	`postal_code` text NOT NULL,
	`city` text NOT NULL,
	`excerpt` text NOT NULL,
	`description` text NOT NULL,
	`program_json` text DEFAULT '[]' NOT NULL,
	`faq_json` text DEFAULT '[]' NOT NULL,
	`gallery_json` text DEFAULT '[]' NOT NULL,
	`cover_image` text NOT NULL,
	`facebook_url` text,
	`instagram_url` text,
	`maps_url` text,
	`registration_url` text,
	`video_url` text,
	`seo_title` text NOT NULL,
	`seo_description` text NOT NULL,
	`seo_keywords` text DEFAULT '' NOT NULL,
	`published_at` text,
	`archived_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `events_slug_unique` ON `events` (`slug`);