import { Arrow, SiteHeader } from "../../SiteChrome";
import ScientificName from "../../plantes/ScientificName";
import { languageTags, localizedPath, type TranslatedLocale } from "@/lib/i18n/config";
import { getWave1Family, getWave1Genre, getWave1Plant } from "@/lib/i18n/wave1";

const ui = {
  en: { encyclopedia: "Plant encyclopedia", home: "Home", plants: "Plants", family: "Family", genus: "Genus", species: "Species", cultivar: "Cultivar", identity: "Botanical identity", care: "Complete care", toxicity: "Toxicity and safety", problems: "Problems and diagnosis", comparisons: "Similar plants", gallery: "Plant gallery", advice: "Tibaldo Jungle advice", faq: "Frequently asked questions", sources: "Sources and caution", origin: "Origin", habitat: "Natural habitat", status: "Botanical status", growth: "Growth", adult: "Adult size", light: "Light", water: "Watering", humidity: "Humidity", temperature: "Temperature", substrate: "Substrate", repotting: "Repotting", fertilizing: "Feeding", propagation: "Propagation", probable: "Probable cause", action: "Recommended action", local: "Tibaldo Jungle in Lille", read: "Read the profile", profiles: "Documented species and cultivars", index: "Botanical classification", details: "Growing guide", diagnostics: "Diagnosis", common: "Common names", synonyms: "Synonyms", specimen: "Tibaldo Jungle observation" },
  es: { encyclopedia: "Enciclopedia vegetal", home: "Inicio", plants: "Plantas", family: "Familia", genus: "Género", species: "Especie", cultivar: "Cultivar", identity: "Identidad botánica", care: "Cuidados completos", toxicity: "Toxicidad y seguridad", problems: "Problemas y diagnóstico", comparisons: "Plantas similares", gallery: "Galería vegetal", advice: "Consejos Tibaldo Jungle", faq: "Preguntas frecuentes", sources: "Fuentes y prudencia", origin: "Origen", habitat: "Hábitat natural", status: "Estatus botánico", growth: "Crecimiento", adult: "Tamaño adulto", light: "Luz", water: "Riego", humidity: "Humedad", temperature: "Temperatura", substrate: "Sustrato", repotting: "Trasplante", fertilizing: "Abono", propagation: "Multiplicación", probable: "Causa probable", action: "Actuación recomendada", local: "Tibaldo Jungle en Lille", read: "Leer la ficha", profiles: "Especies y cultivares documentados", index: "Clasificación botánica", details: "Guía de cultivo", diagnostics: "Diagnóstico", common: "Nombres comunes", synonyms: "Sinónimos", specimen: "Observación Tibaldo Jungle" },
} as const;
const origin = "https://jungle.tibaldo.fr";
const JsonLd = ({ value }: { value: unknown }) => <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(value) }} />;

function Footer({ locale }: { locale: TranslatedLocale }) {
  return <footer className="pilot-localized-footer"><div className="shell"><strong>Studio Végétal — Tibaldo Jungle</strong><p>{locale === "en" ? "Rare plants, botanical guidance, repotting and horticultural substrates in Lille." : "Plantas raras, asesoramiento botánico, trasplante y sustratos hortícolas en Lille."}</p><span>3 place de l’Arbonnoise · 59000 Lille</span></div></footer>;
}

function Breadcrumbs({ locale, last, genre }: { locale: TranslatedLocale; last: string; genre?: string }) {
  const l = ui[locale];
  return <nav className="pilot-breadcrumbs shell" aria-label="Breadcrumb"><ol><li><a href={localizedPath("/", locale)}>{l.home}</a></li><li><a href={localizedPath("/plantes", locale)}>{l.plants}</a></li>{genre && <li><a href={localizedPath(`/plantes/${genre}`, locale)}>{genre}</a></li>}<li><span aria-current="page">{last}</span></li></ol></nav>;
}

const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => <section id={id} data-wave1-section={id} className="plant-profile-section" data-reveal><header className="plant-section-heading"><p className="section-kicker">{title}</p><h2>{title}</h2></header>{children}</section>;

export default function Wave1BotanicalPage({ path, locale }: { path: string; locale: TranslatedLocale }) {
  const l = ui[locale];
  const plant = getWave1Plant(path, locale);
  if (plant) {
    const gallery = plant.gallery.filter((image, index, images) => images.findIndex((candidate) => candidate.src === image.src) === index);
    const url = `${origin}${localizedPath(path, locale)}`;
    const structuredData = { "@context": "https://schema.org", "@graph": [
      { "@type": "Article", "@id": `${url}#article`, url, headline: plant.seo.title, description: plant.seo.description, inLanguage: languageTags[locale], datePublished: plant.publishedAt, dateModified: plant.updatedAt, image: gallery.map(({ src }) => `${origin}${src}`), about: { "@type": "Thing", name: plant.botanicalName, alternateName: plant.synonyms } },
      ...(plant.faq.length ? [{ "@type": "FAQPage", "@id": `${url}#faq`, inLanguage: languageTags[locale], mainEntity: plant.faq.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] : []),
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: l.home, item: `${origin}${localizedPath("/", locale)}` }, { "@type": "ListItem", position: 2, name: l.plants, item: `${origin}${localizedPath("/plantes", locale)}` }, { "@type": "ListItem", position: 3, name: plant.taxonomy.genus, item: `${origin}${localizedPath(`/plantes/${plant.genre}`, locale)}` }, { "@type": "ListItem", position: 4, name: plant.botanicalName, item: url }] },
      ...gallery.map((image) => ({ "@type": "ImageObject", contentUrl: `${origin}${image.src}`, caption: image.caption, width: image.width, height: image.height, inLanguage: languageTags[locale] })),
    ] };
    return <main className="editorial-page plant-profile-page localized-wave1-page" lang={locale}>
      <JsonLd value={structuredData} />
      <section className="plant-profile-hero"><img className="plant-profile-hero-image" src={plant.gallery[0].src} alt={plant.gallery[0].alt} width={plant.gallery[0].width} height={plant.gallery[0].height} /><div className="plant-profile-hero-shade" aria-hidden="true" /><SiteHeader locale={locale} currentPath={path} /><div className="shell plant-profile-hero-content"><p className="eyebrow"><span /> {l.encyclopedia} · {plant.genreLabel}</p><h1><ScientificName name={plant.botanicalName} className="scientific-name-hero" /></h1><p>{plant.subtitle}</p></div></section>
      <Breadcrumbs locale={locale} last={plant.displayName} genre={plant.genre} />
      <article className="shell wave1-rich-profile">
        <Section id="identity" title={l.identity}><div className="wave1-copy">{plant.description.map((text) => <p key={text}>{text}</p>)}</div><dl className="plant-facts plant-taxonomy"><div><dt>{l.family}</dt><dd>{plant.taxonomy.family}</dd></div><div><dt>{l.genus}</dt><dd>{plant.taxonomy.genus}</dd></div><div><dt>{l.species}</dt><dd><ScientificName name={plant.taxonomy.species} /></dd></div>{plant.taxonomy.cultivar && <div><dt>{l.cultivar}</dt><dd>‘{plant.taxonomy.cultivar}’</dd></div>}<div><dt>{l.common}</dt><dd>{plant.taxonomy.commonNames.join(" · ")}</dd></div><div><dt>{l.synonyms}</dt><dd>{plant.synonyms.join(" · ")}</dd></div><div><dt>{l.origin}</dt><dd>{plant.origin}</dd></div><div><dt>{l.habitat}</dt><dd>{plant.habitat}</dd></div><div><dt>{l.status}</dt><dd>{plant.hybridization}</dd></div><div><dt>{l.growth}</dt><dd>{plant.growth.speed} · {plant.growth.habit}</dd></div><div><dt>{l.adult}</dt><dd>{plant.growth.adultSize}</dd></div></dl><aside className="specimen-note"><span>{l.specimen}</span><strong>{plant.specimen.observedHeight}</strong><p>{plant.specimen.note}</p></aside></Section>
        <Section id="care" title={l.care}><div className="care-details">{[[l.light, plant.care.lightText], [l.water, plant.care.watering], [l.humidity, plant.care.humidityText], [l.temperature, plant.care.temperature], [l.substrate, plant.care.substrate], [l.repotting, plant.care.repotting], [l.fertilizing, plant.care.fertilizing], [l.propagation, plant.care.propagation]].map(([title, text]) => <article key={title}><span>{title}</span><p>{text}</p></article>)}</div></Section>
        <Section id="toxicity" title={l.toxicity}><aside className="toxicity-card"><div><span>{plant.toxicity.level}</span><strong>{plant.toxicity.summary}</strong></div><p>{plant.toxicity.details}</p></aside></Section>
        <Section id="problems" title={l.problems}><div className="plant-problem-list">{plant.problems.map((problem, index) => <details key={problem.title}><summary><span>{String(index + 1).padStart(2, "0")}</span><strong>{problem.title}</strong></summary><div><p><b>{l.probable}.</b> {problem.cause}</p><p><b>{l.action}.</b> {problem.advice}</p></div></details>)}</div></Section>
        <Section id="comparisons" title={l.comparisons}><div className="plant-comparison-grid">{plant.comparisons.map((item) => <article key={item.name}><h3>{item.name}</h3><p>{item.difference}</p></article>)}</div></Section>
        <Section id="gallery" title={l.gallery}><div className="wave1-gallery">{gallery.map((image) => <figure key={image.src}><img src={image.src} alt={image.alt} width={image.width} height={image.height} loading="lazy" /><figcaption>{image.caption}</figcaption></figure>)}</div></Section>
        <Section id="advice" title={l.advice}><ol className="wave1-advice">{plant.tibaldoAdvice.map((advice, index) => <li key={advice}><span>{String(index + 1).padStart(2, "0")}</span><p>{advice}</p></li>)}</ol></Section>
        <Section id="faq" title={l.faq}><div className="plant-faq">{plant.faq.map((item) => <details key={item.question}><summary><strong>{item.question}</strong><span>+</span></summary><p>{item.answer}</p></details>)}</div></Section>
        <Section id="sources" title={l.sources}><p>{locale === "en" ? "This profile cross-checks identified botanical and horticultural references. Conditions in each home may change the plant’s response." : "Esta ficha contrasta referencias botánicas y hortícolas identificadas. Las condiciones de cada hogar pueden modificar la respuesta de la planta."}</p><div>{plant.sources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.label} <Arrow /></a>)}</div></Section>
      </article><Footer locale={locale} /></main>;
  }

  const genre = getWave1Genre(path, locale);
  if (genre) {
    const { guide } = genre;
    const name = "botanicalName" in guide ? guide.botanicalName : guide.name;
    const url = `${origin}${localizedPath(path, locale)}`;
    const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Article", "@id": `${url}#page`, url, headline: `${guide.name}: ${l.details}`, description: guide.lead, inLanguage: languageTags[locale], image: `${origin}${guide.image}` }, ...(guide.faq.length ? [{ "@type": "FAQPage", "@id": `${url}#faq`, inLanguage: languageTags[locale], mainEntity: guide.faq.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] : []), { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: l.home, item: `${origin}${localizedPath("/", locale)}` }, { "@type": "ListItem", position: 2, name: l.plants, item: `${origin}${localizedPath("/plantes", locale)}` }, { "@type": "ListItem", position: 3, name: guide.name, item: url }] }] };
    return <main className="editorial-page localized-wave1-page" lang={locale}><JsonLd value={structuredData} /><section className="inner-hero compact-inner-hero"><div className="inner-hero-shade" /><SiteHeader locale={locale} currentPath={path} /><div className="shell inner-hero-content"><p className="eyebrow"><span /> {l.encyclopedia} · {l.genus}</p><h1><em>{name}</em></h1><p>{guide.heroSubtitle}</p></div></section><Breadcrumbs locale={locale} last={guide.name} /><article className="shell wave1-rich-profile">
      <Section id="introduction" title={l.identity}><div className="wave1-copy"><p>{guide.lead}</p><p>{guide.origin}</p></div></Section>
      <Section id="editorial" title={l.details}><div className="family-editorial">{genre.editorials.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</div></Section>
      <Section id="care" title={l.care}><div className="care-details"><article><span>{l.substrate}</span><p>{guide.care.substrate}</p></article><article><span>{l.fertilizing}</span><p>{guide.care.nutrition}</p></article>{guide.facts.map((fact) => <article key={fact.label}><span>{fact.label}</span><p>{fact.value}</p></article>)}</div></Section>
      <Section id="sections" title={l.details}><div className="family-guide-sections">{guide.sections.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{item.title}</h2><p>{item.text}</p></div></article>)}</div></Section>
      <Section id="problems" title={l.diagnostics}><div className="plant-comparison-grid">{guide.problems.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></Section>
      <Section id="local" title={l.local}><p>{locale === "en" ? "Visit us at 3 place de l’Arbonnoise in Lille for advice tailored to your light and free repotting throughout the year." : "Visítanos en 3 place de l’Arbonnoise, Lille, para recibir consejos adaptados a tu luz y un trasplante gratuito durante todo el año."}</p></Section>
      <Section id="faq" title={l.faq}><div className="plant-faq">{guide.faq.map((item) => <details key={item.question}><summary><strong>{item.question}</strong><span>+</span></summary><p>{item.answer}</p></details>)}</div></Section>
      <Section id="sources" title={l.sources}><div>{guide.sources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.label} <Arrow /></a>)}</div></Section>
      <Section id="profiles" title={l.profiles}><div className="plant-index-grid">{genre.plants.map((entry) => <a href={localizedPath(`/plantes/${entry.genre}/${entry.slug}`, locale)} key={entry.slug}><img src={entry.gallery[0].src} alt={entry.gallery[0].alt} width={entry.gallery[0].width} height={entry.gallery[0].height} /><h2>{entry.botanicalName}</h2><p>{entry.subtitle}</p><strong>{l.read} <Arrow /></strong></a>)}</div></Section>
      </article><Footer locale={locale} /></main>;
  }

  const family = getWave1Family(path, locale);
  if (family) { const url = `${origin}${localizedPath(path, locale)}`; const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", "@id": `${url}#page`, url, name: `${family.family}: ${l.profiles}`, inLanguage: languageTags[locale] }, { "@type": "ItemList", numberOfItems: family.plants.length, itemListElement: family.plants.map((entry, index) => ({ "@type": "ListItem", position: index + 1, name: entry.botanicalName, url: `${origin}${localizedPath(`/plantes/${entry.genre}/${entry.slug}`, locale)}` })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: l.home, item: `${origin}${localizedPath("/", locale)}` }, { "@type": "ListItem", position: 2, name: l.plants, item: `${origin}${localizedPath("/plantes", locale)}` }, { "@type": "ListItem", position: 3, name: family.family, item: url }] }] }; return <main className="editorial-page localized-wave1-page" lang={locale}><JsonLd value={structuredData} /><section className="inner-hero compact-inner-hero"><div className="inner-hero-shade" /><SiteHeader locale={locale} currentPath={path} /><div className="shell inner-hero-content"><p className="eyebrow"><span /> {l.encyclopedia} · {l.family}</p><h1><em>{family.family}</em></h1><p>{locale === "en" ? `Explore the genera, species and cultivars of the ${family.family} family documented by Tibaldo Jungle.` : `Explora los géneros, especies y cultivares de la familia ${family.family} documentados por Tibaldo Jungle.`}</p></div></section><Breadcrumbs locale={locale} last={family.family} /><article className="shell wave1-rich-profile"><Section id="classification" title={l.index}><p>{locale === "en" ? `This page brings together all published profiles in the ${family.family} family without creating a second botanical identity.` : `Esta página reúne todas las fichas publicadas de la familia ${family.family} sin crear una segunda identidad botánica.`}</p></Section><Section id="profiles" title={l.profiles}><div className="plant-index-grid">{family.plants.map((entry) => <a href={localizedPath(`/plantes/${entry.genre}/${entry.slug}`, locale)} key={`${entry.genre}-${entry.slug}`}><img src={entry.gallery[0].src} alt={entry.gallery[0].alt} width={entry.gallery[0].width} height={entry.gallery[0].height} /><span>{entry.taxonomy.genus} · {entry.taxonomy.species}</span><h2>{entry.botanicalName}</h2><p>{entry.subtitle}</p><strong>{l.read} <Arrow /></strong></a>)}</div></Section></article><Footer locale={locale} /></main>; }
  return null;
}
