import type { Level, PlantEntry } from "@/lib/plants/types";
import ScrollReveal from "../ScrollReveal";
import { Arrow, SiteFooter, SiteHeader } from "../SiteChrome";
import PlantSectionNav from "./PlantSectionNav";
import PlantCarePassport from "./PlantCarePassport";

function Meter({ label, value, copy }: { label: string; value: Level; copy: string }) { return <article className="care-meter" data-reveal><div><span>{label}</span><strong>{value}/5</strong></div><div className="care-meter-track" aria-label={`${label} : ${value} sur 5`}>{[1,2,3,4,5].map((level) => <i className={level <= value ? "is-filled" : ""} key={level} />)}</div><p>{copy}</p></article>; }

export default function PlantProfile({ plant }: { plant: PlantEntry }) {
  const difficultyLabels = ["", "Très facile", "Facile", "Intermédiaire", "Difficile", "Expert"];
  const gallery = plant.gallery.filter((image, index, images) => images.findIndex((candidate) => candidate.src === image.src) === index);
  return <main className="editorial-page plant-profile-page"><ScrollReveal />
    <section className="plant-profile-hero"><img className="plant-profile-hero-image" src={plant.gallery[0].src} alt={plant.gallery[0].alt} width={plant.gallery[0].width} height={plant.gallery[0].height} /><div className="plant-profile-hero-shade" aria-hidden="true" /><SiteHeader /><div className="shell plant-profile-hero-content"><p className="eyebrow"><span /> Encyclopédie végétale · {plant.genreLabel}</p><h1><span className="hero-line"><span>{plant.genreLabel}</span></span><span className="hero-line"><span><em>{plant.taxonomy.cultivar ? `‘${plant.taxonomy.cultivar}’` : plant.displayName}</em></span></span></h1><p>{plant.subtitle}</p><div className="plant-profile-hero-meta"><a href={`/plantes/famille/${plant.taxonomy.family.toLowerCase()}`}>{plant.taxonomy.family}</a><a href={`/plantes/${plant.genre}`}>{plant.taxonomy.genus}</a><span>{plant.specimen.observedHeight}</span></div></div></section>
    <PlantCarePassport indicators={[{ label: `Difficulté · ${difficultyLabels[plant.care.difficulty]}`, value: plant.care.difficulty, tone: "coral" }, { label: "Lumière", value: plant.care.light, tone: "gold" }, { label: "Arrosage", value: plant.care.water, tone: "blue" }, { label: "Humidité", value: plant.care.humidity, tone: "sage" }]} substrate={plant.care.substrate} nutrition={plant.care.fertilizing} />
    <div className="plant-profile-layout shell"><aside><PlantSectionNav /></aside><div className="plant-profile-content">
      <section className="plant-profile-section" id="identite" data-reveal><p className="section-kicker">Identité botanique</p><h2>Une identité végétale<br /><em>singulière.</em></h2>{plant.description.map((text) => <p key={text}>{text}</p>)}<dl className="plant-facts plant-taxonomy"><div><dt>Famille</dt><dd><a href={`/plantes/famille/${plant.taxonomy.family.toLowerCase()}`}>{plant.taxonomy.family}</a></dd></div><div><dt>Genre</dt><dd><a href={`/plantes/${plant.genre}`}>{plant.taxonomy.genus}</a></dd></div><div><dt>Espèce</dt><dd>{plant.taxonomy.species}</dd></div>{plant.taxonomy.cultivar && <div><dt>Cultivar</dt><dd>‘{plant.taxonomy.cultivar}’</dd></div>}<div className="is-secondary"><dt>Ordre</dt><dd>{plant.taxonomy.order}</dd></div><div><dt>Noms communs</dt><dd>{plant.taxonomy.commonNames.join(" · ")}</dd></div><div><dt>Origine</dt><dd>{plant.origin}</dd></div><div><dt>Habitat naturel</dt><dd>{plant.habitat}</dd></div><div><dt>Hybridation</dt><dd>{plant.hybridization}</dd></div><div><dt>Synonymes</dt><dd>{plant.synonyms.join(" · ")}</dd></div><div><dt>Port</dt><dd>{plant.growth.habit}</dd></div><div><dt>Croissance</dt><dd>{plant.growth.speed}</dd></div><div><dt>Taille adulte</dt><dd>{plant.growth.adultSize}</dd></div></dl><aside className="specimen-note"><span>Observation Tibaldo Jungle</span><strong>{plant.specimen.observedHeight}</strong><p>{plant.specimen.note}</p></aside></section>
      <section className="plant-profile-section" id="entretien"><header className="plant-section-heading" data-reveal><p className="section-kicker">Les bons équilibres</p><h2>Comprendre ses besoins.</h2></header><div className="care-meter-grid"><Meter label="Lumière" value={plant.care.light} copy={plant.care.lightText} /><Meter label="Arrosage" value={plant.care.water} copy={plant.care.watering} /><Meter label="Humidité" value={plant.care.humidity} copy={plant.care.humidityText} /><Meter label="Difficulté" value={plant.care.difficulty} copy="Vigoureuse lorsque lumière, chaleur et drainage restent cohérents." /></div><div className="care-details" data-reveal>{[["Température",plant.care.temperature],["Substrat",plant.care.substrate],["Rempotage",plant.care.repotting],["Fertilisation",plant.care.fertilizing],["Multiplication",plant.care.propagation]].map(([title,text]) => <article key={title}><span>{title}</span><p>{text}</p></article>)}</div><aside className="toxicity-card" data-reveal><div><span>Toxicité · {plant.toxicity.level}</span><strong>{plant.toxicity.summary}</strong></div><p>{plant.toxicity.details}</p></aside></section>
      <section className="plant-profile-section" id="problemes"><header className="plant-section-heading" data-reveal><p className="section-kicker">Diagnostic</p><h2>Lire ce que la plante raconte.</h2></header><div className="plant-problem-list">{plant.problems.map((problem,index) => <details key={problem.title} data-reveal><summary><span>0{index+1}</span><strong>{problem.title}</strong><i>+</i></summary><div><p><b>Cause probable.</b> {problem.cause}</p><p><b>Le bon réflexe.</b> {problem.advice}</p></div></details>)}</div></section>
      <section className="plant-profile-section" id="comparaison"><header className="plant-section-heading" data-reveal><p className="section-kicker">Plantes proches</p><h2>Ne plus les confondre.</h2></header><div className="plant-comparison-grid">{plant.comparisons.map((item) => <article key={item.name} data-reveal><span>À comparer</span><h3>{item.name}</h3><p>{item.difference}</p></article>)}</div></section>
      <section className="plant-gallery plant-profile-section" data-reveal><p className="section-kicker">Galerie végétale</p><div>{gallery.map((image) => <figure key={image.src}><img src={image.src} alt={image.alt} width={image.width} height={image.height} loading="lazy" /><figcaption>{image.caption}</figcaption></figure>)}</div></section>
      <section className="tibaldo-advice plant-profile-section" id="conseils" data-reveal><p className="section-kicker">Conseils Tibaldo Jungle</p><h2>Notre regard<br />au Studio.</h2><ol>{plant.tibaldoAdvice.map((advice,index) => <li key={advice}><span>0{index+1}</span><p>{advice}</p></li>)}</ol><div className="plant-availability"><span>{plant.shopUrl ? "Disponibilité en boutique" : "Poursuivre l’exploration"}</span><p>{plant.shopUrl ? "Consultez la fiche marchande pour connaître le stock actuel. Cette encyclopédie reste indépendante du catalogue de vente." : "Cette fiche appartient à la bibliothèque végétale Tibaldo Jungle. Explorez les plantes du même genre ou de la même famille botanique."}</p><a className="button button-light" href={plant.shopUrl || `/plantes/${plant.genre}`}>{plant.shopUrl ? "Voir en boutique" : `Découvrir les ${plant.genreLabel}`} <Arrow /></a></div></section>
      <section className="plant-faq plant-profile-section" id="faq"><header className="plant-section-heading" data-reveal><p className="section-kicker">Questions fréquentes</p><h2>Tout savoir avant de l’accueillir.</h2></header><div>{plant.faq.map((item) => <details key={item.question} data-reveal><summary><strong>{item.question}</strong><span>+</span></summary><p>{item.answer}</p></details>)}</div></section>
      <section className="plant-sources" data-reveal><p className="section-kicker">Sources & prudence</p><p>Fiche croisée avec des références botaniques et horticoles identifiées. Les conditions de chaque intérieur peuvent modifier le comportement de la plante.</p><div>{plant.sources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.label} <Arrow /></a>)}</div></section>
    </div></div><SiteFooter /></main>;
}
