import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";
export const metadata: Metadata = { title: "Politique de confidentialité | Studio Végétal Tibaldo Jungle", description: "Politique de protection des données personnelles de Studio Végétal Tibaldo Jungle à Lille.", alternates: { canonical: "/politique-confidentialite" }, robots: { index: false, follow: false } };
const sections: LegalSection[] = [
  { id: "responsable", title: "Responsable du traitement", content: <><p>Le responsable des traitements est <strong>Pruvost Romain, Entrepreneur individuel</strong>, exerçant sous le nom commercial Tibaldo Jungle et la signature Studio Végétal — Tibaldo Jungle, 3 place de l’Arbonnoise, 59000 Lille.</p><p>Pour toute question ou exercice de droits : <a href="mailto:jungle@tibaldo.fr">jungle@tibaldo.fr</a> ou 07 43 72 70 79.</p></> },
  { id: "donnees", title: "Données susceptibles d’être traitées", content: <><p>Selon la relation avec Tibaldo Jungle, les données peuvent comprendre : identité, coordonnées, date de naissance pour l’avantage anniversaire, identifiant client, achats, produits et passages, récompenses, cartes cadeaux, réservations, inscriptions aux ateliers, factures, paiements sans conservation des données bancaires complètes, demandes de devis floral, date et ville d’événement, préférences de fleurs et de couleurs, budget indicatif, demandes, réclamations, photographies de végétaux, diagnostic et solutions apportées.</p><p>Les données demandées comme obligatoires sont signalées lors de la collecte. L’absence d’une donnée nécessaire peut empêcher la création du compte, l’exécution d’une réservation ou le traitement complet d’une demande.</p></> },
  { id: "finalites", title: "Finalités et bases légales", content: <><ul><li><strong>Vente, réservation, atelier, carte cadeau et service après-vente :</strong> exécution du contrat ou mesures précontractuelles.</li><li><strong>Facturation, comptabilité et obligations fiscales :</strong> obligation légale.</li><li><strong>Programme de fidélité :</strong> exécution des conditions du programme demandé par le membre.</li><li><strong>Date de naissance et contrôle de l’avantage anniversaire :</strong> exécution du programme ; seule la vérification de la pièce est notée, sans copie.</li><li><strong>Prévention de la fraude, sécurité des cartes cadeaux et défense des droits :</strong> intérêt légitime, sous réserve des droits des personnes.</li><li><strong>Prospection par e-mail ou SMS lorsque le consentement est requis :</strong> consentement, distinct de l’adhésion fidélité.</li><li><strong>Réponse aux demandes et amélioration des services :</strong> intérêt légitime à assurer une relation client de qualité.</li></ul></> },
  { id: "fidelite", title: "Fidélité et historique d’achat", content: <><p>Le compte fidélité permet de calculer les tranches d’achats, les passages et les récompenses. L’historique peut inclure les références des produits achetés lorsqu’elles sont nécessaires au calcul, à une réclamation ou à l’exercice des droits du client.</p><p>L’adhésion n’entraîne aucune inscription automatique à une newsletter, à des SMS ou au démarchage téléphonique. Les préférences de communication sont indépendantes et peuvent être modifiées à tout moment.</p></> },
  { id: "durees", title: "Durées de conservation", content: <><ul><li>Données du compte et de fidélité : pendant la relation active, puis suppression ou anonymisation après trois ans d’inactivité, sauf donnée légalement requise ou nécessaire à un litige.</li><li>Demandes de devis sans suite : pendant le temps nécessaire à l’étude et au suivi de la demande, puis au maximum trois ans après le dernier contact.</li><li>Prospection commerciale : pendant la relation, puis trois ans à compter de sa fin ou du dernier contact actif selon la situation.</li><li>Pièces comptables et factures : durée légale applicable, généralement dix ans.</li><li>Réclamations et diagnostics : pendant le traitement, puis archivage restreint pendant la durée nécessaire à la preuve et aux délais de prescription applicables.</li><li>Cartes cadeaux : pendant leur validité, puis archivage de l’historique nécessaire à la comptabilité, à la prévention de la double utilisation et aux contestations.</li><li>Consentements et oppositions : pendant la durée nécessaire à démontrer le respect du choix et à éviter toute nouvelle sollicitation contraire.</li></ul><p>Ces durées peuvent être prolongées lorsqu’une obligation légale, un contrôle ou un contentieux l’exige.</p></> },
  { id: "destinataires", title: "Destinataires et prestataires", content: <><p>Les données sont accessibles aux seules personnes autorisées au sein de Tibaldo Jungle et, dans la limite de leurs missions, aux prestataires de caisse, paiement, hébergement, messagerie, maintenance, comptabilité ou communication.</p><p>OpenAI Ireland Limited intervient pour la publication et l’hébergement du site via ChatGPT Sites. Hostinger International Limited assure la gestion du nom de domaine et de sa configuration DNS. Les prestataires de paiement — notamment SumUp ou Stripe lorsqu’ils sont utilisés — traitent les données nécessaires au paiement selon leurs propres obligations. Tibaldo Jungle ne conserve pas le numéro complet de carte bancaire.</p><p>Aucune donnée n’est vendue. Une transmission aux autorités peut intervenir lorsqu’elle est légalement requise.</p></> },
  { id: "transferts", title: "Hébergement et transferts hors Union européenne", content: <><p>Certains prestataires techniques peuvent traiter ou héberger des données depuis des pays extérieurs à l’Espace économique européen. Dans ce cas, Tibaldo Jungle vérifie l’existence d’un mécanisme reconnu par le droit applicable, tel qu’une décision d’adéquation ou des clauses contractuelles types assorties, si nécessaire, de garanties complémentaires.</p><p>La liste concrète des prestataires devra être tenue à jour lors de la mise en service de la caisse, de la fidélité et de la boutique en ligne.</p></> },
  { id: "droits", title: "Vos droits", content: <><p>Selon le traitement, toute personne peut demander l’accès à ses données, leur rectification, leur effacement, la limitation du traitement, s’opposer à certains usages et exercer son droit à la portabilité. Un consentement peut être retiré à tout moment sans remettre en cause les traitements antérieurs.</p><p>La demande peut être adressée à <a href="mailto:jungle@tibaldo.fr">jungle@tibaldo.fr</a>. Une preuve d’identité peut être demandée uniquement en cas de doute raisonnable ; elle n’est pas conservée au-delà du contrôle nécessaire.</p><p>En cas de difficulté non résolue, la personne peut déposer une réclamation auprès de la <a href="https://www.cnil.fr" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  { id: "securite", title: "Sécurité et confidentialité", content: <><p>Tibaldo Jungle met en œuvre des mesures proportionnées aux risques : comptes nominatifs, contrôle des accès, mots de passe robustes, sauvegardes, chiffrement lorsque disponible, mises à jour, traçabilité des opérations sensibles et limitation des exports.</p><p>Les photographies et informations d’une réclamation ne sont utilisées que pour le diagnostic, la réponse, la preuve et l’amélioration du service, sans publication sans autorisation distincte.</p></> },
  { id: "cookies", title: "Site vitrine et cookies", content: <><p>Le site peut utiliser des éléments techniques strictement nécessaires à son fonctionnement et à sa sécurité. Si des outils de mesure d’audience, de publicité ou des contenus tiers déposant des traceurs non essentiels sont ajoutés, un mécanisme d’information et de choix conforme sera mis en place avant leur activation.</p><p>Les cartes ou contenus intégrés de tiers peuvent transmettre des données à leur fournisseur lorsque l’utilisateur les charge ou interagit avec eux. Les liens externes ouvrent les services concernés selon leurs propres politiques.</p></> },
  { id: "mise-jour", title: "Mise à jour de la politique", content: <><p>Cette politique évolue avec les services et la réglementation. Toute modification substantielle concernant une finalité, une base légale ou les droits fera l’objet d’une information adaptée.</p></> },
];
export default function PrivacyPage() { return <LegalPage eyebrow="Vos données · Vos choix" title="Politique de confidentialité" intro="Une utilisation sobre, transparente et sécurisée des informations confiées à Tibaldo Jungle." updated="7 août 2026" warning={<><strong>Prépublication</strong><p>La liste définitive des prestataires de caisse, hébergement, e-mail et fidélité devra être ajoutée après validation de l’architecture technique.</p></>} sections={sections} />; }
