import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const PRIVACY_POLICY_VERSION = "TIBALDO_PRIVACY_BETA_V2_2026-08-30";

export const metadata: Metadata = {
  title: "Politique de confidentialité — BÊTA | Tibaldo",
  description: "Politique de confidentialité BÊTA transverse de Jungle, du Shop, de l’espace client et de Beta Lab.",
  alternates: { canonical: "/politique-confidentialite" },
  robots: { index: false, follow: false },
};

const sections: LegalSection[] = [
  { id: "responsable", title: "Responsable du traitement et contact", content: <><p>Le responsable des traitements est <strong>Pruvost Romain, Entrepreneur individuel</strong>, exerçant sous le nom commercial Tibaldo Jungle et la signature <strong>Studio Végétal — TIBALDO Jungle</strong>.</p><p>Le Studio accueille ses clients au 3 place de l’Arbonnoise, 59000 Lille. L’adresse actuellement inscrite au RNE reste 16 rue Voltaire, 59139 Wattignies, dans l’attente de la mise à jour administrative liée au nouvel établissement.</p><p>Pour toute question ou exercice de droits : <a href="mailto:contact@tibaldo.fr">contact@tibaldo.fr</a>. Une vérification d’identité proportionnée peut être demandée uniquement en cas de doute raisonnable.</p></> },
  { id: "perimetre", title: "Services couverts", content: <><p>Cette politique constitue la source transverse pour le site éditorial Jungle, le Shop, l’espace client et Beta Lab. Les conditions propres au programme de test restent détaillées dans les <a href="https://beta.tibaldo.fr/conditions-beta">Conditions du bêta-test</a> sans créer une seconde politique concurrente.</p><p>Les traitements varient selon le service effectivement utilisé. Une visite de Jungle n’entraîne pas la création d’un compte Shop ou d’une candidature Beta Lab.</p></> },
  { id: "donnees", title: "Données traitées", content: <><ul><li><strong>Jungle et demandes :</strong> coordonnées et contenu transmis lors d’une prise de contact, d’un devis ou d’une demande de conseil.</li><li><strong>Shop et espace client :</strong> identité, email, téléphone, adresses, compte et session, panier, commandes, retrait ou livraison, factures, paiements, remboursements, support et préférences marketing séparées.</li><li><strong>Beta Lab :</strong> candidature, sélection, propositions et sessions, réponses, progression, durées, informations générales d’appareil et de navigateur, assistance, récompenses et journaux techniques.</li><li><strong>Captures Beta Lab :</strong> fichiers facultatifs envoyés volontairement pour documenter un problème.</li></ul><p>Tibaldo ne conserve pas les numéros complets de carte bancaire ni les codes de sécurité. Le prestataire de paiement traite les données nécessaires dans son propre environnement.</p></> },
  { id: "finalites", title: "Finalités et bases à confirmer", content: <><ul><li>Répondre aux demandes et préparer les services demandés.</li><li>Créer et sécuriser un compte, conserver le panier et exécuter les commandes, retraits, livraisons directes et remboursements.</li><li>Gérer la candidature, la sélection, la participation, l’assistance et les récompenses Beta Lab.</li><li>Assurer la facturation, les obligations légales, la preuve des opérations et la sécurité.</li><li>Analyser des résultats de test minimisés ou anonymisés afin d’améliorer les services.</li></ul><p>Les bases envisagées sont l’exécution du contrat ou de mesures précontractuelles, les obligations légales, le consentement lorsqu’il est requis et l’intérêt légitime pour la sécurité, la preuve et certaines analyses UX. La mise en balance de l’intérêt légitime et la qualification finale des bases restent soumises à revue juridique.</p><p>La création d’un compte, un achat ou une candidature Beta Lab n’entraîne aucune inscription automatique à une newsletter. Le choix marketing est séparé, facultatif et non précoché.</p></> },
  { id: "beta-lab", title: "Beta Lab et captures privées", content: <><p>Les réponses, durées, informations techniques générales et demandes d’assistance servent uniquement à organiser et analyser le bêta-test. Les captures sont <strong>volontaires, privées et réservées au propriétaire ou aux personnes autorisées pour la session concernée</strong>. Elles ne constituent ni des médias publics, ni des contenus marketing.</p><p>Les opérations d’accès, export, effacement ou anonymisation sont encadrées par des contrôles réservés au propriétaire. Un motif légal documenté peut suspendre une suppression pour le seul périmètre nécessaire.</p></> },
  { id: "conservation", title: "Conservation", content: <><p>La politique Beta Lab actuellement implémentée prévoit : candidature du pool général jusqu’à 12 mois après décision ou candidature selon le cas ; données directement rattachées à une participation jusqu’à 12 mois après la dernière participation ; résultats réellement anonymisés jusqu’à 5 ans ; captures avec une cible de suppression 6 mois après résolution et un plafond de 12 mois après création ; sessions navigateur 90 jours ; journaux des opérations Privacy 2 ans.</p><p>Les captures sont supprimées par défaut lors d’une anonymisation. Aucune purge automatique n’est promise : les opérations sont contrôlées, prévisualisées et confirmées par le propriétaire.</p><p>Les durées commerciales, comptables et fiscales du Shop, des factures et des récompenses, ainsi que leurs exceptions en cas de litige ou d’obligation légale, restent à valider juridiquement avant publication publique. Aucune durée non implémentée n’est promise dans cette version BÊTA.</p></> },
  { id: "destinataires", title: "Destinataires, prestataires et transferts", content: <><p>Les données sont accessibles aux seules personnes autorisées de Tibaldo et, selon le service, aux prestataires nécessaires : Cloudflare et l’hébergement Sites pour la diffusion, la sécurité, Beta Lab et ses stockages privés ; Supabase pour l’authentification et les données centrales du Shop ; Stripe pour le paiement TEST puis le paiement lorsqu’il sera activé ; Resend pour les emails transactionnels ; et les services d’adresse ou d’itinéraire nécessaires aux devis de livraison.</p><p>Aucune donnée n’est vendue. La liste contractuelle, le rôle exact de chaque prestataire, ses sous-traitants et les garanties applicables aux éventuels transferts hors Espace économique européen restent soumis à vérification avant publication publique.</p></> },
  { id: "droits", title: "Droits des personnes", content: <><p>Selon le traitement, une personne peut demander l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité de ses données, et retirer un consentement lorsque le traitement repose sur celui-ci. Les demandes sont adressées à <a href="mailto:contact@tibaldo.fr">contact@tibaldo.fr</a>.</p><p>En cas de difficulté non résolue, une réclamation peut être adressée à la <a href="https://www.cnil.fr" target="_blank" rel="noreferrer">CNIL</a>.</p></> },
  { id: "securite", title: "Sécurité", content: <><p>Les mesures observées comprennent l’authentification, le contrôle des accès, la séparation BÊTA/production, la limitation des accès directs, des cookies de session sécurisés, l’idempotence des opérations sensibles, la journalisation et le stockage privé des captures Beta Lab.</p><p>Aucune mesure ne supprime tous les risques. Les données personnelles ne doivent pas être ajoutées inutilement aux commentaires libres ou aux captures.</p></> },
  { id: "cookies", title: "Cookies et traceurs", content: <><p>La configuration BÊTA auditée utilise uniquement des mécanismes techniques nécessaires à la sécurité, à l’authentification, à la session et au panier. Aucun outil d’analytics non essentiel, pixel publicitaire, retargeting ou replay de session n’a été identifié. Aucun bandeau de consentement cosmétique n’est donc ajouté.</p><p>Avant toute activation future d’un traceur non essentiel ou d’un contenu tiers qui en dépose, Tibaldo réauditera la configuration et mettra en place l’information et le choix requis avant activation.</p></> },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="BÊTA · Données personnelles" title="Politique de confidentialité" intro="Une source transverse pour Jungle, le Shop, l’espace client et Beta Lab." updated="30 août 2026" warning={<><strong>VERSION BÊTA · REVUE OWNER ET JURIDIQUE REQUISE</strong><p>Version : {PRIVACY_POLICY_VERSION}. Ce document prépare la validation finale ; il ne constitue pas une certification juridique.</p></>} sections={sections} />;
}
