"use client";
import { useState } from "react";

export default function FlowerQuoteForm({ initialFlowers = [] }: { initialFlowers?: string[] }) {
  const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [error, setError] = useState("");
  const [reference, setReference] = useState("");
  return <form className="flower-quote-form" onSubmit={async (event) => { event.preventDefault(); const formElement = event.currentTarget; setState("sending"); setError(""); const form = new FormData(formElement); const payload = Object.fromEntries(form); try { const response = await fetch("/api/flower-quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, flowerSlugs: initialFlowers, consent: form.get("consent") === "on" }) }); const result = await response.json() as { error?: string; reference?: string }; if (!response.ok) throw new Error(result.error); setReference(result.reference ?? ""); setState("sent"); formElement.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Une erreur est survenue."); setState("error"); } }}>
    <div className="flower-form-grid"><label>Prénom *<input name="firstName" required autoComplete="given-name" /></label><label>Nom *<input name="lastName" required autoComplete="family-name" /></label><label>E-mail *<input name="email" type="email" required autoComplete="email" /></label><label>Téléphone<input name="phone" type="tel" autoComplete="tel" /></label><label>Type de projet *<select name="eventType" required defaultValue=""><option value="" disabled>Choisir</option><option>Mariage</option><option>Anniversaire</option><option>Réception privée</option><option>Événement professionnel</option><option>Commande personnelle</option><option>Autre</option></select></label><label>Date souhaitée<input name="eventDate" type="date" /></label><label>Ville *<input name="city" required autoComplete="address-level2" placeholder="Lille" /></label><label>Réception *<select name="fulfillment" required defaultValue=""><option value="" disabled>Choisir</option><option value="retrait">Retrait au Studio</option><option value="livraison">Livraison à étudier</option></select></label><label>Budget indicatif<select name="budget" defaultValue=""><option value="">À définir</option><option>Moins de 150 €</option><option>150 à 300 €</option><option>300 à 600 €</option><option>Plus de 600 €</option></select></label><label>Couleurs souhaitées<input name="colors" placeholder="Blanc, vert, rose poudré…" /></label></div>
    <label>Votre projet *<textarea name="message" required rows={6} placeholder="Quantités, nombre de tables, fleurs aimées, ambiance, contraintes de livraison…" /></label>
    <label className="flower-form-consent"><input type="checkbox" name="consent" required /><span>J’accepte que mes informations soient utilisées uniquement pour étudier ma demande de devis. Consultez notre <a href="/politique-confidentialite">politique de confidentialité</a>.</span></label>
    <button type="submit" data-action="quote" disabled={state === "sending"}>{state === "sending" ? "Envoi en cours…" : "Envoyer ma demande de devis"}<span>↗</span></button>
    {state === "sent" && <div className="flower-form-success"><strong>Demande {reference} enregistrée.</strong><span>Nous vérifions les disponibilités et préparons votre devis. Aucun acompte n’est demandé avant votre validation.</span></div>}{state === "error" && <p className="flower-form-error">{error}</p>}
  </form>;
}
