import type { Metadata } from "next";
import FlowerLocalPage from "../FlowerLocalPage";

export const metadata: Metadata = {
  title: "Bouquets de fleurs avec livraison à Lille sur demande | Tibaldo",
  description: "Bouquets déjà confectionnés par un fournisseur professionnel, disponibles sur commande à Lille. Devis transparent, retrait ou livraison étudiée.",
  alternates: { canonical: "/bouquets-fleurs-livraison-lille" },
  openGraph: { title: "Bouquets fournisseurs sur commande à Lille", description: "Tibaldo Jungle recherche des bouquets déjà confectionnés chez ses fournisseurs professionnels, avec retrait ou livraison sur devis.", url: "/bouquets-fleurs-livraison-lille", type: "website" },
};

export default function Page() {
  return <FlowerLocalPage canonical="/bouquets-fleurs-livraison-lille" eyebrow="Bouquets fournisseurs · Sur demande · Lille" title="Un bouquet disponible" accent="sans fausse promesse." intro="Tibaldo Jungle ne compose pas les bouquets. Nous pouvons rechercher, commander et remettre ou livrer à Lille des bouquets déjà confectionnés par un fournisseur professionnel." sections={[{ title: "Pas de composition maison", copy: "Le bouquet est réalisé en amont par le fournisseur professionnel. Tibaldo Jungle intervient pour rechercher l’offre, vérifier la disponibilité, commander et organiser le retrait ou la livraison." }, { title: "Un devis transparent", copy: "Le prix proposé intègre le bouquet fournisseur, l’organisation de la commande, la manutention et la livraison éventuelle. L’absence de confection par le Studio peut contenir le coût, sans promettre systématiquement le prix le plus bas." }, { title: "Uniquement sur demande", copy: "Style, couleurs, budget, date et destination sont transmis avant consultation. Le visuel exact dépend des offres et arrivages disponibles au moment de la demande." }]} faq={[{ question: "Tibaldo Jungle réalise-t-il les bouquets ?", answer: "Non. Tibaldo Jungle ne compose pas de bouquets. Les bouquets proposés sont déjà confectionnés par un fournisseur professionnel." }, { question: "Peut-on faire livrer un bouquet à Lille ?", answer: "Oui, selon la date, l’adresse et la disponibilité fournisseur. Le coût de livraison est indiqué dans le devis." }, { question: "Puis-je choisir toutes les fleurs du bouquet ?", answer: "Vous pouvez indiquer un style, des couleurs, un budget et des fleurs appréciées. Le bouquet exact dépend toutefois des propositions réellement disponibles chez le fournisseur." }, { question: "Pourquoi passer par Tibaldo Jungle ?", answer: "Le Studio centralise la recherche, la commande et la logistique locale. Vous recevez une proposition claire sans devoir gérer directement l’approvisionnement professionnel." }, { question: "Un acompte est-il nécessaire ?", answer: "Oui, lorsque le devis le prévoit. La commande fournisseur n’est lancée qu’après validation du devis et réception de l’acompte demandé." }]} />;
}
