import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";
export const metadata: Metadata = { title: "Cartes cadeaux | Tibaldo Jungle Lille", description: "Conditions d’utilisation des cartes cadeaux Tibaldo Jungle, valables dans le Studio Végétal à Lille.", alternates: { canonical: "/cartes-cadeaux" }, robots: { index: false, follow: false } };
const sections: LegalSection[] = [
  { id: "formats", title: "Formats et émission", content: <><p>La carte cadeau peut prendre la forme d’une carte papier ou physique, d’un bon imprimé, d’un document numérique ou d’un code unique. Elle est émise après encaissement effectif de son montant.</p><p>Chaque carte est associée à un identifiant, un montant initial, une date d’achat, une date d’expiration, un solde, un statut et un historique d’utilisation.</p></> },
  { id: "validite", title: "Validité d’un an", content: <><p>La carte est valable pendant un an à compter de sa date d’achat, jusqu’à la fermeture de la boutique le jour anniversaire correspondant. Sa date d’expiration est indiquée sur le support ou peut être communiquée sur demande.</p><p>À l’expiration, le solde non utilisé n’est plus mobilisable, sous réserve de toute règle impérative ou geste commercial exceptionnel décidé par Tibaldo Jungle.</p></> },
  { id: "utilisation", title: "Utilisation partielle et complément", content: <><p>La carte peut être utilisée en une ou plusieurs fois dans la boutique physique Tibaldo Jungle. Son solde est diminué du montant de chaque achat validé.</p><p>Si le prix est inférieur au solde, le reliquat demeure disponible jusqu’à l’expiration. Si le prix est supérieur, le bénéficiaire complète avec un moyen de paiement accepté. Aucun rendu de monnaie en espèces n’est effectué.</p></> },
  { id: "produits", title: "Produits et services éligibles", content: <><p>Sauf indication contraire lors de l’achat, la carte peut régler les produits et prestations directement vendus par Tibaldo Jungle. Elle ne peut pas servir à acheter une autre carte cadeau ni être convertie en espèces.</p><p>Son utilisation future sur une boutique en ligne ou dans un autre point de vente ne sera possible qu’après confirmation expresse de cette compatibilité.</p></> },
  { id: "securite", title: "Code, perte et utilisation frauduleuse", content: <><p>Le détenteur doit protéger le support et le code. Toute utilisation validée diminue le solde disponible. Tibaldo Jungle peut bloquer temporairement une carte en cas de suspicion raisonnable de fraude, duplication ou anomalie technique.</p><p>En cas de perte ou vol, le blocage ou remplacement n’est possible que si l’acheteur fournit une preuve permettant d’identifier la carte et si son solde n’a pas déjà été utilisé. Aucun remboursement ne peut être exigé pour une utilisation antérieure au signalement qui ne serait pas imputable à Tibaldo Jungle.</p></> },
  { id: "statuts", title: "Statuts et consultation du solde", content: <><p>Les statuts utilisés sont : <strong>ACTIVE</strong>, <strong>PARTIELLEMENT UTILISÉE</strong>, <strong>ÉPUISÉE</strong>, <strong>EXPIRÉE</strong> et <strong>ANNULÉE</strong>.</p><p>Le solde et l’échéance peuvent être consultés en boutique sur présentation du support ou du code. Un historique technique est conservé pour empêcher la double utilisation et traiter les réclamations.</p></> },
  { id: "annulation", title: "Annulation, remboursement et garanties", content: <><p>L’achat d’une carte en boutique physique ne bénéficie pas automatiquement d’un droit de rétractation. Une carte ne peut être remboursée ou convertie en espèces en cas de simple changement d’avis.</p><p>Cette règle ne fait pas obstacle aux droits légaux en cas d’erreur, d’inexécution ou de défaut imputable à Tibaldo Jungle.</p></> },
];
export default function GiftCardsPage() { return <LegalPage eyebrow="Offrir le vivant" title="Cartes cadeaux" intro="Une attention végétale, utilisable librement et en plusieurs fois au Studio." updated="7 août 2026" warning={<><strong>Usage actuel</strong><p>Ces conditions couvrent la boutique physique. L’usage en ligne et la compatibilité avec la future caisse devront être confirmés avant d’être annoncés.</p></>} sections={sections} />; }
