import type { Metadata } from "next";
import LocalSeoPage from "../LocalSeoPage";

export const metadata: Metadata = {
  title: "Livraison de plantes à Lille | Tibaldo Jungle",
  description: "Livraison de plantes d’intérieur, plantes rares et grands végétaux à Lille. Disponibilité, accès, créneau et tarif confirmés avant la livraison.",
  alternates: { canonical: "/livraison-plantes-lille" },
  openGraph: { title: "Livraison de plantes à Lille | Tibaldo Jungle", description: "Faites livrer une plante d’intérieur ou un grand végétal disponible chez Tibaldo Jungle à Lille.", url: "/livraison-plantes-lille", type: "website" },
};

export default function Page() {
  return <LocalSeoPage canonical="/livraison-plantes-lille" eyebrow="Livraison de plantes · Lille" title="Votre plante arrive" accent="jusqu’à sa nouvelle maison." intro="Plantes d’intérieur, raretés végétales et grands sujets peuvent être livrés à Lille selon leur disponibilité, leur volume et les conditions d’accès." sectionTitle="Une livraison végétale" sectionAccent="préparée avec soin." paragraphs={["Tibaldo Jungle propose la livraison de plantes à Lille pour les végétaux disponibles au Studio ou commandés spécialement. Ce service peut concerner une plante d’intérieur, une plante rare, un grand Monstera, un bananier, un oiseau du paradis ou une sélection destinée à un logement, un bureau ou un commerce.", "Avant confirmation, nous vérifions les dimensions de la plante et du pot, l’adresse, l’étage, la présence d’un ascenseur, les possibilités de stationnement et le créneau souhaité. Le montant de la livraison est communiqué avant validation : aucune commande n’est engagée sans accord clair."]} highlights={[{ title: "Plantes disponibles", copy: "La livraison porte sur les plantes réellement disponibles au Studio ou confirmées après commande fournisseur." }, { title: "Grands végétaux", copy: "Les plantes XL et XXL font l’objet d’une vérification particulière du transport, des accès et de la manutention." }, { title: "Lille et métropole", copy: "Lille est prioritaire. Une livraison dans la métropole lilloise peut être étudiée selon le trajet et le volume." }]} faq={[{ question: "Peut-on faire livrer une plante à Lille ?", answer: "Oui. Tibaldo Jungle étudie la livraison des plantes disponibles à Lille selon leur taille, l’adresse, les accès et le créneau souhaité." }, { question: "Livrez-vous les grandes plantes et plantes XXL ?", answer: "Oui, lorsque le véhicule, les accès et les conditions de manutention le permettent. Ces éléments sont vérifiés avant le devis." }, { question: "Le prix de la livraison est-il fixe ?", answer: "Non. Il dépend notamment de la distance, du volume, du nombre de plantes, de l’étage et des contraintes d’accès. Le tarif est annoncé avant validation." }, { question: "Puis-je commander une plante puis demander sa livraison ?", answer: "Oui. La disponibilité de la plante et les modalités de livraison sont confirmées ensemble avant le règlement." }]} links={[{ href: "/boutique-plantes-lille", label: "Boutique de plantes à Lille", copy: "Découvrir la sélection végétale et préparer votre visite au Studio." }, { href: "/plantes", label: "Encyclopédie végétale", copy: "Comparer les besoins des genres et variétés avant de choisir." }, { href: "/contact", label: "Demander une livraison", copy: "Indiquer la plante, l’adresse, l’étage et le créneau souhaité." }]} />;
}
