import type { PilotPath, TranslatedLocale } from "./config";

export type ParitySection = { id: string; title: string; paragraphs: string[] };
export type ParityPage = { sections: ParitySection[]; faq: { question: string; answer: string }[] };

const en: Record<PilotPath, ParityPage> = {
  "/": {
    sections: [
      { id: "opening-event", title: "Grand opening · 26 September 2026", paragraphs: ["The Plant Studio opens at 3 place de l’Arbonnoise in Lille on 26 September 2026. Free repotting will be available throughout the year; the event page lets visitors discover the Studio and indicate that they are coming."] },
      { id: "three-universes", title: "Three universes, one standard", paragraphs: ["Plants: rare specimens, houseplants and an encyclopedia for choosing according to your light and daily routine.", "Substrates: compost, bark, fibres and minerals sold loose, with mixes adapted to the roots.", "The Studio: the Tibaldo Jungle address in Lille, its plants, materials and in-person guidance."] },
      { id: "essential-services", title: "The right help at the right time", paragraphs: ["Plant SOS helps identify symptoms before acting.", "Repotting starts by examining roots and adjusting the growing medium.", "Plant delivery serves Lille and the European Metropolis of Lille.", "Natural living walls are designed as bespoke planted landscapes, with or without maintenance."] },
      { id: "studio-lille", title: "In Lille, close to your plants", paragraphs: ["Tibaldo Jungle is a rare and exotic plant shop as well as a place for practical advice. Plant selection, repotting and substrates are considered together to avoid unnecessary purchases and support each plant over time.", "Address: 3 place de l’Arbonnoise, 59000 Lille. Opening: 26 September 2026."] },
      { id: "expertise", title: "Observe, understand, advise without overselling", paragraphs: ["A carefully chosen collection, plants monitored between Lille and Wattignies, and advice grounded in the actual conditions of your home.", "Visitors can read the care guides, explore the encyclopedia and follow the Studio behind the scenes."] },
      { id: "practical-information", title: "The new Lille jungle is taking root", paragraphs: ["The Studio is near Cormontaigne at 3 place de l’Arbonnoise. Opening hours: Tuesday 2–7 pm; Wednesday to Saturday 10 am–7 pm; Sunday 10 am–1 pm.", "Contact: jungle@tibaldo.fr · +33 7 43 72 70 79. The practical section explains metro, bus, bicycle and parking options."] },
    ], faq: [],
  },
  "/plantes": {
    sections: [
      { id: "botanical-universes", title: "Botanical universes", paragraphs: ["Browse the major plant genera before opening individual species and cultivar profiles. The encyclopedia distinguishes botanical identity from commercial availability."] },
      { id: "search-and-filters", title: "Search by name, explore by needs", paragraphs: ["Search scientific names, common names, families, genera, species, cultivars and synonyms.", "Filters cover light, maximum difficulty, watering, minimum room temperature, growth habit and pet compatibility. They can be combined and reset."] },
      { id: "plant-sos", title: "Yellow leaves, pests or crowded roots", paragraphs: ["The encyclopedia explains a species. Plant SOS starts from the observed symptom to avoid unnecessary treatment and unsuitable care changes."] },
      { id: "genus-index", title: "Choose a genus and enter its world", paragraphs: ["The index covers the published universes, including banana plants, Alocasia, Anthurium, Monstera, Philodendron, Epipremnum, Asparagus, Epiphyllum, Colocasia, Pilea, Peperomia, cacti, Maranta, Calathea, Aloe, Chlorophytum, Yucca, Cycas, Plumeria, Japanese horsetail, Ficus, Syngonium, Hoya, Sansevieria and ferns."] },
      { id: "studio-collection", title: "The Studio collection", paragraphs: ["This list reflects plants currently grown or monitored by Tibaldo Jungle in Wattignies. It gradually feeds the encyclopedia and is not a live shop inventory.", "Identifications marked ‘to be confirmed’ remain provisional until the horticultural label or supplier information has been checked."] },
      { id: "opening-event", title: "Discover Tibaldo Jungle on opening day", paragraphs: ["The opening event connects the plant encyclopedia with the physical Studio in Lille without turning Jungle into a commercial stock database."] },
    ], faq: [],
  },
  "/plantes/cycas/revoluta": {
    sections: [
      { id: "botanical-identity", title: "Botanical identity", paragraphs: ["Cycas revoluta is an accepted species in the order Cycadales and family Cycadaceae. It is not a palm.", "Common names include Japanese cycad and sago palm. It originates from south-eastern China, southern Japan and Taiwan.", "This slow-growing subtropical shrub forms successive flushes of tough fronds around a thick caudex.", "Its upright habit and eventual outdoor size vary with conditions. The Studio specimen still needs to be measured and photographed after its identity has been checked."] },
      { id: "care", title: "Light, water and growing conditions", paragraphs: ["Light: a very bright to sunny position, with gradual acclimatisation.", "Watering: water after part of the mix has dried, then allow it to drain completely.", "Humidity: outdoor humidity is suitable when drainage remains effective.", "Temperature: requirements depend on pot culture and exposure; protect the plant during severe frost.", "Substrate: a free-draining outdoor mix in a container with drainage holes.", "Repotting: only when roots genuinely occupy the pot, moving to a slightly larger drained container.", "Feeding: moderate fertilisation during active growth, always on already moist substrate.", "Propagation: the appropriate method depends on the plant material; divisions or offsets must have viable roots."] },
      { id: "toxicity", title: "Toxicity and safety", paragraphs: ["All parts are toxic if eaten, particularly the seeds. Keep the plant away from children and animals and never treat an ornamental cycad as edible.", "Seek professional advice after suspected ingestion; do not wait for symptoms or rely on the plant’s decorative common names."] },
      { id: "problems", title: "Common problems and pests", paragraphs: ["Yellow foliage may reflect unsuitable watering, insufficient light, cold or natural ageing. Check roots and real conditions before feeding.", "Dry margins can follow irregular watering, sudden sun exposure, dry air or salt build-up. Stabilise conditions and assess new fronds.", "Slow growth can be normal during a cool, low-light rest period. Adjust exposure while respecting its seasonal rhythm.", "Scale insects, spider mites or thrips may hide around new growth and below fronds. Isolate the plant and inspect carefully."] },
      { id: "gallery", title: "Plant gallery", paragraphs: ["Only a real, correctly identified photograph will be used. The Studio specimen image and measurements are still to be added."] },
      { id: "studio-advice", title: "Tibaldo Jungle advice", paragraphs: ["Keep the original label for collection material and confirm the specimen before changing its identity.", "Examine roots before changing the watering routine.", "This profile remains tied to the Studio collection until the real photograph and identification are validated."] },
      { id: "sources", title: "Sources and caution", paragraphs: ["Botanical identity is checked against Kew Science — Plants of the World Online. Conditions in each home or garden can change the plant’s response."] },
    ],
    faq: [
      { question: "What light does Cycas revoluta need?", answer: "Give it a very bright to sunny position and acclimatise it gradually to direct sun." },
      { question: "How should Japanese cycad be watered?", answer: "Water after part of the mix has dried, then let the root ball drain completely." },
      { question: "What substrate should I use?", answer: "Use a sharply draining mix suitable for outdoor cultivation in a pot with drainage holes." },
      { question: "Why is the photograph missing?", answer: "Tibaldo Jungle only uses real, correctly identified images. It will be added after the Studio specimen has been photographed." },
      { question: "Does the pot need drainage holes?", answer: "Yes. Excess water must be able to leave the entire root ball." },
    ],
  },
  "/plantes/anthurium/clarinervium": {
    sections: [
      { id: "botanical-identity", title: "Botanical identity and morphology", paragraphs: ["Anthurium clarinervium is an accepted Araceae species described by Eizi Matuda, not a hybrid or horticultural cultivar.", "It is endemic to Chiapas, Mexico, in a seasonally dry tropical biome. It grows mainly on the ground, rooted deeply in limestone crevices, and more rarely as an epipetric plant in a thin soil layer.", "It forms a compact rosette of thick, matt, velvety, oval to heart-shaped leaves. Greenish-white primary veins create a strong pattern on the dark blade.", "New leaves are tender and pale before becoming thicker, darker and more rigid. Handling them while they unfurl can leave permanent marks.", "Indoor rosettes often reach 40–65 cm. Growth is slow to moderate, one leaf at a time. Commercial measurements belong to each Shop specimen, not this botanical identity."] },
      { id: "care", title: "Complete care", paragraphs: ["Light: bright indirect light; gentle filtered sun may be suitable after acclimatisation, while hot sun can bleach or burn the velvet.", "Watering: soak the mix when its upper layer begins to dry, then drain fully. Avoid both permanent saturation and prolonged complete dryness.", "Humidity: stable above-average humidity supports clean unfurling only when paired with genuine airflow.", "Temperature: ideally 18–27 °C; protect from cold draughts and prolonged temperatures below 16 °C.", "Substrate: an acidic, porous mix of bark, coco fibre or chips, a mineral drainage fraction and a small amount of potting compost. Drainage holes are essential.", "Repotting: wait until the fleshy roots occupy the container, protect them, choose a barely larger pot and keep the crown above the mix.", "Feeding: during active growth, use a very dilute complete fertiliser every three to four weeks on moist substrate; reduce sharply in low light.", "Propagation: divide a multi-growth plant, take a stem cutting with a viable node, or sow fresh ripe seed. A leaf without a node cannot make a complete plant."] },
      { id: "toxicity", title: "Toxicity", paragraphs: ["The plant is toxic if eaten and must be kept away from children, cats and dogs.", "Insoluble calcium oxalate crystals can cause oral pain, irritation, salivation and swelling; sap may irritate sensitive skin."] },
      { id: "problems", title: "Diagnosis and common problems", paragraphs: ["Soft yellow leaves: prolonged saturation, an oversized pot, cold or oxygen-starved roots. Inspect the root ball before watering again.", "Brown brittle margins: prolonged dryness, very dry air, salt build-up or abrupt wet–dry cycles. Stabilise watering and periodically flush the mix.", "Misshapen new leaves: unstable humidity, contact while unfurling, thrips or weak roots. Never force the leaf open.", "Dark spots: leaves staying wet, stagnant air, cold or opportunistic infection. Improve airflow and water the substrate, not the foliage.", "Thrips, scale insects and mites hide below leaves, on petioles and around new growth. Isolate, clean and repeat appropriate treatment over several cycles."] },
      { id: "comparisons", title: "Similar Anthurium", paragraphs: ["Anthurium crystallinum usually has longer, thinner leaves and a less compact habit.", "Anthurium magnificum has distinctly angular petioles and becomes larger.", "Anthurium forgetii has a closed or nearly closed blade base, unlike the open heart-shaped sinus of A. clarinervium."] },
      { id: "gallery", title: "Plant gallery", paragraphs: ["The Studio specimen still needs to be photographed. No generated image is used to identify this plant."] },
      { id: "studio-advice", title: "Tibaldo Jungle advice", paragraphs: ["Keep the pot fairly snug so a large volume of wet mix does not deprive roots of oxygen.", "Do not rub the velvet; remove dust gently with a very soft, dry brush.", "After receiving the plant, stabilise light, warmth and watering before considering repotting."] },
      { id: "sources", title: "Sources and caution", paragraphs: ["Identity and horticultural guidance are cross-checked with Kew Science, CATE Araceae, the Royal Horticultural Society and NC State Extension."] },
    ],
    faq: [
      { question: "What light should Anthurium clarinervium receive?", answer: "Bright indirect light keeps growth compact and the veins contrasting. Avoid hot direct sun, especially on a new leaf." },
      { question: "When should Anthurium clarinervium be watered?", answer: "Water when the upper mix has begun to dry, never on a fixed weekday, and let the pot drain fully." },
      { question: "What substrate should I use?", answer: "Use an acidic, airy blend of bark, coco, a mineral drainage component and a small potting-compost fraction rather than dense compost alone." },
      { question: "Does it need very high humidity?", answer: "Stable moderate-to-high humidity helps leaves unfurl, but it must always be accompanied by good airflow." },
      { question: "Why are the veins less white?", answer: "Contrast varies with leaf age, clone and light. A young leaf has not yet reached its final colour." },
      { question: "Can a single leaf be propagated?", answer: "No. Vegetative propagation needs a viable node or growth point; an isolated leaf may survive without producing a new plant." },
    ],
  },
  "/plantes/monstera/thai-constellation": {
    sections: [
      { id: "botanical-identity", title: "Botanical identity and growth", paragraphs: ["Monstera deliciosa ‘Thai Constellation’ is a horticultural cultivar of Monstera deliciosa in the Araceae family. Its name and cultivar remain identical in every language.", "Cream sectors and fine speckles create a starry pattern. The variegation is distributed through the tissues and is relatively stable, although every leaf is different.", "With less chlorophyll than a green Monstera deliciosa, it grows more slowly and needs bright light without hot sun.", "It is a climbing vine that can reach several metres on a support. The proportion of cream naturally varies between leaves."] },
      { id: "care", title: "Complete care", paragraphs: ["Light: very bright indirect light supports the cream tissue without scorching it.", "Watering: allow the upper potting mix to dry; roots do not tolerate permanent moisture.", "Humidity: moderate to high, with ventilation.", "Temperature: a stable 18–28 °C.", "Substrate: a very airy aroid mix in a suitably sized pot with drainage holes.", "Repotting: only when roots occupy the container, moving to a slightly larger drained pot.", "Feeding: diluted complete fertiliser during the bright growing season, applied to already moist substrate.", "Propagation: a cutting with at least one active node, or division of an established plant."] },
      { id: "toxicity", title: "Toxicity", paragraphs: ["The plant is toxic and should be kept away from children, cats and dogs.", "As with many Araceae, calcium oxalate crystals irritate tissues when chewed or swallowed."] },
      { id: "problems", title: "Diagnosis and common problems", paragraphs: ["Yellow leaves: excess water, cold, insufficient light or natural ageing. Check roots and actual drying before changing watering.", "Brown tips or cream patches: hot sun, dry air, salts or irregular watering. Stabilise conditions and avoid abrupt changes.", "Slow growth: insufficient light, low temperature or inactive roots. Correct light and warmth before adding fertiliser.", "Thrips and spider mites often target young growth and leaf undersides. Isolate, clean and monitor repeatedly for several weeks."] },
      { id: "comparisons", title: "Do not confuse the cultivars", paragraphs: ["Monstera deliciosa ‘Albo Variegata’ usually has whiter, more sectoral variegation that varies more from node to node.", "Monstera deliciosa ‘Mint’ has diffuse pale marbling with a mint-like cast rather than cream speckling."] },
      { id: "gallery", title: "Botanical plate", paragraphs: ["The same owner-supplied image is used in every language: seven adult Thai Constellation leaves arranged as a botanical plate."] },
      { id: "studio-advice", title: "Tibaldo Jungle advice", paragraphs: ["Inspect the root ball before watering; the surface alone does not tell the whole story.", "Suitable light produces stronger growth than excessive fertiliser.", "Cream areas scorch sooner, so increase light gradually."] },
      { id: "sources", title: "Sources and caution", paragraphs: ["Horticultural guidance is cross-checked against the Royal Horticultural Society profile for Monstera deliciosa."] },
    ],
    faq: [
      { question: "What light does Monstera deliciosa ‘Thai Constellation’ need?", answer: "Very bright indirect light supports the cream areas without exposing them to hot sun." },
      { question: "How should Thai Constellation be watered?", answer: "Let the upper potting mix dry; its roots do not tolerate permanent moisture." },
      { question: "What substrate should I use?", answer: "Use a very airy aroid mix in a suitably sized pot with drainage holes." },
      { question: "Does the pot need drainage holes?", answer: "Yes. After watering, excess water must be able to leave the entire root ball." },
      { question: "Is this plant toxic?", answer: "Yes. Chewing its tissues can irritate people and animals." },
      { question: "When should it be repotted?", answer: "Repot when roots have colonised the pot and the mix dries unusually quickly, rather than on a fixed schedule." },
    ],
  },
  "/plantes/bananiers": {
    sections: [
      { id: "botanical-foundations", title: "A tropical silhouette, several strategies", paragraphs: ["A banana plant is a giant herb, not a tree. Its apparent trunk is a pseudostem built from overlapping leaf sheaths.", "Musa are often rhizomatous and produce offsets, while Ensete are normally solitary. This distinction changes propagation, space requirements and overwintering.", "Hardiness is not a single number: leaves, pseudostem and rhizome have different limits, and winter moisture can matter as much as cold."] },
      { id: "genera", title: "Musa and Ensete", paragraphs: ["Musa includes Basjoo, Red Tiger and Florida Variegata, three plants with very different uses.", "Ensete are normally solitary plants with a swollen base, represented here by the striking ‘Maurelii’."] },
      { id: "lille-north", title: "Growing banana plants in Lille and northern France", paragraphs: ["The Lille climate combines possible frost, low winter light, wind and wet periods. Outdoors, choose shelter and sharply draining soil. Musa basjoo is the most logical candidate, with crown protection and no promise that foliage will survive.", "In pots, plan an autumn move indoors. Florida Variegata and Ensete ‘Maurelii’ need frost-free conditions; Red Tiger deserves caution. Resume generous water and feeding only after the soil warms in spring."] },
      { id: "fundamentals", title: "Light, water, soil and winter", paragraphs: ["Light and wind: provide generous light, acclimatise to sun and protect leaves from strong gusts.", "Water and nutrition: supply generously during growth, then reduce sharply as temperature and light fall.", "Soil and pot: use a rich but free-draining mix, drainage holes and a stable volume for rapidly heavy plants.", "Winter: identify the taxon first; mulching a hardy crown and bringing a tender plant indoors are not equivalent."] },
      { id: "four-taxa", title: "Four banana plants, four approaches", paragraphs: ["Musa basjoo: broad green foliage; ground or large pot; protected crown; breathable mulch and drainage; propagated from rooted offsets.", "Musa sikkimensis ‘Red Tiger’: variable red markings; pot or sheltered outdoor site; do not copy Basjoo’s cold thresholds; protect seriously or bring indoors; seedlings are not true to the cultivar.", "Musa ‘Florida Variegata’: green-and-cream variegation; bright pot culture; cold-sensitive; bright frost-free winter conditions; no undocumented promise of stable propagation.", "Ensete ventricosum ‘Maurelii’: dark green, red and purple foliage; pot or seasonal outdoor display; frost-sensitive; overwinter frost-free; solitary habit without spontaneous offsets."] },
    ], faq: [],
  },
  "/conseils/arroser-plantes-interieur": {
    sections: [
      { id: "check-substrate", title: "Check the substrate", paragraphs: ["A dry surface does not reveal what is happening at the centre of the pot. Check several centimetres down and learn how the container feels when wet and when nearly dry.", "Leaves offer clues, but waiting for severe wilting puts many species under unnecessary stress."] },
      { id: "water-thoroughly", title: "Water thoroughly", paragraphs: ["When watering is needed, moisten the whole root ball evenly until excess water runs from the drainage holes. Empty the saucer or decorative pot afterwards.", "Repeated small sips leave dry zones and encourage roots to remain near the surface."] },
      { id: "adapt-seasons", title: "Adapt to the seasons", paragraphs: ["Plants generally use less water when light and temperature decrease. Do not keep a summer frequency through winter without checking the mix.", "After repotting, moving the plant or changing its light, observe again because the former rhythm may no longer suit it."] },
      { id: "studio-help", title: "Unsure about the container?", paragraphs: ["Bring the plant and its pot to the Plant Studio. Together we can check drainage, container volume and substrate instead of guessing."] },
    ], faq: [],
  },
};

const es: Record<PilotPath, ParityPage> = {
  "/": {
    sections: [
      { id: "opening-event", title: "Gran apertura · 26 de septiembre de 2026", paragraphs: ["El Estudio Vegetal abre el 26 de septiembre de 2026 en 3 place de l’Arbonnoise, Lille. El trasplante será gratuito durante todo el año; la página del evento permite descubrir el Studio y confirmar la asistencia."] },
      { id: "three-universes", title: "Tres universos, una misma exigencia", paragraphs: ["Plantas: ejemplares singulares, plantas de interior y una enciclopedia para elegir según la luz y la vida cotidiana.", "Sustratos: tierra, cortezas, fibras y minerales a granel, con mezclas adaptadas a las raíces.", "El Studio: la nueva dirección Tibaldo Jungle en Lille, sus plantas, materiales y consejos presenciales."] },
      { id: "essential-services", title: "La ayuda adecuada en el momento oportuno", paragraphs: ["SOS Plantas ayuda a comprender los síntomas antes de actuar.", "El trasplante empieza observando las raíces y ajustando la mezcla.", "La entrega de plantas cubre Lille y la Métropole Européenne de Lille.", "Los muros vegetales naturales se diseñan a medida, con o sin mantenimiento."] },
      { id: "studio-lille", title: "En Lille, cerca de tus plantas", paragraphs: ["Tibaldo Jungle es una tienda de plantas raras y exóticas y también un lugar de asesoramiento. Selección, trasplante y sustratos se piensan conjuntamente para evitar compras inútiles y acompañar cada planta.", "Dirección: 3 place de l’Arbonnoise, 59000 Lille. Apertura: 26 de septiembre de 2026."] },
      { id: "expertise", title: "Observar, comprender y aconsejar sin vender de más", paragraphs: ["Una selección cuidada, un cultivo seguido entre Lille y Wattignies y consejos adaptados a las condiciones reales de cada hogar.", "El visitante puede leer los consejos, explorar la enciclopedia y seguir los entresijos del Studio."] },
      { id: "practical-information", title: "La nueva jungla de Lille echa raíces", paragraphs: ["El Studio está cerca de Cormontaigne, en 3 place de l’Arbonnoise. Horarios: martes 14–19 h; miércoles a sábado 10–19 h; domingo 10–13 h.", "Contacto: jungle@tibaldo.fr · +33 7 43 72 70 79. La información práctica explica metro, autobús, bicicleta y aparcamiento."] },
    ], faq: [],
  },
  "/plantes": {
    sections: [
      { id: "botanical-universes", title: "Universos botánicos", paragraphs: ["Recorre los grandes géneros antes de abrir las fichas de especies y cultivares. La enciclopedia separa identidad botánica y disponibilidad comercial."] },
      { id: "search-and-filters", title: "Buscar por nombre y explorar por necesidades", paragraphs: ["La búsqueda comprende nombres científicos y comunes, familias, géneros, especies, cultivares y sinónimos.", "Los filtros cubren luz, dificultad máxima, riego, temperatura mínima, porte y compatibilidad con animales. Pueden combinarse y restablecerse."] },
      { id: "plant-sos", title: "Hojas amarillas, plagas o raíces apretadas", paragraphs: ["La enciclopedia explica una especie. SOS Plantas parte del síntoma observado para evitar tratamientos inútiles y cambios inadecuados."] },
      { id: "genus-index", title: "Elegir un género y entrar en su universo", paragraphs: ["El índice incluye bananeras, Alocasia, Anthurium, Monstera, Philodendron, Epipremnum, Asparagus, Epiphyllum, Colocasia, Pilea, Peperomia, cactus, Maranta, Calathea, Aloe, Chlorophytum, Yucca, Cycas, Plumeria, cola de caballo japonesa, Ficus, Syngonium, Hoya, Sansevieria y helechos."] },
      { id: "studio-collection", title: "La colección del Studio", paragraphs: ["La lista refleja las plantas cultivadas u observadas actualmente por Tibaldo Jungle en Wattignies. Alimenta progresivamente la enciclopedia y no representa el stock de la tienda.", "Las identificaciones «por confirmar» siguen siendo provisionales hasta revisar la etiqueta hortícola o el proveedor."] },
      { id: "opening-event", title: "Descubrir Tibaldo Jungle el día de la apertura", paragraphs: ["El evento vincula la enciclopedia con el Studio físico de Lille sin convertir Jungle en una base comercial de stock."] },
    ], faq: [],
  },
  "/plantes/cycas/revoluta": {
    sections: [
      { id: "botanical-identity", title: "Identidad botánica", paragraphs: ["Cycas revoluta es una especie aceptada del orden Cycadales y la familia Cycadaceae. No es una palmera.", "Sus nombres comunes incluyen cica del Japón y palma de sagú. Procede del sudeste de China, sur de Japón y Taiwán.", "Este arbusto subtropical lento forma coronas sucesivas de frondes coriáceas alrededor de un caudex grueso.", "Su porte es erguido y el tamaño exterior depende de las condiciones. El ejemplar del Studio aún debe medirse y fotografiarse tras confirmar su identidad."] },
      { id: "care", title: "Luz, riego y condiciones de cultivo", paragraphs: ["Luz: ubicación muy luminosa o soleada, con aclimatación gradual.", "Riego: regar después de un secado parcial y dejar escurrir completamente.", "Humedad: la humedad exterior conviene si el drenaje sigue siendo eficaz.", "Temperatura: depende del cultivo en maceta y la exposición; proteger durante heladas intensas.", "Sustrato: mezcla muy drenante para exterior en un recipiente con agujeros.", "Trasplante: solo cuando las raíces ocupen realmente la maceta, pasando a otra apenas mayor y perforada.", "Abono: moderado durante el crecimiento activo y siempre sobre sustrato húmedo.", "Multiplicación: el método depende del material; divisiones o hijuelos deben conservar raíces viables."] },
      { id: "toxicity", title: "Toxicidad y seguridad", paragraphs: ["Todas las partes son tóxicas por ingestión, especialmente las semillas. Mantener lejos de niños y animales y no considerar comestible una cícada ornamental.", "Tras una posible ingestión hay que consultar a un profesional y no esperar a que aparezcan síntomas."] },
      { id: "problems", title: "Problemas y plagas frecuentes", paragraphs: ["El follaje amarillo puede indicar riego inadecuado, poca luz, frío o envejecimiento. Revisar raíces y condiciones antes de abonar.", "Los bordes secos pueden deberse a riegos irregulares, sol brusco, aire seco o sales. Estabilizar y observar las nuevas frondes.", "El crecimiento lento puede ser normal con frío y poca luz. Adaptar la exposición respetando el ritmo estacional.", "Cochinillas, ácaros o trips pueden esconderse en los brotes y bajo las frondes. Aislar e inspeccionar."] },
      { id: "gallery", title: "Galería vegetal", paragraphs: ["Solo se utilizará una fotografía real y correctamente identificada. Quedan por añadir la imagen y las medidas del ejemplar del Studio."] },
      { id: "studio-advice", title: "Consejos Tibaldo Jungle", paragraphs: ["Conservar la etiqueta de origen y confirmar el ejemplar antes de cambiar su identidad.", "Observar las raíces antes de modificar el riego.", "Esta ficha permanece vinculada a la colección del Studio hasta validar fotografía e identificación."] },
      { id: "sources", title: "Fuentes y prudencia", paragraphs: ["La identidad botánica se contrasta con Kew Science — Plants of the World Online. Las condiciones de cada hogar o jardín pueden modificar la respuesta."] },
    ],
    faq: [
      { question: "¿Qué luz necesita Cycas revoluta?", answer: "Una ubicación muy luminosa o soleada, con aclimatación gradual al sol directo." },
      { question: "¿Cómo se riega la cica del Japón?", answer: "Después de un secado parcial de la mezcla, dejando escurrir completamente el cepellón." },
      { question: "¿Qué sustrato debo utilizar?", answer: "Una mezcla muy drenante para exterior en una maceta con agujeros." },
      { question: "¿Por qué falta la fotografía?", answer: "Tibaldo Jungle solo utiliza imágenes reales y correctamente identificadas. Se añadirá tras fotografiar el ejemplar del Studio." },
      { question: "¿La maceta debe estar perforada?", answer: "Sí. El exceso de agua debe poder salir completamente del cepellón." },
    ],
  },
  "/plantes/anthurium/clarinervium": {
    sections: [
      { id: "botanical-identity", title: "Identidad botánica y morfología", paragraphs: ["Anthurium clarinervium es una especie aceptada de Araceae descrita por Eizi Matuda; no es híbrido ni cultivar.", "Es endémica de Chiapas, México, en un bioma tropical estacionalmente seco. Crece principalmente en tierra, arraigada en fisuras calizas, y más raramente como epipétrica.", "Forma una roseta compacta de hojas gruesas, mates, aterciopeladas y acorazonadas. Los nervios principales blanco verdosos destacan sobre el limbo oscuro.", "Las hojas nuevas son tiernas y claras antes de ganar grosor, contraste y rigidez. Tocarlas al desplegarse puede dejar marcas permanentes.", "La roseta de interior suele medir 40–65 cm y crece lenta o moderadamente, una hoja tras otra. Las medidas comerciales pertenecen a cada ejemplar del Shop."] },
      { id: "care", title: "Cuidados completos", paragraphs: ["Luz: indirecta intensa; un sol suave filtrado puede convenir tras aclimatar, pero el sol fuerte quema el terciopelo.", "Riego: empapar cuando la capa superior empiece a secarse y dejar escurrir. Evitar saturación permanente y sequedad total prolongada.", "Humedad: estable y superior a la media, siempre con circulación real de aire.", "Temperatura: idealmente 18–27 °C; evitar corrientes frías y periodos prolongados por debajo de 16 °C.", "Sustrato: ácido y poroso, con corteza, fibra o chips de coco, fracción mineral y poca tierra. Agujeros de drenaje imprescindibles.", "Trasplante: esperar a que las raíces carnosas ocupen la maceta, protegerlas, elegir un recipiente apenas mayor y mantener el cuello sobre la mezcla.", "Abono: completo y muy diluido cada tres o cuatro semanas durante el crecimiento, sobre sustrato húmedo; reducir con poca luz.", "Multiplicación: división con varios puntos de crecimiento, esqueje de tallo con nudo viable o semillas frescas. Una hoja sin nudo no forma una planta completa."] },
      { id: "toxicity", title: "Toxicidad", paragraphs: ["Es tóxico por ingestión y debe mantenerse lejos de niños, gatos y perros.", "Los cristales insolubles de oxalato de calcio pueden causar dolor, irritación, salivación e hinchazón; la savia irrita pieles sensibles."] },
      { id: "problems", title: "Diagnóstico y problemas frecuentes", paragraphs: ["Hojas amarillas y blandas: saturación, maceta grande, frío o raíces asfixiadas. Revisar el cepellón antes de regar.", "Bordes marrones y quebradizos: sequedad, aire seco, sales o ciclos bruscos. Estabilizar y lavar periódicamente la mezcla.", "Hojas nuevas deformadas: humedad inestable, contacto, trips o raíces débiles. No forzar nunca la apertura.", "Manchas oscuras: follaje mojado, aire estancado, frío o infección oportunista. Ventilar y regar el sustrato.", "Trips, cochinillas y ácaros se ocultan bajo hojas, pecíolos y brotes. Aislar, limpiar y repetir el tratamiento adecuado."] },
      { id: "comparisons", title: "Anthurium parecidos", paragraphs: ["Anthurium crystallinum suele tener hojas más alargadas y finas y un porte menos compacto.", "Anthurium magnificum presenta pecíolos angulosos y mayor desarrollo.", "Anthurium forgetii tiene la base cerrada o casi cerrada, a diferencia del seno cordiforme abierto de A. clarinervium."] },
      { id: "gallery", title: "Galería vegetal", paragraphs: ["Todavía debe fotografiarse el ejemplar del Studio. No se utiliza ninguna imagen generada para identificar esta planta."] },
      { id: "studio-advice", title: "Consejos Tibaldo Jungle", paragraphs: ["Mantener una maceta ajustada para evitar un gran volumen de mezcla húmeda.", "No frotar el terciopelo; retirar el polvo con un pincel muy suave y seco.", "Después de recibirla, estabilizar luz, calor y riego antes de trasplantar."] },
      { id: "sources", title: "Fuentes y prudencia", paragraphs: ["La identidad y los cuidados se contrastan con Kew Science, CATE Araceae, Royal Horticultural Society y NC State Extension."] },
    ],
    faq: [
      { question: "¿Qué luz necesita Anthurium clarinervium?", answer: "Luz indirecta intensa para mantener un porte compacto y buenos contrastes. Evita el sol fuerte, especialmente sobre hojas nuevas." },
      { question: "¿Cuándo debo regarlo?", answer: "Cuando la capa superior empiece a secarse, nunca según un día fijo, y dejando escurrir completamente." },
      { question: "¿Qué sustrato debo utilizar?", answer: "Una mezcla ácida y aireada de corteza, coco, componente mineral y poca tierra, mejor que un sustrato compacto solo." },
      { question: "¿Necesita mucha humedad?", answer: "Una humedad moderada-alta y estable ayuda al despliegue, siempre acompañada de ventilación." },
      { question: "¿Por qué los nervios son menos blancos?", answer: "El contraste varía según edad, clon y luz. Una hoja joven todavía no tiene su color definitivo." },
      { question: "¿Puede multiplicarse una hoja sola?", answer: "No. La multiplicación vegetativa necesita un nudo o punto de crecimiento viable." },
    ],
  },
  "/plantes/monstera/thai-constellation": {
    sections: [
      { id: "botanical-identity", title: "Identidad botánica y crecimiento", paragraphs: ["Monstera deliciosa ‘Thai Constellation’ es un cultivar hortícola de Monstera deliciosa, familia Araceae. Nombre y cultivar permanecen idénticos.", "Las zonas crema y salpicaduras finas crean un dibujo estrellado. La variegación está repartida por los tejidos y es relativamente estable, aunque cada hoja cambia.", "Al tener menos clorofila que una Monstera verde, crece más despacio y necesita luz intensa sin sol fuerte.", "Es una liana trepadora que alcanza varios metros con soporte. La proporción de crema cambia naturalmente entre hojas."] },
      { id: "care", title: "Cuidados completos", paragraphs: ["Luz: indirecta muy intensa para sostener las zonas crema sin quemarlas.", "Riego: dejar secar la parte superior; las raíces no toleran humedad permanente.", "Humedad: media-alta con ventilación.", "Temperatura: estable entre 18 y 28 °C.", "Sustrato: mezcla muy aireada para aráceas en maceta ajustada y perforada.", "Trasplante: cuando las raíces ocupen el recipiente, pasando a otro solo un poco mayor.", "Abono: completo y diluido durante la época luminosa, sobre sustrato húmedo.", "Multiplicación: esqueje con al menos un nudo activo o división de una planta establecida."] },
      { id: "toxicity", title: "Toxicidad", paragraphs: ["Es tóxica y debe mantenerse lejos de niños, gatos y perros.", "Como otras Araceae, contiene cristales de oxalato de calcio irritantes al masticar o ingerir."] },
      { id: "problems", title: "Diagnóstico y problemas frecuentes", paragraphs: ["Hojas amarillas: exceso de agua, frío, poca luz o envejecimiento. Revisar raíces y secado real.", "Puntas o zonas crema marrones: sol fuerte, aire seco, sales o riego irregular. Estabilizar sin cambios bruscos.", "Crecimiento lento: poca luz, baja temperatura o raíces inactivas. Corregir luz y calor antes de abonar.", "Trips y ácaros atacan brotes y reversos. Aislar, limpiar y vigilar varias semanas."] },
      { id: "comparisons", title: "No confundir los cultivares", paragraphs: ["Monstera deliciosa ‘Albo Variegata’ suele tener blanco más sectorial y variable entre nudos.", "Monstera deliciosa ‘Mint’ muestra un marmoleado pálido difuso y mentolado, no salpicaduras crema."] },
      { id: "gallery", title: "Lámina botánica", paragraphs: ["Las tres lenguas utilizan la misma foto del propietario: siete hojas adultas de Thai Constellation dispuestas como lámina botánica."] },
      { id: "studio-advice", title: "Consejos Tibaldo Jungle", paragraphs: ["Observar el cepellón antes de regar; la superficie no lo cuenta todo.", "La luz adecuada produce un crecimiento más sólido que el exceso de abono.", "Las zonas crema se queman antes: aumentar la luz progresivamente."] },
      { id: "sources", title: "Fuentes y prudencia", paragraphs: ["Los consejos se contrastan con la ficha de Monstera deliciosa de la Royal Horticultural Society."] },
    ],
    faq: [
      { question: "¿Qué luz necesita Monstera deliciosa ‘Thai Constellation’?", answer: "Luz indirecta muy intensa para mantener las zonas crema sin sol fuerte." },
      { question: "¿Cómo se riega Thai Constellation?", answer: "Deja secar la parte superior; sus raíces no toleran humedad permanente." },
      { question: "¿Qué sustrato debo utilizar?", answer: "Una mezcla muy aireada para aráceas en una maceta ajustada y perforada." },
      { question: "¿La maceta debe estar perforada?", answer: "Sí. Después de regar, el exceso debe salir completamente del cepellón." },
      { question: "¿Es tóxica?", answer: "Sí. Masticar sus tejidos puede irritar a personas y animales." },
      { question: "¿Cuándo debo trasplantarla?", answer: "Cuando las raíces hayan colonizado la maceta y la mezcla se seque demasiado rápido, no según un calendario fijo." },
    ],
  },
  "/plantes/bananiers": {
    sections: [
      { id: "botanical-foundations", title: "Una silueta tropical, varias estrategias", paragraphs: ["Una bananera es una gran herbácea, no un árbol. Su aparente tronco es un pseudotallo formado por vainas superpuestas.", "Las Musa suelen ser rizomatosas y producir hijuelos; las Ensete son normalmente solitarias. Esto modifica multiplicación, espacio e invernada.", "La rusticidad no es un único número: hojas, pseudotallo y rizoma tienen límites distintos, y la humedad invernal puede ser tan decisiva como el frío."] },
      { id: "genera", title: "Musa y Ensete", paragraphs: ["Musa incluye Basjoo, Red Tiger y Florida Variegata, con usos muy diferentes.", "Ensete reúne plantas normalmente solitarias y de base engrosada, representadas aquí por ‘Maurelii’."] },
      { id: "lille-north", title: "Cultivar bananeras en Lille y el norte de Francia", paragraphs: ["El clima de Lille combina posibles heladas, poca luz invernal, viento y humedad. En tierra, elegir abrigo y drenaje. Musa basjoo es la candidata más lógica, protegiendo la cepa sin prometer conservar las hojas.", "En maceta, planificar la entrada en otoño. Florida Variegata y Ensete ‘Maurelii’ necesitan ausencia de heladas; Red Tiger exige prudencia. Retomar agua y abono abundantes cuando el suelo se caliente."] },
      { id: "fundamentals", title: "Luz, agua, suelo e invierno", paragraphs: ["Luz y viento: mucha luz, aclimatación al sol y protección de las ráfagas.", "Agua y nutrición: abundantes durante el crecimiento y claramente reducidas al bajar luz y temperatura.", "Suelo y maceta: mezcla rica pero drenante, agujeros y recipiente estable para plantas pesadas.", "Invierno: identificar el taxón; acolchar una cepa resistente y meter una planta sensible no son lo mismo."] },
      { id: "four-taxa", title: "Cuatro bananeras, cuatro tratamientos", paragraphs: ["Musa basjoo: hoja verde amplia; tierra o maceta grande; cepa protegida; acolchado respirable y drenaje; hijuelos enraizados.", "Musa sikkimensis ‘Red Tiger’: marcas rojas variables; maceta o exterior protegido; no copiar los límites de Basjoo; protección seria o entrada; semilla no fiel al cultivar.", "Musa ‘Florida Variegata’: verde y crema; maceta luminosa; sensible al frío; invierno luminoso sin heladas; sin prometer estabilidad no documentada.", "Ensete ventricosum ‘Maurelii’: verde oscuro, rojo y púrpura; maceta o exterior estacional; sensible a heladas; invernada sin heladas; porte solitario sin hijuelos espontáneos."] },
    ], faq: [],
  },
  "/conseils/arroser-plantes-interieur": {
    sections: [
      { id: "check-substrate", title: "Comprobar el sustrato", paragraphs: ["Una superficie seca no revela el centro de la maceta. Comprueba varios centímetros y aprende el peso del recipiente mojado y casi seco.", "Las hojas dan pistas, pero esperar un marchitamiento grave provoca estrés innecesario."] },
      { id: "water-thoroughly", title: "Regar completamente", paragraphs: ["Cuando sea necesario, humedece uniformemente todo el cepellón hasta que salga el exceso. Vacía después el plato o cubremaceta.", "Pequeñas cantidades repetidas dejan zonas secas y concentran raíces cerca de la superficie."] },
      { id: "adapt-seasons", title: "Adaptarse a las estaciones", paragraphs: ["Las plantas consumen menos cuando disminuyen luz y temperatura. No mantengas la frecuencia de verano sin comprobar la mezcla.", "Tras trasplantar, mover o cambiar la luz, vuelve a observar: el ritmo anterior puede dejar de servir."] },
      { id: "studio-help", title: "¿Dudas sobre el recipiente?", paragraphs: ["Lleva la planta y su maceta al Estudio Vegetal. Podemos comprobar juntos drenaje, volumen y sustrato en lugar de adivinar."] },
    ], faq: [],
  },
};

export const pilotParityContent: Record<TranslatedLocale, Record<PilotPath, ParityPage>> = { en, es };
