import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "../LegalPage";

export const metadata: Metadata = {
  title: "Politique de confidentialité — BÊTA DRAFT | Tibaldo Jungle",
  description: "Projet de politique de confidentialité Tibaldo Jungle et Shop, soumis à la revue juridique de l’Owner.",
  alternates: { canonical: "/politique-de-confidentialite" },
  robots: { index: false, follow: false },
};

const sections: LegalSection[] = [
  { id: "statut", title: "Statut de ce document", content: <><p>Cette page est un <strong>projet BÊTA</strong> préparé à partir de l’audit technique des traitements réellement observés. Elle doit être relue et validée par l’Owner et un professionnel compétent avant toute publication finale.</p><p>Elle ne clôt pas les chantiers relatifs aux durées et procédures de suppression, à l’exercice opérationnel des droits, ni à la qualification contractuelle des sous-traitants et transferts.</p></> },
  { id: "responsable", title: "Responsable du traitement et contact", content: <><p>Le responsable des traitements est Pruvost Romain, Entrepreneur individuel, exerçant sous le nom commercial Tibaldo Jungle et la signature Studio Végétal — Tibaldo Jungle.</p><p>Les demandes relatives aux données personnelles peuvent être adressées à <a href="mailto:jungle@tibaldo.fr">jungle@tibaldo.fr</a>. L’identité du demandeur pourra être vérifiée uniquement lorsqu’un doute raisonnable le justifie.</p></> },
  { id: "donnees", title: "Données traitées dans les services observés", content: <><p>Selon le service utilisé, Tibaldo peut traiter des données d’identité et de contact, des adresses et informations de livraison, les données du compte et de session, le panier, les commandes et devis, les informations nécessaires au retrait ou à la livraison, les factures et faits de paiement, les notifications transactionnelles ainsi que des journaux techniques de sécurité.</p><p>Tibaldo ne conserve pas les numéros complets de carte bancaire, CVC ou jetons Apple Pay. Les données nécessaires au paiement sont traitées par le prestataire de paiement dans son environnement sécurisé.</p></> },
  { id: "finalites", title: "Finalités et bases juridiques à valider", content: <><ul><li>Créer et sécuriser le compte client, conserver le panier et permettre la reprise du parcours.</li><li>Préparer, exécuter et suivre les commandes, retraits, livraisons et demandes de devis.</li><li>Assurer facturation, comptabilité, rapprochement des paiements, service après-vente et preuve transactionnelle.</li><li>Envoyer uniquement les notifications transactionnelles nécessaires au service.</li><li>Prévenir les doubles effets, les abus et les incidents techniques.</li></ul><p>Les bases candidates sont l’exécution du contrat ou de mesures précontractuelles, les obligations légales et l’intérêt légitime de sécurité et de défense des droits. Leur qualification finale reste soumise à revue juridique.</p></> },
  { id: "destinataires", title: "Destinataires et prestataires", content: <><p>Les données sont accessibles aux personnes autorisées de Tibaldo et, pour leur seule mission, aux prestataires techniques effectivement utilisés : Supabase pour la base de données et l’authentification, Stripe pour le paiement, Resend pour les emails transactionnels, Cloudflare et l’hébergement Sites pour la diffusion et la sécurité, ainsi que les services de calcul d’itinéraire utilisés pour les devis de livraison.</p><p>Aucune donnée n’est vendue. La liste contractuelle, les rôles exacts de chaque prestataire et les mécanismes applicables aux transferts hors Espace économique européen restent à finaliser avant publication.</p></> },
  { id: "conservation", title: "Conservation — chantier ouvert", content: <><p>Les données ne doivent être conservées que pendant la durée nécessaire au service, à la preuve, aux obligations comptables et fiscales ou à la défense de droits. Les durées détaillées, le nettoyage automatisé des données arrivées à échéance et la conservation des outbox, logs, devis et snapshots ne sont pas encore finalisés.</p><p><strong>PRIV-P1-002 reste ouvert :</strong> ce projet ne promet aucune suppression automatique qui ne soit pas encore implémentée et vérifiée.</p></> },
  { id: "droits", title: "Droits des personnes — procédure à finaliser", content: <><p>Selon la situation, une personne peut demander l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité de ses données, et retirer un consentement lorsqu’un traitement repose sur celui-ci. Une réclamation peut être adressée à la CNIL.</p><p><strong>PRIV-P1-003 reste ouvert :</strong> les parcours vérifiés d’export, d’effacement, de restriction et de suivi des demandes doivent être finalisés avant ouverture.</p></> },
  { id: "transferts", title: "Sous-traitants et transferts — revue requise", content: <><p>Certains prestataires peuvent traiter des données en dehors de l’Espace économique européen. Les mécanismes de transfert, garanties complémentaires, durées contractuelles et listes de sous-traitants doivent être vérifiés service par service.</p><p><strong>PRIV-P1-004 reste ouvert :</strong> cette page n’atteste pas que cette revue contractuelle est terminée.</p></> },
  { id: "securite", title: "Sécurité et confidentialité", content: <><p>Les mesures observées comprennent l’authentification, le contrôle des accès, la séparation TEST/PROD, la limitation des accès directs aux données, l’idempotence des opérations sensibles, la journalisation technique et l’absence de secrets dans les clients publics.</p><p>Aucune mesure ne supprime tous les risques. Les incidents et demandes de support doivent être traités par les personnes habilitées.</p></> },
  { id: "cookies", title: "Cookies et traceurs", content: <><p>La configuration actuellement observée n’utilise ni analytics, ni pixel publicitaire, ni retargeting, ni replay de session. Aucun bandeau de consentement n’est donc ajouté dans cette version BÊTA. Des éléments strictement nécessaires peuvent être utilisés pour la session, la sécurité, le panier et l’idempotence.</p><p>Le parcours Stripe hébergé et les dispositifs Cloudflare devront être réinventoriés avant ouverture. Tout ajout futur de traceurs non essentiels devra être précédé d’une information et, lorsque requis, d’un mécanisme de choix.</p></> },
];

export default function PrivacyPolicyPage() {
  return <LegalPage eyebrow="BÊTA · Données personnelles" title="Politique de confidentialité" intro="Projet fondé sur les traitements techniques observés — revue juridique Owner requise." updated="26 août 2026" warning={<><strong>DRAFT · OWNER LEGAL REVIEW REQUIRED</strong><p>Ce document n’est pas une publication juridique finale. Les chantiers PRIV-P1-002, PRIV-P1-003 et PRIV-P1-004 restent ouverts.</p></>} sections={sections} />;
}
