import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPlant, plants } from "@/lib/plants/catalog";
import PlantProfile from "../../PlantProfile";
import PlantFamilyPage, { generateMetadata as generateFamilyMetadata } from "../../famille/[family]/page";
type Props = { params: Promise<{ genre: string; slug: string }> };
const families = [...new Set(plants.map((plant) => plant.taxonomy.family.toLowerCase()))];
export const generateStaticParams = () => [...plants.map(({ genre, slug }) => ({ genre, slug })), ...families.map((slug) => ({ genre: "famille", slug }))];
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { genre, slug } = await params; if (genre === "famille") return generateFamilyMetadata({ params: Promise.resolve({ family: slug }) }); const plant = getPlant(genre, slug); if (!plant) return {}; const url = `/plantes/${genre}/${slug}`; return { title: plant.seo.title, description: plant.seo.description, keywords: plant.seo.keywords, alternates: { canonical: url }, openGraph: { type: "article", locale: "fr_FR", url, title: plant.seo.title, description: plant.seo.description, images: [{ url: plant.gallery[0].src, width: plant.gallery[0].width, height: plant.gallery[0].height, alt: plant.gallery[0].alt }] } }; }
export default async function Page({ params }: Props) { const { genre, slug } = await params; if (genre === "famille") return PlantFamilyPage({ params: Promise.resolve({ family: slug }) }); const plant = getPlant(genre, slug); if (!plant) notFound(); const url = `https://jungle.tibaldo.fr/plantes/${genre}/${slug}`; const data = { "@context": "https://schema.org", "@graph": [
  { "@type": "Article", headline: plant.botanicalName, description: plant.seo.description, datePublished: plant.publishedAt, dateModified: plant.updatedAt, author: { "@type": "Organization", name: "Studio Végétal — Tibaldo Jungle" }, publisher: { "@id": "https://jungle.tibaldo.fr/#store" }, image: plant.gallery.map(({ src }) => `https://jungle.tibaldo.fr${src}`), about: { "@type": "Thing", name: plant.botanicalName, alternateName: plant.synonyms } },
  { "@type": "FAQPage", mainEntity: plant.faq.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: "https://jungle.tibaldo.fr/" }, { "@type": "ListItem", position: 2, name: "Plantes", item: "https://jungle.tibaldo.fr/plantes" }, { "@type": "ListItem", position: 3, name: plant.genreLabel, item: `https://jungle.tibaldo.fr/plantes/${genre}` }, { "@type": "ListItem", position: 4, name: plant.displayName, item: url }] },
  ...plant.gallery.map((image) => ({ "@type": "ImageObject", contentUrl: `https://jungle.tibaldo.fr${image.src}`, caption: image.caption, width: image.width, height: image.height })),
  { "@type": ["Florist", "LocalBusiness"], "@id": "https://jungle.tibaldo.fr/#store", name: "Studio Végétal — Tibaldo Jungle", alternateName: "Tibaldo Jungle", address: { "@type": "PostalAddress", streetAddress: "3 place de l’Arbonnoise", postalCode: "59000", addressLocality: "Lille", addressCountry: "FR" } }
] }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} /><PlantProfile plant={plant} /></>; }
