export const substrates = [
  {
    slug: "terreau-signature",
    name: "Terreau Signature by Romain",
    number: "01",
    tone: "earth",
    description: "Le mélange maison du Studio : une base équilibrée, souple et vivante, pensée pour offrir aux racines un juste rapport entre humidité, air et nutrition.",
    benefits: ["Équilibre eau et oxygène", "Structure durable", "Prêt à utiliser"],
    uses: "Rempotage courant, reprise après achat et entretien des plantes d’intérieur.",
    plants: "Monstera, Philodendron, Ficus, Pothos et plantes tropicales faciles.",
  },
  {
    slug: "ecorce-pin",
    name: "Écorce de pin",
    number: "02",
    tone: "bark",
    description: "Des fragments structurants qui ouvrent le mélange et ménagent des poches d’air autour des racines. Un geste simple pour retrouver un sol plus proche de celui des épiphytes.",
    benefits: ["Aération durable", "Drainage renforcé", "Limite le tassement"],
    uses: "À incorporer aux mélanges aérés ou à employer comme base pour orchidées.",
    plants: "Anthurium, Monstera, Philodendron, Hoya et orchidées.",
  },
  {
    slug: "chips-coco",
    name: "Chips de coco",
    number: "03",
    tone: "coco",
    description: "Une matière fibreuse et légère qui retient une part d’humidité sans étouffer les racines. Elle donne du ressort au substrat et accompagne les croissances actives.",
    benefits: ["Réserve d’humidité", "Bonne circulation de l’air", "Mélange plus souple"],
    uses: "En complément d’un terreau ou dans un mélange très aéré pour plantes tropicales.",
    plants: "Alocasia, Anthurium, Philodendron, Monstera et Hoya.",
  },
  {
    slug: "perlite",
    name: "Perlite",
    number: "04",
    tone: "pearl",
    description: "Cette roche expansée très légère allège les mélanges compacts et facilite l’écoulement de l’eau. Les jeunes racines y trouvent un environnement plus respirant.",
    benefits: ["Allège le substrat", "Favorise le drainage", "Soutient l’enracinement"],
    uses: "Mélanges de rempotage, semis, boutures et récupération d’une plante trop arrosée.",
    plants: "La plupart des plantes d’intérieur, semis et boutures.",
  },
  {
    slug: "sphaigne-sechee",
    name: "Sphaigne séchée",
    number: "05",
    tone: "moss",
    description: "Une fibre végétale capable de conserver une humidité régulière tout en restant aérienne. Réhydratée avec soin, elle devient un support précieux pour les racines fragiles.",
    benefits: ["Humidité homogène", "Texture aérienne", "Idéale en propagation"],
    uses: "Bouturage, marcottage, reprise racinaire, tuteurs et culture temporaire.",
    plants: "Anthurium, Hoya, orchidées, boutures tropicales et jeunes plants.",
  },
  {
    slug: "charbon-actif",
    name: "Charbon actif",
    number: "06",
    tone: "coal",
    description: "Un composant sombre, poreux et discret qui complète les mélanges techniques. Il contribue à maintenir un environnement plus sain dans les contenants peu ventilés.",
    benefits: ["Capte certaines impuretés", "Aide à limiter les odeurs", "Structure poreuse"],
    uses: "En petite proportion dans les terrariums, mélanges tropicaux et substrats de propagation.",
    plants: "Terrariums, orchidées, Anthurium et plantes à racines sensibles.",
  },
  {
    slug: "billes-argile",
    name: "Billes d’argile",
    number: "07",
    tone: "clay",
    description: "Des granulés robustes et réutilisables pour stabiliser un pot, créer une réserve autour d’un cache-pot ou installer une culture semi-hydroponique.",
    benefits: ["Réutilisables", "Stables et propres", "Adaptées à la semi-hydro"],
    uses: "Culture semi-hydroponique, plateaux d’humidité et allègement de grands contenants.",
    plants: "Plantes tropicales adaptées à la semi-hydro et grands sujets d’intérieur.",
  },
  {
    slug: "pierre-ponce",
    name: "Pierre ponce",
    number: "08",
    tone: "stone",
    description: "Une roche volcanique poreuse qui apporte du poids sans fermer le mélange. Elle garde une fine réserve d’eau et de nutriments tout en laissant les racines respirer.",
    benefits: ["Drainage stable", "Bonne porosité", "Retient une fine réserve"],
    uses: "Mélanges minéraux, bonsaïs, plantes matures et substrats devant rester structurés.",
    plants: "Alocasia, Anthurium, bonsaïs, succulentes et plantes méditerranéennes.",
  },
  {
    slug: "vermiculite",
    name: "Vermiculite",
    number: "09",
    tone: "gold",
    description: "Un minéral feuilleté qui absorbe doucement l’eau et la restitue dans le temps. Il apporte de la régularité aux cultures qui redoutent les sécheresses brusques.",
    benefits: ["Retient l’humidité", "Restitution progressive", "Très légère"],
    uses: "Semis, jeunes plants et mélanges qui sèchent trop rapidement.",
    plants: "Calathea, Maranta, fougères, semis et plantes appréciant un sol frais.",
  },
  {
    slug: "zeolite",
    name: "Zéolite",
    number: "10",
    tone: "zeolite",
    description: "Une pierre minérale microporeuse qui aide le mélange à mieux gérer eau et éléments nutritifs. Sa structure reste stable et convient aux compositions de longue durée.",
    benefits: ["Échanges nutritifs", "Structure durable", "Gestion de l’humidité"],
    uses: "Mélanges minéraux, semi-hydroponie et substrats techniques à renouvellement lent.",
    plants: "Plantes tropicales, bonsaïs, succulentes et cultures semi-hydroponiques.",
  },
] as const;
