// Editorial snapshot. No runtime supplier request, price, stock or Shop identity.
export const sourceReviewedAt = "2026-09-03";
const source = (slug: string) => `https://www.sybotanica.com/products/${slug}`;
export type Mix = { id: string; name: string; plants: string[]; hubs: string[]; group: string; profile: string; why: string; ingredients: string; source: string };
export const mixGroups = [
  { id: "air", title: "De l’air entre les racines.", label: "Tropicales aérées", intro: "Des fragments structurants pour garder un milieu ouvert, sans confondre aération et sécheresse." },
  { id: "moisture", title: "Garder de la fraîcheur.", label: "Humidité maîtrisée", intro: "Retenir une part d’eau tout en laissant le surplus s’écouler : deux fonctions complémentaires." },
  { id: "drainage", title: "Laisser l’eau circuler.", label: "Drainage & structure", intro: "Une présence minérale marquée ou une structure plus dense, selon la plante et son contenant." },
  { id: "special", title: "À chaque milieu, ses nuances.", label: "Les spécialistes", intro: "Orchidées, carnivores et terrariums ne partagent pas une recette unique. Identifiez d’abord votre plante et son mode de culture." },
];
export const readyMixes: Mix[] = [
  { id: "aroid", name: "Aroid Mix", plants: ["Monstera", "Philodendron", "Pothos", "Aglaonema"], hubs: ["monstera", "philodendron", "epipremnum"], group: "air", profile: "Aéré · structuré", why: "Les morceaux de coco et la perlite ouvrent le mélange ; la fibre de coco conserve une part d’humidité.", ingredients: "Fibre et chips de coco, perlite, lombricompost", source: source("premium-aroid-soil-mix-5-liter") },
  { id: "alocasia", name: "Alocasia Mix", plants: ["Alocasia"], hubs: ["alocasia"], group: "moisture", profile: "Rétenteur · humidité régulière", why: "La vermiculite prolonge la rétention d’eau : un repère utile pour surveiller le séchage plutôt qu’arroser par habitude.", ingredients: "Vermiculite — composant mis en avant par le fabricant", source: source("premium-alocasia-soil-mix-5-liter") },
  { id: "anthurium", name: "Anthurium Mix", plants: ["Anthurium"], hubs: ["anthurium"], group: "air", profile: "Grossier · aéré", why: "Écorces et chips de coco ménagent de l’espace autour des racines des Anthurium cultivés en mélange aéré.", ingredients: "Chips de coco, écorces pour orchidées, perlite, charbon actif", source: source("premium-anthurium-soil-mix-5-liter") },
  { id: "hoya", name: "Hoya Mix", plants: ["Hoya"], hubs: ["hoya"], group: "air", profile: "Aéré · drainant", why: "Les écorces et chips de coco structurent un mélange conçu pour s’égoutter rapidement entre deux apports d’eau.", ingredients: "Écorces, chips et fibre de coco, perlite", source: source("hoya-soil-mix-5l") },
  { id: "syngonium", name: "Syngonium Mix", plants: ["Syngonium"], hubs: ["syngonium"], group: "air", profile: "Organique & minéral", why: "Une base de coco associée à la ponce et à la perlite réunit rétention et éléments structurants.", ingredients: "Fibre et chips de coco, ponce, perlite, lombricompost", source: source("premium-syngonium-soil-mix-5-liter") },
  { id: "calathea-maranta", name: "Calathea & Maranta Mix", plants: ["Calathea", "Maranta"], hubs: ["calathea", "maranta"], group: "moisture", profile: "Rétention & drainage", why: "La vermiculite retient l’humidité tandis que la perlite contribue à l’aération : le mélange cherche une fraîcheur régulière.", ingredients: "Perlite et vermiculite — éléments distinctifs", source: source("premium-calathea-maranta-mix-5-liter") },
  { id: "fern", name: "Fern Mix", plants: ["Fougère"], hubs: ["fougeres"], group: "moisture", profile: "Frais · texture fine", why: "Coco et lombricompost retiennent l’eau ; perlite et sable horticole complètent la structure autour des racines fines.", ingredients: "Fibre de coco, lombricompost, perlite, sable horticole", source: source("premium-fern-soil-mix-5-liter") },
  { id: "cacti", name: "Cacti & Succulent Mix", plants: ["Cactus", "Succulente"], hubs: ["cactus", "aloe"], group: "drainage", profile: "Granuleux · drainant", why: "Ponce, perlite et sable horticole donnent une place importante aux éléments minéraux dans ce mélange pour plantes de milieux secs.", ingredients: "Perlite, ponce, sable horticole", source: source("cacti-and-succulent-soil-mix-5-liter") },
  { id: "bonsai", name: "Bonsai Mix", plants: ["Bonsaï"], hubs: [], group: "drainage", profile: "Minéral & organique", why: "La ponce et la perlite occupent une place importante, avec une base organique. Le choix reste à adapter à l’espèce d’arbre.", ingredients: "Ponce, perlite, fibre de coco, lombricompost", source: source("premium-bonsai-soil-mix-5-liter") },
  { id: "ficus", name: "Ficus Mix", plants: ["Ficus"], hubs: ["ficus"], group: "drainage", profile: "Structuré · drainant", why: "Chips et perlite aèrent la zone racinaire ; le sable horticole apporte une texture plus dense au mélange.", ingredients: "Chips de coco, perlite, sable horticole", source: source("premium-ficus-soil-mix-5-liter") },
  { id: "orchid", name: "Orchid Mix", plants: ["Orchidée"], hubs: [], group: "special", profile: "Écorces · structure ouverte", why: "Une base de morceaux de coco et d’écorces, accompagnée de sphaigne. Vérifiez les besoins de votre orchidée : toutes ne se cultivent pas sur écorces.", ingredients: "Chips de coco, écorces, sphaigne, charbon actif, lave", source: source("orchid-mix-5l") },
  { id: "carnivorous", name: "Carnivorous Mix", plants: ["Carnivore"], hubs: [], group: "special", profile: "Coco · sphaigne · vermiculite", why: "Une proposition spécifique du fabricant, à vérifier pour le genre cultivé et la qualité de l’eau. Ne lui associez pas automatiquement un engrais tropical.", ingredients: "Fibre de coco, vermiculite, sphaigne, sable horticole, charbon actif", source: source("premium-carnivorous-soil-mix-5-liter") },
  { id: "terrarium", name: "Terrarium Mix", plants: ["Terrarium"], hubs: [], group: "special", profile: "Rétention · milieu tropical", why: "Conçu par le fabricant pour les installations tropicales et subtropicales qui demandent une réserve d’humidité. Un terrarium aride relève d’un autre équilibre.", ingredients: "Composition détaillée non reproduite : consulter la fiche fabricant", source: source("terrarium-substrate-mix-5-liter") },
];
// Single authority shared by the finder and the compact matching guide.
export const plantMixMapping = readyMixes.flatMap(mix => mix.plants.map(plant => ({ plant, mixId: mix.id, mixName: mix.name })));
export const selectedComponents = [
  { id: "coco-coir", name: "Coco coir", role: "Rétention · base fibreuse", text: "Une fibre fine qui conserve de l’eau et sert de base aux mélanges. Elle n’a pas le même rôle que les gros chips de coco.", source: source("coco-coir-5liter-soil-component") },
  { id: "sphagnum", name: "Sphaigne", role: "Rétention · support racinaire", text: "Ses fibres absorbantes accompagnent les boutures et certains mélanges. Conserver de l’humidité ne signifie pas maintenir les racines saturées.", source: source("sphagnum-moss-5-liter") },
  { id: "carbon", name: "Charbon actif", role: "Adsorption · matériau poreux", text: "Sa surface poreuse peut fixer certaines substances. Il ne remplace ni un drainage adapté, ni le diagnostic d’une racine abîmée.", source: source("activated-carbon-pellets-1-2-5-liter") },
  { id: "zeolite", name: "Zéolite", role: "Minéral · échanges nutritifs", text: "Ce minéral peut retenir certains ions nutritifs puis les échanger avec son environnement. Un composant du mélange, pas un engrais complet.", source: source("zeolite-houseplants-5-8mm") },
];
export const mineral = { name: "SYBA-Hydro / Vulkastrat", currentName: "SYBAStones Base Mix — non fertilisé", source: source("syba-hydro-vulkastrat-3l"), text: "La page fournie présente aujourd’hui une base minérale non fertilisée : ponce, zéolite et lave. Elle associe structure et gestion de l’eau sans base de terreau. En semi-hydro, le suivi de la réserve d’eau et de la nutrition demande une conduite spécifique ; ce n’est pas un changement automatique pour toute plante." };
export const nutrition = [
  { id: "tropical-slow", name: "Tropical Slow Release", mode: "slow", for: "Plantes tropicales", text: "Granulés à libération progressive pour la nutrition des plantes tropicales.", source: source("tropical-slow-release-plant-food-for-houseplants") },
  { id: "orchid-slow", name: "Orchid Slow Release", mode: "slow", for: "Orchidées", text: "Une formulation à libération progressive destinée aux orchidées.", source: source("orchid-slow-release-plant-food-for-houseplants") },
  { id: "cacti-slow", name: "Cacti Slow Release", mode: "slow", for: "Cactus & succulentes", text: "Une nutrition progressive présentée pour les plantes adaptées aux milieux secs.", source: source("cacti-slow-release-plant-food-for-houseplants") },
  { id: "tropical-liquid", name: "Tropical Bio Liquid", mode: "liquid", for: "Plantes tropicales", text: "Une formule liquide à diluer dans l’eau d’arrosage selon la notice.", source: source("tropical-bio-liquid-plant-food-for-houseplants") },
  { id: "orchid-liquid", name: "Orchid Bio Liquid", mode: "liquid", for: "Orchidées", text: "Une formule liquide dédiée aux orchidées, à mélanger à l’eau selon la notice.", source: source("orchid-bio-liquid-plant-food-for-houseplants") },
  { id: "cacti-liquid", name: "Cacti Bio Liquid", mode: "liquid", for: "Cactus & succulentes", text: "Un apport liquide destiné aux cactus et succulentes, à adapter à leur croissance.", source: source("cacti-bio-liquid-plant-food-for-houseplants") },
];
export const sourceRegistry = [...readyMixes, ...selectedComponents, mineral, ...nutrition].map(item => ({ name: item.name, url: item.source, authority: "SYBOTANICA_MANUFACTURER", reviewedAt: sourceReviewedAt, facts: "Local French summary of product identity, role and selected ingredients; not a stock or efficacy guarantee", mediaRights: "OWNER_CONFIRMED_PARTNERSHIP_PUBLIC_USE" }));
